-- ========== GENERATED BY QuestsDef Editor (Ctrl-Alt-Q) DO NOT EDIT MANUALLY! ==========

PlaceObj('QuestsDef', {
	Author = "Boyan",
	Chapter = "Act2",
	DevNotes = "To Do - on betrayal remember to flip k16 to enemy set it as a guardpost, foce conflict, add squad and add militia option. Also probabaly a destination for diamond shipments.\n\nThe bools for Faucheux are here, but some of the Notes are in 03_DefeatTheLegion in order to avoid spoilers.",
	DisplayName = T(887414655774, --[[QuestsDef 05_TakeDownFaucheux DisplayName]] "Taking Down Col. Faucheux"),
	Main = true,
	NoteDefs = {
		LastNoteIdx = 9,
		PlaceObj('QuestNote', {
			Badges = {
				PlaceObj('QuestBadgePlacement', {
					Sector = "K16",
				}),
			},
			CompletionConditions = {
				PlaceObj('QuestIsVariableBool', {
					QuestId = "05_TakeDownFaucheux",
					Vars = set( "Completed" ),
					__eval = function ()
						local quest = gv_Quests['05_TakeDownFaucheux'] or QuestGetState('05_TakeDownFaucheux')
						return quest.Completed
					end,
				}),
			},
			Idx = 2,
			ShowConditions = {
				PlaceObj('QuestIsVariableBool', {
					QuestId = "05_TakeDownFaucheux",
					Vars = set( "Given" ),
					__eval = function ()
						local quest = gv_Quests['05_TakeDownFaucheux'] or QuestGetState('05_TakeDownFaucheux')
						return quest.Given
					end,
				}),
			},
			Text = T(319492053936, --[[QuestsDef 05_TakeDownFaucheux Text]] "<em>Colonel Faucheux</em> and his troops must be defeated at <em><SectorName('K16')></em>"),
		}),
		PlaceObj('QuestNote', {
			Badges = {
				PlaceObj('QuestBadgePlacement', {
					BadgeUnit = "Underground",
					Sector = "H16",
				}),
			},
			CompletionConditions = {
				PlaceObj('QuestIsVariableBool', {
					Condition = "or",
					QuestId = "05_TakeDownFaucheux",
					Vars = set( "TCE_FaucheuxCombatBanter", "TCE_GuardCombatBanter" ),
					__eval = function ()
						local quest = gv_Quests['05_TakeDownFaucheux'] or QuestGetState('05_TakeDownFaucheux')
						return quest.TCE_FaucheuxCombatBanter or quest.TCE_GuardCombatBanter
					end,
				}),
			},
			Idx = 7,
			ShowConditions = {
				PlaceObj('QuestIsVariableBool', {
					QuestId = "05_TakeDownFaucheux",
					Vars = set( "FaucheuxSecretEntrance" ),
					__eval = function ()
						local quest = gv_Quests['05_TakeDownFaucheux'] or QuestGetState('05_TakeDownFaucheux')
						return quest.FaucheuxSecretEntrance
					end,
				}),
			},
			Text = T(533079322096, --[[QuestsDef 05_TakeDownFaucheux Text]] "There is a <em>secret entrance</em> to the Colonel's base <em><SectorName('K16')></em>"),
		}),
		PlaceObj('QuestNote', {
			Badges = {
				PlaceObj('QuestBadgePlacement', {
					BadgeUnit = "FaucheuxEnemy",
					Sector = "K16",
				}),
			},
			HideConditions = {
				PlaceObj('OR', {
					Conditions = {
						PlaceObj('QuestIsVariableBool', {
							Condition = "or",
							QuestId = "05_TakeDownFaucheux",
							Vars = set( "FaucheuxDead", "FaucheuxEscaped" ),
							__eval = function ()
								local quest = gv_Quests['05_TakeDownFaucheux'] or QuestGetState('05_TakeDownFaucheux')
								return quest.FaucheuxDead or quest.FaucheuxEscaped
							end,
						}),
						PlaceObj('CheckIsPersistentUnitDead', {
							per_ses_id = "NPC_Faucheux",
						}),
					},
				}),
			},
			Idx = 4,
			ShowConditions = {
				PlaceObj('VillainIsDefeated', {
					Group = "Faucheux",
				}),
				PlaceObj('QuestIsVariableBool', {
					QuestId = "05_TakeDownFaucheux",
					Vars = set( "Given" ),
					__eval = function ()
						local quest = gv_Quests['05_TakeDownFaucheux'] or QuestGetState('05_TakeDownFaucheux')
						return quest.Given
					end,
				}),
			},
			Text = T(777073916546, --[[QuestsDef 05_TakeDownFaucheux Text]] "<em>Col. Faucheux</em> is trying to <em>escape</em> from <em><SectorName('K16')></em>"),
		}),
		PlaceObj('QuestNote', {
			AddInHistory = true,
			CompletionConditions = {
				PlaceObj('CheckIsPersistentUnitDead', {
					per_ses_id = "NPC_Faucheux",
				}),
			},
			Idx = 8,
			ShowConditions = {
				PlaceObj('CheckIsPersistentUnitDead', {
					per_ses_id = "NPC_Faucheux",
				}),
			},
			Text = T(949023534937, --[[QuestsDef 05_TakeDownFaucheux Text]] "<em>Outcome:</em> <em>Col. Faucheux</em> is dead"),
		}),
		PlaceObj('QuestNote', {
			AddInHistory = true,
			CompletionConditions = {
				PlaceObj('QuestIsVariableBool', {
					QuestId = "05_TakeDownFaucheux",
					Vars = set( "FaucheuxEscaped" ),
					__eval = function ()
						local quest = gv_Quests['05_TakeDownFaucheux'] or QuestGetState('05_TakeDownFaucheux')
						return quest.FaucheuxEscaped
					end,
				}),
			},
			Idx = 9,
			ShowConditions = {
				PlaceObj('QuestIsVariableBool', {
					QuestId = "05_TakeDownFaucheux",
					Vars = set( "FaucheuxEscaped" ),
					__eval = function ()
						local quest = gv_Quests['05_TakeDownFaucheux'] or QuestGetState('05_TakeDownFaucheux')
						return quest.FaucheuxEscaped
					end,
				}),
			},
			Text = T(685283843942, --[[QuestsDef 05_TakeDownFaucheux Text]] "<em>Outcome:</em> <em>Col. Faucheux</em> was defeated but he managed to escape"),
		}),
	},
	QuestGroup = "The Fate Of Grand Chien",
	TCEs = {
		PlaceObj('TriggeredConditionalEvent', {
			Conditions = {
				PlaceObj('QuestIsVariableBool', {
					QuestId = "05_TakeDownFaucheux",
					Vars = set( "Given" ),
					__eval = function ()
						local quest = gv_Quests['05_TakeDownFaucheux'] or QuestGetState('05_TakeDownFaucheux')
						return quest.Given
					end,
				}),
				PlaceObj('SectorCheckOwner', {
					sector_id = "K16",
				}),
			},
			Effects = {
				PlaceObj('ConditionalEffect', {
					'Conditions', {
						PlaceObj('QuestIsVariableBool', {
							QuestId = "05_TakeDownMajor",
							Vars = set({
	Completed = false,
}),
							__eval = function ()
								local quest = gv_Quests['05_TakeDownMajor'] or QuestGetState('05_TakeDownMajor')
								return not quest.Completed
							end,
						}),
					},
					'Effects', {
						PlaceObj('QuestSetVariableBool', {
							Prop = "PresidentStillMissing",
							QuestId = "05_TakeDownFaucheux",
						}),
					},
				}),
				PlaceObj('GrantExperienceSector', {
					Amount = "XPQuestReward_Large",
					logImportant = true,
				}),
				PlaceObj('QuestSetVariableBool', {
					Prop = "Completed",
					QuestId = "05_TakeDownFaucheux",
				}),
			},
			Once = true,
			ParamId = "TCE_FaucheuxDone",
			QuestId = "05_TakeDownFaucheux",
		}),
		PlaceObj('TriggeredConditionalEvent', {
			Conditions = {
				PlaceObj('PlayerIsInSectors', {
					Sectors = {
						"K16",
					},
				}),
				PlaceObj('UnitIsAroundMarkerOfGroup', {
					MarkerGroup = "WallAreaBanter",
					TargetUnit = "any merc",
				}),
			},
			Effects = {
				PlaceObj('PlayBanterEffect', {
					AnyActorOverrideGroup = "WallAreaBanter",
					Banters = {
						"WallSkillCheck_Area",
					},
					searchInMap = true,
					searchInMarker = false,
				}),
			},
			Once = true,
			ParamId = "TCE_WallAreaBanter",
			QuestId = "05_TakeDownFaucheux",
			requiredSectors = {
				"K16",
			},
		}),
		PlaceObj('TriggeredConditionalEvent', {
			Conditions = {
				PlaceObj('BanterHasPlayed', {
					Banters = {
						"FortBrigandGuard_01_beforeBetrayal",
					},
				}),
				PlaceObj('QuestIsVariableBool', {
					QuestId = "04_Betrayal",
					Vars = set({
	WorldFlipDone = false,
}),
					__eval = function ()
						local quest = gv_Quests['04_Betrayal'] or QuestGetState('04_Betrayal')
						return not quest.WorldFlipDone
					end,
				}),
			},
			Effects = {
				PlaceObj('QuestSetVariableBool', {
					Prop = "FaucheuxInvite",
					QuestId = "05_TakeDownFaucheux",
				}),
			},
			Once = true,
			ParamId = "TCE_GiveInvite",
			QuestId = "05_TakeDownFaucheux",
		}),
		PlaceObj('TriggeredConditionalEvent', {
			Conditions = {
				PlaceObj('PlayerIsInSectors', {
					Sectors = {
						"K16",
					},
				}),
				PlaceObj('QuestIsVariableBool', {
					QuestId = "_GroupsAttacked",
					Vars = set( "AllAllies" ),
					__eval = function ()
						local quest = gv_Quests['_GroupsAttacked'] or QuestGetState('_GroupsAttacked')
						return quest.AllAllies
					end,
				}),
				PlaceObj('QuestIsVariableBool', {
					QuestId = "04_Betrayal",
					Vars = set({
	WorldFlipDone = false,
}),
					__eval = function ()
						local quest = gv_Quests['04_Betrayal'] or QuestGetState('04_Betrayal')
						return not quest.WorldFlipDone
					end,
				}),
			},
			Effects = {
				PlaceObj('PlayBanterEffect', {
					Banters = {
						"FortBrigandGuard_02_failedattack",
					},
					searchInMap = true,
					searchInMarker = false,
				}),
			},
			Once = true,
			ParamId = "TCE_AllyAttackBanter",
			QuestId = "05_TakeDownFaucheux",
			requiredSectors = {
				"K16",
			},
		}),
		PlaceObj('TriggeredConditionalEvent', {
			Conditions = {
				PlaceObj('QuestIsVariableBool', {
					QuestId = "04_Betrayal",
					Vars = set( "WorldFlipDone" ),
					__eval = function ()
						local quest = gv_Quests['04_Betrayal'] or QuestGetState('04_Betrayal')
						return quest.WorldFlipDone
					end,
				}),
				PlaceObj('PlayerIsInSectors', {
					Sectors = {
						"K16",
					},
				}),
				PlaceObj('UnitIsAware', {
					TargetUnit = "EnemySquad",
				}),
				PlaceObj('UnitIsAroundMarkerOfGroup', {
					DisableContextModification = true,
					MarkerGroup = "FaucheuxRoom",
					Negate = true,
					TargetUnit = "any merc",
				}),
			},
			Effects = {
				PlaceObj('PlayBanterEffect', {
					Banters = {
						"FortBrigandGuard_02_attacked",
					},
					searchInMap = true,
					searchInMarker = false,
				}),
			},
			Once = true,
			ParamId = "TCE_GuardCombatBanter",
			QuestId = "05_TakeDownFaucheux",
			requiredSectors = {
				"K16",
			},
		}),
		PlaceObj('TriggeredConditionalEvent', {
			Conditions = {
				PlaceObj('QuestIsVariableBool', {
					QuestId = "04_Betrayal",
					Vars = set( "WorldFlipDone" ),
					__eval = function ()
						local quest = gv_Quests['04_Betrayal'] or QuestGetState('04_Betrayal')
						return quest.WorldFlipDone
					end,
				}),
				PlaceObj('QuestIsVariableBool', {
					QuestId = "05_TakeDownFaucheux",
					Vars = set({
	FaucheuxDead = false,
}),
					__eval = function ()
						local quest = gv_Quests['05_TakeDownFaucheux'] or QuestGetState('05_TakeDownFaucheux')
						return not quest.FaucheuxDead
					end,
				}),
				PlaceObj('PlayerIsInSectors', {
					Sectors = {
						"K16",
					},
				}),
				PlaceObj('CombatIsActive', {
					Negate = true,
				}),
				PlaceObj('UnitIsAroundMarkerOfGroup', {
					DisableContextModification = true,
					MarkerGroup = "FaucheuxRoom",
					TargetUnit = "any merc",
				}),
			},
			Effects = {
				PlaceObj('PlayBanterEffect', {
					Banters = {
						"FortBrigandFaucheux_03_sneak",
					},
					searchInMap = true,
					searchInMarker = false,
				}),
				PlaceObj('GroupAlert', {
					TargetUnit = "FaucheuxEnemy",
				}),
			},
			Once = true,
			ParamId = "TCE_FaucheuxSneakBanter",
			QuestId = "05_TakeDownFaucheux",
			requiredSectors = {
				"K16",
			},
		}),
		PlaceObj('TriggeredConditionalEvent', {
			Conditions = {
				PlaceObj('QuestIsVariableBool', {
					QuestId = "04_Betrayal",
					Vars = set( "WorldFlipDone" ),
					__eval = function ()
						local quest = gv_Quests['04_Betrayal'] or QuestGetState('04_Betrayal')
						return quest.WorldFlipDone
					end,
				}),
				PlaceObj('QuestIsVariableBool', {
					QuestId = "05_TakeDownFaucheux",
					Vars = set({
	FaucheuxDead = false,
}),
					__eval = function ()
						local quest = gv_Quests['05_TakeDownFaucheux'] or QuestGetState('05_TakeDownFaucheux')
						return not quest.FaucheuxDead
					end,
				}),
				PlaceObj('PlayerIsInSectors', {
					Sectors = {
						"K16",
					},
				}),
				PlaceObj('UnitIsAroundOtherUnit', {
					Distance = 10,
					SecondTargetUnit = "FaucheuxEnemy",
					TargetUnit = "any merc",
				}),
				PlaceObj('CombatIsActive', {}),
				PlaceObj('CombatTurn', {
					Amount = 2,
					Condition = ">=",
				}),
			},
			Effects = {
				PlaceObj('PlayBanterEffect', {
					Banters = {
						"FortBrigandFaucheux_02_battle",
					},
					banterSequentialWaitFor = "BanterStart",
					searchInMap = true,
					searchInMarker = false,
				}),
			},
			Once = true,
			ParamId = "TCE_FaucheuxCombatBanter",
			QuestId = "05_TakeDownFaucheux",
			requiredSectors = {
				"K16",
			},
		}),
		PlaceObj('TriggeredConditionalEvent', {
			Conditions = {
				PlaceObj('QuestIsVariableBool', {
					QuestId = "05_TakeDownFaucheux",
					Vars = set( "Given" ),
					__eval = function ()
						local quest = gv_Quests['05_TakeDownFaucheux'] or QuestGetState('05_TakeDownFaucheux')
						return quest.Given
					end,
				}),
				PlaceObj('PlayerIsInSectors', {
					Sectors = {
						"K16",
					},
				}),
				PlaceObj('CheckExpression', {
					Expression = function (self, obj) return IsKindOf(g_Encounter, "BossfightFaucheaux") and g_Encounter.run_away end,
				}),
			},
			Effects = {
				PlaceObj('PlayBanterEffect', {
					Banters = {
						"FortBrigandFaucheux_04_defeated",
					},
					banterSequentialWaitFor = "BanterLineStart",
					searchInMap = true,
					searchInMarker = false,
				}),
			},
			Once = true,
			ParamId = "TCE_FuacheuxRetreatStart",
			QuestId = "05_TakeDownFaucheux",
			requiredSectors = {
				"K16",
			},
		}),
		PlaceObj('TriggeredConditionalEvent', {
			Conditions = {
				PlaceObj('QuestIsVariableBool', {
					QuestId = "05_TakeDownFaucheux",
					Vars = set( "Given" ),
					__eval = function ()
						local quest = gv_Quests['05_TakeDownFaucheux'] or QuestGetState('05_TakeDownFaucheux')
						return quest.Given
					end,
				}),
				PlaceObj('PlayerIsInSectors', {
					Sectors = {
						"K16",
					},
				}),
				PlaceObj('CheckExpression', {
					Expression = function (self, obj) return IsKindOf(g_Encounter, "BossfightFaucheaux") and g_Encounter.escaped end,
				}),
				PlaceObj('QuestIsVariableBool', {
					QuestId = "05_TakeDownFaucheux",
					Vars = set({
	FaucheuxDead = false,
}),
					__eval = function ()
						local quest = gv_Quests['05_TakeDownFaucheux'] or QuestGetState('05_TakeDownFaucheux')
						return not quest.FaucheuxDead
					end,
				}),
			},
			Effects = {
				PlaceObj('QuestSetVariableBool', {
					Prop = "FaucheuxEscaped",
					QuestId = "05_TakeDownFaucheux",
				}),
				PlaceObj('PlaySetpiece', {
					setpiece = "FaucheuxRetreat",
				}),
			},
			Once = true,
			ParamId = "TCE_FuacheuxRetreatEnd",
			QuestId = "05_TakeDownFaucheux",
			requiredSectors = {
				"K16",
			},
		}),
		PlaceObj('TriggeredConditionalEvent', {
			Conditions = {
				PlaceObj('PlayerIsInSectors', {
					Sectors = {
						"K16",
					},
				}),
				PlaceObj('GroupIsDead', {
					Group = "FaucheuxEnemy",
				}),
			},
			Effects = {
				PlaceObj('QuestSetVariableBool', {
					Prop = "FaucheuxDead",
					QuestId = "05_TakeDownFaucheux",
				}),
				PlaceObj('PlayBanterEffect', {
					Banters = {
						"FortBrigandFaucheux_05_killed",
					},
					banterSequentialWaitFor = "BanterLineStart",
					searchInMap = true,
					searchInMarker = false,
				}),
			},
			Once = true,
			ParamId = "TCE_FuacheuxKilled",
			QuestId = "05_TakeDownFaucheux",
			requiredSectors = {
				"K16",
			},
		}),
		PlaceObj('TriggeredConditionalEvent', {
			Conditions = {
				PlaceObj('PlayerIsInSectors', {
					Sectors = {
						"K16_Underground",
					},
				}),
				PlaceObj('QuestIsVariableBool', {
					QuestId = "05_TakeDownFaucheux",
					Vars = set( "K16U_KillSwitchTriggered" ),
					__eval = function ()
						local quest = gv_Quests['05_TakeDownFaucheux'] or QuestGetState('05_TakeDownFaucheux')
						return quest.K16U_KillSwitchTriggered
					end,
				}),
			},
			Effects = {
				PlaceObj('SectorEnterConflict', {
					disable_travel = true,
					lock_conflict = true,
					sector_id = "K16_Underground",
				}),
				PlaceObj('SetTimer', {
					Label = T(115711416393, --[[QuestsDef 05_TakeDownFaucheux Label]] "Alarm Raised"),
					Name = "KillSwitch_Counter",
				}),
				PlaceObj('QuestSetVariableBool', {
					Prop = "K16U_KillSwitchFailed",
					QuestId = "05_TakeDownFaucheux",
				}),
				PlaceObj('GroupAlert', {
					TargetUnit = "KillSwitch_Reinforcements",
				}),
				PlaceObj('SectorEnterConflict', {
					conflict_mode = false,
					sector_id = "K16_Underground",
				}),
			},
			Once = true,
			ParamId = "TCE_KillSwitch_StartCountdown",
			QuestId = "05_TakeDownFaucheux",
			requiredSectors = {
				"K16_Underground",
			},
		}),
		PlaceObj('TriggeredConditionalEvent', {
			Conditions = {
				PlaceObj('PlayerIsInSectors', {
					Sectors = {
						"K16_Underground",
					},
				}),
				PlaceObj('QuestIsVariableBool', {
					QuestId = "05_TakeDownFaucheux",
					Vars = set( "K16U_KillSwitchEndCountdown" ),
					__eval = function ()
						local quest = gv_Quests['05_TakeDownFaucheux'] or QuestGetState('05_TakeDownFaucheux')
						return quest.K16U_KillSwitchEndCountdown
					end,
				}),
			},
			Effects = {
				PlaceObj('KillTimer', {
					Name = "KillSwitch_Counter",
					StopTCE = true,
				}),
				PlaceObj('SectorEnterConflict', {
					conflict_mode = false,
					sector_id = "K16_Underground",
				}),
			},
			Once = true,
			ParamId = "TCE_KillSwitch_StopCountdown",
			QuestId = "05_TakeDownFaucheux",
			requiredSectors = {
				"K16_Underground",
			},
		}),
		PlaceObj('TriggeredConditionalEvent', {
			Conditions = {
				PlaceObj('PlayerIsInSectors', {
					Sectors = {
						"K16_Underground",
					},
				}),
				PlaceObj('QuestIsVariableBool', {
					QuestId = "04_Betrayal",
					Vars = set( "WorldFlipDone" ),
					__eval = function ()
						local quest = gv_Quests['04_Betrayal'] or QuestGetState('04_Betrayal')
						return quest.WorldFlipDone
					end,
				}),
			},
			Effects = {
				PlaceObj('GroupSetSide', {
					Side = "enemy1",
					TargetUnit = "InnerGuards",
				}),
			},
			Once = true,
			ParamId = "TCE_UndergroundEnemies",
			QuestId = "05_TakeDownFaucheux",
			requiredSectors = {
				"K16_Underground",
			},
		}),
		PlaceObj('TriggeredConditionalEvent', {
			Conditions = {
				PlaceObj('PlayerIsInSectors', {
					Sectors = {
						"K16",
					},
				}),
				PlaceObj('QuestIsVariableBool', {
					QuestId = "05_TakeDownFaucheux",
					Vars = set( "K16U_KillSwitchEndCountdown" ),
					__eval = function ()
						local quest = gv_Quests['05_TakeDownFaucheux'] or QuestGetState('05_TakeDownFaucheux')
						return quest.K16U_KillSwitchEndCountdown
					end,
				}),
			},
			Effects = {
				PlaceObj('LightsSetState', {
					MarkerGroup = "KillSwitch_Lights",
					TurnOn = false,
				}),
				PlaceObj('GrantExperienceSector', {
					Amount = "XPQuestReward_Minor",
					logImportant = true,
				}),
			},
			Once = true,
			ParamId = "TCE_KillSwitchEffects",
			QuestId = "05_TakeDownFaucheux",
			requiredSectors = {
				"K16",
			},
		}),
	},
	Variables = {
		PlaceObj('QuestVarBool', {
			Name = "Completed",
		}),
		PlaceObj('QuestVarBool', {
			Name = "Given",
		}),
		PlaceObj('QuestVarBool', {
			Name = "Failed",
		}),
		PlaceObj('QuestVarBool', {
			Name = "NotStarted",
			Value = true,
		}),
		PlaceObj('QuestVarBool', {
			Name = "K16U_KillSwitchTriggered",
		}),
		PlaceObj('QuestVarBool', {
			Name = "K16U_KillSwitchEndCountdown",
		}),
		PlaceObj('QuestVarBool', {
			Name = "K16U_KillSwitchFailed",
		}),
		PlaceObj('QuestVarBool', {
			Name = "PresidentStillMissing",
		}),
		PlaceObj('QuestVarTCEState', {
			Name = "TCE_FaucheuxDone",
		}),
		PlaceObj('QuestVarTCEState', {
			Name = "TCE_WallAreaBanter",
		}),
		PlaceObj('QuestVarBool', {
			Name = "FaucheuxInvite",
		}),
		PlaceObj('QuestVarBool', {
			Name = "FaucheuxTaunted",
		}),
		PlaceObj('QuestVarBool', {
			Name = "FaucheuxMission",
		}),
		PlaceObj('QuestVarBool', {
			Name = "FaucheuxArt",
		}),
		PlaceObj('QuestVarBool', {
			Name = "FaucheuxArtLooted",
		}),
		PlaceObj('QuestVarBool', {
			Name = "FaucheuxEscaped",
		}),
		PlaceObj('QuestVarBool', {
			Name = "FaucheuxDead",
		}),
		PlaceObj('QuestVarBool', {
			Name = "FaucheuxSecretEntrance",
		}),
		PlaceObj('QuestVarNum', {
			Name = "Clues",
		}),
		PlaceObj('QuestVarNum', {
			Name = "CluesRequired",
			Value = 4,
		}),
		PlaceObj('QuestVarTCEState', {
			Name = "TCE_GiveInvite",
		}),
		PlaceObj('QuestVarTCEState', {
			Name = "TCE_AllyAttackBanter",
		}),
		PlaceObj('QuestVarTCEState', {
			Name = "TCE_GuardCombatBanter",
		}),
		PlaceObj('QuestVarTCEState', {
			Name = "TCE_FaucheuxSneakBanter",
		}),
		PlaceObj('QuestVarTCEState', {
			Name = "TCE_FaucheuxCombatBanter",
		}),
		PlaceObj('QuestVarTCEState', {
			Name = "TCE_FuacheuxRetreatStart",
		}),
		PlaceObj('QuestVarTCEState', {
			Name = "TCE_FuacheuxRetreatEnd",
		}),
		PlaceObj('QuestVarTCEState', {
			Name = "TCE_FuacheuxKilled",
		}),
		PlaceObj('QuestVarTCEState', {
			Name = "TCE_KillSwitch_StartCountdown",
		}),
		PlaceObj('QuestVarTCEState', {
			Name = "TCE_KillSwitch_StopCountdown",
		}),
		PlaceObj('QuestVarTCEState', {
			Name = "TCE_UndergroundEnemies",
		}),
		PlaceObj('QuestVarTCEState', {
			Name = "TCE_KillSwitchEffects",
		}),
		PlaceObj('QuestVarBool', {
			Name = "Quartermaster_Yav_SuppliesTaken",
		}),
		PlaceObj('QuestVarBool', {
			Name = "Quartermaster_Lenge_SuppliesTaken",
		}),
	},
	group = "Main",
	id = "05_TakeDownFaucheux",
})

