-- ========== GENERATED BY QuestsDef Editor (Ctrl-Alt-Q) DO NOT EDIT MANUALLY! ==========

PlaceObj('QuestsDef', {
	Author = "Radomir",
	Chapter = "Act1",
	DevNotes = "Notes in RefugeeBlues",
	DisplayName = T(528486928826, --[[QuestsDef FaithHealing DisplayName]] "Helping Sangoma"),
	EffectOnChangeVarValue = {
		PlaceObj('QuestEffectOnStatus', {
			Effects = {
				PlaceObj('SectorRemoveCustomOperation', {
					operation = "RefugeeCamp_HelpShaman",
					sector_id = "E9",
				}),
			},
			Prop = "Completed",
		}),
	},
	Hidden = true,
	KillTCEsConditions = {
		PlaceObj('QuestIsVariableBool', {
			Condition = "or",
			QuestId = "FaithHealing",
			Vars = set( "Completed", "Failed" ),
			__eval = function ()
				local quest = gv_Quests['FaithHealing'] or QuestGetState('FaithHealing')
				return quest.Completed or quest.Failed
			end,
		}),
	},
	NoteDefs = {
		LastNoteIdx = 9,
	},
	QuestGroup = "Savanah",
	TCEs = {
		PlaceObj('TriggeredConditionalEvent', {
			Conditions = {
				PlaceObj('QuestIsVariableBool', {
					Condition = "or",
					QuestId = "FaithHealing",
					Vars = set( "AllowHelpActivity" ),
					__eval = function ()
						local quest = gv_Quests['FaithHealing'] or QuestGetState('FaithHealing')
						return quest.AllowHelpActivity
					end,
				}),
			},
			Effects = {
				PlaceObj('SectorEnableCustomOperation', {
					DisplayLog = true,
					EffectsOnSuccess = {
						PlaceObj('CityGrantLoyalty', {
							Amount = 25,
							City = "RefugeeCamp",
							SpecialConversationMessage = T(892806162142, --[[QuestsDef FaithHealing SpecialConversationMessage]] "cured the family of <em>Sangoma</em>"),
						}),
						PlaceObj('QuestSetVariableBool', {
							Prop = "FamilyHealed",
							QuestId = "FaithHealing",
						}),
						PlaceObj('QuestSetVariableBool', {
							Prop = "ActivityHealed",
							QuestId = "FaithHealing",
						}),
					},
					operation = "RefugeeCamp_HelpShaman",
					sector_id = "E9",
				}),
			},
			Once = true,
			ParamId = "TCE_TriggerHelpActivity",
			QuestId = "FaithHealing",
		}),
		PlaceObj('TriggeredConditionalEvent', {
			Conditions = {
				PlaceObj('QuestIsVariableBool', {
					Condition = "or",
					QuestId = "FaithHealing",
					Vars = set( "FamilyHealed" ),
					__eval = function ()
						local quest = gv_Quests['FaithHealing'] or QuestGetState('FaithHealing')
						return quest.FamilyHealed
					end,
				}),
			},
			Effects = {
				PlaceObj('GrantExperienceSector', {
					logImportant = true,
				}),
				PlaceObj('SectorRemoveCustomOperation', {
					operation = "RefugeeCamp_HelpShaman",
					sector_id = "E9",
				}),
				PlaceObj('QuestSetVariableBool', {
					Prop = "Completed",
					QuestId = "FaithHealing",
				}),
			},
			ParamId = "TCE_FamilyHealed",
			QuestId = "FaithHealing",
		}),
	},
	Variables = {
		PlaceObj('QuestVarBool', {
			Name = "AllowHelpActivity",
		}),
		PlaceObj('QuestVarBool', {
			Name = "Lead_Metaviron",
		}),
		PlaceObj('QuestVarBool', {
			Name = "MetavironGiven",
		}),
		PlaceObj('QuestVarBool', {
			Name = "FamilyHealed",
		}),
		PlaceObj('QuestVarTCEState', {
			Name = "TCE_TriggerHelpActivity",
		}),
		PlaceObj('QuestVarTCEState', {
			Name = "TCE_FamilyHealed",
		}),
		PlaceObj('QuestVarBool', {
			Name = "ActivityHealed",
		}),
		PlaceObj('QuestVarBool', {
			Name = "Completed",
		}),
		PlaceObj('QuestVarBool', {
			Name = "Given",
		}),
		PlaceObj('QuestVarBool', {
			Name = "Failed",
		}),
		PlaceObj('QuestVarBool', {
			Name = "NotStarted",
			Value = true,
		}),
	},
	group = "Savanna",
	id = "FaithHealing",
})

