-- ========== GENERATED BY QuestsDef Editor (Ctrl-Alt-Q) DO NOT EDIT MANUALLY! ==========

PlaceObj('QuestsDef', {
	DevNotes = "Needs to also lock the sector into conflict when the timer starts but that will be done when used somewhere.",
	KillTCEsConditions = {
		PlaceObj('QuestKillTCEsOnCompleted', {}),
	},
	TCEs = {
		PlaceObj('TriggeredConditionalEvent', {
			Conditions = {
				PlaceObj('QuestIsVariableBool', {
					QuestId = "TimedTrap",
					Vars = set( "InitialInteractionDone" ),
					__eval = function ()
						local quest = gv_Quests['TimedTrap'] or QuestGetState('TimedTrap')
						return quest.InitialInteractionDone
					end,
				}),
			},
			Effects = {
				PlaceObj('QuestSetVariableBool', {
					Prop = "Given",
					QuestId = "TimedTrap",
				}),
				PlaceObj('SetTimer', {
					Label = T(963052125569, --[[QuestsDef TimedTrap Label]] "It's A Trap!"),
					Name = "TimedBomb",
				}),
				PlaceObj('Explosion', {
					AppliedEffect = "IncreaseTiredness",
					AreaOfEffect = 6,
					Damage = 70,
					ExplosionType = "FragGrenade",
					LocationGroup = "TimmedTrap_Initial",
				}),
			},
			Once = true,
			ParamId = "TCE_StartTimer",
			QuestId = "TimedTrap",
		}),
		PlaceObj('TriggeredConditionalEvent', {
			Conditions = {
				PlaceObj('QuestIsVariableBool', {
					QuestId = "TimedTrap",
					Vars = set( "InitialInteractionDone", "SkillCheckSuccess" ),
					__eval = function ()
						local quest = gv_Quests['TimedTrap'] or QuestGetState('TimedTrap')
						return quest.InitialInteractionDone and quest.SkillCheckSuccess
					end,
				}),
			},
			Effects = {
				PlaceObj('KillTimer', {
					Name = "TimedBomb",
					StopTCE = true,
				}),
			},
			Once = true,
			ParamId = "TCE_KillTimer",
			QuestId = "TimedTrap",
		}),
	},
	Variables = {
		PlaceObj('QuestVarBool', {
			Name = "Completed",
		}),
		PlaceObj('QuestVarBool', {
			Name = "Given",
		}),
		PlaceObj('QuestVarBool', {
			Name = "Failed",
		}),
		PlaceObj('QuestVarBool', {
			Name = "NotStarted",
			Value = true,
		}),
		PlaceObj('QuestVarBool', {
			Name = "InitialInteractionDone",
		}),
		PlaceObj('QuestVarBool', {
			Name = "SkillCheckSuccess",
		}),
		PlaceObj('QuestVarTCEState', {
			Name = "TCE_StartTimer",
		}),
		PlaceObj('QuestVarTCEState', {
			Name = "TCE_KillTimer",
		}),
	},
	group = "Default",
	id = "TimedTrap",
})

