-- ========== GENERATED BY CharacterEffectCompositeDef Editor DO NOT EDIT MANUALLY! ==========

UndefineClass('BulletHell')
DefineClass.BulletHell = {
	__parents = { "Perk" },
	__generated_by_class = "CharacterEffectCompositeDef",


	object_class = "Perk",
	DisplayName = T(702007600283, --[[CharacterEffectCompositeDef BulletHell DisplayName]] "Bullet Hell"),
	Description = T(973701395706, --[[CharacterEffectCompositeDef BulletHell Description]] "<em>Area attack</em> that sends targets <GameTerm('Prone')> and inflicts <GameTerm('Suppressed')>."),
	Icon = "UI/Icons/Perks/BulletHell",
	Tier = "Personal",
}

