-- ========== GENERATED BY CharacterEffectCompositeDef Editor DO NOT EDIT MANUALLY! ==========

UndefineClass('CollateralDamage')
DefineClass.CollateralDamage = {
	__parents = { "Perk" },
	__generated_by_class = "CharacterEffectCompositeDef",


	object_class = "Perk",
	msg_reactions = {
		PlaceObj('MsgActorReaction', {
			ActorParam = "attacker",
			Event = "GatherDamageModifications",
			Handler = function (self, attacker, target, action_id, weapon, attack_args, hit_descr, mod_data)
				
				local function exec(self, attacker, target, action_id, weapon, attack_args, hit_descr, mod_data)
				if not IsKindOf(target, "CombatObject") or not IsKindOfClasses(mod_data.weapon, "HeavyWeapon", "MachineGun") then
					return
				end
					
				if IsKindOf(target,"Unit") then
					if GetCoversAt(target:GetPos()) then
						local damageBonus = self:ResolveValue("enemyDamageMod") 
						mod_data.base_damage = MulDivRound(mod_data.base_damage, 100 + damageBonus, 100)
						mod_data.breakdown[#mod_data.breakdown + 1] = { name = self.DisplayName, value = damageBonus }
					end
				else
					local damageBonus = self:ResolveValue("objectDamageMod") 
					mod_data.base_damage = MulDivRound(mod_data.base_damage, 100 + damageBonus, 100)
					mod_data.breakdown[#mod_data.breakdown + 1] = { name = self.DisplayName, value = damageBonus }
				end
				end
				
				if not IsKindOf(self, "MsgReactionsPreset") then return end
				
				local reaction_def = (self.msg_reactions or empty_table)[1]
				if not reaction_def or reaction_def.Event ~= "GatherDamageModifications" then return end
				
				if not IsKindOf(self, "MsgActorReactionsPreset") then
					exec(self, attacker, target, action_id, weapon, attack_args, hit_descr, mod_data)
				end
				
				if self:VerifyReaction("GatherDamageModifications", reaction_def, attacker, attacker, target, action_id, weapon, attack_args, hit_descr, mod_data) then
					exec(self, attacker, target, action_id, weapon, attack_args, hit_descr, mod_data)
				end
			end,
			HandlerCode = function (self, attacker, target, attack_args, hit_descr, mod_data)
				if not IsKindOf(target, "CombatObject") or not IsKindOfClasses(mod_data.weapon, "HeavyWeapon", "MachineGun") then
					return
				end
					
				if IsKindOf(target,"Unit") then
					if GetCoversAt(target:GetPos()) then
						local damageBonus = self:ResolveValue("enemyDamageMod") 
						mod_data.base_damage = MulDivRound(mod_data.base_damage, 100 + damageBonus, 100)
						mod_data.breakdown[#mod_data.breakdown + 1] = { name = self.DisplayName, value = damageBonus }
					end
				else
					local damageBonus = self:ResolveValue("objectDamageMod") 
					mod_data.base_damage = MulDivRound(mod_data.base_damage, 100 + damageBonus, 100)
					mod_data.breakdown[#mod_data.breakdown + 1] = { name = self.DisplayName, value = damageBonus }
				end
			end,
		}),
	},
	DisplayName = T(462837297109, --[[CharacterEffectCompositeDef CollateralDamage DisplayName]] "Collateral Damage"),
	Description = T(247186377267, --[[CharacterEffectCompositeDef CollateralDamage Description]] "Deal <em><percent(enemyDamageMod)></em> extra <em>Damage</em> to enemies behind cover with <em>Heavy</em> <em>Weapons</em> and <em>Machine Guns</em>.\n\nDeal <em><percent(objectDamageMod)> Damage</em> to objects with <em>Heavy</em> <em>Weapons</em> and <em>Machine Guns</em>."),
	Icon = "UI/Icons/Perks/CollateralDamage",
	Tier = "Gold",
	Stat = "Strength",
	StatValue = 90,
}

