-- ========== GENERATED BY CharacterEffectCompositeDef Editor DO NOT EDIT MANUALLY! ==========

UndefineClass('Panicked')
DefineClass.Panicked = {
	__parents = { "CharacterEffect" },
	__generated_by_class = "CharacterEffectCompositeDef",


	object_class = "CharacterEffect",
	DisplayName = T(179133370621, --[[CharacterEffectCompositeDef Panicked DisplayName]] "Panicked"),
	Description = T(583680307590, --[[CharacterEffectCompositeDef Panicked Description]] "Uncontrollable. Runs away from the enemies."),
	AddEffectText = T(629484886928, --[[CharacterEffectCompositeDef Panicked AddEffectText]] "<em><DisplayName></em> panicked"),
	RemoveEffectText = T(633681873712, --[[CharacterEffectCompositeDef Panicked RemoveEffectText]] "<em><DisplayName></em> calmed down from the Panic"),
	OnAdded = function (self, obj)
		obj:RemoveStatusEffect("Berserk")
		obj:InterruptPreparedAttack()
		if g_Teams[g_CurrentTeam] == obj.team then
			ScheduleMoraleActions()
		end
	end,
	lifetime = "Until End of Next Turn",
	Icon = "UI/Hud/Status effects/panic",
	RemoveOnEndCombat = true,
	Shown = true,
	HasFloatingText = true,
}

