OptionsData.VideoPresetsData = {
	Low = {
		Textures = "Low",
		Shadows = "Low",
		Terrain = "Low",
		Effects = "Low",
		ViewDistance = "Low",
		Antialiasing = { "TAA", "FXAA" },
		ResolutionPercent = "50",
		Upscaling = { "DLSS", "FSR2", "XESS", "Bilinear" },
		Anisotropy = "Off",
		Lights = "Low",
		Postprocess = "Low",
		Bloom = "On",
		EyeAdaptation = "On",
		Vignette = "On",
		ObjectDetail = "Low",
		MaxFps = "240",
		SSAO = "Off",
		SSR = "Off",
	},
	Medium = {
		Textures = "Medium",
		Shadows = "Medium",
		Terrain = "Medium",
		Effects = "Medium",
		ViewDistance = "Medium",
		Antialiasing = { "TAA", "FXAA" },
		ResolutionPercent = "77",
		Upscaling = { "DLSS", "FSR2", "XESS", "FSR" },
		Anisotropy = "2x",
		Lights = "Medium",
		Postprocess = "Medium",
		Bloom = "On",
		EyeAdaptation = "On",
		Vignette = "On",
		ObjectDetail = "Medium",
		MaxFps = "240",
		SSAO = "On",
		SSR = "Medium",
	},
	High = {
		Textures = "High",
		Shadows = "High",
		Terrain = "High",
		Effects = "High",
		ViewDistance = "High",
		Antialiasing = { "TAA", "SMAA" },
		ResolutionPercent = "100",
		Anisotropy = "4x",
		Lights = "High",
		Postprocess = "High",
		Bloom = "On",
		EyeAdaptation = "On",
		Vignette = "On",
		ObjectDetail = "High",
		MaxFps = "240",
		SSAO = "On",
		SSR = "High",
	},
	Ultra = {
		Textures = "Ultra",
		Shadows = "Ultra",
		Terrain = "Ultra",
		Effects = "Ultra",
		ViewDistance = "Ultra",
		Antialiasing = { "TAA", "SMAA" },
		ResolutionPercent = "100",
		Anisotropy = "16x",
		Lights = "High",
		Postprocess = "Ultra",
		Bloom = "On",
		EyeAdaptation = "On",
		Vignette = "On",
		ObjectDetail = "High",
		MaxFps = "240",
		SSAO = "On",
		SSR = "Ultra",
	},
	XboxOne = {
		Textures = "Low (Consoles)",
		Shadows = "Medium (PS4,XboxOne)",
		Terrain = "Medium",
		Effects = "High",
		ViewDistance = "High",
		Antialiasing = "FSR2",
		Anisotropy = "4x",
		ResolutionPercent = "67",
		Lights = "High",
		Postprocess = "Low",
		Bloom = "On",
		EyeAdaptation = "On",
		Vignette = "On",
		FPSCounter = "Off",
		ObjectDetail = "Low",
		SSAO = "Off",
		SSR = "Off",
	},
	XboxOneXQuality = {
		Textures = "Medium (Consoles)",
		Shadows = "High",
		Terrain = "Medium",
		Effects = "High",
		ViewDistance = "High",
		Antialiasing = "FSR2",
		Anisotropy = "8x",
		ResolutionPercent = "77",
		Lights = "High",
		Postprocess = "Low",
		Bloom = "On",
		EyeAdaptation = "On",
		Vignette = "On",
		FPSCounter = "Off",
		ObjectDetail = "Low",
		SSAO = "On",
		SSR = "High",
	},
	XboxOneXPerformance = {
		Textures = "Medium (Consoles)",
		Shadows = "High",
		Terrain = "Medium",
		Effects = "High",
		ViewDistance = "High",
		Antialiasing = "FSR2",
		Anisotropy = "8x",
		ResolutionPercent = "59",
		Lights = "High",
		Postprocess = "Low",
		Bloom = "On",
		EyeAdaptation = "On",
		Vignette = "On",
		FPSCounter = "Off",
		ObjectDetail = "Low",
		SSAO = "On",
		SSR = "High",
	},
	XboxSeriesSQuality = {
		Textures = "High",
		Shadows = "High",
		Terrain = "High",
		Effects = "High",
		ViewDistance = "High",
		Antialiasing = "FSR2",
		Anisotropy = "4x",
		ResolutionPercent = "77",
		Lights = "High",
		Postprocess = "High",
		Bloom = "On",
		EyeAdaptation = "On",
		Vignette = "On",
		ObjectDetail = "High",
		FPSCounter = "Off",
		SSAO = "On",
		SSR = "Medium",
	},
	XboxSeriesSPerformance = {
		Textures = "High",
		Shadows = "High",
		Terrain = "High",
		Effects = "High",
		ViewDistance = "High",
		Antialiasing = "FSR2",
		Anisotropy = "4x",
		ResolutionPercent = "59",
		Lights = "High",
		Postprocess = "High",
		Bloom = "On",
		EyeAdaptation = "On",
		Vignette = "On",
		ObjectDetail = "High",
		FPSCounter = "Off",
		SSAO = "On",
		SSR = "Medium",
	},
	XboxSeriesXQuality = {
		Textures = "Ultra",
		Shadows = "High",
		Terrain = "High",
		Effects = "High",
		ViewDistance = "High",
		Antialiasing = "FSR2",
		Anisotropy = "8x",
		ResolutionPercent = "100",
		Lights = "High",
		Postprocess = "High",
		Bloom = "On",
		EyeAdaptation = "On",
		Vignette = "On",
		ObjectDetail = "High",
		FPSCounter = "Off",
		SSAO = "On",
		SSR = "Medium",
	},
	XboxSeriesXPerformance = {
		Textures = "Ultra",
		Shadows = "High",
		Terrain = "High",
		Effects = "High",
		ViewDistance = "High",
		Antialiasing = "FSR2",
		Anisotropy = "4x",
		ResolutionPercent = "77",
		Lights = "High",
		Postprocess = "High",
		Bloom = "On",
		EyeAdaptation = "On",
		Vignette = "On",
		ObjectDetail = "High",
		FPSCounter = "Off",
		SSAO = "On",
		SSR = "Medium",
	},
	PS4 = {
		Textures = "Medium (Consoles)",
		Shadows = "Medium (PS4,XboxOne)",
		Terrain = "Medium",
		Effects = "High",
		ViewDistance = "High",
		Antialiasing = "FXAA",
		Anisotropy = "4x",
		ResolutionPercent = "100",
		Lights = "High",
		Postprocess = "Medium",
		Bloom = "On",
		EyeAdaptation = "On",
		Vignette = "On",
		ObjectDetail = "Low",
		FPSCounter = "Off",
		SSAO = "Off",
		SSR = "Off",
	},
	PS4Pro = {
		Textures = "Medium (Consoles)",
		Shadows = "High (PS4Pro)",
		Terrain = "Medium",
		Effects = "High",
		ViewDistance = "High",
		Antialiasing = "FXAA",
		Anisotropy = "8x",
		ResolutionPercent = "100",
		Lights = "High",
		Postprocess = "Medium",
		Bloom = "On",
		EyeAdaptation = "On",
		Vignette = "On",
		ObjectDetail = "Low",
		FPSCounter = "Off",
		SSAO = "On",
		SSR = "High",
	},
	PS5Quality = {
		Textures = "Ultra",
		Shadows = "High",
		Terrain = "Ultra",
		Effects = "Ultra",
		ViewDistance = "Ultra",
		Antialiasing = "SMAA",
		Anisotropy = "16x",
		ResolutionPercent = "100",
		Lights = "High",
		Postprocess = "High",
		Bloom = "On",
		EyeAdaptation = "On",
		Vignette = "On",
		ObjectDetail = "High",
		FPSCounter = "Off",
		SSAO = "On",
		SSR = "Medium",
	},
	PS5Performance = {
		Textures = "High",
		Shadows = "High",
		Terrain = "High",
		Effects = "High",
		ViewDistance = "High",
		Antialiasing = "SMAA",
		Anisotropy = "8x",
		ResolutionPercent = "77",
		Lights = "High",
		Postprocess = "Medium",
		Bloom = "On",
		EyeAdaptation = "On",
		Vignette = "On",
		ObjectDetail = "High",
		FPSCounter = "Off",
		SSAO = "On",
		SSR = "Medium",
	},
	Switch = {
		Textures = "Low",
		Shadows = "Low (Switch)",
		Terrain = "Low",
		Effects = "Low (Switch)",
		ViewDistance = "Low (Switch)",
		ObjectDetail = "Very Low",
		Antialiasing = "FXAA",
		Anisotropy = "2x",
		ResolutionPercent = "switch",
		Lights = "Low",
		Postprocess = "Low",
		Bloom = "Off",
		EyeAdaptation = "On",
		Vignette = "Off",
		FPSCounter = "Off",
		MaxFps = "Unlimited",
		SSAO = "Off",
		SSR = "Off",
	},
	SteamDeck = {
		Textures = "High",
		Shadows = "Medium",
		Terrain = "High",
		Effects = "High",
		ViewDistance = "High",
		Antialiasing = "FSR2",
		Anisotropy = "2x",
		ResolutionPercent = "77",
		Lights = "High",
		Postprocess = "High",
		Bloom = "On",
		EyeAdaptation = "On",
		Vignette = "On",
		ObjectDetail = "Medium",
		MaxFps = "30",
		SSAO = "On",
		SSR = "Medium",
		Vsync = true,
	},
}

local ExcludeFromPresetCheck =
{
	Vsync = true,
	FPSCounter = true,
}

if FirstLoad then
	PresetVideoOptions = {}
	for preset, vals in pairs(OptionsData.VideoPresetsData) do
		for k, _ in pairs(vals) do
			if not ExcludeFromPresetCheck[k] then
				PresetVideoOptions[k] = true
			end
		end
	end
end

OptionsData.Options.ObjectDetail = {
	{ value = "Low", text = T(215633457448, --[[options:Object detail is turned to Low]] "Low"),
		ObjectLODPercents = 50, Optionals = 50, EyeCandies = 33,
		hr = { ObjectLODCapMin = 1, LightShadowsDetailLevel = 1, LightShadowsMinContribDistance = 40, },
	},
	{ value = "Medium", text = T(679289081998, --[[options:Object detail is turned to Medium]] "Medium"),
		ObjectLODPercents = 75, Optionals = 75, EyeCandies = 66,
		hr = { ObjectLODCapMin = 0, LightShadowsDetailLevel = 2, LightShadowsMinContribDistance = 60, },
	},
	{ value = "High", text = T(564085803851, --[[options:Object detail is turned to High]] "High"),
		ObjectLODPercents = 100,  Optionals = 100, EyeCandies = 100,
		hr = { ObjectLODCapMin = 0, LightShadowsDetailLevel = 3, LightShadowsMinContribDistance = 100, },
	},
}

AppendClass.OptionsObject = {
	properties = {
		{ id = "Gamepad", no_edit = true },
		{ id = "DisplayAreaMargin", no_edit = true },
	},
}

function HideChangeUserCategory()
	return true
end

function AccountOptionFixups.CameraShakeStorage(account_options)
	if EngineOptions and EngineOptions.CameraShake then
		account_options.CameraShake = EngineOptions.CameraShake
	end
end

function AccountOptionFixups.ActivePauseStorage(account_options)
	if EngineOptions and EngineOptions.ActivePauseMode then
		account_options.ActivePauseMode = EngineOptions.ActivePauseMode
	end
end

function AccountOptionFixups.DifficultyStorage(account_options)
	if EngineOptions and EngineOptions.Difficulty then
		account_options.Difficulty = EngineOptions.Difficulty
	end
end

function AccountOptionFixups.ForgivingModeStorage(account_options)
	if EngineOptions and EngineOptions.ForgivingModeToggle then
		account_options.ForgivingModeToggle = EngineOptions.ForgivingModeToggle
	end
end