-- ========== GENERATED BY Conversation Editor DO NOT EDIT MANUALLY! ==========

PlaceObj('Conversation', {
	AssignToGroup = "Herman",
	Comment = "The player finds Herman standing n a minefield with several legionaires torturing him by threatening to shoot the mine.",
	Conditions = {
		PlaceObj('PlayerIsInSectors', {
			Sectors = {
				"I3",
			},
		}),
		PlaceObj('QuestIsVariableBool', {
			QuestId = "RescueHerMan",
			Vars = {
				HermanRescued = false,
				RaidersDefeated = false,
			},
			__eval = function ()
				local quest = gv_Quests['RescueHerMan'] or QuestGetState('RescueHerMan')
				return not quest.HermanRescued and not quest.RaidersDefeated
			end,
		}),
		PlaceObj('CombatIsActive', {
			Negate = true,
		}),
	},
	DefaultActor = "LegionRaider",
	group = "Ernie",
	id = "Herman_1",
	PlaceObj('ConversationPhrase', {
		Comment = "Conversation starter",
		Effects = {
			PlaceObj('QuestSetVariableBool', {
				Prop = "RaidersMet",
				QuestId = "RescueHerMan",
			}),
		},
		Keyword = "Greeting",
		KeywordT = T(774381032385, --[[Conversation Herman_1 KeywordT]] "Greeting"),
		Lines = {
			PlaceObj('ConversationLine', {
				AlwaysInterject = true,
				Character = "LegionRaider",
				SoundAfter = "Sounds/ConversationEffects/Herman_shots.wav",
				Text = T(651040808250, --[[Conversation Herman_1 Text voice:LegionRaider section:Herman_1 keyword:Greeting2]] "Herman, you dance like a pregnant warthog! Get those knees up!"),
			}),
			PlaceObj('ConversationLine', {
				Character = "Herman",
				Text = T(282865324856, --[[Conversation Herman_1 Text voice:Herman section:Herman_1 keyword:Greeting2]] "But I don't understand! I told you what you wanted to know!"),
			}),
			PlaceObj('ConversationLine', {
				AlwaysInterject = true,
				Character = "LegionRaider",
				Text = T(124111237846, --[[Conversation Herman_1 Text voice:LegionRaider section:Herman_1 keyword:Greeting2]] "Yes, you ratted out your friend. Well done. Now, I want you to dance in a <em>minefield</em>. If you survive, you get paid."),
			}),
			PlaceObj('ConversationLine', {
				Character = "Herman",
				Text = T(357107362756, --[[Conversation Herman_1 Text voice:Herman section:Herman_1 keyword:Greeting2]] "Keep your money, just let me go!..."),
			}),
			PlaceObj('ConversationLine', {
				AlwaysInterject = true,
				Character = "Herman",
				SoundBefore = "Sounds/ConversationEffects/iact_steponmine1m.wav",
				Text = T(858245047843, --[[Conversation Herman_1 Text voice:Herman section:Herman_1 keyword:Greeting2]] "...Oh sweet Jesus, I think I just stepped on one..."),
			}),
		},
		id = "Greeting2",
	}),
	PlaceObj('ConversationPhrase', {
		Align = "right",
		AutoRemove = true,
		Comment = "Forces combat with the legionaires",
		GoTo = "CombatRedirect",
		Keyword = "Let him go",
		KeywordT = T(791279735899, --[[Conversation Herman_1 KeywordT]] "Let him go"),
		Lines = {
			PlaceObj('ConversationInterjectionList', {
				Interjections = {
					PlaceObj('ConversationInterjection', {
						Lines = {
							PlaceObj('ConversationLine', {
								Character = "Raider",
								Text = T(165306391611, --[[Conversation Herman_1 Text voice:Raider section:Herman_1 keyword:Let him go]] "Sir, I'm going to have to ask you to cease discharging your firearm at the man in the minefield."),
							}),
						},
					}),
					PlaceObj('ConversationInterjection', {
						Lines = {
							PlaceObj('ConversationLine', {
								Character = "Grizzly",
								Text = T(350171780028, --[[Conversation Herman_1 Text voice:Grizzly section:Herman_1 keyword:Let him go]] "Cut the crap, buttwad. Let him go."),
							}),
						},
					}),
					PlaceObj('ConversationInterjection', {
						Lines = {
							PlaceObj('ConversationLine', {
								Character = "Livewire",
								Text = T(235599288424, --[[Conversation Herman_1 Text voice:Livewire section:Herman_1 keyword:Let him go]] "Perhaps it is not my place to say, but I really think you are being very mean to that man."),
							}),
						},
					}),
				},
			}),
		},
		PlayGoToPhrase = true,
		StoryBranchIcon = "conversation_action",
		id = "Friendly",
	}),
	PlaceObj('ConversationPhrase', {
		Align = "right",
		AutoRemove = true,
		Comment = "When a merc can scare away the legionaires",
		Conditions = {
			PlaceObj('UnitSquadHasMerc', {
				HasPerk = "Psycho",
			}),
		},
		Effects = {
			PlaceObj('GroupSetBehaviorExit', {
				MarkerGroup = "North",
				Running = true,
				TargetUnit = "HermanRaiders",
				UseWeapons = true,
			}),
			PlaceObj('GroupSetBehaviorIdle', {
				TargetUnit = "Herman",
			}),
			PlaceObj('QuestSetVariableBool', {
				Prop = "RaidersDefeated",
				QuestId = "RescueHerMan",
			}),
			PlaceObj('GrantExperienceSector', {
				Amount = "XPQuestReward_Minor",
			}),
		},
		GoTo = "<end conversation>",
		Keyword = "Get out of here",
		KeywordT = T(118462598598, --[[Conversation Herman_1 KeywordT]] "Get out of here"),
		Lines = {
			PlaceObj('ConversationInterjectionList', {
				Interjections = {
					PlaceObj('ConversationInterjection', {
						Lines = {
							PlaceObj('ConversationLine', {
								Character = "Fidel",
								Text = T(306228815291, --[[Conversation Herman_1 Text voice:Fidel section:Herman_1 keyword:Get out of here]] "Fidel likes mines, too! Maybe I take these mines. Maybe you run away while you still have legs!"),
							}),
						},
					}),
					PlaceObj('ConversationInterjection', {
						Lines = {
							PlaceObj('ConversationLine', {
								Character = "Meltdown",
								Text = T(919290748274, --[[Conversation Herman_1 Text voice:Meltdown section:Herman_1 keyword:Get out of here]] "There's just one fucking mine field between you and me, dumbass. And guess what, my bullets don't need boots to cross it."),
							}),
						},
					}),
				},
			}),
			PlaceObj('ConversationLine', {
				Character = "LegionRaider",
				Text = T(483250742133, --[[Conversation Herman_1 Text voice:LegionRaider section:Herman_1 keyword:Get out of here]] "Okay, fine. Forget it. Fun's over, I guess. Let's go find some more booze."),
			}),
		},
		StoryBranchIcon = "conversation_action",
		VariantPhrase = true,
		id = "Intimidate",
	}),
	PlaceObj('ConversationPhrase', {
		Align = "right",
		AutoRemove = true,
		Comment = "A merc tries to scare the legionaires but fails",
		Conditions = {
			PlaceObj('UnitSquadHasMerc', {
				HasPerk = "Psycho",
				Negate = true,
			}),
		},
		GoTo = "CombatRedirect",
		Keyword = "Get out of here",
		KeywordT = T(118462598598, --[[Conversation Herman_1 KeywordT]] "Get out of here"),
		Lines = {
			PlaceObj('ConversationInterjectionList', {
				Interjections = {
					PlaceObj('ConversationInterjection', {
						Lines = {
							PlaceObj('ConversationLine', {
								Character = "Steroid",
								Text = T(106727324111, --[[Conversation Herman_1 Text voice:Steroid section:Herman_1 keyword:Get out of here]] "Make like a leaf and split!"),
							}),
						},
					}),
					PlaceObj('ConversationInterjection', {
						Lines = {
							PlaceObj('ConversationLine', {
								Character = "Raven",
								Text = T(160940183001, --[[Conversation Herman_1 Text voice:Raven section:Herman_1 keyword:Get out of here]] "Cease, desist, and disperse!"),
							}),
						},
					}),
					PlaceObj('ConversationInterjection', {
						Lines = {
							PlaceObj('ConversationLine', {
								Character = "Wolf",
								Text = T(575037729025, --[[Conversation Herman_1 Text voice:Wolf section:Herman_1 keyword:Get out of here]] "All right, fun's over. Take a hike."),
							}),
						},
					}),
				},
			}),
		},
		PlayGoToPhrase = true,
		StoryBranchIcon = "conversation_action",
		id = "GetOutOfHere",
	}),
	PlaceObj('ConversationPhrase', {
		Align = "right",
		Effects = {
			PlaceObj('GroupSetSide', {
				Side = "enemy1",
				TargetUnit = "HermanRaiders",
			}),
			PlaceObj('GroupAlert', {
				TargetUnit = "HermanRaiders",
			}),
		},
		Enabled = false,
		GoTo = "<end conversation>",
		Keyword = "CombatRedirect",
		KeywordT = T(236527406375, --[[Conversation Herman_1 KeywordT]] "CombatRedirect"),
		Lines = {
			PlaceObj('ConversationLine', {
				Character = "LegionRaider",
				Text = T(887141502836, --[[Conversation Herman_1 Text voice:LegionRaider section:Herman_1 keyword:CombatRedirect]] "Who are you?! No, don't tell me, I don't care. First we kill you, then this rat here."),
			}),
		},
		StoryBranchIcon = "conversation_action",
		id = "CombatRedirect",
	}),
	PlaceObj('ConversationPhrase', {
		Align = "right",
		Comment = "Alternate way to trigger combat",
		Effects = {
			PlaceObj('GroupSetSide', {
				Side = "enemy1",
				TargetUnit = "HermanRaiders",
			}),
			PlaceObj('GroupAlert', {
				TargetUnit = "HermanRaiders",
			}),
		},
		GoTo = "<end conversation>",
		Keyword = "Die!",
		KeywordT = T(482976736771, --[[Conversation Herman_1 KeywordT]] "Die!"),
		Lines = {
			PlaceObj('ConversationLine', {
				Character = "LegionRaider",
				Text = T(924177724087, --[[Conversation Herman_1 Text voice:LegionRaider section:Herman_1 keyword:Die!]] "Merde! Kill them all!"),
			}),
		},
		StoryBranchIcon = "conversation_attack",
		id = "Attack",
	}),
})

