-- ========== GENERATED BY Conversation Editor DO NOT EDIT MANUALLY! ==========

PlaceObj('Conversation', {
	AssignToGroup = "TimTurtledove",
	Conditions = {
		PlaceObj('CheckOR', {
			Conditions = {
				PlaceObj('QuestIsVariableBool', {
					QuestId = "PantagruelClinic",
					Vars = set({
	ClinicWorking = false,
}),
					__eval = function ()
						local quest = gv_Quests['PantagruelClinic'] or QuestGetState('PantagruelClinic')
						return not quest.ClinicWorking
					end,
				}),
				PlaceObj('QuestIsVariableBool', {
					QuestId = "RebelManifesto",
					Vars = set({
	Completed = false,
	Failed = false,
	PamphletsGiven_Turtledove = false,
}),
					__eval = function ()
						local quest = gv_Quests['RebelManifesto'] or QuestGetState('RebelManifesto')
						return not quest.Completed and not quest.Failed and not quest.PamphletsGiven_Turtledove
					end,
				}),
			},
		}),
	},
	DefaultActor = "TimTurtledove",
	Parameters = {
		PlaceObj('PresetParamNumber', {
			'Name', "MoneyPay_High",
			'Value', 3000,
			'Tag', "<MoneyPay_High>",
		}),
		PlaceObj('PresetParamNumber', {
			'Name', "MoneyPay_Low",
			'Value', 1000,
			'Tag', "<MoneyPay_Low>",
		}),
	},
	disabledInConflict = true,
	group = "Savanna - Pantagruel",
	id = "TimTurtledove_1",
	PlaceObj('ConversationPhrase', {
		AutoRemove = true,
		Conditions = {
			PlaceObj('QuestIsVariableBool', {
				QuestId = "PantagruelClinic",
				Vars = set({
	ClinicWorking = false,
	MaquisConvinced = true,
}),
				__eval = function ()
					local quest = gv_Quests['PantagruelClinic'] or QuestGetState('PantagruelClinic')
					return not quest.ClinicWorking and quest.MaquisConvinced
				end,
			}),
			PlaceObj('QuestIsVariableBool', {
				QuestId = "PantagruelRebels",
				Vars = set({
	MaquieDefeated = false,
}),
				__eval = function ()
					local quest = gv_Quests['PantagruelRebels'] or QuestGetState('PantagruelRebels')
					return not quest.MaquieDefeated
				end,
			}),
		},
		GoTo = "Redirect",
		Keyword = "Greeting",
		KeywordT = T(774381032385, --[[Conversation TimTurtledove_1 KeywordT]] "Greeting"),
		Lines = {
			PlaceObj('ConversationLine', {
				Character = "TimTurtledove",
				Text = T(128880374950, --[[Conversation TimTurtledove_1 Text voice:TimTurtledove section:TimTurtledove_1 keyword:Greeting3]] "Happy to see you again! Mister <em>Chimurenga</em> has informed me that he decided to agree with our terms and conditions. You must have been very persuasive! Now..."),
			}),
		},
		PlayGoToPhrase = true,
		id = "Greeting3",
	}),
	PlaceObj('ConversationPhrase', {
		AutoRemove = true,
		Conditions = {
			PlaceObj('QuestIsVariableBool', {
				QuestId = "PantagruelClinic",
				Vars = set({
	ClinicWorking = false,
}),
				__eval = function ()
					local quest = gv_Quests['PantagruelClinic'] or QuestGetState('PantagruelClinic')
					return not quest.ClinicWorking
				end,
			}),
		},
		Keyword = "Greeting",
		KeywordT = T(774381032385, --[[Conversation TimTurtledove_1 KeywordT]] "Greeting"),
		Lines = {
			PlaceObj('ConversationLine', {
				Character = "TimTurtledove",
				Text = T(101875456038, --[[Conversation TimTurtledove_1 Text voice:TimTurtledove section:TimTurtledove_1 keyword:Greeting]] 'Hello there! Welcome to the <em>"Vulture of Hope"</em> - the best <em>clinic</em> in the region! We shall start our life saving operations any day now!... As soon as we solve a <em>minor issue</em> or two.'),
			}),
		},
		id = "Greeting",
	}),
	PlaceObj('ConversationPhrase', {
		Conditions = {
			PlaceObj('QuestIsVariableBool', {
				QuestId = "PantagruelClinic",
				Vars = set({
	ClinicWorking = false,
}),
				__eval = function ()
					local quest = gv_Quests['PantagruelClinic'] or QuestGetState('PantagruelClinic')
					return not quest.ClinicWorking
				end,
			}),
		},
		Keyword = "Greeting",
		KeywordT = T(774381032385, --[[Conversation TimTurtledove_1 KeywordT]] "Greeting"),
		Lines = {
			PlaceObj('ConversationLine', {
				Character = "TimTurtledove",
				Text = T(634563883125, --[[Conversation TimTurtledove_1 Text voice:TimTurtledove section:TimTurtledove_1 keyword:Greeting2]] 'Happy to see you again at the <em>"Vulture of Hope"</em>!'),
			}),
			PlaceObj('ConversationLine', {
				AlwaysInterject = true,
				Character = "TimTurtledove",
				Text = T(777905008101, --[[Conversation TimTurtledove_1 Text voice:TimTurtledove section:TimTurtledove_1 keyword:Greeting2]] "Regrettably, we still have some <em>minor issues</em> to solve before we open for business."),
			}),
		},
		id = "Greeting2",
	}),
	PlaceObj('ConversationPhrase', {
		Keyword = "Greeting",
		KeywordT = T(774381032385, --[[Conversation TimTurtledove_1 KeywordT]] "Greeting"),
		Lines = {
			PlaceObj('ConversationLine', {
				Character = "TimTurtledove",
				Text = T(334611384676, --[[Conversation TimTurtledove_1 Text voice:TimTurtledove section:TimTurtledove_1 keyword:Greeting4]] 'Happy to see you again at the <em>"Vulture of Hope"</em>!'),
			}),
		},
		id = "Greeting4",
	}),
	PlaceObj('ConversationPhrase', {
		Effects = {
			PlaceObj('QuestSetVariableBool', {
				Prop = "MentionBoard",
				QuestId = "PantagruelClinic",
			}),
		},
		Keyword = "Vulture of hope?!",
		KeywordT = T(145183128025, --[[Conversation TimTurtledove_1 KeywordT]] "Vulture of Hope?!"),
		Lines = {
			PlaceObj('ConversationLine', {
				Character = "TimTurtledove",
				Text = T(848908825826, --[[Conversation TimTurtledove_1 Text voice:TimTurtledove section:TimTurtledove_1 keyword:Vulture of hope?!]] 'Yes! We wanted to name the clinic "The Dove of Hope", but the <em>Donation Board</em> pointed out that we need to be more sensitive to the local heritage, so we were asked to pick a local bird.'),
			}),
			PlaceObj('ConversationInterjectionList', {
				Interjections = {
					PlaceObj('ConversationInterjection', {
						Lines = {
							PlaceObj('ConversationLine', {
								Character = "Len",
								Text = T(450201943319, --[[Conversation TimTurtledove_1 Text voice:Len section:TimTurtledove_1 keyword:Vulture of hope?!]] '"The Vulture of Hope" sounds just about right for this place.'),
							}),
						},
					}),
					PlaceObj('ConversationInterjection', {
						Lines = {
							PlaceObj('ConversationLine', {
								Character = "MD",
								Text = T(537753545300, --[[Conversation TimTurtledove_1 Text voice:MD section:TimTurtledove_1 keyword:Vulture of hope?!]] "Well, I suppose having a name like that is one way to cut down on ER visits."),
							}),
						},
					}),
					PlaceObj('ConversationInterjection', {
						Lines = {
							PlaceObj('ConversationLine', {
								Character = "Raven",
								Text = T(748062459896, --[[Conversation TimTurtledove_1 Text voice:Raven section:TimTurtledove_1 keyword:Vulture of hope?!]] 'You should have called it "The Raven of Hope." Has a nicer ring to it.'),
							}),
							PlaceObj('ConversationLine', {
								Character = "TimTurtledove",
								Text = T(846095687591, --[[Conversation TimTurtledove_1 Text voice:TimTurtledove section:TimTurtledove_1 keyword:Vulture of hope?!]] "Ah, well, you see there aren't any ravens around these parts."),
							}),
							PlaceObj('ConversationLine', {
								Character = "Raven",
								Text = T(186919453756, --[[Conversation TimTurtledove_1 Text voice:Raven section:TimTurtledove_1 keyword:Vulture of hope?!]] "No, there is one."),
							}),
							PlaceObj('ConversationLine', {
								Character = "TimTurtledove",
								Text = T(145222012570, --[[Conversation TimTurtledove_1 Text voice:TimTurtledove section:TimTurtledove_1 keyword:Vulture of hope?!]] "One?"),
							}),
							PlaceObj('ConversationLine', {
								Character = "Raven",
								Text = T(558678091281, --[[Conversation TimTurtledove_1 Text voice:Raven section:TimTurtledove_1 keyword:Vulture of hope?!]] "Never more."),
							}),
						},
					}),
					PlaceObj('ConversationInterjection', {
						Lines = {
							PlaceObj('ConversationLine', {
								Character = "Flay",
								Text = T(368399379310, --[[Conversation TimTurtledove_1 Text voice:Flay section:TimTurtledove_1 keyword:Vulture of hope?!]] "This name is good. The vulture, she is strong, resilient and... uh, very good at sanitation. Nature's janitors, no?"),
							}),
						},
					}),
					PlaceObj('ConversationInterjection', {
						Lines = {
							PlaceObj('ConversationLine', {
								Character = "DrQ",
								Text = T(122971123642, --[[Conversation TimTurtledove_1 Text voice:DrQ section:TimTurtledove_1 keyword:Vulture of hope?!]] 'The "Quail of Hope" was not acceptable?'),
							}),
							PlaceObj('ConversationLine', {
								Character = "TimTurtledove",
								Text = T(899075650246, --[[Conversation TimTurtledove_1 Text voice:TimTurtledove section:TimTurtledove_1 keyword:Vulture of hope?!]] "The Board thought it sounded too scary."),
							}),
						},
					}),
					PlaceObj('ConversationInterjection', {
						Lines = {
							PlaceObj('ConversationLine', {
								Character = "Reaper",
								Text = T(285753705863, --[[Conversation TimTurtledove_1 Text voice:Reaper section:TimTurtledove_1 keyword:Vulture of hope?!]] "I think it's rather elegant."),
							}),
						},
					}),
				},
				MaxPlayed = 2,
			}),
		},
		StoryBranchIcon = "conversation_sarcastic",
		id = "Vultureofhope",
	}),
	PlaceObj('ConversationPhrase', {
		Conditions = {
			PlaceObj('QuestIsVariableBool', {
				QuestId = "PantagruelClinic",
				Vars = set( "MentionBoard" ),
				__eval = function ()
					local quest = gv_Quests['PantagruelClinic'] or QuestGetState('PantagruelClinic')
					return quest.MentionBoard
				end,
			}),
		},
		Keyword = "What is this Donation Board?",
		KeywordT = T(336933393565, --[[Conversation TimTurtledove_1 KeywordT]] "What is this Donation Board?"),
		Lines = {
			PlaceObj('ConversationLine', {
				Character = "TimTurtledove",
				Text = T(156689551346, --[[Conversation TimTurtledove_1 Text voice:TimTurtledove section:TimTurtledove_1 keyword:What is this Donation Board?]] "Well, the money for the hospital comes from donations, and the good madams and sirs on the Donation Board make sure it is well spent!"),
			}),
		},
		id = "WhatisthisAuditoryBoard",
	}),
	PlaceObj('ConversationPhrase', {
		AutoRemove = true,
		Conditions = {
			PlaceObj('QuestIsVariableBool', {
				QuestId = "PantagruelClinic",
				Vars = set({
	ClinicWorking = false,
}),
				__eval = function ()
					local quest = gv_Quests['PantagruelClinic'] or QuestGetState('PantagruelClinic')
					return not quest.ClinicWorking
				end,
			}),
		},
		Effects = {
			PlaceObj('QuestSetVariableBool', {
				Prop = "MentionMilitia",
				QuestId = "PantagruelClinic",
			}),
		},
		Keyword = "A clinic?",
		KeywordT = T(168510120417, --[[Conversation TimTurtledove_1 KeywordT]] "A clinic?"),
		Lines = {
			PlaceObj('ConversationLine', {
				Character = "TimTurtledove",
				Text = T(613079693202, --[[Conversation TimTurtledove_1 Text voice:TimTurtledove section:TimTurtledove_1 keyword:A clinic?]] "This country has its problems and one of the worst is the lack of quality healthcare! We have a mission to provide it, free of charge, to any and all <em>civilians</em> who need it."),
			}),
			PlaceObj('ConversationInterjectionList', {
				Interjections = {
					PlaceObj('ConversationInterjection', {
						Lines = {
							PlaceObj('ConversationLine', {
								Character = "Larry_Clean",
								Text = T(130577550544, --[[Conversation TimTurtledove_1 Text voice:Larry_Clean section:TimTurtledove_1 keyword:A clinic?]] "Man, that is so great. I just love free clinics."),
							}),
						},
					}),
					PlaceObj('ConversationInterjection', {
						Lines = {
							PlaceObj('ConversationLine', {
								Character = "Shadow",
								Text = T(334560438110, --[[Conversation TimTurtledove_1 Text voice:Shadow section:TimTurtledove_1 keyword:A clinic?]] "So I'll need a convincing disguise. Got it."),
							}),
						},
					}),
					PlaceObj('ConversationInterjection', {
						Lines = {
							PlaceObj('ConversationLine', {
								Character = "Steroid",
								Text = T(824110472642, --[[Conversation TimTurtledove_1 Text voice:Steroid section:TimTurtledove_1 keyword:A clinic?]] "I am very civil. I am civiler even than you, I bet!"),
							}),
						},
					}),
				},
			}),
			PlaceObj('ConversationLine', {
				Character = "TimTurtledove",
				Text = T(970102058883, --[[Conversation TimTurtledove_1 Text voice:TimTurtledove section:TimTurtledove_1 keyword:A clinic?]] "You fine people wouldn't really qualify for free aid, because you're not civilians, nor local <em>militia</em>. But once we open for business, we can provide you with medical assistance at some very reasonable prices!"),
			}),
		},
		id = "Aclinic",
	}),
	PlaceObj('ConversationPhrase', {
		AutoRemove = true,
		Conditions = {
			PlaceObj('QuestIsVariableBool', {
				QuestId = "PantagruelDramas",
				Vars = set({
	ChimurengaDead = false,
	ChimurengaEnemy = false,
	ChimurengaLeave = false,
	MaquisPamphletsAd = true,
}),
				__eval = function ()
					local quest = gv_Quests['PantagruelDramas'] or QuestGetState('PantagruelDramas')
					return not quest.ChimurengaDead and not quest.ChimurengaEnemy and not quest.ChimurengaLeave and quest.MaquisPamphletsAd
				end,
			}),
			PlaceObj('QuestIsVariableBool', {
				QuestId = "PantagruelClinic",
				Vars = set( "MentionMaquis", "MentionMilitia" ),
				__eval = function ()
					local quest = gv_Quests['PantagruelClinic'] or QuestGetState('PantagruelClinic')
					return quest.MentionMaquis and quest.MentionMilitia
				end,
			}),
			PlaceObj('QuestIsVariableBool', {
				QuestId = "RebelManifesto",
				Vars = set({
	PamphletsGiven_Turtledove = false,
}),
				__eval = function ()
					local quest = gv_Quests['RebelManifesto'] or QuestGetState('RebelManifesto')
					return not quest.PamphletsGiven_Turtledove
				end,
			}),
			PlaceObj('UnitSquadHasItem', {
				ItemId = "Pamphlets_LysRouge",
			}),
		},
		Effects = {
			PlaceObj('CityGrantLoyalty', {
				Amount = 5,
				City = "Pantagruel",
				SpecialConversationMessage = T(637084225216, --[[Conversation TimTurtledove_1 SpecialConversationMessage]] "Maquis Manifesto"),
			}),
			PlaceObj('QuestSetVariableBool', {
				Prop = "PamphletsGiven_Turtledove",
				QuestId = "RebelManifesto",
			}),
			PlaceObj('QuestSetVariableNum', {
				Amount = 1,
				Prop = "PamphletsGiven",
				QuestId = "RebelManifesto",
			}),
		},
		Keyword = "Read this Maquis Manifesto",
		KeywordT = T(576499920250, --[[Conversation TimTurtledove_1 KeywordT]] "Read this Maquis Manifesto"),
		Lines = {
			PlaceObj('ConversationLine', {
				Character = "TimTurtledove",
				Text = T(909622042215, --[[Conversation TimTurtledove_1 Text voice:TimTurtledove section:TimTurtledove_1 keyword:Read this Maquis Manifesto]] "This is very, um, interesting. Are these young ladies from the... Yes, I see. Maybe I should pay them a visit to, um, survey them about their medical needs."),
			}),
			PlaceObj('ConversationInterjectionList', {
				Interjections = {
					PlaceObj('ConversationInterjection', {
						Lines = {
							PlaceObj('ConversationLine', {
								Character = "Hitman",
								Text = T(864245799937, --[[Conversation TimTurtledove_1 Text voice:Hitman section:TimTurtledove_1 keyword:Read this Maquis Manifesto]] "I would survey them as well! I'd survey them big time."),
							}),
						},
					}),
					PlaceObj('ConversationInterjection', {
						Lines = {
							PlaceObj('ConversationLine', {
								Character = "Wolf",
								Text = T(866003849449, --[[Conversation TimTurtledove_1 Text voice:Wolf section:TimTurtledove_1 keyword:Read this Maquis Manifesto]] "Survey them, huh? Well, that's a new one."),
							}),
						},
					}),
					PlaceObj('ConversationInterjection', {
						Lines = {
							PlaceObj('ConversationLine', {
								Character = "Red",
								Text = T(412664477000, --[[Conversation TimTurtledove_1 Text voice:Red section:TimTurtledove_1 keyword:Read this Maquis Manifesto]] "If ye plan on taking notes, just make sure your pen is sterilized, lad."),
							}),
						},
					}),
				},
			}),
		},
		PhraseRolloverText = T(879369141361, --[[Conversation TimTurtledove_1 PhraseRolloverText]] "Give a propaganda pamphlet"),
		StoryBranchIcon = "conversation_action",
		id = "ReadthisMaquisManifesto1",
	}),
	PlaceObj('ConversationPhrase', {
		AutoRemove = true,
		Conditions = {
			PlaceObj('QuestIsVariableBool', {
				QuestId = "PantagruelDramas",
				Vars = set({
	ChimurengaDead = false,
	ChimurengaEnemy = false,
	ChimurengaLeave = false,
	MaquisPamphlets = true,
}),
				__eval = function ()
					local quest = gv_Quests['PantagruelDramas'] or QuestGetState('PantagruelDramas')
					return not quest.ChimurengaDead and not quest.ChimurengaEnemy and not quest.ChimurengaLeave and quest.MaquisPamphlets
				end,
			}),
			PlaceObj('QuestIsVariableBool', {
				QuestId = "PantagruelClinic",
				Vars = set( "MentionMaquis", "MentionMilitia" ),
				__eval = function ()
					local quest = gv_Quests['PantagruelClinic'] or QuestGetState('PantagruelClinic')
					return quest.MentionMaquis and quest.MentionMilitia
				end,
			}),
			PlaceObj('QuestIsVariableBool', {
				QuestId = "RebelManifesto",
				Vars = set({
	PamphletsGiven_Turtledove = false,
}),
				__eval = function ()
					local quest = gv_Quests['RebelManifesto'] or QuestGetState('RebelManifesto')
					return not quest.PamphletsGiven_Turtledove
				end,
			}),
			PlaceObj('UnitSquadHasItem', {
				ItemId = "Pamphlets",
			}),
		},
		Effects = {
			PlaceObj('QuestSetVariableBool', {
				Prop = "PamphletsGiven_Turtledove",
				QuestId = "RebelManifesto",
			}),
			PlaceObj('QuestSetVariableNum', {
				Amount = 1,
				Prop = "PamphletsGiven",
				QuestId = "RebelManifesto",
			}),
		},
		Keyword = "Read this Maquis Manifesto",
		KeywordT = T(576499920250, --[[Conversation TimTurtledove_1 KeywordT]] "Read this Maquis Manifesto"),
		Lines = {
			PlaceObj('ConversationLine', {
				Character = "TimTurtledove",
				Text = T(689436254716, --[[Conversation TimTurtledove_1 Text voice:TimTurtledove section:TimTurtledove_1 keyword:Read this Maquis Manifesto]] "I have signed a contract that stipulates non-involvement in local politics. Apologies, but I am not allowed to read this document."),
			}),
			PlaceObj('ConversationInterjectionList', {
				Interjections = {
					PlaceObj('ConversationInterjection', {
						Lines = {
							PlaceObj('ConversationLine', {
								Character = "Grizzly",
								Text = T(326872491636, --[[Conversation TimTurtledove_1 Text voice:Grizzly section:TimTurtledove_1 keyword:Read this Maquis Manifesto]] "Lucky you."),
							}),
						},
					}),
					PlaceObj('ConversationInterjection', {
						Lines = {
							PlaceObj('ConversationLine', {
								Character = "Steroid",
								Text = T(575165684816, --[[Conversation TimTurtledove_1 Text voice:Steroid section:TimTurtledove_1 keyword:Read this Maquis Manifesto]] "It is good to exercise your stipulates."),
							}),
						},
					}),
					PlaceObj('ConversationInterjection', {
						Lines = {
							PlaceObj('ConversationLine', {
								Character = "Kalyna",
								Text = T(369435901664, --[[Conversation TimTurtledove_1 Text voice:Kalyna section:TimTurtledove_1 keyword:Read this Maquis Manifesto]] "It's very boring. Not a single witch or demon or anything! One out of five stars. Would not recommend."),
							}),
						},
					}),
				},
			}),
		},
		PhraseRolloverText = T(879369141361, --[[Conversation TimTurtledove_1 PhraseRolloverText]] "Give a propaganda pamphlet"),
		StoryBranchIcon = "conversation_action",
		id = "ReadthisMaquisManifesto2",
	}),
	PlaceObj('ConversationPhrase', {
		Align = "right",
		Conditions = {
			PlaceObj('CheckOR', {
				Conditions = {
					PlaceObj('QuestIsVariableBool', {
						Condition = "or",
						QuestId = "PantagruelDramas",
						Vars = set( "ChimurengaDead", "ChimurengaEnemy", "ChimurengaLeave" ),
						__eval = function ()
							local quest = gv_Quests['PantagruelDramas'] or QuestGetState('PantagruelDramas')
							return quest.ChimurengaDead or quest.ChimurengaEnemy or quest.ChimurengaLeave
						end,
					}),
					PlaceObj('QuestIsVariableBool', {
						QuestId = "PantagruelRebels",
						Vars = set( "MaquieDefeated" ),
						__eval = function ()
							local quest = gv_Quests['PantagruelRebels'] or QuestGetState('PantagruelRebels')
							return quest.MaquieDefeated
						end,
					}),
				},
			}),
			PlaceObj('QuestIsVariableBool', {
				QuestId = "PantagruelClinic",
				Vars = set({
	ClinicWorking = false,
}),
				__eval = function ()
					local quest = gv_Quests['PantagruelClinic'] or QuestGetState('PantagruelClinic')
					return not quest.ClinicWorking
				end,
			}),
			PlaceObj('SectorMilitiaNumber', {
				Amount = 2,
				Condition = "<",
			}),
		},
		Effects = {
			PlaceObj('QuestSetVariableBool', {
				Prop = "RequestMilitia",
				QuestId = "PantagruelClinic",
			}),
		},
		Keyword = "What minor issue?",
		KeywordT = T(164782329624, --[[Conversation TimTurtledove_1 KeywordT]] "What minor issue?"),
		Lines = {
			PlaceObj('ConversationLine', {
				Character = "TimTurtledove",
				Text = T(225143611496, --[[Conversation TimTurtledove_1 Text voice:TimTurtledove section:TimTurtledove_1 keyword:What minor issue?]] "Since you have already resolved your conflict with these... Maquis people, I'm anxious to open for business! However, it seems the, um, <em>Donation Board</em>..."),
			}),
			PlaceObj('ConversationInterjectionList', {
				Interjections = {
					PlaceObj('ConversationInterjection', {
						Conditions = {
							PlaceObj('QuestIsVariableBool', {
								QuestId = "PantagruelClinic",
								Vars = set( "MentionBoard" ),
								__eval = function ()
									local quest = gv_Quests['PantagruelClinic'] or QuestGetState('PantagruelClinic')
									return quest.MentionBoard
								end,
							}),
						},
						Lines = {
							PlaceObj('ConversationLine', {
								Character = "Meltdown",
								Text = T(591271422250, --[[Conversation TimTurtledove_1 Text voice:Meltdown section:TimTurtledove_1 keyword:What minor issue?]] "If you mention that Board again, I'll punch you in the gut, you pathetic little fuck."),
							}),
						},
					}),
					PlaceObj('ConversationInterjection', {
						Lines = {
							PlaceObj('ConversationLine', {
								Character = "Raider",
								Text = T(288677880672, --[[Conversation TimTurtledove_1 Text voice:Raider section:TimTurtledove_1 keyword:What minor issue?]] "Let me guess - another minor issue?"),
							}),
						},
					}),
					PlaceObj('ConversationInterjection', {
						Lines = {
							PlaceObj('ConversationLine', {
								Character = "Nails",
								Text = T(105499990465, --[[Conversation TimTurtledove_1 Text voice:Nails section:TimTurtledove_1 keyword:What minor issue?]] "Can suck my left nut."),
							}),
						},
					}),
				},
			}),
			PlaceObj('ConversationLine', {
				Character = "TimTurtledove",
				Text = T(181042479250, --[[Conversation TimTurtledove_1 Text voice:TimTurtledove section:TimTurtledove_1 keyword:What minor issue?]] "It's just not safe out there. Those Legion thugs can attack any moment, can't they? If there was some solution to this security issue - like a local <em>militia</em> protecting the town, for example - I'm sure we could open right away!"),
			}),
		},
		StoryBranchIcon = "conversation_arrow",
		id = "Whatminorissue",
	}),
	PlaceObj('ConversationPhrase', {
		Align = "right",
		Conditions = {
			PlaceObj('QuestIsVariableBool', {
				QuestId = "PantagruelClinic",
				Vars = set({
	ClinicWorking = false,
	DonatedMoney = false,
}),
				__eval = function ()
					local quest = gv_Quests['PantagruelClinic'] or QuestGetState('PantagruelClinic')
					return not quest.ClinicWorking and not quest.DonatedMoney
				end,
			}),
			PlaceObj('SectorMilitiaNumber', {
				Amount = 2,
				Condition = "<",
			}),
			PlaceObj('CheckOR', {
				Conditions = {
					PlaceObj('QuestIsVariableBool', {
						QuestId = "PantagruelClinic",
						Vars = set( "MentionBoard", "MentionMaquis" ),
						__eval = function ()
							local quest = gv_Quests['PantagruelClinic'] or QuestGetState('PantagruelClinic')
							return quest.MentionBoard and quest.MentionMaquis
						end,
					}),
					PlaceObj('QuestIsVariableBool', {
						QuestId = "PantagruelClinic",
						Vars = set( "MentionBoard", "RequestMilitia" ),
						__eval = function ()
							local quest = gv_Quests['PantagruelClinic'] or QuestGetState('PantagruelClinic')
							return quest.MentionBoard and quest.RequestMilitia
						end,
					}),
				},
			}),
		},
		Effects = {
			PlaceObj('QuestSetVariableBool', {
				Prop = "RequestDonation",
				QuestId = "PantagruelClinic",
			}),
		},
		GoTo = "Whatminorissue2.Whataboutadonation",
		Keyword = "What about a donation?",
		KeywordT = T(680909370846, --[[Conversation TimTurtledove_1 KeywordT]] "What about a donation?"),
		PlayGoToPhrase = true,
		StoryBranchIcon = "conversation_friendly",
		id = "Whataboutadonation2",
	}),
	PlaceObj('ConversationPhrase', {
		Align = "right",
		AutoRemove = true,
		Conditions = {
			PlaceObj('SectorMilitiaNumber', {
				Amount = 2,
				Condition = ">=",
			}),
			PlaceObj('QuestIsVariableBool', {
				QuestId = "PantagruelClinic",
				Vars = set({
	ClinicWorking = false,
	RequestMilitia = true,
}),
				__eval = function ()
					local quest = gv_Quests['PantagruelClinic'] or QuestGetState('PantagruelClinic')
					return not quest.ClinicWorking and quest.RequestMilitia
				end,
			}),
		},
		GoTo = "Redirect",
		Keyword = "We have trained Militia",
		KeywordT = T(648162287486, --[[Conversation TimTurtledove_1 KeywordT]] "We have trained Militia"),
		Lines = {
			PlaceObj('ConversationLine', {
				Character = "TimTurtledove",
				Text = T(520496065771, --[[Conversation TimTurtledove_1 Text voice:TimTurtledove section:TimTurtledove_1 keyword:We have trained Militia]] "Oh! You have? Really?"),
			}),
			PlaceObj('ConversationInterjectionList', {
				Interjections = {
					PlaceObj('ConversationInterjection', {
						Lines = {
							PlaceObj('ConversationLine', {
								Character = "Len",
								Text = T(485966971640, --[[Conversation TimTurtledove_1 Text voice:Len section:TimTurtledove_1 keyword:We have trained Militia]] "Really."),
							}),
						},
					}),
					PlaceObj('ConversationInterjection', {
						Lines = {
							PlaceObj('ConversationLine', {
								Character = "Gus",
								Text = T(142606269882, --[[Conversation TimTurtledove_1 Text voice:Gus section:TimTurtledove_1 keyword:We have trained Militia]] "Open your eyes, Woodstock!"),
							}),
						},
					}),
					PlaceObj('ConversationInterjection', {
						Lines = {
							PlaceObj('ConversationLine', {
								Character = "Scully",
								Text = T(317977444910, --[[Conversation TimTurtledove_1 Text voice:Scully section:TimTurtledove_1 keyword:We have trained Militia]] "The streets are filled with fresh squaddies, mate."),
							}),
						},
					}),
				},
			}),
		},
		PlayGoToPhrase = true,
		StoryBranchIcon = "conversation_arrow",
		id = "WehavetrainedMilitia",
	}),
	PlaceObj('ConversationPhrase', {
		Align = "right",
		AutoRemove = true,
		Conditions = {
			PlaceObj('CheckOR', {
				Conditions = {
					PlaceObj('UnitSquadHasMerc', {
						Name = "Flay",
					}),
					PlaceObj('UnitSquadHasMerc', {
						HasPerk = "Psycho",
					}),
				},
			}),
			PlaceObj('QuestIsVariableBool', {
				QuestId = "PantagruelClinic",
				Vars = set({
	ClinicWorking = false,
	RequestMilitia = true,
}),
				__eval = function ()
					local quest = gv_Quests['PantagruelClinic'] or QuestGetState('PantagruelClinic')
					return not quest.ClinicWorking and quest.RequestMilitia
				end,
			}),
			PlaceObj('QuestIsVariableBool', {
				QuestId = "PantagruelRebels",
				Vars = set( "MaquieDefeated" ),
				__eval = function ()
					local quest = gv_Quests['PantagruelRebels'] or QuestGetState('PantagruelRebels')
					return quest.MaquieDefeated
				end,
			}),
		},
		GoTo = "Redirect",
		Keyword = "Open the clinic NOW",
		KeywordT = T(573496138062, --[[Conversation TimTurtledove_1 KeywordT]] "Open the clinic NOW"),
		Lines = {
			PlaceObj('ConversationInterjectionList', {
				Interjections = {
					PlaceObj('ConversationInterjection', {
						Lines = {
							PlaceObj('ConversationLine', {
								Character = "Nails",
								Text = T(833834365749, --[[Conversation TimTurtledove_1 Text voice:Nails section:TimTurtledove_1 keyword:Open the clinic NOW]] "Don't bullshit me, dweeb. Open the fucking clinic, or you'll be the first one that's gonna need to use it."),
							}),
						},
					}),
					PlaceObj('ConversationInterjection', {
						Lines = {
							PlaceObj('ConversationLine', {
								Character = "Flay",
								Text = T(970340796400, --[[Conversation TimTurtledove_1 Text voice:Flay section:TimTurtledove_1 keyword:Open the clinic NOW]] "Your skin... There is something wrong with it."),
							}),
							PlaceObj('ConversationLine', {
								Character = "TimTurtledove",
								Text = T(541971692240, --[[Conversation TimTurtledove_1 Text voice:TimTurtledove section:TimTurtledove_1 keyword:Open the clinic NOW]] "My skin?! What's... What's wrong with it?"),
							}),
							PlaceObj('ConversationLine', {
								Character = "Flay",
								Text = T(114361599447, --[[Conversation TimTurtledove_1 Text voice:Flay section:TimTurtledove_1 keyword:Open the clinic NOW]] "It's too thin. Really hard not to damage it while flaying. But I like the challenge."),
							}),
						},
					}),
					PlaceObj('ConversationInterjection', {
						Lines = {
							PlaceObj('ConversationLine', {
								Character = "Fidel",
								Text = T(996870834002, --[[Conversation TimTurtledove_1 Text voice:Fidel section:TimTurtledove_1 keyword:Open the clinic NOW]] "Fidel is tired of watching your mouth move. Maybe I put grenade in it."),
							}),
						},
					}),
					PlaceObj('ConversationInterjection', {
						Lines = {
							PlaceObj('ConversationLine', {
								Character = "Meltdown",
								Text = T(848218377286, --[[Conversation TimTurtledove_1 Text voice:Meltdown section:TimTurtledove_1 keyword:Open the clinic NOW]] "Listen here, you little shit! Open this damn clinic up or I'll kick your ass so hard you'll need to get an X-ray to find my boot!"),
							}),
						},
					}),
				},
			}),
			PlaceObj('ConversationLine', {
				Character = "TimTurtledove",
				Text = T(818340911060, --[[Conversation TimTurtledove_1 Text voice:TimTurtledove section:TimTurtledove_1 keyword:Open the clinic NOW]] "Oh, dear! That is, um... Please don't hurt me."),
			}),
		},
		PlayGoToPhrase = true,
		StoryBranchIcon = "conversation_threaten",
		id = "OpentheclinicNOW",
	}),
	PlaceObj('ConversationPhrase', {
		Align = "right",
		Conditions = {
			PlaceObj('QuestIsVariableBool', {
				QuestId = "PantagruelClinic",
				Vars = set({
	ClinicWorking = false,
	MaquisConvinced = false,
}),
				__eval = function ()
					local quest = gv_Quests['PantagruelClinic'] or QuestGetState('PantagruelClinic')
					return not quest.ClinicWorking and not quest.MaquisConvinced
				end,
			}),
			PlaceObj('QuestIsVariableBool', {
				QuestId = "PantagruelRebels",
				Vars = set({
	MaquieDefeated = false,
	MaquieEnemies = false,
}),
				__eval = function ()
					local quest = gv_Quests['PantagruelRebels'] or QuestGetState('PantagruelRebels')
					return not quest.MaquieDefeated and not quest.MaquieEnemies
				end,
			}),
			PlaceObj('QuestIsVariableBool', {
				QuestId = "PantagruelDramas",
				Vars = set({
	ChimurengaDead = false,
	ChimurengaEnemy = false,
	ChimurengaLeave = false,
}),
				__eval = function ()
					local quest = gv_Quests['PantagruelDramas'] or QuestGetState('PantagruelDramas')
					return not quest.ChimurengaDead and not quest.ChimurengaEnemy and not quest.ChimurengaLeave
				end,
			}),
		},
		Effects = {
			PlaceObj('QuestSetVariableBool', {
				Prop = "MentionBoard",
				QuestId = "PantagruelClinic",
			}),
			PlaceObj('QuestSetVariableBool', {
				Prop = "MentionMaquis",
				QuestId = "PantagruelClinic",
			}),
		},
		Keyword = "What minor issue?",
		KeywordT = T(164782329624, --[[Conversation TimTurtledove_1 KeywordT]] "What minor issue?"),
		Lines = {
			PlaceObj('ConversationLine', {
				Character = "TimTurtledove",
				Text = T(644896340239, --[[Conversation TimTurtledove_1 Text voice:TimTurtledove section:TimTurtledove_1 keyword:What minor issue?]] "There is this gentlemen, Mister... um, <em>Chimurenga</em>. He was very enthusiastic about us opening a clinic here in Pantagruel, yet he made a request that the <em>Donation Board</em> could never approve of..."),
			}),
			PlaceObj('ConversationInterjectionList', {
				Interjections = {
					PlaceObj('ConversationInterjection', {
						Conditions = {
							PlaceObj('QuestIsVariableBool', {
								QuestId = "PantagruelClinic",
								Vars = set( "MentionBoard" ),
								__eval = function ()
									local quest = gv_Quests['PantagruelClinic'] or QuestGetState('PantagruelClinic')
									return quest.MentionBoard
								end,
							}),
						},
						Lines = {
							PlaceObj('ConversationLine', {
								Character = "Meltdown",
								Text = T(311468686016, --[[Conversation TimTurtledove_1 Text voice:Meltdown section:TimTurtledove_1 keyword:What minor issue?]] "Your fucking board again!"),
							}),
						},
					}),
				},
			}),
			PlaceObj('ConversationInterjectionList', {
				Interjections = {
					PlaceObj('ConversationInterjection', {
						Lines = {
							PlaceObj('ConversationLine', {
								Character = "Larry_Clean",
								Text = T(955325841315, --[[Conversation TimTurtledove_1 Text voice:Larry_Clean section:TimTurtledove_1 keyword:What minor issue?]] "Did he ask for a frequent customer program? I've tried making that request at clinics back home."),
							}),
						},
					}),
					PlaceObj('ConversationInterjection', {
						Lines = {
							PlaceObj('ConversationLine', {
								Character = "Grunty",
								Text = T(644789630850, --[[Conversation TimTurtledove_1 Text voice:Grunty section:TimTurtledove_1 keyword:What minor issue?]] "Did he want a clown that makes balloon weapons instead of balloon animals? My mother made that request at the hospital where I had my tonsils removed."),
							}),
						},
					}),
					PlaceObj('ConversationInterjection', {
						Lines = {
							PlaceObj('ConversationLine', {
								Character = "Red",
								Text = T(604047613200, --[[Conversation TimTurtledove_1 Text voice:Red section:TimTurtledove_1 keyword:What minor issue?]] "Did he ask for a free sponge bath with every visit? Hehe. Tried that one myself."),
							}),
						},
					}),
				},
			}),
			PlaceObj('ConversationLine', {
				Character = "TimTurtledove",
				Text = T(857793054586, --[[Conversation TimTurtledove_1 Text voice:TimTurtledove section:TimTurtledove_1 keyword:What minor issue?]] "He wants us to provide free healthcare to the People, meaning, well, his people - <em>The Maquis</em>, I believe he calls them? Well, that we cannot do. They qualify neither as <em>civilians</em> nor local <em>law enforcement</em>. The Board would never allow it."),
			}),
		},
		StoryBranchIcon = "conversation_arrow",
		id = "Whatminorissue2",
		PlaceObj('ConversationPhrase', {
			AutoRemove = true,
			Conditions = {
				PlaceObj('QuestIsVariableBool', {
					QuestId = "PantagruelClinic",
					Vars = set({
	ClinicWorking = false,
	DonatedMoney = false,
	RequestDonation = false,
}),
					__eval = function ()
						local quest = gv_Quests['PantagruelClinic'] or QuestGetState('PantagruelClinic')
						return not quest.ClinicWorking and not quest.DonatedMoney and not quest.RequestDonation
					end,
				}),
			},
			Effects = {
				PlaceObj('QuestSetVariableBool', {
					Prop = "RequestDonation",
					QuestId = "PantagruelClinic",
				}),
			},
			Keyword = "What about a donation?",
			KeywordT = T(680909370846, --[[Conversation TimTurtledove_1 KeywordT]] "What about a donation?"),
			Lines = {
				PlaceObj('ConversationLine', {
					Character = "TimTurtledove",
					Text = T(824611620750, --[[Conversation TimTurtledove_1 Text voice:TimTurtledove section:TimTurtledove_1 keyword:What about a donation?]] "Oh, well, if you were to contribute a substantial sum, say, <em>three thousand</em>, then you would actually be entitled to join the <em>Donation Board</em>! In fact, you'd be my boss!"),
				}),
				PlaceObj('ConversationInterjectionList', {
					Interjections = {
						PlaceObj('ConversationInterjection', {
							Lines = {
								PlaceObj('ConversationLine', {
									Character = "Meltdown",
									Text = T(698289607268, --[[Conversation TimTurtledove_1 Text voice:Meltdown section:TimTurtledove_1 keyword:What about a donation?]] "Could we fire you?"),
								}),
								PlaceObj('ConversationLine', {
									Character = "TimTurtledove",
									Text = T(643933254927, --[[Conversation TimTurtledove_1 Text voice:TimTurtledove section:TimTurtledove_1 keyword:What about a donation?]] "Uh, well... No."),
								}),
								PlaceObj('ConversationLine', {
									Character = "Meltdown",
									Text = T(601705421413, --[[Conversation TimTurtledove_1 Text voice:Meltdown section:TimTurtledove_1 keyword:What about a donation?]] "Then what the hell's the point?"),
								}),
							},
						}),
						PlaceObj('ConversationInterjection', {
							Lines = {
								PlaceObj('ConversationLine', {
									Character = "Smiley",
									Text = T(991948364513, --[[Conversation TimTurtledove_1 Text voice:Smiley section:TimTurtledove_1 keyword:What about a donation?]] "Boss of a hospital! That would be wonderful! I volunteer to personally oversee the nursing staff."),
								}),
							},
						}),
						PlaceObj('ConversationInterjection', {
							Lines = {
								PlaceObj('ConversationLine', {
									Character = "Omryn",
									Text = T(662885050409, --[[Conversation TimTurtledove_1 Text voice:Omryn section:TimTurtledove_1 keyword:What about a donation?]] "So, I tell you bring me snack, you do it?"),
								}),
								PlaceObj('ConversationLine', {
									Character = "TimTurtledove",
									Text = T(854357976830, --[[Conversation TimTurtledove_1 Text voice:TimTurtledove section:TimTurtledove_1 keyword:What about a donation?]] "Um, well, we actually have tea and biscuits available in the..."),
								}),
								PlaceObj('ConversationLine', {
									Character = "Omryn",
									Text = T(489908803982, --[[Conversation TimTurtledove_1 Text voice:Omryn section:TimTurtledove_1 keyword:What about a donation?]] "Okay. Sound good."),
								}),
							},
						}),
					},
				}),
			},
			StoryBranchIcon = "conversation_friendly",
			id = "Whataboutadonation",
		}),
		PlaceObj('ConversationPhrase', {
			Align = "right",
			AutoRemove = true,
			Conditions = {
				PlaceObj('UnitSquadHasMerc', {
					HasPerk = "Negotiator",
					Negate = true,
				}),
				PlaceObj('PlayerHasMoney', {
					Amount = 3000,
					param_bindings = {
						Amount = "MoneyPay_High",
					},
				}),
				PlaceObj('QuestIsVariableBool', {
					QuestId = "PantagruelClinic",
					Vars = set({
	ClinicWorking = false,
	DonatedMoney = false,
	RequestDonation = true,
}),
					__eval = function ()
						local quest = gv_Quests['PantagruelClinic'] or QuestGetState('PantagruelClinic')
						return not quest.ClinicWorking and not quest.DonatedMoney and quest.RequestDonation
					end,
				}),
			},
			Effects = {
				PlaceObj('PlayerPayMoney', {
					Amount = 3000,
					param_bindings = {
						Amount = "MoneyPay_High",
					},
				}),
				PlaceObj('QuestSetVariableBool', {
					Prop = "DonatedMoney",
					QuestId = "PantagruelClinic",
				}),
			},
			GoTo = "Redirect",
			Keyword = "We’ll donate $3000",
			KeywordT = T(165782403060, --[[Conversation TimTurtledove_1 KeywordT]] "We’ll donate $3000"),
			Lines = {
				PlaceObj('ConversationLine', {
					Character = "TimTurtledove",
					Text = T(451824143081, --[[Conversation TimTurtledove_1 Text voice:TimTurtledove section:TimTurtledove_1 keyword:We’ll donate $3000]] "Thank you for your generosity! I have no choice but to accept this wonderful donation."),
				}),
				PlaceObj('ConversationInterjectionList', {
					Interjections = {
						PlaceObj('ConversationInterjection', {
							Lines = {
								PlaceObj('ConversationLine', {
									Character = "DrQ",
									Text = T(972030507355, --[[Conversation TimTurtledove_1 Text voice:DrQ section:TimTurtledove_1 keyword:We’ll donate $3000]] "May you always have the resources to carry out your noble mission."),
								}),
							},
						}),
						PlaceObj('ConversationInterjection', {
							Lines = {
								PlaceObj('ConversationLine', {
									Character = "Smiley",
									Text = T(887723524408, --[[Conversation TimTurtledove_1 Text voice:Smiley section:TimTurtledove_1 keyword:We’ll donate $3000]] "Good. I have a few ideas about uniforms for the nurses..."),
								}),
							},
						}),
						PlaceObj('ConversationInterjection', {
							Lines = {
								PlaceObj('ConversationLine', {
									Character = "Larry_Clean",
									Text = T(446843440875, --[[Conversation TimTurtledove_1 Text voice:Larry_Clean section:TimTurtledove_1 keyword:We’ll donate $3000]] "So, as board members, do we get free samples? Know what? Forget I asked that."),
								}),
							},
						}),
					},
				}),
			},
			PlayGoToPhrase = true,
			StoryBranchIcon = "conversation_trade",
			id = "Welldonate3000",
		}),
		PlaceObj('ConversationPhrase', {
			Align = "right",
			AutoRemove = true,
			Conditions = {
				PlaceObj('UnitSquadHasMerc', {
					HasPerk = "Negotiator",
				}),
				PlaceObj('PlayerHasMoney', {
					Amount = 1000,
					param_bindings = {
						Amount = "MoneyPay_Low",
					},
				}),
				PlaceObj('QuestIsVariableBool', {
					QuestId = "PantagruelClinic",
					Vars = set({
	ClinicWorking = false,
	DonatedMoney = false,
	RequestDonation = true,
}),
					__eval = function ()
						local quest = gv_Quests['PantagruelClinic'] or QuestGetState('PantagruelClinic')
						return not quest.ClinicWorking and not quest.DonatedMoney and quest.RequestDonation
					end,
				}),
			},
			Effects = {
				PlaceObj('PlayerPayMoney', {
					Amount = 1000,
					param_bindings = {
						Amount = "MoneyPay_Low",
					},
				}),
				PlaceObj('QuestSetVariableBool', {
					Prop = "DonatedMoney",
					QuestId = "PantagruelClinic",
				}),
			},
			GoTo = "Redirect",
			Keyword = "We’ll donate $1000",
			KeywordT = T(876142394338, --[[Conversation TimTurtledove_1 KeywordT]] "We’ll donate $1000"),
			Lines = {
				PlaceObj('ConversationInterjectionList', {
					Interjections = {
						PlaceObj('ConversationInterjection', {
							Lines = {
								PlaceObj('ConversationLine', {
									Character = "Buns",
									Text = T(396534756840, --[[Conversation TimTurtledove_1 Text voice:Buns section:TimTurtledove_1 keyword:We’ll donate $1000]] "The actual sum doesn't matter as long as it is big enough, correct?"),
								}),
							},
						}),
						PlaceObj('ConversationInterjection', {
							Lines = {
								PlaceObj('ConversationLine', {
									Character = "Raider",
									Text = T(443536749496, --[[Conversation TimTurtledove_1 Text voice:Raider section:TimTurtledove_1 keyword:We’ll donate $1000]] "Sir, please accept this donation and our heartfelt promise to help protect and serve this clinic."),
								}),
							},
						}),
						PlaceObj('ConversationInterjection', {
							Lines = {
								PlaceObj('ConversationLine', {
									Character = "Sidney",
									Text = T(947211288808, --[[Conversation TimTurtledove_1 Text voice:Sidney section:TimTurtledove_1 keyword:We’ll donate $1000]] "I happen to have a contact or two at the British Embassy. If you accept this somewhat more modest donation, I can assure you that Her Majesty's government would be eternally grateful."),
								}),
							},
						}),
					},
				}),
				PlaceObj('ConversationLine', {
					Character = "TimTurtledove",
					Text = T(669853105256, --[[Conversation TimTurtledove_1 Text voice:TimTurtledove section:TimTurtledove_1 keyword:We’ll donate $1000]] "Well, to be honest, it's not the size of the sum that matters, it's the spirit in which it is given. Thank you! I happily accept your donation."),
				}),
			},
			PlayGoToPhrase = true,
			StoryBranchIcon = "conversation_trade",
			id = "Welldonate1000",
		}),
		PlaceObj('ConversationPhrase', {
			Align = "right",
			AutoRemove = true,
			Conditions = {
				PlaceObj('UnitSquadHasMerc', {
					HasPerk = "Negotiator",
				}),
				PlaceObj('QuestIsVariableBool', {
					QuestId = "PantagruelClinic",
					Vars = set({
	ClinicWorking = false,
	MaquisConvinced = false,
	MentionBoard = true,
	MentionMaquis = true,
	MentionMilitia = true,
}),
					__eval = function ()
						local quest = gv_Quests['PantagruelClinic'] or QuestGetState('PantagruelClinic')
						return not quest.ClinicWorking and not quest.MaquisConvinced and quest.MentionBoard and quest.MentionMaquis and quest.MentionMilitia
					end,
				}),
				PlaceObj('QuestIsVariableBool', {
					QuestId = "PantagruelRebels",
					Vars = set({
	MaquieDefeated = false,
	MaquieEnemies = false,
}),
					__eval = function ()
						local quest = gv_Quests['PantagruelRebels'] or QuestGetState('PantagruelRebels')
						return not quest.MaquieDefeated and not quest.MaquieEnemies
					end,
				}),
				PlaceObj('QuestIsVariableBool', {
					QuestId = "PantagruelDramas",
					Vars = set({
	ChimurengaDead = false,
	ChimurengaEnemy = false,
	ChimurengaLeave = false,
}),
					__eval = function ()
						local quest = gv_Quests['PantagruelDramas'] or QuestGetState('PantagruelDramas')
						return not quest.ChimurengaDead and not quest.ChimurengaEnemy and not quest.ChimurengaLeave
					end,
				}),
			},
			GoTo = "Redirect",
			Keyword = "The Maquis ARE the local law enforcement",
			KeywordT = T(693977995369, --[[Conversation TimTurtledove_1 KeywordT]] "The Maquis ARE the local law enforcement"),
			Lines = {
				PlaceObj('ConversationInterjectionList', {
					Interjections = {
						PlaceObj('ConversationInterjection', {
							Lines = {
								PlaceObj('ConversationLine', {
									Character = "Buns",
									Text = T(530475447334, --[[Conversation TimTurtledove_1 Text voice:Buns section:TimTurtledove_1 keyword:The Maquis ARE the local law enforcement]] "In case you had not noticed, the Maquis are the ones running this town."),
								}),
							},
						}),
						PlaceObj('ConversationInterjection', {
							Lines = {
								PlaceObj('ConversationLine', {
									Character = "Raider",
									Text = T(558994758511, --[[Conversation TimTurtledove_1 Text voice:Raider section:TimTurtledove_1 keyword:The Maquis ARE the local law enforcement]] "I can assure you that the Maquis are more than capable of keeping the peace."),
								}),
							},
						}),
						PlaceObj('ConversationInterjection', {
							Lines = {
								PlaceObj('ConversationLine', {
									Character = "Sidney",
									Text = T(658946968538, --[[Conversation TimTurtledove_1 Text voice:Sidney section:TimTurtledove_1 keyword:The Maquis ARE the local law enforcement]] "My good man, I know they may not look the part, but the Maquis actually make for quite an acceptable group of bobbies."),
								}),
							},
						}),
					},
				}),
				PlaceObj('ConversationLine', {
					Character = "TimTurtledove",
					Text = T(797765352824, --[[Conversation TimTurtledove_1 Text voice:TimTurtledove section:TimTurtledove_1 keyword:The Maquis ARE the local law enforcement]] "Uh, you mean, they qualify as a local enforcement body under the provisions of article 72, paragraph 11-b of the Donation Board Establishment Act? Hmm, I hadn't thought of that..."),
				}),
			},
			PlayGoToPhrase = true,
			StoryBranchIcon = "conversation_sarcastic",
			id = "TheMaquisAREthelocalMilitia",
		}),
		PlaceObj('ConversationPhrase', {
			Conditions = {
				PlaceObj('QuestIsVariableBool', {
					QuestId = "PantagruelClinic",
					Vars = set({
	ClinicWorking = false,
	MaquisConvinced = false,
	MentionBoard = true,
	MentionMaquis = true,
	MentionMilitia = true,
}),
					__eval = function ()
						local quest = gv_Quests['PantagruelClinic'] or QuestGetState('PantagruelClinic')
						return not quest.ClinicWorking and not quest.MaquisConvinced and quest.MentionBoard and quest.MentionMaquis and quest.MentionMilitia
					end,
				}),
				PlaceObj('QuestIsVariableBool', {
					QuestId = "PantagruelRebels",
					Vars = set({
	MaquieDefeated = false,
	MaquieEnemies = false,
}),
					__eval = function ()
						local quest = gv_Quests['PantagruelRebels'] or QuestGetState('PantagruelRebels')
						return not quest.MaquieDefeated and not quest.MaquieEnemies
					end,
				}),
				PlaceObj('QuestIsVariableBool', {
					QuestId = "PantagruelDramas",
					Vars = set({
	ChimurengaDead = false,
	ChimurengaEnemy = false,
	ChimurengaLeave = false,
}),
					__eval = function ()
						local quest = gv_Quests['PantagruelDramas'] or QuestGetState('PantagruelDramas')
						return not quest.ChimurengaDead and not quest.ChimurengaEnemy and not quest.ChimurengaLeave
					end,
				}),
			},
			Keyword = "We’ll talk to Chimurenga",
			KeywordT = T(240783102008, --[[Conversation TimTurtledove_1 KeywordT]] "We’ll talk to Chimurenga"),
			Lines = {
				PlaceObj('ConversationLine', {
					Character = "TimTurtledove",
					Text = T(577327944229, --[[Conversation TimTurtledove_1 Text voice:TimTurtledove section:TimTurtledove_1 keyword:We’ll talk to Chimurenga]] "I wish you good luck! Uh, that is, I am sure you will get along smashingly with the gentleman!"),
				}),
			},
			id = "WelltalktoChimurenga",
		}),
	}),
	PlaceObj('ConversationPhrase', {
		Align = "right",
		Effects = {
			PlaceObj('QuestSetVariableBool', {
				Prop = "ClinicWorking",
				QuestId = "PantagruelClinic",
			}),
		},
		Enabled = false,
		GoTo = "<end conversation>",
		Keyword = "Redirect",
		KeywordT = T(328092960140, --[[Conversation TimTurtledove_1 KeywordT]] "Redirect"),
		Lines = {
			PlaceObj('ConversationLine', {
				Character = "TimTurtledove",
				Text = T(761769266181, --[[Conversation TimTurtledove_1 Text voice:TimTurtledove section:TimTurtledove_1 keyword:Redirect]] "Let me think if there are any other issues that need addressing..."),
			}),
			PlaceObj('ConversationInterjectionList', {
				Interjections = {
					PlaceObj('ConversationInterjection', {
						Lines = {
							PlaceObj('ConversationLine', {
								Character = "Meltdown",
								Text = T(283194420568, --[[Conversation TimTurtledove_1 Text voice:Meltdown section:TimTurtledove_1 keyword:Redirect]] "My boot's itching to start kicking."),
							}),
						},
					}),
					PlaceObj('ConversationInterjection', {
						Lines = {
							PlaceObj('ConversationLine', {
								Character = "Fidel",
								Text = T(507085739053, --[[Conversation TimTurtledove_1 Text voice:Fidel section:TimTurtledove_1 keyword:Redirect]] "Fidel drop his grenade! Where it went? Here, ps-ps-ps-ps grenade!"),
							}),
						},
					}),
					PlaceObj('ConversationInterjection', {
						Lines = {
							PlaceObj('ConversationLine', {
								Character = "Flay",
								Text = T(185536714631, --[[Conversation TimTurtledove_1 Text voice:Flay section:TimTurtledove_1 keyword:Redirect]] "You like this knife, oui? Would you like to see how it feels against your skin?"),
							}),
						},
					}),
					PlaceObj('ConversationInterjection', {
						Lines = {
							PlaceObj('ConversationLine', {
								Character = "Nails",
								Text = T(768261790615, --[[Conversation TimTurtledove_1 Text voice:Nails section:TimTurtledove_1 keyword:Redirect]] "I can answer that for you right now: There ain't."),
							}),
						},
					}),
				},
				MaxPlayed = 2,
			}),
			PlaceObj('ConversationLine', {
				Character = "TimTurtledove",
				Text = T(232754539779, --[[Conversation TimTurtledove_1 Text voice:TimTurtledove section:TimTurtledove_1 keyword:Redirect]] "No, it appears we've got everything in order... We can open for business right away! The <em>\"Vulture of Hope\"</em> will fly high and wide! Uh, hooray!... I guess."),
			}),
		},
		PhraseConditionRolloverText = T(100317028562, --[[Conversation TimTurtledove_1 PhraseConditionRolloverText]] "Operation is available: <color EmStyle>Hospital Treatment</color>"),
		StoryBranchIcon = "conversation_goodbye",
		id = "Redirect",
	}),
	PlaceObj('ConversationPhrase', {
		GoTo = "<end conversation>",
		Keyword = "Goodbye",
		KeywordT = T(557225474228, --[[Conversation TimTurtledove_1 KeywordT]] "Goodbye"),
		Lines = {
			PlaceObj('ConversationLine', {
				Character = "TimTurtledove",
				Text = T(233213093822, --[[Conversation TimTurtledove_1 Text voice:TimTurtledove section:TimTurtledove_1 keyword:Goodbye]] "Goodbye and have a nice day! Don't you worry, the \"Vulture of Hope\" will be there for you soon enough!"),
			}),
		},
		StoryBranchIcon = "conversation_goodbye",
		id = "Goodbye",
	}),
})

