-- ========== GENERATED BY ExtrasGen Editor (Ctrl-Alt-G) DO NOT EDIT MANUALLY! ==========

PlaceObj('ExtrasGen', {
	RequiresClass = "EditorLineGuide",
	ToolbarSection = "Guide-Aligned Objects",
	group = "PlaceObjects",
	id = "LayDirt",
	PlaceObj('LayDecalsAlongGuide', {
		Decals = {
			PlaceObj('PlaceObjectDataDecal', {
				EditorClass = "DecWallDirt_03",
				FlipVertically = true,
				MoveDownPercent = 5,
				ScaleAfterPlace = 108,
			}),
			PlaceObj('PlaceObjectDataDecal', {
				EditorClass = "DecWallDirt_06",
				MoveDownPercent = 50,
			}),
			PlaceObj('PlaceObjectDataDecal', {
				EditorClass = "DecWallDirt_07",
				MoveDownPercent = 50,
			}),
		},
		GuidesVar = "initial_selection",
	}),
})

