-- ========== GENERATED BY ExtrasGen Editor (Ctrl-Alt-G) DO NOT EDIT MANUALLY! ==========

PlaceObj('ExtrasGen', {
	RequiresClass = "EditorLineGuide",
	Shortcut = "Left",
	Shortcut2 = "Shift-Left",
	ToolbarSection = "Guide Operations",
	group = "ModifyGuides",
	id = "MoveBack",
	PlaceObj('MoveSizeGuides', {
		Along = -1,
		AlongScale = 1,
		GuidesVar = "initial_selection",
		ShiftForHalfStep = true,
	}),
})

