-- ========== GENERATED BY InventoryItemCompositeDef Editor (Ctrl-Alt-Y) DO NOT EDIT MANUALLY! ==========

PlaceObj('InventoryItemCompositeDef', {
	'Group', "Ammo",
	'Id', "_556_Basic",
	'object_class', "Ammo",
	'Icon', "UI/Icons/Items/556_nato_bullets_basic",
	'DisplayName', T(798472357246, --[[InventoryItemCompositeDef _556_Basic DisplayName]] "5.56 mm Standard"),
	'DisplayNamePlural', T(124208305458, --[[InventoryItemCompositeDef _556_Basic DisplayNamePlural]] "5.56 mm Standard"),
	'colorStyle', "AmmoBasicColor",
	'Description', T(114938435533, --[[InventoryItemCompositeDef _556_Basic Description]] "5.56 Ammo for Assault Rifles, SMGs, and Machine Guns."),
	'MaxStacks', 500,
	'Caliber', "556",
})

