-- ========== GENERATED BY InventoryItemCompositeDef Editor (Ctrl-Alt-Y) DO NOT EDIT MANUALLY! ==========

PlaceObj('InventoryItemCompositeDef', {
	'Group', "Firearm - Handgun",
	'Id', "FlareHandgun",
	'object_class', "FlareGun",
	'RepairCost', 70,
	'Reliability', 20,
	'ScrapParts', 2,
	'Icon', "UI/Icons/Weapons/FlareGun",
	'ItemType', "FlareGun",
	'DisplayName', T(335515845100, --[[InventoryItemCompositeDef FlareHandgun DisplayName]] "Flare Gun"),
	'DisplayNamePlural', T(989166829697, --[[InventoryItemCompositeDef FlareHandgun DisplayNamePlural]] "Flare Guns"),
	'Description', T(323491634965, --[[InventoryItemCompositeDef FlareHandgun Description]] "Single-shot breech-loading pistol you can use to light up the sky. "),
	'AdditionalHint', T(327868916279, --[[InventoryItemCompositeDef FlareHandgun AdditionalHint]] "<bullet_point> Illuminates a large area\n<bullet_point> Long range\n<bullet_point> Silent"),
	'UnitStat', "Marksmanship",
	'is_valuable', true,
	'Cost', 3000,
	'Caliber', "Flare",
	'ObjDamageMod', 0,
	'CritChanceScaled', 0,
	'WeaponRange', 35,
	'OverwatchAngle', 2160,
	'Noise', 3,
	'Entity', "Weapon_FlareGun",
	'HolsterSlot', "Leg",
	'PreparedAttackType', "None",
	'AvailableAttacks', {
		"FireFlare",
	},
	'MinMishapChance', 20,
	'MaxMishapChance', 60,
})

