-- ========== GENERATED BY InventoryItemCompositeDef Editor (Ctrl-Alt-Y) DO NOT EDIT MANUALLY! ==========

PlaceObj('InventoryItemCompositeDef', {
	'Group', "Personal - Equipment",
	'Id', "IvanUshanka",
	'object_class', "Armor",
	'Degradation', 0,
	'Icon', "UI/Icons/Items/ivan_ushanka",
	'DisplayName', T(577081433689, --[[InventoryItemCompositeDef IvanUshanka DisplayName]] "Ushanka"),
	'DisplayNamePlural', T(786597442135, --[[InventoryItemCompositeDef IvanUshanka DisplayNamePlural]] "Ushanki"),
	'AdditionalHint', T(650793471533, --[[InventoryItemCompositeDef IvanUshanka AdditionalHint]] "<bullet_point> Protects against capitalism"),
	'locked', true,
	'Slot', "Head",
	'DamageReduction', 0,
	'ProtectedBodyParts', set( "Head" ),
})

