-- ========== GENERATED BY InventoryItemCompositeDef Editor (Ctrl-Alt-Y) DO NOT EDIT MANUALLY! ==========

PlaceObj('InventoryItemCompositeDef', {
	'Group', "Armor - Kevlar",
	'Id', "KevlarLeggings_WeavePadding",
	'object_class', "Armor",
	'ScrapParts', 4,
	'Degradation', 6,
	'Icon', "UI/Icons/Items/kevlar_leggings",
	'SubIcon', "UI/Icons/Items/padded",
	'DisplayName', T(995619097583, --[[InventoryItemCompositeDef KevlarLeggings_WeavePadding DisplayName]] "Kevlar Leggings"),
	'DisplayNamePlural', T(297011337212, --[[InventoryItemCompositeDef KevlarLeggings_WeavePadding DisplayNamePlural]] "Kevlar Leggings"),
	'AdditionalHint', T(357999944878, --[[InventoryItemCompositeDef KevlarLeggings_WeavePadding AdditionalHint]] "<bullet_point> Damage reduction improved by Weave Padding"),
	'Cost', 2800,
	'CanAppearInShop', true,
	'Tier', 2,
	'MaxStock', 1,
	'RestockWeight', 25,
	'CategoryPair', "Medium",
	'CanAppearStandard', false,
	'Slot', "Legs",
	'PenetrationClass', 3,
	'AdditionalReduction', 40,
	'ProtectedBodyParts', set( "Groin", "Legs" ),
})

