-- ========== GENERATED BY InventoryItemCompositeDef Editor (Ctrl-Alt-Y) DO NOT EDIT MANUALLY! ==========

PlaceObj('InventoryItemCompositeDef', {
	'Group', "Valuables",
	'Id', "TreasureIdol",
	'object_class', "Valuables",
	'Repairable', false,
	'Icon', "UI/Icons/Items/treasure_creepy_idol",
	'DisplayName', T(362936711543, --[[InventoryItemCompositeDef TreasureIdol DisplayName]] "Ancient Idol"),
	'DisplayNamePlural', T(236454752036, --[[InventoryItemCompositeDef TreasureIdol DisplayNamePlural]] "Ancient Idols"),
	'Description', T(404773919112, --[[InventoryItemCompositeDef TreasureIdol Description]] "It is a very common archaeological find that certainleh hath no spethialui mglw'nafh Cthulhu R'lyeh wgah'nagl fhtagn."),
	'AdditionalHint', T(561902646382, --[[InventoryItemCompositeDef TreasureIdol AdditionalHint]] "<bullet_point> A piece of Grand Chien's glorious past\n<bullet_point> <GameColorD>Can be cashed in for Money</GameColorD>"),
	'is_valuable', true,
	'Cost', 3000,
})

