-- ========== GENERATED BY VoiceResponse Editor (Ctrl-Alt-V) DO NOT EDIT MANUALLY! ==========

PlaceObj('VoiceResponse', {
	ActivityFinished = TConcat({
		T(443359447216, --[[VoiceResponse Ice ActivityFinished VoiceResponse ActivityFinished - SatView activity finished voice:Ice]] "That's all set. Now, I'm just chillaxin'.")
	}),
	ActivityStarted = TConcat({
		T(422137389009, --[[VoiceResponse Ice ActivityStarted VoiceResponse ActivityStarted - When an activity is started. Played by the firs merc associated with the task voice:Ice]] "On it like white on rice.")
	}),
	AimAttack = TConcat({
		T(242407483057, --[[VoiceResponse Ice AimAttack VoiceResponse AimAttack - When aiming and there is a decent chance of hitting voice:Ice]] "Watch me pop a cap in this dude."),
		T(461152457683, --[[VoiceResponse Ice AimAttack VoiceResponse AimAttack - When aiming and there is a decent chance of hitting voice:Ice]] "Thug for life."),
		T(698666506743, --[[VoiceResponse Ice AimAttack VoiceResponse AimAttack - When aiming and there is a decent chance of hitting voice:Ice]] "Got a good shot on this mutha'.")
	}),
	AimAttackStealth = TConcat({
		T(537011715730, --[[VoiceResponse Ice AimAttackStealth VoiceResponse AimAttackStealth - When aiming and there is a decent chance of hitting. Used while Sneaking - voice should be shushed (except Steroid) voice:Ice]] "Imma serve up some cold justice."),
		T(873340873559, --[[VoiceResponse Ice AimAttackStealth VoiceResponse AimAttackStealth - When aiming and there is a decent chance of hitting. Used while Sneaking - voice should be shushed (except Steroid) voice:Ice]] "This dude won't hear me coming."),
		T(784524953182, --[[VoiceResponse Ice AimAttackStealth VoiceResponse AimAttackStealth - When aiming and there is a decent chance of hitting. Used while Sneaking - voice should be shushed (except Steroid) voice:Ice]] "Got the angle to do this quiet and quick.")
	}),
	AimAttack_Low = TConcat({
		T(367745332442, --[[VoiceResponse Ice AimAttack_Low VoiceResponse AimAttack_Low - When aiming and the CtH is less than 20% voice:Ice]] "You straight trippin'.")
	}),
	AimAttack_LowStealth = TConcat({
		T(443310269049, --[[VoiceResponse Ice AimAttack_LowStealth VoiceResponse AimAttack_LowStealth - When aiming and there is very low chance of hitting. Used while Sneaking - voice should be shushed (except Steroid) voice:Ice]] "I try this, imma get played.")
	}),
	AmmoLow = TConcat({
		T(178556628045, --[[VoiceResponse Ice AmmoLow VoiceResponse AmmoLow - Played when there is less than 25% of clip size or a full reload cannot be made voice:Ice]] "Yo! Need bullets for my gun!")
	}),
	AnimalFound = TConcat({
		T(523424117482, --[[VoiceResponse Ice AnimalFound VoiceResponse AnimalFound - Enemy animal spotted. voice:Ice]] "Yo! Who let the dogs out?")
	}),
	Autofire = TConcat({
		T(679106588320, --[[VoiceResponse Ice Autofire VoiceResponse Autofire - When using machine gun autofire attacks. Voice is played during the attack and gunfire sounds. voice:Ice]] "Givin' you lead like it's your birthday! ")
	}),
	BecomeHidden = TConcat({
		T(422575354972, --[[VoiceResponse Ice BecomeHidden VoiceResponse BecomeHidden - Played when entering Sneak mode. Voice should be shushed (except Steroid) voice:Ice]] "Goin' low profile."),
		T(168621190187, --[[VoiceResponse Ice BecomeHidden VoiceResponse BecomeHidden - Played when entering Sneak mode. Voice should be shushed (except Steroid) voice:Ice]] "Time to sneak and peek."),
		T(657101785997, --[[VoiceResponse Ice BecomeHidden VoiceResponse BecomeHidden - Played when entering Sneak mode. Voice should be shushed (except Steroid) voice:Ice]] "Forget you ever saw me.")
	}),
	BusySatView = TConcat({
		T(347301380730, --[[VoiceResponse Ice BusySatView VoiceResponse BusySatView - Played when merc is in an activity for more than 8 hours. Students and Patients excluded. Played once per activity. voice:Ice]] "Still gettin' this done. Shoulda brought more music.")
	}),
	Climbing = TConcat({
		T(485865850822, --[[VoiceResponse Ice Climbing VoiceResponse Climbing - Emote. When unit is climbing over fences, on cliffs, etc. voice:Ice]] "(climbing)"),
		T(517996570676, --[[VoiceResponse Ice Climbing VoiceResponse Climbing - Emote. When unit is climbing over fences, on cliffs, etc. voice:Ice]] "(climbing_2)")
	}),
	CombatEndEnemiesRemain = TConcat({
		T(922588296143, --[[VoiceResponse Ice CombatEndEnemiesRemain VoiceResponse CombatEndEnemiesRemain - There are no more aware enemies but there are still enemies in the sector. voice:Ice]] "Still got some business to attend to. Bad dudes still out there.")
	}),
	CombatEndEnemiesRetreated = TConcat({
		T(289496734844, --[[VoiceResponse Ice CombatEndEnemiesRetreated VoiceResponse CombatEndEnemiesRetreated - All enemies have retreated voice:Ice]] "Looks like they split.")
	}),
	CombatEndNoEnemies = TConcat({
		T(400677268130, --[[VoiceResponse Ice CombatEndNoEnemies VoiceResponse CombatEndNoEnemies - All enemies have been killed. voice:Ice]] "Smoked 'em all.")
	}),
	CombatMovement = TConcat({
		T(927661959233, --[[VoiceResponse Ice CombatMovement VoiceResponse CombatMovement - When ordering movement in combat. Up to one full sentence or two short ones. voice:Ice]] "You got it, killah."),
		T(268691738474, --[[VoiceResponse Ice CombatMovement VoiceResponse CombatMovement - When ordering movement in combat. Up to one full sentence or two short ones. voice:Ice]] "I'm packin' steel. You feel me?"),
		T(490202873328, --[[VoiceResponse Ice CombatMovement VoiceResponse CombatMovement - When ordering movement in combat. Up to one full sentence or two short ones. voice:Ice]] "Yo, watch my back."),
		T(291200854454, --[[VoiceResponse Ice CombatMovement VoiceResponse CombatMovement - When ordering movement in combat. Up to one full sentence or two short ones. voice:Ice]] "'ayight."),
		T(720554912709, --[[VoiceResponse Ice CombatMovement VoiceResponse CombatMovement - When ordering movement in combat. Up to one full sentence or two short ones. voice:Ice]] "Word up."),
		T(331936759141, --[[VoiceResponse Ice CombatMovement VoiceResponse CombatMovement - When ordering movement in combat. Up to one full sentence or two short ones. voice:Ice]] "On my way.")
	}),
	CombatMovementStealth = TConcat({
		T(864044387659, --[[VoiceResponse Ice CombatMovementStealth VoiceResponse CombatMovementStealth - When ordering movement while sneaking. Voice should be shushed (except Steroid) voice:Ice]] "Keepin' it on the down low."),
		T(119692324918, --[[VoiceResponse Ice CombatMovementStealth VoiceResponse CombatMovementStealth - When ordering movement while sneaking. Voice should be shushed (except Steroid) voice:Ice]] "Good thing I brought my sneaks."),
		T(150442610789, --[[VoiceResponse Ice CombatMovementStealth VoiceResponse CombatMovementStealth - When ordering movement while sneaking. Voice should be shushed (except Steroid) voice:Ice]] "Playin' it smooth.")
	}),
	CombatStartDetected = TConcat({
		T(834460234253, --[[VoiceResponse Ice CombatStartDetected VoiceResponse CombatStartDetected - When enemy detects a merc who was hiding. voice:Ice]] "Busted! Bad dudes spotted me!")
	}),
	CombatStartPlayer = TConcat({
		T(995829038080, --[[VoiceResponse Ice CombatStartPlayer VoiceResponse CombatStartPlayer - When player initiates combat with shot. voice:Ice]] "Gettin' the party started over here!")
	}),
	CombatTaskCompleted = TConcat({
		T(813562803499, --[[VoiceResponse Ice CombatTaskCompleted VoiceResponse CombatTaskCompleted - When the Combat Task issued by the merc is completed voice:Ice]] "That little side hustle was damn smooth.")
	}),
	CombatTaskFailed = TConcat({
		T(579662354964, --[[VoiceResponse Ice CombatTaskFailed VoiceResponse CombatTaskFailed - When the Combat Task issued by the merc is failed voice:Ice]] "I don't think this gang is ready for no side hustles. We suck.")
	}),
	CombatTaskGiven = TConcat({
		T(881136889492, --[[VoiceResponse Ice CombatTaskGiven VoiceResponse CombatTaskGiven - When the merc sets the player a new Combat Task voice:Ice]] "I'm thinking we should run a little side hustle on these dudes. What do you say?")
	}),
	Comment = "Urban American accent. Gangster. Player. Baller. Age: Adult, young.",
	ContractExpired = TConcat({
		T(607764844988, --[[VoiceResponse Ice ContractExpired VoiceResponse ContractExpired - when the mercs contract expires and the player has not extended it voice:Ice]] "Contract's up, playah.  We cool? All right, I'm outtie.")
	}),
	DeathBuddy1 = TConcat({
		T(691792081697, --[[VoiceResponse Ice DeathBuddy1 VoiceResponse DeathBuddy1 - Played on the death of Magic. voice:Ice]] "Magic, my brother, I owe you everything. Imma get the ones that did this to you, don't you worry about that.")
	}),
	DeathBuddy2 = TConcat({
		T(518754318336, --[[VoiceResponse Ice DeathBuddy2 VoiceResponse DeathBuddy2 - Played on the death of Grizzly. voice:Ice]] "You were the coolest white dude I ever knew, Grizz. Gonna miss seeing you in action. Peace out.")
	}),
	DeathBuddy3 = TConcat({
		T(164283278719, --[[VoiceResponse Ice DeathBuddy3 VoiceResponse DeathBuddy3 - Played on the death of Blood. voice:Ice]] "Damn, Blood, I got mad respect for you. You always kept it real. Gonna miss you, brother.")
	}),
	DeathGeneral = TConcat({
		T(853013314509, --[[VoiceResponse Ice DeathGeneral VoiceResponse DeathGeneral - Played when a character that is neither liked or disliked dies voice:Ice]] "Pour one out for you later, killah.")
	}),
	DeathLearnToLike1 = TConcat({
		T(153655687338, --[[VoiceResponse Ice DeathLearnToLike1 VoiceResponse DeathLearnToLike1 - Played on the death of character who became liked - Livewire. voice:Ice]] "Livewire was a good kid. She was real street.")
	}),
	DoorLocked = TConcat({
		T(305844496312, --[[VoiceResponse Ice DoorLocked VoiceResponse DoorLocked - When a attempting to open locked door voice:Ice]] "Door's locked, playah.")
	}),
	Downed = TConcat({
		T(609631746340, --[[VoiceResponse Ice Downed VoiceResponse Downed - When entering Downed state. Voice should be as if losing consciousness voice:Ice]] "Thug... 'til... I die.")
	}),
	Exhausted = TConcat({
		T(111021116143, --[[VoiceResponse Ice Exhausted VoiceResponse Exhausted - when the merc becomes Exhausted voice:Ice]] "I'm sackin' out, dude. Be back.")
	}),
	FriendlyFireBuddy1 = TConcat({
		T(287101952837, --[[VoiceResponse Ice FriendlyFireBuddy1 VoiceResponse FriendlyFireBuddy1 - Played on friendly fire by the unit hit if the hitting unit is Liked - Magic. voice:Ice]] "What gives, Magic? We come from way back.")
	}),
	FriendlyFireBuddy2 = TConcat({
		T(582046433526, --[[VoiceResponse Ice FriendlyFireBuddy2 VoiceResponse FriendlyFireBuddy2 - Played on friendly fire by the unit hit if the hitting unit is Liked - Grizzly. voice:Ice]] "Grizzly, don't do that to me, man.")
	}),
	FriendlyFireBuddy3 = TConcat({
		T(515125161164, --[[VoiceResponse Ice FriendlyFireBuddy3 VoiceResponse FriendlyFireBuddy3 - Played on friendly fire by the unit hit if the hitting unit is Liked - Blood. voice:Ice]] "We're almost blood, Blood. Don't do no more of that shit.")
	}),
	FriendlyFireGeneral = TConcat({
		T(234133136721, --[[VoiceResponse Ice FriendlyFireGeneral VoiceResponse FriendlyFireGeneral - Played on friendly fire by the unit hit if the hitting unit is neither Liked or Disliked voice:Ice]] "Yo, what's up? Don't do me like that!")
	}),
	FriendlyFireLearnToLike1 = TConcat({
		T(715701944538, --[[VoiceResponse Ice FriendlyFireLearnToLike1 VoiceResponse FriendlyFireLearnToLike1 - Played on friendly fire by the unit hit if the hitting unit has become Liked - Livewire. voice:Ice]] "Sistah... What you doin'?")
	}),
	GasAreaSelection = TConcat({
		T(655699241825, --[[VoiceResponse Ice GasAreaSelection VoiceResponse GasAreaSelection - Unit receiving gas effect or starting round in one. voice:Ice]] "(coughing)")
	}),
	GroupOrder = TConcat({
		T(619672657430, --[[VoiceResponse Ice GroupOrder VoiceResponse GroupOrder - When movement ordered in follow mode or multi selected with other mercs. voice:Ice]] "Let's bounce."),
		T(622633649375, --[[VoiceResponse Ice GroupOrder VoiceResponse GroupOrder - When movement ordered in follow mode or multi selected with other mercs. voice:Ice]] "We outtie."),
		T(424271120402, --[[VoiceResponse Ice GroupOrder VoiceResponse GroupOrder - When movement ordered in follow mode or multi selected with other mercs. voice:Ice]] "On our way."),
		T(291200854454, --[[VoiceResponse Ice GroupOrder VoiceResponse GroupOrder - When movement ordered in follow mode or multi selected with other mercs. voice:Ice]] "'ayight."),
		T(720554912709, --[[VoiceResponse Ice GroupOrder VoiceResponse GroupOrder - When movement ordered in follow mode or multi selected with other mercs. voice:Ice]] "Word up.")
	}),
	HealReceived = TConcat({
		T(407277633411, --[[VoiceResponse Ice HealReceived VoiceResponse HealReceived - Bandaged by a merc or Metvirion used in Inventory voice:Ice]] "Thanks. Feelin' hella good now.")
	}),
	HeavilyWoundedSelection = TConcat({
		T(332902358654, --[[VoiceResponse Ice HeavilyWoundedSelection VoiceResponse HeavilyWoundedSelection - Selected or autoselected with less than 20% health voice:Ice]] "Feel like I just got my ass whooped.")
	}),
	HeavyBreathing = TConcat({
		T(132849153307, --[[VoiceResponse Ice HeavyBreathing VoiceResponse HeavyBreathing - During physical exertion voice:Ice]] "(heavy breath)"),
		T(292474809655, --[[VoiceResponse Ice HeavyBreathing VoiceResponse HeavyBreathing - During physical exertion voice:Ice]] "(heavy breath_2)")
	}),
	Idle = TConcat({
		T(422811061014, --[[VoiceResponse Ice Idle VoiceResponse Idle - Play every 4 hours during which a squad has been inactive.. Played by any of the mercs in the squad. voice:Ice]] "I can just hang, if you want, but I'm ready to roll.")
	}),
	InteractableFound = TConcat({
		T(625257615120, --[[VoiceResponse Ice InteractableFound VoiceResponse InteractableFound - A custom interactable (quest related etc), herbs or salvage material found. voice:Ice]] "Hold up. Check this out."),
		T(226381695272, --[[VoiceResponse Ice InteractableFound VoiceResponse InteractableFound - A custom interactable (quest related etc), herbs or salvage material found. voice:Ice]] "What's up with this thing?")
	}),
	InterestingSector = TConcat({
		T(568300718494, --[[VoiceResponse Ice InterestingSector VoiceResponse InterestingSector - Reached a sector that is marked as interesting. There is somethingin there the player should explore. voice:Ice]] "This place got a lot going on. We should check it out.")
	}),
	ItemDeteriorates = TConcat({
		T(283648225940, --[[VoiceResponse Ice ItemDeteriorates VoiceResponse ItemDeteriorates - Played when a piece of equipment deteriotes to the point when it is in the Needs Repair condition voice:Ice]] "Time to leave this thing out on the corner.")
	}),
	ItemInPoorConditionEquipped = TConcat({
		T(170150051333, --[[VoiceResponse Ice ItemInPoorConditionEquipped VoiceResponse ItemInPoorConditionEquipped - Played in Inventory when player equips weapon/armor that is in Poor Condition voice:Ice]] "Oh come on, man! Don't hand me no Salvation Army reject!")
	}),
	Jumping = TConcat({
		T(788862486493, --[[VoiceResponse Ice Jumping VoiceResponse Jumping - When jumping over small obstacles (e.g. puddles) voice:Ice]] "(jumping over something)"),
		T(868212560684, --[[VoiceResponse Ice Jumping VoiceResponse Jumping - When jumping over small obstacles (e.g. puddles) voice:Ice]] "(jumping over something_2)")
	}),
	KillFriendlyFireBuddy1 = TConcat({
		T(768283776233, --[[VoiceResponse Ice KillFriendlyFireBuddy1 VoiceResponse KillFriendlyFireBuddy1 - Played when a unit kills an ally with friendly fire and the dying unit is Liked - Magic. voice:Ice]] "That's messed up. I knew Magic from way back. This hurts real bad.")
	}),
	KillFriendlyFireBuddy2 = TConcat({
		T(464252973396, --[[VoiceResponse Ice KillFriendlyFireBuddy2 VoiceResponse KillFriendlyFireBuddy2 - Played when a unit kills an ally with friendly fire and the dying unit is Liked - Grizzly. voice:Ice]] "I killed the Grizzly bear. That's not cool. Don't think I'll find another dude like him.")
	}),
	KillFriendlyFireBuddy3 = TConcat({
		T(216586496625, --[[VoiceResponse Ice KillFriendlyFireBuddy3 VoiceResponse KillFriendlyFireBuddy3 - Played when a unit kills an ally with friendly fire and the dying unit is Liked - Blood. voice:Ice]] "Damn. Blood was my brother from another mother.")
	}),
	KillFriendlyFireGeneral = TConcat({
		T(554277403158, --[[VoiceResponse Ice KillFriendlyFireGeneral VoiceResponse KillFriendlyFireGeneral - Played when a unit kills an ally with friendly fire and the dying unit is neither Liked nor Disliked voice:Ice]] "Tryin' hard not to lose my cool.")
	}),
	KillFriendlyFireLearnToLike1 = TConcat({
		T(137746789254, --[[VoiceResponse Ice KillFriendlyFireLearnToLike1 VoiceResponse KillFriendlyFireLearnToLike1 - Played when a unit kills an ally with friendly fire and the dying unit has become Liked - Livewire. voice:Ice]] "Sistah, you had some moves. This shoulda never happened. I wish I could take it back.")
	}),
	LearnToLike1 = TConcat({
		T(186766984946, --[[VoiceResponse Ice LearnToLike1 VoiceResponse LearnToLike1 - Played when a character becomes liked - Livewire. voice:Ice]] "That Livewire, she's kinda fly. I ain't lyin'.")
	}),
	LevelUp = TConcat({
		T(827079737210, --[[VoiceResponse Ice LevelUp VoiceResponse LevelUp - Leveled up or a magazine is read. Only one played if multiple character level up. voice:Ice]] "I'm gettin' big, playah! We gonna have to talk about my fee.")
	}),
	LootFound = TConcat({
		T(210973498289, --[[VoiceResponse Ice LootFound VoiceResponse LootFound - A loot container is nearby (e.g. dead body, crate,...) 10s cooldown voice:Ice]] "Check it. Might be a little somethin'-somethin'."),
		T(595193948533, --[[VoiceResponse Ice LootFound VoiceResponse LootFound - A loot container is nearby (e.g. dead body, crate,...) 10s cooldown voice:Ice]] "Something worth checking out over here."),
		T(521671964404, --[[VoiceResponse Ice LootFound VoiceResponse LootFound - A loot container is nearby (e.g. dead body, crate,...) 10s cooldown voice:Ice]] "Let's grab and go.")
	}),
	LootOpened = TConcat({
		T(622296835938, --[[VoiceResponse Ice LootOpened VoiceResponse LootOpened - Loot container opened. Supressed by ValuableItemFound voice:Ice]] "Come on, show me some bling. Show me some cheddar.")
	}),
	LowChanceShot = TConcat({
		T(965790407036, --[[VoiceResponse Ice LowChanceShot VoiceResponse LowChanceShot - Successful attack when the CtH is less than 20% voice:Ice]] "Oh snap! I hope everyone saw that!")
	}),
	ManyEnemiesSelection = TConcat({
		T(207123324902, --[[VoiceResponse Ice ManyEnemiesSelection VoiceResponse ManyEnemiesSelection - Selected when the unit sees 5+ units in line of fire voice:Ice]] "A lot of bad dudes coming my way.")
	}),
	MeleeEnemiesClosing = TConcat({
		T(843328052921, --[[VoiceResponse Ice MeleeEnemiesClosing VoiceResponse MeleeEnemiesClosing - When enemy in melee range. Needs further clarification!!! voice:Ice]] "Looks like this one wants to step to me.")
	}),
	MineFound = TConcat({
		T(704282086474, --[[VoiceResponse Ice MineFound VoiceResponse MineFound - A mine (or other explosive trap) was found nearby voice:Ice]] "Awww, man... This looks set to blow.")
	}),
	MineNearbySelection = TConcat({
		T(807486389842, --[[VoiceResponse Ice MineNearbySelection VoiceResponse MineNearbySelection - Selected when there is a trap nearby voice:Ice]] "Got a nasty-ass trap over here.")
	}),
	MissedByKillShot = TConcat({
		T(634303679240, --[[VoiceResponse Ice MissedByKillShot VoiceResponse MissedByKillShot - When character missed a by a shot that would've killed him/her. Shot must have had 50%+ CtH. voice:Ice]] "That dude almost got me! I ain't goin' out like that!")
	}),
	MockGeneral = TConcat({
		T(567835648266, --[[VoiceResponse Ice MockGeneral VoiceResponse MockGeneral - 20% chance to play when another merc misses a high chance shot voice:Ice]] "Yo! Put the crack pipe down!")
	}),
	MockLearnToLike1 = TConcat({
		T(230026797493, --[[VoiceResponse Ice MockLearnToLike1 VoiceResponse MockLearnToLike1 - Played on a high chance miss by Livewire. voice:Ice]] "Don't let 'em dis you, Wire. Show your roots.")
	}),
	MockLike1 = TConcat({
		T(600197380795, --[[VoiceResponse Ice MockLike1 VoiceResponse MockLike1 - Played on a high chance miss by Magic. voice:Ice]] "Come on, Magic! Now, you know I saw that!")
	}),
	MockLike2 = TConcat({
		T(241289685280, --[[VoiceResponse Ice MockLike2 VoiceResponse MockLike2 - Played on a high chance miss by Grizzly. voice:Ice]] "Who that? That Grizzly Bear or Teddy Bear?")
	}),
	MockLike3 = TConcat({
		T(725944329247, --[[VoiceResponse Ice MockLike3 VoiceResponse MockLike3 - Played on a high chance miss by Blood. voice:Ice]] "Try it with your eyes open next time, Blood!")
	}),
	NoAmmo = TConcat({
		T(646250517667, --[[VoiceResponse Ice NoAmmo VoiceResponse NoAmmo - No more ammo in the gun and no more bullets. voice:Ice]] "Need some lead for my gun!")
	}),
	NotNow = TConcat({
		T(962842076371, --[[VoiceResponse Ice NotNow VoiceResponse NotNow - When interacting with a NPC while in combat voice:Ice]] "Be cool, man. We got business to attend to.")
	}),
	OpponentFound = TConcat({
		T(235069759654, --[[VoiceResponse Ice OpponentFound VoiceResponse OpponentFound - Enemy spotted. voice:Ice]] "Hootie-hoo. Bad dude spotted."),
		T(656402535090, --[[VoiceResponse Ice OpponentFound VoiceResponse OpponentFound - Enemy spotted. voice:Ice]] "Bad dudes are here.")
	}),
	OpponentKilled = TConcat({
		T(899812836991, --[[VoiceResponse Ice OpponentKilled VoiceResponse OpponentKilled - When opponent killed (unless OponentKilledCrit or OponentKilled multi isplayed) voice:Ice]] "One less bad dude to worry about."),
		T(119688797524, --[[VoiceResponse Ice OpponentKilled VoiceResponse OpponentKilled - When opponent killed (unless OponentKilledCrit or OponentKilled multi isplayed) voice:Ice]] "Ice Williams, representin'."),
		T(183553999850, --[[VoiceResponse Ice OpponentKilled VoiceResponse OpponentKilled - When opponent killed (unless OponentKilledCrit or OponentKilled multi isplayed) voice:Ice]] "Dumb dude shoulda' run."),
		T(819630472534, --[[VoiceResponse Ice OpponentKilled VoiceResponse OpponentKilled - When opponent killed (unless OponentKilledCrit or OponentKilled multi isplayed) voice:Ice]] "I ain't playin' with you!"),
		T(975896944046, --[[VoiceResponse Ice OpponentKilled VoiceResponse OpponentKilled - When opponent killed (unless OponentKilledCrit or OponentKilled multi isplayed) voice:Ice]] "I do this all day!")
	}),
	OpponentKilledAnimal = TConcat({
		T(648168530260, --[[VoiceResponse Ice OpponentKilledAnimal VoiceResponse OpponentKilledAnimal - When animal is killed voice:Ice]] "I ain't tryin' to get turned into kibble, know what I'm sayin'?")
	}),
	OpponentKilledHeadshot = TConcat({
		T(930344432706, --[[VoiceResponse Ice OpponentKilledHeadshot VoiceResponse OpponentKilledHeadshot - Opponent killed with a headshot voice:Ice]] "You see that shot? That was tight!"),
		T(426845195153, --[[VoiceResponse Ice OpponentKilledHeadshot VoiceResponse OpponentKilledHeadshot - Opponent killed with a headshot voice:Ice]] "Whoah dude... Blood bath!"),
		T(850584380638, --[[VoiceResponse Ice OpponentKilledHeadshot VoiceResponse OpponentKilledHeadshot - Opponent killed with a headshot voice:Ice]] "Popped that one right in the grill!")
	}),
	OpponentKilledMelee = TConcat({
		T(297498072289, --[[VoiceResponse Ice OpponentKilledMelee VoiceResponse OpponentKilledMelee - Played when killing a unit with melee weapon voice:Ice]] "You come strong or you don't come at all!")
	}),
	OpponentKilledStealth = TConcat({
		T(264455760276, --[[VoiceResponse Ice OpponentKilledStealth VoiceResponse OpponentKilledStealth - Played when a Stealth kill happens. Voice should be shushed (except Steroid) voice:Ice]] "Took 'em down nice and quiet."),
		T(499040482559, --[[VoiceResponse Ice OpponentKilledStealth VoiceResponse OpponentKilledStealth - Played when a Stealth kill happens. Voice should be shushed (except Steroid) voice:Ice]] "Nobody saw nothin'."),
		T(315179450126, --[[VoiceResponse Ice OpponentKilledStealth VoiceResponse OpponentKilledStealth - Played when a Stealth kill happens. Voice should be shushed (except Steroid) voice:Ice]] "That dude never saw me coming.")
	}),
	Order = TConcat({
		T(291200854454, --[[VoiceResponse Ice Order VoiceResponse Order - When movement ordered (out of combat) Should be very short (3-5 words) voice:Ice]] "'ayight."),
		T(436203512101, --[[VoiceResponse Ice Order VoiceResponse Order - When movement ordered (out of combat) Should be very short (3-5 words) voice:Ice]] "I'm 'bout it."),
		T(989968899120, --[[VoiceResponse Ice Order VoiceResponse Order - When movement ordered (out of combat) Should be very short (3-5 words) voice:Ice]] "No diggity."),
		T(720554912709, --[[VoiceResponse Ice Order VoiceResponse Order - When movement ordered (out of combat) Should be very short (3-5 words) voice:Ice]] "Word up."),
		T(331936759141, --[[VoiceResponse Ice Order VoiceResponse Order - When movement ordered (out of combat) Should be very short (3-5 words) voice:Ice]] "On my way."),
		T(927661959233, --[[VoiceResponse Ice Order VoiceResponse Order - When movement ordered (out of combat) Should be very short (3-5 words) voice:Ice]] "You got it, killah.")
	}),
	Outnumbered = TConcat({
		T(172513181390, --[[VoiceResponse Ice Outnumbered VoiceResponse Outnumbered - Unit sees more enemies than allies voice:Ice]] "Feelin' the heat over here!")
	}),
	Overwatch = TConcat({
		T(498359571144, --[[VoiceResponse Ice Overwatch VoiceResponse Overwatch - When setting overwatch voice:Ice]] "You got it. The Iceman gonna keep everyone covered.")
	}),
	OverwatchSelection = TConcat({
		T(923858969468, --[[VoiceResponse Ice OverwatchSelection VoiceResponse OverwatchSelection - Selected when under Overwatch. voice:Ice]] "If I move, they gonna pop a cap in my ass.")
	}),
	Pain = TConcat({
		T(175996823527, --[[VoiceResponse Ice Pain VoiceResponse Pain - Hit by an attack (if surrounded SurroundedPain is played instead). Short. These are emotes - disregard the written text. voice:Ice]] "head1"),
		T(808279460482, --[[VoiceResponse Ice Pain VoiceResponse Pain - Hit by an attack (if surrounded SurroundedPain is played instead). Short. These are emotes - disregard the written text. voice:Ice]] "head2"),
		T(416951050793, --[[VoiceResponse Ice Pain VoiceResponse Pain - Hit by an attack (if surrounded SurroundedPain is played instead). Short. These are emotes - disregard the written text. voice:Ice]] "head3"),
		T(890455042925, --[[VoiceResponse Ice Pain VoiceResponse Pain - Hit by an attack (if surrounded SurroundedPain is played instead). Short. These are emotes - disregard the written text. voice:Ice]] "chest1"),
		T(974525586115, --[[VoiceResponse Ice Pain VoiceResponse Pain - Hit by an attack (if surrounded SurroundedPain is played instead). Short. These are emotes - disregard the written text. voice:Ice]] "chest2"),
		T(109598085128, --[[VoiceResponse Ice Pain VoiceResponse Pain - Hit by an attack (if surrounded SurroundedPain is played instead). Short. These are emotes - disregard the written text. voice:Ice]] "chest3"),
		T(105574692677, --[[VoiceResponse Ice Pain VoiceResponse Pain - Hit by an attack (if surrounded SurroundedPain is played instead). Short. These are emotes - disregard the written text. voice:Ice]] "arm1"),
		T(983844846565, --[[VoiceResponse Ice Pain VoiceResponse Pain - Hit by an attack (if surrounded SurroundedPain is played instead). Short. These are emotes - disregard the written text. voice:Ice]] "arm2"),
		T(746554529907, --[[VoiceResponse Ice Pain VoiceResponse Pain - Hit by an attack (if surrounded SurroundedPain is played instead). Short. These are emotes - disregard the written text. voice:Ice]] "arm3"),
		T(675767242605, --[[VoiceResponse Ice Pain VoiceResponse Pain - Hit by an attack (if surrounded SurroundedPain is played instead). Short. These are emotes - disregard the written text. voice:Ice]] "leg1"),
		T(944014444013, --[[VoiceResponse Ice Pain VoiceResponse Pain - Hit by an attack (if surrounded SurroundedPain is played instead). Short. These are emotes - disregard the written text. voice:Ice]] "leg2"),
		T(926221316430, --[[VoiceResponse Ice Pain VoiceResponse Pain - Hit by an attack (if surrounded SurroundedPain is played instead). Short. These are emotes - disregard the written text. voice:Ice]] "leg3"),
		T(643079709749, --[[VoiceResponse Ice Pain VoiceResponse Pain - Hit by an attack (if surrounded SurroundedPain is played instead). Short. These are emotes - disregard the written text. voice:Ice]] "shin1"),
		T(869511026400, --[[VoiceResponse Ice Pain VoiceResponse Pain - Hit by an attack (if surrounded SurroundedPain is played instead). Short. These are emotes - disregard the written text. voice:Ice]] "shin2"),
		T(854968482022, --[[VoiceResponse Ice Pain VoiceResponse Pain - Hit by an attack (if surrounded SurroundedPain is played instead). Short. These are emotes - disregard the written text. voice:Ice]] "shin3")
	}),
	PersonalPerkSubtitled = TConcat({
		T(393499346321, --[[VoiceResponse Ice PersonalPerkSubtitled VoiceResponse PersonalPerkSubtitled - Custom use for personal perks. Uses PersonalPerk if blank. voice:Ice]] "Time for the Ice storm!")
	}),
	PinDown = TConcat({
		T(161354808818, --[[VoiceResponse Ice PinDown VoiceResponse PinDown - When pinning down (sniper rifles only) voice:Ice]] "Go ahead and try an' pick your head up!")
	}),
	PraisesBuddy1 = TConcat({
		T(454150754282, --[[VoiceResponse Ice PraisesBuddy1 VoiceResponse PraisesBuddy1 - Played on a successful kill by Magic. voice:Ice]] "Way to be, brother man! Hey, they don't call him Magic for nothin'!")
	}),
	PraisesBuddy2 = TConcat({
		T(124934172256, --[[VoiceResponse Ice PraisesBuddy2 VoiceResponse PraisesBuddy2 - Played on a successful kill by Grizzly. voice:Ice]] "Don't poke the bear! Ain't that right, Grizz? Yeah, that's what's up!")
	}),
	PraisesBuddy3 = TConcat({
		T(581449840436, --[[VoiceResponse Ice PraisesBuddy3 VoiceResponse PraisesBuddy3 - Played on a successful kill by Blood. voice:Ice]] "Hey, check out my man Blood over here. Stylin' and profilin'!")
	}),
	PraisesFemale = TConcat({
		T(753448361930, --[[VoiceResponse Ice PraisesFemale VoiceResponse PraisesFemale - Played when a female merc makes a kill (20% chance) voice:Ice]] "That's one badass bitch! Good thing she's on our side.")
	}),
	PraisesLearnToLike1 = TConcat({
		T(343107581648, --[[VoiceResponse Ice PraisesLearnToLike1 VoiceResponse PraisesLearnToLike1 - Played on a successful kill by Livewire. voice:Ice]] "Way to go, sistah! Show your cred.")
	}),
	PraisesMale = TConcat({
		T(289269207449, --[[VoiceResponse Ice PraisesMale VoiceResponse PraisesMale - Played when a male merc makes a kill (20% chance) voice:Ice]] "I see you, killah!")
	}),
	SectorArrived = TConcat({
		T(933815676907, --[[VoiceResponse Ice SectorArrived VoiceResponse SectorArrived - SatView - new sector reached. Played by random merc in squad. voice:Ice]] "I'm here, playah. Holla back. I'll be where I'm at.")
	}),
	Selection = TConcat({
		T(611414300692, --[[VoiceResponse Ice Selection VoiceResponse Selection - when selected or autoselected voice:Ice]] "Ice here."),
		T(727635837480, --[[VoiceResponse Ice Selection VoiceResponse Selection - when selected or autoselected voice:Ice]] "Keepin' it real."),
		T(557242143322, --[[VoiceResponse Ice Selection VoiceResponse Selection - when selected or autoselected voice:Ice]] "'sup, playah?")
	}),
	SelectionStealth = TConcat({
		T(168621190187, --[[VoiceResponse Ice SelectionStealth VoiceResponse SelectionStealth - when selected or autoselected voice:Ice]] "Time to sneak and peek."),
		T(657101785997, --[[VoiceResponse Ice SelectionStealth VoiceResponse SelectionStealth - when selected or autoselected voice:Ice]] "Forget you ever saw me."),
		T(150442610789, --[[VoiceResponse Ice SelectionStealth VoiceResponse SelectionStealth - when selected or autoselected voice:Ice]] "Playin' it smooth.")
	}),
	SeriouslyWounded = TConcat({
		T(854480407438, --[[VoiceResponse Ice SeriouslyWounded VoiceResponse SeriouslyWounded - Unit is seriously wounded (3 or more wounds) voice:Ice]] "I'm hurt real bad over here. Like, all critical and shit.")
	}),
	Startled = TConcat({
		T(169781015365, --[[VoiceResponse Ice Startled VoiceResponse Startled - Startled by hearing a sudden noise voice:Ice]] "Huh?"),
		T(679259652160, --[[VoiceResponse Ice Startled VoiceResponse Startled - Startled by hearing a sudden noise voice:Ice]] "Wha-?")
	}),
	SurroundedPain = TConcat({
		T(513306547828, --[[VoiceResponse Ice SurroundedPain VoiceResponse SurroundedPain - hit by an attack when surrounded. Situation should be very dire voice:Ice]] "I ain't tryin' to die out here, you feel me?")
	}),
	TacticalCareful = TConcat({
		T(236549153697, --[[VoiceResponse Ice TacticalCareful VoiceResponse TacticalCareful - The other team is making gains during the battle (inflicted 2+ wounds during their turn) voice:Ice]] "Chill, guys. Time to get Icy.")
	}),
	TacticalKilling = TConcat({
		T(176008827443, --[[VoiceResponse Ice TacticalKilling VoiceResponse TacticalKilling - The team is winning the battle  (2+ units have been downed/killed) voice:Ice]] "Bad dudes never saw us coming.")
	}),
	TacticalPressing = TConcat({
		T(859686439991, --[[VoiceResponse Ice TacticalPressing VoiceResponse TacticalPressing - The team is making gains during the battle (2+ wounds have been inflicted) voice:Ice]] "Feels good when we're winnin'."),
		T(368829591023, --[[VoiceResponse Ice TacticalPressing VoiceResponse TacticalPressing - The team is making gains during the battle (2+ wounds have been inflicted) voice:Ice]] "We are puttin' on the pressure.")
	}),
	TacticalRevenge = TConcat({
		T(829751487391, --[[VoiceResponse Ice TacticalRevenge VoiceResponse TacticalRevenge - A unit from the team has been downed/killed voice:Ice]] "Pour one out, later. Time to get even.")
	}),
	TakeCover = TConcat({
		T(722295365952, --[[VoiceResponse Ice TakeCover VoiceResponse TakeCover - Played when the Take Cover action is used voice:Ice]] "Goin' to ground.")
	}),
	ThreatSelection = TConcat({
		T(523965635825, --[[VoiceResponse Ice ThreatSelection VoiceResponse ThreatSelection - Selected when under Pinned Down or in the area of an incoming explosion. voice:Ice]] "I got to move out, know what I'm sayin'?")
	}),
	ThrowGrenade = TConcat({
		T(812783259083, --[[VoiceResponse Ice ThrowGrenade VoiceResponse ThrowGrenade - When throwing grenade. Voiced line starts before the explosion. voice:Ice]] "Let's see how high these dudes can jump!")
	}),
	Tired = TConcat({
		T(330799516138, --[[VoiceResponse Ice Tired VoiceResponse Tired - when the merc becomes tired voice:Ice]] "I can barely stay awake...")
	}),
	TrainingReceived = TConcat({
		T(693340823952, --[[VoiceResponse Ice TrainingReceived VoiceResponse TrainingReceived - Training received in SatView. Uses LevelUp if blank. voice:Ice]] "Check it. I'm gettin' the hang of this.")
	}),
	Travelling = TConcat({
		T(929082492467, --[[VoiceResponse Ice Travelling VoiceResponse Travelling - When a squad is travelling and enters new sector that is not the final destination of the travel. Played by the squad leader voice:Ice]] "This place is dead. Let's split.")
	}),
	ValuableItemFound = TConcat({
		T(263027458258, --[[VoiceResponse Ice ValuableItemFound VoiceResponse ValuableItemFound - Loot container opened with a valuable item inside voice:Ice]] "Damn, this shit's da bomb, yo.")
	}),
	WeaponBroken = TConcat({
		T(257835604955, --[[VoiceResponse Ice WeaponBroken VoiceResponse WeaponBroken - When the player's weapon breaks voice:Ice]] "Yo! This piece of junk is broke!")
	}),
	WeaponJammed = TConcat({
		T(424386569792, --[[VoiceResponse Ice WeaponJammed VoiceResponse WeaponJammed - When weapon has jammed voice:Ice]] "Yo! Need some WD-40 up in here!")
	}),
	Wounded = TConcat({
		T(598725890047, --[[VoiceResponse Ice Wounded VoiceResponse Wounded - Unit is Wounded. (When the Wounded VR is played, the Pain VR should be suppressed.) voice:Ice]] "Taking fire over here."),
		T(380296628428, --[[VoiceResponse Ice Wounded VoiceResponse Wounded - Unit is Wounded. (When the Wounded VR is played, the Pain VR should be suppressed.) voice:Ice]] "You did NOT just hit me!"),
		T(115737201904, --[[VoiceResponse Ice Wounded VoiceResponse Wounded - Unit is Wounded. (When the Wounded VR is played, the Pain VR should be suppressed.) voice:Ice]] "Damn! These dudes mean business!")
	}),
	group = "MercenariesOld",
	id = "Ice",
})

