-- ========== GENERATED BY VoiceResponse Editor (Ctrl-Alt-V) DO NOT EDIT MANUALLY! ==========

PlaceObj('VoiceResponse', {
	ActivityFinished = TConcat({
		T(858400426454, --[[VoiceResponse Larry ActivityFinished VoiceResponse ActivityFinished - SatView activity finished voice:Larry]] "I'm done. Be right back. Need to powder my nose.")
	}),
	ActivityStarted = TConcat({
		T(495296367872, --[[VoiceResponse Larry ActivityStarted VoiceResponse ActivityStarted - When an activity is started. Played by the firs merc associated with the task voice:Larry]] "I'm starting on this, but only because the Universe tells me to.")
	}),
	AimAttack = TConcat({
		T(394135197337, --[[VoiceResponse Larry AimAttack VoiceResponse AimAttack - When aiming and there is a decent chance of hitting voice:Larry]] "Okay, now watch THIS, man."),
		T(129867965797, --[[VoiceResponse Larry AimAttack VoiceResponse AimAttack - When aiming and there is a decent chance of hitting voice:Larry]] "Aim for the one in the middle, right?"),
		T(123378266431, --[[VoiceResponse Larry AimAttack VoiceResponse AimAttack - When aiming and there is a decent chance of hitting voice:Larry]] "Hang on, let me just make sure I got this pointed the right way.")
	}),
	AimAttackStealth = TConcat({
		T(469894032845, --[[VoiceResponse Larry AimAttackStealth VoiceResponse AimAttackStealth - When aiming and there is a decent chance of hitting. Used while Sneaking - voice should be shushed (except Steroid) voice:Larry]] "They won't feel a thing... or wait, maybe that's me."),
		T(517629253982, --[[VoiceResponse Larry AimAttackStealth VoiceResponse AimAttackStealth - When aiming and there is a decent chance of hitting. Used while Sneaking - voice should be shushed (except Steroid) voice:Larry]] "Got a chance to do this quietly, man."),
		T(905260040154, --[[VoiceResponse Larry AimAttackStealth VoiceResponse AimAttackStealth - When aiming and there is a decent chance of hitting. Used while Sneaking - voice should be shushed (except Steroid) voice:Larry]] "I'm in position to totally do a surprise thing.")
	}),
	AimAttack_Low = TConcat({
		T(333439385598, --[[VoiceResponse Larry AimAttack_Low VoiceResponse AimAttack_Low - When aiming and the CtH is less than 20% voice:Larry]] "No way, man. Are you on drugs? No, seriously, do you have drugs?")
	}),
	AimAttack_LowStealth = TConcat({
		T(990505532342, --[[VoiceResponse Larry AimAttack_LowStealth VoiceResponse AimAttack_LowStealth - When aiming and there is very low chance of hitting. Used while Sneaking - voice should be shushed (except Steroid) voice:Larry]] "No, man. I can barely see them from here and I'm like, real comfy too.")
	}),
	AmmoLow = TConcat({
		T(594206443388, --[[VoiceResponse Larry AmmoLow VoiceResponse AmmoLow - Played when there is less than 25% of clip size or a full reload cannot be made voice:Larry]] "Running low on lead for my gun.")
	}),
	AnimalFound = TConcat({
		T(254536276573, --[[VoiceResponse Larry AnimalFound VoiceResponse AnimalFound - Enemy animal spotted. voice:Larry]] "Whoa! It's a zombie dolphin, man!")
	}),
	BandageDownedUnit = TConcat({
		T(645312334865, --[[VoiceResponse Larry BandageDownedUnit VoiceResponse BandageDownedUnit - When a downed unit is bandaged. Played by the unit that does the bandaging voice:Larry]] "There you go. Feel better? Want to feel EVEN better?")
	}),
	BecomeHidden = TConcat({
		T(669077753362, --[[VoiceResponse Larry BecomeHidden VoiceResponse BecomeHidden - Played when entering Sneak mode. Voice should be shushed (except Steroid) voice:Larry]] "No problemo, man. I'll just take this pill and make myself real small."),
		T(731130328408, --[[VoiceResponse Larry BecomeHidden VoiceResponse BecomeHidden - Played when entering Sneak mode. Voice should be shushed (except Steroid) voice:Larry]] "Ted, shhh... We gotta be quiet.")
	}),
	BusySatView = TConcat({
		T(494550449889, --[[VoiceResponse Larry BusySatView VoiceResponse BusySatView - Played when merc is in an activity for more than 8 hours. Students and Patients excluded. Played once per activity. voice:Larry]] "Don't say that, Ted! I'm doing the best I can!")
	}),
	Climbing = TConcat({
		T(128211388222, --[[VoiceResponse Larry Climbing VoiceResponse Climbing - Emote. When unit is climbing over fences, on cliffs, etc. voice:Larry]] "(climbing)"),
		T(319076906834, --[[VoiceResponse Larry Climbing VoiceResponse Climbing - Emote. When unit is climbing over fences, on cliffs, etc. voice:Larry]] "(climbing_2)")
	}),
	CombatEndEnemiesRemain = TConcat({
		T(594072813686, --[[VoiceResponse Larry CombatEndEnemiesRemain VoiceResponse CombatEndEnemiesRemain - There are no more aware enemies but there are still enemies in the sector. voice:Larry]] "Probably more hiding out there, praying we're just a big hallucination.")
	}),
	CombatEndEnemiesRetreated = TConcat({
		T(815071087938, --[[VoiceResponse Larry CombatEndEnemiesRetreated VoiceResponse CombatEndEnemiesRetreated - All enemies have retreated voice:Larry]] "Grunts took off like someone called the cops.")
	}),
	CombatEndNoEnemies = TConcat({
		T(225327293958, --[[VoiceResponse Larry CombatEndNoEnemies VoiceResponse CombatEndNoEnemies - All enemies have been killed. voice:Larry]] "Everybody's dead, unless I'm hallucinating corpses again.")
	}),
	CombatMovement = TConcat({
		T(816602283414, --[[VoiceResponse Larry CombatMovement VoiceResponse CombatMovement - When ordering movement in combat. Up to one full sentence or two short ones. voice:Larry]] "All the way over there?"),
		T(197773709974, --[[VoiceResponse Larry CombatMovement VoiceResponse CombatMovement - When ordering movement in combat. Up to one full sentence or two short ones. voice:Larry]] "Hang on, Ted!"),
		T(251439944603, --[[VoiceResponse Larry CombatMovement VoiceResponse CombatMovement - When ordering movement in combat. Up to one full sentence or two short ones. voice:Larry]] "The ground feels funny, man."),
		T(609585887879, --[[VoiceResponse Larry CombatMovement VoiceResponse CombatMovement - When ordering movement in combat. Up to one full sentence or two short ones. voice:Larry]] "Whatever."),
		T(411264429348, --[[VoiceResponse Larry CombatMovement VoiceResponse CombatMovement - When ordering movement in combat. Up to one full sentence or two short ones. voice:Larry]] "That's cool with me."),
		T(678118847054, --[[VoiceResponse Larry CombatMovement VoiceResponse CombatMovement - When ordering movement in combat. Up to one full sentence or two short ones. voice:Larry]] "Come on, Ted. Let's go."),
		T(667505641622, --[[VoiceResponse Larry CombatMovement VoiceResponse CombatMovement - When ordering movement in combat. Up to one full sentence or two short ones. voice:Larry]] "No problemo, man.")
	}),
	CombatMovementStealth = TConcat({
		T(569184351897, --[[VoiceResponse Larry CombatMovementStealth VoiceResponse CombatMovementStealth - When ordering movement while sneaking. Voice should be shushed (except Steroid) voice:Larry]] "I'm like a shadow... a super secret shadow that only I can see."),
		T(731130328408, --[[VoiceResponse Larry CombatMovementStealth VoiceResponse CombatMovementStealth - When ordering movement while sneaking. Voice should be shushed (except Steroid) voice:Larry]] "Ted, shhh... We gotta be quiet."),
		T(901927861566, --[[VoiceResponse Larry CombatMovementStealth VoiceResponse CombatMovementStealth - When ordering movement while sneaking. Voice should be shushed (except Steroid) voice:Larry]] "I'm so quiet I can't even hear myself.")
	}),
	CombatStartDetected = TConcat({
		T(447488060434, --[[VoiceResponse Larry CombatStartDetected VoiceResponse CombatStartDetected - When enemy detects a merc who was hiding. voice:Larry]] "How did they see me? Guess I took the wrong pill.")
	}),
	CombatStartPlayer = TConcat({
		T(704838270669, --[[VoiceResponse Larry CombatStartPlayer VoiceResponse CombatStartPlayer - When player initiates combat with shot. voice:Larry]] "I'm telling you, man! Zombies!")
	}),
	CombatTaskCompleted = TConcat({
		T(697586007165, --[[VoiceResponse Larry CombatTaskCompleted VoiceResponse CombatTaskCompleted - When the Combat Task issued by the merc is completed voice:Larry]] "The anti-zombie tactics worked! Our brains are safe... for now.")
	}),
	CombatTaskFailed = TConcat({
		T(684869629623, --[[VoiceResponse Larry CombatTaskFailed VoiceResponse CombatTaskFailed - When the Combat Task issued by the merc is failed voice:Larry]] "The zombies have mutated! Our tactics don't work anymore!")
	}),
	CombatTaskGiven = TConcat({
		T(294999854180, --[[VoiceResponse Larry CombatTaskGiven VoiceResponse CombatTaskGiven - When the merc sets the player a new Combat Task voice:Larry]] "Time to execute a special anti-zombie tactic!")
	}),
	Comment = "Standard American accent. Drunk and high. Hallucinating. Age: Adult, young.",
	DeathGeneral = TConcat({
		T(244911963640, --[[VoiceResponse Larry DeathGeneral VoiceResponse DeathGeneral - Played when a character that is neither liked or disliked dies voice:Larry]] "Oh, bummer man. I'll pour one out for you. Anybody got booze?")
	}),
	DoorLocked = TConcat({
		T(681800693926, --[[VoiceResponse Larry DoorLocked VoiceResponse DoorLocked - When a attempting to open locked door voice:Larry]] "Bummer, man. It's locked.")
	}),
	Downed = TConcat({
		T(390563119597, --[[VoiceResponse Larry Downed VoiceResponse Downed - When entering Downed state. Voice should be as if losing consciousness voice:Larry]] "Oh, man, I think I'm dying. Bummer. I was having the best trip.")
	}),
	Exhausted = TConcat({
		T(138166624520, --[[VoiceResponse Larry Exhausted VoiceResponse Exhausted - when the merc becomes Exhausted voice:Larry]] "Time for me to pass out.")
	}),
	FriendlyFireGeneral = TConcat({
		T(206220002103, --[[VoiceResponse Larry FriendlyFireGeneral VoiceResponse FriendlyFireGeneral - Played on friendly fire by the unit hit if the hitting unit is neither Liked or Disliked voice:Larry]] "Damned mosquitos!")
	}),
	GasAreaSelection = TConcat({
		T(377699448355, --[[VoiceResponse Larry GasAreaSelection VoiceResponse GasAreaSelection - Unit receiving gas effect or starting round in one. voice:Larry]] "(coughing)")
	}),
	GroupOrder = TConcat({
		T(113548193479, --[[VoiceResponse Larry GroupOrder VoiceResponse GroupOrder - When movement ordered in follow mode or multi selected with other mercs. voice:Larry]] "You guys go ahead, I'll catch up."),
		T(345148501525, --[[VoiceResponse Larry GroupOrder VoiceResponse GroupOrder - When movement ordered in follow mode or multi selected with other mercs. voice:Larry]] "Can we stop for snacks on the way?"),
		T(198952960978, --[[VoiceResponse Larry GroupOrder VoiceResponse GroupOrder - When movement ordered in follow mode or multi selected with other mercs. voice:Larry]] "We're moving the party!"),
		T(609585887879, --[[VoiceResponse Larry GroupOrder VoiceResponse GroupOrder - When movement ordered in follow mode or multi selected with other mercs. voice:Larry]] "Whatever.")
	}),
	HealReceived = TConcat({
		T(375564734822, --[[VoiceResponse Larry HealReceived VoiceResponse HealReceived - Bandaged by a merc or Metvirion used in Inventory voice:Larry]] "Oh, yeah. That's real good. Hey, give me some more of that.")
	}),
	HealReceivedSatView = TConcat({
		T(505108227647, --[[VoiceResponse Larry HealReceivedSatView VoiceResponse HealReceivedSatView - When a wound is removed by a Sector Operation. Uses HealReceived if blank. voice:Larry]] "Feeling reeeeeeal good, man.")
	}),
	HeavilyWoundedSelection = TConcat({
		T(870968315455, --[[VoiceResponse Larry HeavilyWoundedSelection VoiceResponse HeavilyWoundedSelection - Selected or autoselected with less than 20% health voice:Larry]] "Oh, wow, man. Look at all this blood and stuff. Should probably take another painkiller.")
	}),
	HeavyBreathing = TConcat({
		T(692674271364, --[[VoiceResponse Larry HeavyBreathing VoiceResponse HeavyBreathing - During physical exertion voice:Larry]] "(heavy breath)"),
		T(253711400240, --[[VoiceResponse Larry HeavyBreathing VoiceResponse HeavyBreathing - During physical exertion voice:Larry]] "(heavy breath_2)")
	}),
	Idle = TConcat({
		T(642330096448, --[[VoiceResponse Larry Idle VoiceResponse Idle - Play every 4 hours during which a squad has been inactive.. Played by any of the mercs in the squad. voice:Larry]] "I can feel the Universe through my nostrils, man. It's nice to have some meditation time.")
	}),
	InteractableFound = TConcat({
		T(218832282098, --[[VoiceResponse Larry InteractableFound VoiceResponse InteractableFound - A custom interactable (quest related etc), herbs or salvage material found. voice:Larry]] "What's that? I think it might be drugs. I should check and see if it's drugs."),
		T(298140693645, --[[VoiceResponse Larry InteractableFound VoiceResponse InteractableFound - A custom interactable (quest related etc), herbs or salvage material found. voice:Larry]] "Hey, man, there's like this thing over there.")
	}),
	InterestingSector = TConcat({
		T(730191282693, --[[VoiceResponse Larry InterestingSector VoiceResponse InterestingSector - Reached a sector that is marked as interesting. There is somethingin there the player should explore. voice:Larry]] "I dig the vibe here. We should look around and soak it in.")
	}),
	ItemDeteriorates = TConcat({
		T(493525003530, --[[VoiceResponse Larry ItemDeteriorates VoiceResponse ItemDeteriorates - Played when a piece of equipment deteriotes to the point when it is in the Needs Repair condition voice:Larry]] "Pieces of me are falling apart. Oh, wait. That's just my gear.")
	}),
	ItemInPoorConditionEquipped = TConcat({
		T(483001333796, --[[VoiceResponse Larry ItemInPoorConditionEquipped VoiceResponse ItemInPoorConditionEquipped - Played in Inventory when player equips weapon/armor that is in Poor Condition voice:Larry]] "About the only thing I can do with this is swap it for some drugs.")
	}),
	Jumping = TConcat({
		T(959283325417, --[[VoiceResponse Larry Jumping VoiceResponse Jumping - When jumping over small obstacles (e.g. puddles) voice:Larry]] "(jumping over something)"),
		T(679556625206, --[[VoiceResponse Larry Jumping VoiceResponse Jumping - When jumping over small obstacles (e.g. puddles) voice:Larry]] "(jumping over something_2)")
	}),
	KillFriendlyFireGeneral = TConcat({
		T(551176304469, --[[VoiceResponse Larry KillFriendlyFireGeneral VoiceResponse KillFriendlyFireGeneral - Played when a unit kills an ally with friendly fire and the dying unit is neither Liked nor Disliked voice:Larry]] "Wait... That wasn't a zombie?")
	}),
	LevelUp = TConcat({
		T(976865638852, --[[VoiceResponse Larry LevelUp VoiceResponse LevelUp - Leveled up or a magazine is read. Only one played if multiple character level up. voice:Larry]] "I'm totally getting better at this, man.")
	}),
	LockedItemMove = TConcat({
		T(210567158951, --[[VoiceResponse Larry LockedItemMove VoiceResponse LockedItemMove - Custom. Played when you try to move a personal item (e.g. Nails' jacket, Ivan's ushanka, and PierreMerc's weapon). Leave blank otherwise. voice:Larry]] "No! Ted is my personal financial advisor. I would be lost without him.")
	}),
	Loner = TConcat({
		T(268608475325, --[[VoiceResponse Larry Loner VoiceResponse Loner - Started instead of CombatStartPlayer when there are no allies in a large area voice:Larry]] "This is good. There are not a lot of colors and sounds around. It's just me versus the zombies.")
	}),
	LootFound = TConcat({
		T(329165413748, --[[VoiceResponse Larry LootFound VoiceResponse LootFound - A loot container is nearby (e.g. dead body, crate,...) 10s cooldown voice:Larry]] "There's some stuff over here that needs to be sniffed - I mean, searched."),
		T(228283125863, --[[VoiceResponse Larry LootFound VoiceResponse LootFound - A loot container is nearby (e.g. dead body, crate,...) 10s cooldown voice:Larry]] "Hey man, is that something we should check out or am I seeing things?"),
		T(663257829777, --[[VoiceResponse Larry LootFound VoiceResponse LootFound - A loot container is nearby (e.g. dead body, crate,...) 10s cooldown voice:Larry]] "I feel like we should grab some stuff.")
	}),
	LootOpened = TConcat({
		T(398536976239, --[[VoiceResponse Larry LootOpened VoiceResponse LootOpened - Loot container opened. Supressed by ValuableItemFound voice:Larry]] 'I call dibs on anything that can be categorized as "medicinal."')
	}),
	LowChanceShot = TConcat({
		T(970647353793, --[[VoiceResponse Larry LowChanceShot VoiceResponse LowChanceShot - Successful attack when the CtH is less than 20% voice:Larry]] "That's what I call my butt shot. Came from out of my butt.")
	}),
	ManyEnemiesSelection = TConcat({
		T(470077102531, --[[VoiceResponse Larry ManyEnemiesSelection VoiceResponse ManyEnemiesSelection - Selected when the unit sees 5+ units in line of fire voice:Larry]] "THE ZOMBIE APOCALYPSE IS UPON US. THEY ARE EVERYWHERE!!!")
	}),
	MineDisarmed = TConcat({
		T(959718376571, --[[VoiceResponse Larry MineDisarmed VoiceResponse MineDisarmed - Mine disarmed voice:Larry]] "Boy, that's real hard when my hands are shaking.")
	}),
	MineFound = TConcat({
		T(314679569511, --[[VoiceResponse Larry MineFound VoiceResponse MineFound - A mine (or other explosive trap) was found nearby voice:Larry]] "Hang on. That thing looks rigged to blow.")
	}),
	MineNearbySelection = TConcat({
		T(163452624181, --[[VoiceResponse Larry MineNearbySelection VoiceResponse MineNearbySelection - Selected when there is a trap nearby voice:Larry]] "Art is subjective but that trap is ugly. ")
	}),
	MissHighChance = TConcat({
		T(882147706775, --[[VoiceResponse Larry MissHighChance VoiceResponse MissHighChance - When a shot with 90%+ CtH was missed voice:Larry]] "Damn shaky hands!")
	}),
	MissedByKillShot = TConcat({
		T(405306571499, --[[VoiceResponse Larry MissedByKillShot VoiceResponse MissedByKillShot - When character missed a by a shot that would've killed him/her. Shot must have had 50%+ CtH. voice:Larry]] "Did anybody else see that pink elephant that almost hit me in the head?!")
	}),
	MockGeneral = TConcat({
		T(695961012866, --[[VoiceResponse Larry MockGeneral VoiceResponse MockGeneral - 20% chance to play when another merc misses a high chance shot voice:Larry]] "And I thought I was the only one here couldn't see straight!")
	}),
	MultiOpponentKilled = TConcat({
		T(316941690326, --[[VoiceResponse Larry MultiOpponentKilled VoiceResponse MultiOpponentKilled - When 2+ enemies are killed with the same attack voice:Larry]] "Kill a group of zombies and you just get a bigger group of zombies!")
	}),
	NoAmmo = TConcat({
		T(517306629524, --[[VoiceResponse Larry NoAmmo VoiceResponse NoAmmo - No more ammo in the gun and no more bullets. voice:Larry]] "Dunno. I keep pressing the trigger, but nothing's coming out.")
	}),
	NotNow = TConcat({
		T(502853909655, --[[VoiceResponse Larry NotNow VoiceResponse NotNow - When interacting with a NPC while in combat voice:Larry]] "We deal with the zombies now, then the unicorns. It's simple stuff, man.")
	}),
	OpponentFound = TConcat({
		T(399993495654, --[[VoiceResponse Larry OpponentFound VoiceResponse OpponentFound - Enemy spotted. voice:Larry]] "I think I see someone."),
		T(356017722979, --[[VoiceResponse Larry OpponentFound VoiceResponse OpponentFound - Enemy spotted. voice:Larry]] "Uh-oh... ZOMBIES.")
	}),
	OpponentKilled = TConcat({
		T(782829667131, --[[VoiceResponse Larry OpponentKilled VoiceResponse OpponentKilled - When opponent killed (unless OponentKilledCrit or OponentKilled multi isplayed) voice:Larry]] "One grunt down, man."),
		T(926151621376, --[[VoiceResponse Larry OpponentKilled VoiceResponse OpponentKilled - When opponent killed (unless OponentKilledCrit or OponentKilled multi isplayed) voice:Larry]] "One less zombie grunt."),
		T(590017142742, --[[VoiceResponse Larry OpponentKilled VoiceResponse OpponentKilled - When opponent killed (unless OponentKilledCrit or OponentKilled multi isplayed) voice:Larry]] "Watch that one. Make sure it doesn't move again, man."),
		T(875198854410, --[[VoiceResponse Larry OpponentKilled VoiceResponse OpponentKilled - When opponent killed (unless OponentKilledCrit or OponentKilled multi isplayed) voice:Larry]] "Die, zombie, die!"),
		T(593987549346, --[[VoiceResponse Larry OpponentKilled VoiceResponse OpponentKilled - When opponent killed (unless OponentKilledCrit or OponentKilled multi isplayed) voice:Larry]] "Death to the undead!")
	}),
	OpponentKilledAnimal = TConcat({
		T(346855408079, --[[VoiceResponse Larry OpponentKilledAnimal VoiceResponse OpponentKilledAnimal - When animal is killed voice:Larry]] "Gotta kill those zombie dolphins before they bite you, man!")
	}),
	OpponentKilledHeadshot = TConcat({
		T(393589964691, --[[VoiceResponse Larry OpponentKilledHeadshot VoiceResponse OpponentKilledHeadshot - Opponent killed with a headshot voice:Larry]] "Pop! Zombie brains everywhere!")
	}),
	OpponentKilledStealth = TConcat({
		T(130675664793, --[[VoiceResponse Larry OpponentKilledStealth VoiceResponse OpponentKilledStealth - Played when a Stealth kill happens. Voice should be shushed (except Steroid) voice:Larry]] "Good thing it's a zombie. I'd feel bad about doing that to a real person.")
	}),
	Order = TConcat({
		T(609585887879, --[[VoiceResponse Larry Order VoiceResponse Order - When movement ordered (out of combat) Should be very short (3-5 words) voice:Larry]] "Whatever."),
		T(873169981830, --[[VoiceResponse Larry Order VoiceResponse Order - When movement ordered (out of combat) Should be very short (3-5 words) voice:Larry]] "How about a little pick-me-up first?"),
		T(411264429348, --[[VoiceResponse Larry Order VoiceResponse Order - When movement ordered (out of combat) Should be very short (3-5 words) voice:Larry]] "That's cool with me."),
		T(678118847054, --[[VoiceResponse Larry Order VoiceResponse Order - When movement ordered (out of combat) Should be very short (3-5 words) voice:Larry]] "Come on, Ted. Let's go."),
		T(290437589177, --[[VoiceResponse Larry Order VoiceResponse Order - When movement ordered (out of combat) Should be very short (3-5 words) voice:Larry]] "Just don't ask me to walk in a straight line."),
		T(197773709974, --[[VoiceResponse Larry Order VoiceResponse Order - When movement ordered (out of combat) Should be very short (3-5 words) voice:Larry]] "Hang on, Ted!"),
		T(667505641622, --[[VoiceResponse Larry Order VoiceResponse Order - When movement ordered (out of combat) Should be very short (3-5 words) voice:Larry]] "No problemo, man.")
	}),
	Outnumbered = TConcat({
		T(480089063970, --[[VoiceResponse Larry Outnumbered VoiceResponse Outnumbered - Unit sees more enemies than allies voice:Larry]] "Zombies all around me!")
	}),
	Overwatch = TConcat({
		T(776847549232, --[[VoiceResponse Larry Overwatch VoiceResponse Overwatch - When setting overwatch voice:Larry]] "Keeping watch on all... um three of everyone.")
	}),
	OverwatchSelection = TConcat({
		T(542514887997, --[[VoiceResponse Larry OverwatchSelection VoiceResponse OverwatchSelection - Selected when under Overwatch. voice:Larry]] "I feel like a pink elephant will fall down on my head.")
	}),
	Pain = TConcat({
		T(106409414703, --[[VoiceResponse Larry Pain VoiceResponse Pain - Hit by an attack (if surrounded SurroundedPain is played instead). Short. These are emotes - disregard the written text. voice:Larry]] "Argh"),
		T(197147346367, --[[VoiceResponse Larry Pain VoiceResponse Pain - Hit by an attack (if surrounded SurroundedPain is played instead). Short. These are emotes - disregard the written text. voice:Larry]] "Mhh"),
		T(805681983467, --[[VoiceResponse Larry Pain VoiceResponse Pain - Hit by an attack (if surrounded SurroundedPain is played instead). Short. These are emotes - disregard the written text. voice:Larry]] "Ah"),
		T(393040056903, --[[VoiceResponse Larry Pain VoiceResponse Pain - Hit by an attack (if surrounded SurroundedPain is played instead). Short. These are emotes - disregard the written text. voice:Larry]] "Ouch"),
		T(109488319202, --[[VoiceResponse Larry Pain VoiceResponse Pain - Hit by an attack (if surrounded SurroundedPain is played instead). Short. These are emotes - disregard the written text. voice:Larry]] "Ugh"),
		T(720939444449, --[[VoiceResponse Larry Pain VoiceResponse Pain - Hit by an attack (if surrounded SurroundedPain is played instead). Short. These are emotes - disregard the written text. voice:Larry]] "Pain6"),
		T(329126676599, --[[VoiceResponse Larry Pain VoiceResponse Pain - Hit by an attack (if surrounded SurroundedPain is played instead). Short. These are emotes - disregard the written text. voice:Larry]] "Pain7"),
		T(807524341355, --[[VoiceResponse Larry Pain VoiceResponse Pain - Hit by an attack (if surrounded SurroundedPain is played instead). Short. These are emotes - disregard the written text. voice:Larry]] "Pain8")
	}),
	PraisesFemale = TConcat({
		T(848746687916, --[[VoiceResponse Larry PraisesFemale VoiceResponse PraisesFemale - Played when a female merc makes a kill (20% chance) voice:Larry]] "Good job, sister! I'll drink to your success!")
	}),
	PraisesMale = TConcat({
		T(448228134822, --[[VoiceResponse Larry PraisesMale VoiceResponse PraisesMale - Played when a male merc makes a kill (20% chance) voice:Larry]] "Right on, man! Death to the zombies!")
	}),
	SectorArrived = TConcat({
		T(817911165465, --[[VoiceResponse Larry SectorArrived VoiceResponse SectorArrived - SatView - new sector reached. Played by random merc in squad. voice:Larry]] "I'm here. This where the party's at?")
	}),
	Selection = TConcat({
		T(145564398556, --[[VoiceResponse Larry Selection VoiceResponse Selection - when selected or autoselected voice:Larry]] "What?"),
		T(729462065691, --[[VoiceResponse Larry Selection VoiceResponse Selection - when selected or autoselected voice:Larry]] "Hey man, what's up?"),
		T(835090518824, --[[VoiceResponse Larry Selection VoiceResponse Selection - when selected or autoselected voice:Larry]] "Huh?")
	}),
	SelectionStealth = TConcat({
		T(517629253982, --[[VoiceResponse Larry SelectionStealth VoiceResponse SelectionStealth - when selected or autoselected voice:Larry]] "Got a chance to do this quietly, man."),
		T(569184351897, --[[VoiceResponse Larry SelectionStealth VoiceResponse SelectionStealth - when selected or autoselected voice:Larry]] "I'm like a shadow... a super secret shadow that only I can see."),
		T(731130328408, --[[VoiceResponse Larry SelectionStealth VoiceResponse SelectionStealth - when selected or autoselected voice:Larry]] "Ted, shhh... We gotta be quiet."),
		T(901927861566, --[[VoiceResponse Larry SelectionStealth VoiceResponse SelectionStealth - when selected or autoselected voice:Larry]] "I'm so quiet I can't even hear myself.")
	}),
	SeriouslyWounded = TConcat({
		T(173444517663, --[[VoiceResponse Larry SeriouslyWounded VoiceResponse SeriouslyWounded - Unit is seriously wounded (3 or more wounds) voice:Larry]] "Wait! I am invincible. I shouldn't be feeling like death.")
	}),
	SpecialThrowGrenade = TConcat({
		T(235210165698, --[[VoiceResponse Larry SpecialThrowGrenade VoiceResponse SpecialThrowGrenade - When throwing grenade voice:Larry]] "Time for a special anti-zombie bomb!")
	}),
	Startled = TConcat({
		T(906070915882, --[[VoiceResponse Larry Startled VoiceResponse Startled - Startled by hearing a sudden noise voice:Larry]] "Huh?"),
		T(625166881602, --[[VoiceResponse Larry Startled VoiceResponse Startled - Startled by hearing a sudden noise voice:Larry]] "Wha-?")
	}),
	SurroundedPain = TConcat({
		T(586571241817, --[[VoiceResponse Larry SurroundedPain VoiceResponse SurroundedPain - hit by an attack when surrounded. Situation should be very dire voice:Larry]] "Zombies closing in! Do something, Ted!")
	}),
	TacticalFocus = TConcat({
		T(396610182825, --[[VoiceResponse Larry TacticalFocus VoiceResponse TacticalFocus - The team has missed  3+ times voice:Larry]] "Yes! Don't shoot them. Shoot their fairies instead!")
	}),
	TacticalLoss = TConcat({
		T(469921814807, --[[VoiceResponse Larry TacticalLoss VoiceResponse TacticalLoss - The team is losing the battle (2+ units have been downed/killed) voice:Larry]] "IT'S A ZOMBIE APOCALYPSE!!! Protect your brains!")
	}),
	TacticalPressing = TConcat({
		T(122577679339, --[[VoiceResponse Larry TacticalPressing VoiceResponse TacticalPressing - The team is making gains during the battle (2+ wounds have been inflicted) voice:Larry]] "We need to shoot even more. These zombies feel no pain.")
	}),
	TacticalRevenge = TConcat({
		T(218153844747, --[[VoiceResponse Larry TacticalRevenge VoiceResponse TacticalRevenge - A unit from the team has been downed/killed voice:Larry]] "Keep your brain inside your head or the zombies may get it.")
	}),
	TacticalTaunt = TConcat({
		T(926733614225, --[[VoiceResponse Larry TacticalTaunt VoiceResponse TacticalTaunt - The team has visible enemies from the other team and is shouting things at them voice:Larry]] "Do these zombies know they're not alive?")
	}),
	TakeCover = TConcat({
		T(835240794179, --[[VoiceResponse Larry TakeCover VoiceResponse TakeCover - Played when the Take Cover action is used voice:Larry]] "Gotta make sure they don't touch me!")
	}),
	ThreatSelection = TConcat({
		T(662281257960, --[[VoiceResponse Larry ThreatSelection VoiceResponse ThreatSelection - Selected when under Pinned Down or in the area of an incoming explosion. voice:Larry]] "I gotta get outta here, man! I gotta get outta here!")
	}),
	ThrowGrenade = TConcat({
		T(869605341966, --[[VoiceResponse Larry ThrowGrenade VoiceResponse ThrowGrenade - When throwing grenade. Voiced line starts before the explosion. voice:Larry]] "Heads up, zombies!")
	}),
	Tired = TConcat({
		T(464051199177, --[[VoiceResponse Larry Tired VoiceResponse Tired - when the merc becomes tired voice:Larry]] "I'm crashing hard, man. Point me towards a sofa.")
	}),
	Travelling = TConcat({
		T(904241681934, --[[VoiceResponse Larry Travelling VoiceResponse Travelling - When a squad is travelling and enters new sector that is not the final destination of the travel. Played by the squad leader voice:Larry]] "Wow, this is such a trip and not in a good way.")
	}),
	ValuableItemFound = TConcat({
		T(327754362322, --[[VoiceResponse Larry ValuableItemFound VoiceResponse ValuableItemFound - Loot container opened with a valuable item inside voice:Larry]] "Hey, far out, man!")
	}),
	WeaponBroken = TConcat({
		T(778805115887, --[[VoiceResponse Larry WeaponBroken VoiceResponse WeaponBroken - When the player's weapon breaks voice:Larry]] "This thing is busted! I swear it wasn't me, man!")
	}),
	WeaponJammed = TConcat({
		T(128971100406, --[[VoiceResponse Larry WeaponJammed VoiceResponse WeaponJammed - When weapon has jammed voice:Larry]] "I think there's like, jam in my gun or something.")
	}),
	Wounded = TConcat({
		T(686144215199, --[[VoiceResponse Larry Wounded VoiceResponse Wounded - Unit is Wounded. (When the Wounded VR is played, the Pain VR should be suppressed.) voice:Larry]] "I think I got hit, but I'm feeling no pain."),
		T(290647288515, --[[VoiceResponse Larry Wounded VoiceResponse Wounded - Unit is Wounded. (When the Wounded VR is played, the Pain VR should be suppressed.) voice:Larry]] "Those zombies sure want to take a bite out of me!"),
		T(540266358752, --[[VoiceResponse Larry Wounded VoiceResponse Wounded - Unit is Wounded. (When the Wounded VR is played, the Pain VR should be suppressed.) voice:Larry]] "Ow! All right, fine! I'll take another painkiller.")
	}),
	group = "MercenariesOld",
	id = "Larry",
})

