-- ========== GENERATED BY VoiceResponse Editor (Ctrl-Alt-V) DO NOT EDIT MANUALLY! ==========

PlaceObj('VoiceResponse', {
	AIArchetypeAngry = TConcat({
		T(330675046605, --[[VoiceResponse LegionRaider AIArchetypeAngry VoiceResponse AIArchetypeAngry - Played when AI switches archetype and weapons because he is angry voice:LegionRaider]] "That's it! You will all die!"),
		T(915887760056, --[[VoiceResponse LegionRaider AIArchetypeAngry VoiceResponse AIArchetypeAngry - Played when AI switches archetype and weapons because he is angry voice:LegionRaider]] "You pissed off the wrong Legionnaire!")
	}),
	AIArchetypeScared = TConcat({
		T(979069754423, --[[VoiceResponse LegionRaider AIArchetypeScared VoiceResponse AIArchetypeScared - Played when AI switches archetype and weapons because he is scared voice:LegionRaider]] "Screw this! I'm taking cover."),
		T(163645355642, --[[VoiceResponse LegionRaider AIArchetypeScared VoiceResponse AIArchetypeScared - Played when AI switches archetype and weapons because he is scared voice:LegionRaider]] "It's too much! We need to fall back!")
	}),
	AIAttack = TConcat({
		T(825481520673, --[[VoiceResponse LegionRaider AIAttack VoiceResponse AIAttack - When attacking voice:LegionRaider]] "For the Major!"),
		T(148467314162, --[[VoiceResponse LegionRaider AIAttack VoiceResponse AIAttack - When attacking voice:LegionRaider]] "For the Legion!"),
		T(628274538146, --[[VoiceResponse LegionRaider AIAttack VoiceResponse AIAttack - When attacking voice:LegionRaider]] "Take that!"),
		T(576234899526, --[[VoiceResponse LegionRaider AIAttack VoiceResponse AIAttack - When attacking voice:LegionRaider]] "Die!"),
		T(667432845458, --[[VoiceResponse LegionRaider AIAttack VoiceResponse AIAttack - When attacking voice:LegionRaider]] "MEURS!"),
		T(154762559814, --[[VoiceResponse LegionRaider AIAttack VoiceResponse AIAttack - When attacking voice:LegionRaider]] "Go to hell!"),
		T(599685199789, --[[VoiceResponse LegionRaider AIAttack VoiceResponse AIAttack - When attacking voice:LegionRaider]] "PRENDS ÇA!"),
		T(860438133258, --[[VoiceResponse LegionRaider AIAttack VoiceResponse AIAttack - When attacking voice:LegionRaider]] "Je les ai!")
	}),
	AIAutofire = TConcat({
		T(391308650697, --[[VoiceResponse LegionRaider AIAutofire VoiceResponse AIAutofire - Enemy uses Autofire. Played during gunfire noises. voice:LegionRaider]] "Suppressive fire!"),
		T(881671357591, --[[VoiceResponse LegionRaider AIAutofire VoiceResponse AIAutofire - Enemy uses Autofire. Played during gunfire noises. voice:LegionRaider]] "Eat this, you foreign dogs!"),
		T(871102426566, --[[VoiceResponse LegionRaider AIAutofire VoiceResponse AIAutofire - Enemy uses Autofire. Played during gunfire noises. voice:LegionRaider]] "Tir de suppression!"),
		T(144101456547, --[[VoiceResponse LegionRaider AIAutofire VoiceResponse AIAutofire - Enemy uses Autofire. Played during gunfire noises. voice:LegionRaider]] "Je vous couvre !")
	}),
	AIBerserkerPerk = TConcat({
		T(324270242050, --[[VoiceResponse LegionRaider AIBerserkerPerk VoiceResponse AIBerserkerPerk - The AI berserker perk is activated voice:LegionRaider]] "I will bathe in your blood!"),
		T(986457713350, --[[VoiceResponse LegionRaider AIBerserkerPerk VoiceResponse AIBerserkerPerk - The AI berserker perk is activated voice:LegionRaider]] "I will rip you to shreds!")
	}),
	AIDeadAlly = TConcat({
		T(931329302121, --[[VoiceResponse LegionRaider AIDeadAlly VoiceResponse AIDeadAlly - Played on dead human enemy ally voice:LegionRaider]] "You will pay for this, foreign dogs!"),
		T(608398943136, --[[VoiceResponse LegionRaider AIDeadAlly VoiceResponse AIDeadAlly - Played on dead human enemy ally voice:LegionRaider]] "The Major will hear of this!"),
		T(886760980814, --[[VoiceResponse LegionRaider AIDeadAlly VoiceResponse AIDeadAlly - Played on dead human enemy ally voice:LegionRaider]] "You will not scare us!"),
		T(844825283918, --[[VoiceResponse LegionRaider AIDeadAlly VoiceResponse AIDeadAlly - Played on dead human enemy ally voice:LegionRaider]] "Stand resolute!"),
		T(589148913065, --[[VoiceResponse LegionRaider AIDeadAlly VoiceResponse AIDeadAlly - Played on dead human enemy ally voice:LegionRaider]] "Ten of you shall fall for every one of us!"),
		T(507506704366, --[[VoiceResponse LegionRaider AIDeadAlly VoiceResponse AIDeadAlly - Played on dead human enemy ally voice:LegionRaider]] "To die in the Legion is to have truly lived!")
	}),
	AIDeadAllyMajorDead = TConcat({
		T(931329302121, --[[VoiceResponse LegionRaider AIDeadAllyMajorDead VoiceResponse AIDeadAllyMajorDead - Major dead version of AIDeadAlly share_id:true voice:LegionRaider]] "You will pay for this, foreign dogs!"),
		T(886760980814, --[[VoiceResponse LegionRaider AIDeadAllyMajorDead VoiceResponse AIDeadAllyMajorDead - Major dead version of AIDeadAlly share_id:true voice:LegionRaider]] "You will not scare us!"),
		T(844825283918, --[[VoiceResponse LegionRaider AIDeadAllyMajorDead VoiceResponse AIDeadAllyMajorDead - Major dead version of AIDeadAlly share_id:true voice:LegionRaider]] "Stand resolute!"),
		T(589148913065, --[[VoiceResponse LegionRaider AIDeadAllyMajorDead VoiceResponse AIDeadAllyMajorDead - Major dead version of AIDeadAlly share_id:true voice:LegionRaider]] "Ten of you shall fall for every one of us!"),
		T(507506704366, --[[VoiceResponse LegionRaider AIDeadAllyMajorDead VoiceResponse AIDeadAllyMajorDead - Major dead version of AIDeadAlly share_id:true voice:LegionRaider]] "To die in the Legion is to have truly lived!")
	}),
	AIDeadAnimal = TConcat({
		T(878820610407, --[[VoiceResponse LegionRaider AIDeadAnimal VoiceResponse AIDeadAnimal - Played on dead non human enemy ally voice:LegionRaider]] "That was a beloved pet, you bastards."),
		T(966767493045, --[[VoiceResponse LegionRaider AIDeadAnimal VoiceResponse AIDeadAnimal - Played on dead non human enemy ally voice:LegionRaider]] "I used to feed it every day. You will pay for this!"),
		T(530657332031, --[[VoiceResponse LegionRaider AIDeadAnimal VoiceResponse AIDeadAnimal - Played on dead non human enemy ally voice:LegionRaider]] "You are nothing but filthy butchers!")
	}),
	AIDeath = TConcat({
		T(721694018917, --[[VoiceResponse LegionRaider AIDeath VoiceResponse AIDeath - Enemy dies voice:LegionRaider]] "Agh Ugh!"),
		T(222347738513, --[[VoiceResponse LegionRaider AIDeath VoiceResponse AIDeath - Enemy dies voice:LegionRaider]] "Hagh Agh!"),
		T(337580525120, --[[VoiceResponse LegionRaider AIDeath VoiceResponse AIDeath - Enemy dies voice:LegionRaider]] "Aghagh..."),
		T(309130274123, --[[VoiceResponse LegionRaider AIDeath VoiceResponse AIDeath - Enemy dies voice:LegionRaider]] "Ahhh... ahhh"),
		T(675906968705, --[[VoiceResponse LegionRaider AIDeath VoiceResponse AIDeath - Enemy dies voice:LegionRaider]] "Uff"),
		T(425136844550, --[[VoiceResponse LegionRaider AIDeath VoiceResponse AIDeath - Enemy dies voice:LegionRaider]] "Aghhh..."),
		T(789475526868, --[[VoiceResponse LegionRaider AIDeath VoiceResponse AIDeath - Enemy dies voice:LegionRaider]] "cough"),
		T(644438951598, --[[VoiceResponse LegionRaider AIDeath VoiceResponse AIDeath - Enemy dies voice:LegionRaider]] "Ahhg"),
		T(864786059266, --[[VoiceResponse LegionRaider AIDeath VoiceResponse AIDeath - Enemy dies voice:LegionRaider]] "Ouch ah"),
		T(843999283642, --[[VoiceResponse LegionRaider AIDeath VoiceResponse AIDeath - Enemy dies voice:LegionRaider]] "Ugh"),
		T(998545328741, --[[VoiceResponse LegionRaider AIDeath VoiceResponse AIDeath - Enemy dies voice:LegionRaider]] "Ah..."),
		T(537831812576, --[[VoiceResponse LegionRaider AIDeath VoiceResponse AIDeath - Enemy dies voice:LegionRaider]] "Agghgh..."),
		T(722988406403, --[[VoiceResponse LegionRaider AIDeath VoiceResponse AIDeath - Enemy dies voice:LegionRaider]] "Ouch"),
		T(845402475432, --[[VoiceResponse LegionRaider AIDeath VoiceResponse AIDeath - Enemy dies voice:LegionRaider]] "Ghh"),
		T(109371047343, --[[VoiceResponse LegionRaider AIDeath VoiceResponse AIDeath - Enemy dies voice:LegionRaider]] "Uh"),
		T(997556720668, --[[VoiceResponse LegionRaider AIDeath VoiceResponse AIDeath - Enemy dies voice:LegionRaider]] "Ouch ouch"),
		T(693279255024, --[[VoiceResponse LegionRaider AIDeath VoiceResponse AIDeath - Enemy dies voice:LegionRaider]] "..."),
		T(536934308866, --[[VoiceResponse LegionRaider AIDeath VoiceResponse AIDeath - Enemy dies voice:LegionRaider]] "Ghhhh")
	}),
	AIDoubleBarrel = TConcat({
		T(943112133206, --[[VoiceResponse LegionRaider AIDoubleBarrel VoiceResponse AIDoubleBarrel - Enemy uses Double Barrel. Played during gunfire noises voice:LegionRaider]] "Take this!"),
		T(655665596293, --[[VoiceResponse LegionRaider AIDoubleBarrel VoiceResponse AIDoubleBarrel - Enemy uses Double Barrel. Played during gunfire noises voice:LegionRaider]] "Giving the big bam!"),
		T(243366087894, --[[VoiceResponse LegionRaider AIDoubleBarrel VoiceResponse AIDoubleBarrel - Enemy uses Double Barrel. Played during gunfire noises voice:LegionRaider]] "I have two barrels for you!")
	}),
	AIFlanked = TConcat({
		T(783264491855, --[[VoiceResponse LegionRaider AIFlanked VoiceResponse AIFlanked - Flanked and hit. voice:LegionRaider]] "They are all over me!"),
		T(727822604064, --[[VoiceResponse LegionRaider AIFlanked VoiceResponse AIFlanked - Flanked and hit. voice:LegionRaider]] "Help! I'm flanked!"),
		T(365347102878, --[[VoiceResponse LegionRaider AIFlanked VoiceResponse AIFlanked - Flanked and hit. voice:LegionRaider]] "I'm surrounded!")
	}),
	AIFlanking = TConcat({
		T(646942339755, --[[VoiceResponse LegionRaider AIFlanking VoiceResponse AIFlanking - Played when the AI is flanking an opponent voice:LegionRaider]] "Surround them!"),
		T(478141286106, --[[VoiceResponse LegionRaider AIFlanking VoiceResponse AIFlanking - Played when the AI is flanking an opponent voice:LegionRaider]] "Cover me!"),
		T(629083027105, --[[VoiceResponse LegionRaider AIFlanking VoiceResponse AIFlanking - Played when the AI is flanking an opponent voice:LegionRaider]] "Flank them!"),
		T(340720640092, --[[VoiceResponse LegionRaider AIFlanking VoiceResponse AIFlanking - Played when the AI is flanking an opponent voice:LegionRaider]] "Encerclez-les!"),
		T(742986042065, --[[VoiceResponse LegionRaider AIFlanking VoiceResponse AIFlanking - Played when the AI is flanking an opponent voice:LegionRaider]] "Couvrez-moi! "),
		T(757140228236, --[[VoiceResponse LegionRaider AIFlanking VoiceResponse AIFlanking - Played when the AI is flanking an opponent voice:LegionRaider]] "Débordez-les !")
	}),
	AIGasAreaSelection = TConcat({
		T(734102557837, --[[VoiceResponse LegionRaider AIGasAreaSelection VoiceResponse AIGasAreaSelection - Unit receiving gas effect or starting round in one. Suffocating. Emote. voice:LegionRaider]] "(coughing)")
	}),
	AILoseCover = TConcat({
		T(909195632546, --[[VoiceResponse LegionRaider AILoseCover VoiceResponse AILoseCover - Unit in cover getting exposed voice:LegionRaider]] "I have no cover here!"),
		T(721232696996, --[[VoiceResponse LegionRaider AILoseCover VoiceResponse AILoseCover - Unit in cover getting exposed voice:LegionRaider]] "Merde! I need some cover!")
	}),
	AIMeleeOpportunist = TConcat({
		T(747871585060, --[[VoiceResponse LegionRaider AIMeleeOpportunist VoiceResponse AIMeleeOpportunist - In melee range voice:LegionRaider]] "I will take you apart!"),
		T(461412855229, --[[VoiceResponse LegionRaider AIMeleeOpportunist VoiceResponse AIMeleeOpportunist - In melee range voice:LegionRaider]] "Je t’ai eu!"),
		T(962115219953, --[[VoiceResponse LegionRaider AIMeleeOpportunist VoiceResponse AIMeleeOpportunist - In melee range voice:LegionRaider]] "Maintenant, tu es à moi!")
	}),
	AIMobile = TConcat({
		T(558474937762, --[[VoiceResponse LegionRaider AIMobile VoiceResponse AIMobile - Enemy uses a mobile shot or run&gun voice:LegionRaider]] "Charge!"),
		T(352496512968, --[[VoiceResponse LegionRaider AIMobile VoiceResponse AIMobile - Enemy uses a mobile shot or run&gun voice:LegionRaider]] "Let the Major see my courage!"),
		T(283962767115, --[[VoiceResponse LegionRaider AIMobile VoiceResponse AIMobile - Enemy uses a mobile shot or run&gun voice:LegionRaider]] "I will take the fight to them!")
	}),
	AIMobileMajorDead = TConcat({
		T(558474937762, --[[VoiceResponse LegionRaider AIMobileMajorDead VoiceResponse AIMobileMajorDead - Major dead version of AIMobile share_id:true voice:LegionRaider]] "Charge!"),
		T(283962767115, --[[VoiceResponse LegionRaider AIMobileMajorDead VoiceResponse AIMobileMajorDead - Major dead version of AIMobile share_id:true voice:LegionRaider]] "I will take the fight to them!")
	}),
	AIOverwatch = TConcat({
		T(592455310906, --[[VoiceResponse LegionRaider AIOverwatch VoiceResponse AIOverwatch - Enemy sets up overwatch voice:LegionRaider]] "Poke your head up. I dare you."),
		T(388680483744, --[[VoiceResponse LegionRaider AIOverwatch VoiceResponse AIOverwatch - Enemy sets up overwatch voice:LegionRaider]] "There you are!"),
		T(810190819293, --[[VoiceResponse LegionRaider AIOverwatch VoiceResponse AIOverwatch - Enemy sets up overwatch voice:LegionRaider]] "Les voici! "),
		T(847784216824, --[[VoiceResponse LegionRaider AIOverwatch VoiceResponse AIOverwatch - Enemy sets up overwatch voice:LegionRaider]] "Vous voilà!")
	}),
	AIPinDown = TConcat({
		T(310002806055, --[[VoiceResponse LegionRaider AIPinDown VoiceResponse AIPinDown - Enemy uses PinDown voice:LegionRaider]] "Target is exposed!"),
		T(495180119414, --[[VoiceResponse LegionRaider AIPinDown VoiceResponse AIPinDown - Enemy uses PinDown voice:LegionRaider]] "Nail this one to the ground!"),
		T(109180065960, --[[VoiceResponse LegionRaider AIPinDown VoiceResponse AIPinDown - Enemy uses PinDown voice:LegionRaider]] "Cible repérée!")
	}),
	AIStartingTurnAttack = TConcat({
		T(773520911461, --[[VoiceResponse LegionRaider AIStartingTurnAttack VoiceResponse AIStartingTurnAttack - Will move and attack this turn voice:LegionRaider]] "Shoot! Drive these foreigners back where they came from."),
		T(168817269512, --[[VoiceResponse LegionRaider AIStartingTurnAttack VoiceResponse AIStartingTurnAttack - Will move and attack this turn voice:LegionRaider]] "Let the Major see our courage!"),
		T(707403177585, --[[VoiceResponse LegionRaider AIStartingTurnAttack VoiceResponse AIStartingTurnAttack - Will move and attack this turn voice:LegionRaider]] "Kill them all and send them to hell!"),
		T(414647778772, --[[VoiceResponse LegionRaider AIStartingTurnAttack VoiceResponse AIStartingTurnAttack - Will move and attack this turn voice:LegionRaider]] "Show them our strength!"),
		T(381631308385, --[[VoiceResponse LegionRaider AIStartingTurnAttack VoiceResponse AIStartingTurnAttack - Will move and attack this turn voice:LegionRaider]] "Forward! For the Legion!")
	}),
	AIStartingTurnAttackMajorDead = TConcat({
		T(773520911461, --[[VoiceResponse LegionRaider AIStartingTurnAttackMajorDead VoiceResponse AIStartingTurnAttackMajorDead - Major dead version of AIStartingTurnAttack share_id:true voice:LegionRaider]] "Shoot! Drive these foreigners back where they came from."),
		T(707403177585, --[[VoiceResponse LegionRaider AIStartingTurnAttackMajorDead VoiceResponse AIStartingTurnAttackMajorDead - Major dead version of AIStartingTurnAttack share_id:true voice:LegionRaider]] "Kill them all and send them to hell!"),
		T(414647778772, --[[VoiceResponse LegionRaider AIStartingTurnAttackMajorDead VoiceResponse AIStartingTurnAttackMajorDead - Major dead version of AIStartingTurnAttack share_id:true voice:LegionRaider]] "Show them our strength!"),
		T(381631308385, --[[VoiceResponse LegionRaider AIStartingTurnAttackMajorDead VoiceResponse AIStartingTurnAttackMajorDead - Major dead version of AIStartingTurnAttack share_id:true voice:LegionRaider]] "Forward! For the Legion!"),
		T(838516170624, --[[VoiceResponse LegionRaider AIStartingTurnAttackMajorDead VoiceResponse AIStartingTurnAttackMajorDead - Major dead version of AIStartingTurnAttack share_id:true voice:LegionRaider]] "Spread Out!"),
		T(615234826606, --[[VoiceResponse LegionRaider AIStartingTurnAttackMajorDead VoiceResponse AIStartingTurnAttackMajorDead - Major dead version of AIStartingTurnAttack share_id:true voice:LegionRaider]] "Reposition for an attack!")
	}),
	AIStartingTurnLastEnemy = TConcat({
		T(236374511290, --[[VoiceResponse LegionRaider AIStartingTurnLastEnemy VoiceResponse AIStartingTurnLastEnemy - This is the last standing enemy voice:LegionRaider]] "You may kill us but I refuse to yield."),
		T(743993824479, --[[VoiceResponse LegionRaider AIStartingTurnLastEnemy VoiceResponse AIStartingTurnLastEnemy - This is the last standing enemy voice:LegionRaider]] "Guys? Anyone still alive? Guys?"),
		T(293310015355, --[[VoiceResponse LegionRaider AIStartingTurnLastEnemy VoiceResponse AIStartingTurnLastEnemy - This is the last standing enemy voice:LegionRaider]] "Time for a last stand."),
		T(763452132003, --[[VoiceResponse LegionRaider AIStartingTurnLastEnemy VoiceResponse AIStartingTurnLastEnemy - This is the last standing enemy voice:LegionRaider]] "The Major will hear of my bravery.")
	}),
	AIStartingTurnLastEnemyMajorDead = TConcat({
		T(236374511290, --[[VoiceResponse LegionRaider AIStartingTurnLastEnemyMajorDead VoiceResponse AIStartingTurnLastEnemyMajorDead - Major dead version of AIStartingTurnLastEnemy share_id:true voice:LegionRaider]] "You may kill us but I refuse to yield."),
		T(743993824479, --[[VoiceResponse LegionRaider AIStartingTurnLastEnemyMajorDead VoiceResponse AIStartingTurnLastEnemyMajorDead - Major dead version of AIStartingTurnLastEnemy share_id:true voice:LegionRaider]] "Guys? Anyone still alive? Guys?"),
		T(293310015355, --[[VoiceResponse LegionRaider AIStartingTurnLastEnemyMajorDead VoiceResponse AIStartingTurnLastEnemyMajorDead - Major dead version of AIStartingTurnLastEnemy share_id:true voice:LegionRaider]] "Time for a last stand.")
	}),
	AIStartingTurnMoving = TConcat({
		T(606505617755, --[[VoiceResponse LegionRaider AIStartingTurnMoving VoiceResponse AIStartingTurnMoving - All enemy units will just move this turn. voice:LegionRaider]] "Let's move out!"),
		T(645759079444, --[[VoiceResponse LegionRaider AIStartingTurnMoving VoiceResponse AIStartingTurnMoving - All enemy units will just move this turn. voice:LegionRaider]] "Find a good position!"),
		T(404628459419, --[[VoiceResponse LegionRaider AIStartingTurnMoving VoiceResponse AIStartingTurnMoving - All enemy units will just move this turn. voice:LegionRaider]] "Scatter!"),
		T(380884549551, --[[VoiceResponse LegionRaider AIStartingTurnMoving VoiceResponse AIStartingTurnMoving - All enemy units will just move this turn. voice:LegionRaider]] "Dispersez-vous!"),
		T(926406893944, --[[VoiceResponse LegionRaider AIStartingTurnMoving VoiceResponse AIStartingTurnMoving - All enemy units will just move this turn. voice:LegionRaider]] "Gardez vos distances!"),
		T(461999723260, --[[VoiceResponse LegionRaider AIStartingTurnMoving VoiceResponse AIStartingTurnMoving - All enemy units will just move this turn. voice:LegionRaider]] "Planquez-vous!")
	}),
	AITaunt = TConcat({
		T(704953444587, --[[VoiceResponse LegionRaider AITaunt VoiceResponse AITaunt - Played during the player's turn when the player has missed with 3 attacks. voice:LegionRaider]] "You could not hit me if you tried a thousand times!"),
		T(492818527808, --[[VoiceResponse LegionRaider AITaunt VoiceResponse AITaunt - Played during the player's turn when the player has missed with 3 attacks. voice:LegionRaider]] "Loser! You will never get us Legion boys."),
		T(430085260697, --[[VoiceResponse LegionRaider AITaunt VoiceResponse AITaunt - Played during the player's turn when the player has missed with 3 attacks. voice:LegionRaider]] "Ha! Care to try again, dog?"),
		T(277931474787, --[[VoiceResponse LegionRaider AITaunt VoiceResponse AITaunt - Played during the player's turn when the player has missed with 3 attacks. voice:LegionRaider]] "I am invincible!!!")
	}),
	AIThrowGrenade = TConcat({
		T(940643911340, --[[VoiceResponse LegionRaider AIThrowGrenade VoiceResponse AIThrowGrenade - Enemy throws grenade voice:LegionRaider]] "Grenade!"),
		T(615517620177, --[[VoiceResponse LegionRaider AIThrowGrenade VoiceResponse AIThrowGrenade - Enemy throws grenade voice:LegionRaider]] "Eat this, cowards!"),
		T(941635024041, --[[VoiceResponse LegionRaider AIThrowGrenade VoiceResponse AIThrowGrenade - Enemy throws grenade voice:LegionRaider]] "Ça va chauffer! "),
		T(982396930397, --[[VoiceResponse LegionRaider AIThrowGrenade VoiceResponse AIThrowGrenade - Enemy throws grenade voice:LegionRaider]] "Have a blast!")
	}),
	BecomeAware = TConcat({
		T(487314460392, --[[VoiceResponse LegionRaider BecomeAware VoiceResponse BecomeAware - Becomes aware voice:LegionRaider]] "Huh? Enemies!"),
		T(955750400317, --[[VoiceResponse LegionRaider BecomeAware VoiceResponse BecomeAware - Becomes aware voice:LegionRaider]] "Alerter! Alerter!"),
		T(228222615830, --[[VoiceResponse LegionRaider BecomeAware VoiceResponse BecomeAware - Becomes aware voice:LegionRaider]] "We're under attack!"),
		T(453781901442, --[[VoiceResponse LegionRaider BecomeAware VoiceResponse BecomeAware - Becomes aware voice:LegionRaider]] "Intruders! Alarm!"),
		T(512811805112, --[[VoiceResponse LegionRaider BecomeAware VoiceResponse BecomeAware - Becomes aware voice:LegionRaider]] "The foreigners are here! To arms!"),
		T(263339193755, --[[VoiceResponse LegionRaider BecomeAware VoiceResponse BecomeAware - Becomes aware voice:LegionRaider]] "Enemy spotted!")
	}),
	BecomeAwarePierreDead = TConcat({
		T(970312184593, --[[VoiceResponse LegionRaider BecomeAwarePierreDead VoiceResponse BecomeAwarePierreDead - Enemy becomes aware, but Pierre is recruited share_id:true voice:LegionRaider]] "It's the foreigners who killed Pierre! You will die here, dogs!"),
		T(158948057658, --[[VoiceResponse LegionRaider BecomeAwarePierreDead VoiceResponse BecomeAwarePierreDead - Enemy becomes aware, but Pierre is recruited share_id:true voice:LegionRaider]] "You killed Pierre! Now you must die!"),
		T(487314460392, --[[VoiceResponse LegionRaider BecomeAwarePierreDead VoiceResponse BecomeAwarePierreDead - Enemy becomes aware, but Pierre is recruited share_id:true voice:LegionRaider]] "Huh? Enemies!"),
		T(955750400317, --[[VoiceResponse LegionRaider BecomeAwarePierreDead VoiceResponse BecomeAwarePierreDead - Enemy becomes aware, but Pierre is recruited share_id:true voice:LegionRaider]] "Alerter! Alerter!"),
		T(228222615830, --[[VoiceResponse LegionRaider BecomeAwarePierreDead VoiceResponse BecomeAwarePierreDead - Enemy becomes aware, but Pierre is recruited share_id:true voice:LegionRaider]] "We're under attack!"),
		T(453781901442, --[[VoiceResponse LegionRaider BecomeAwarePierreDead VoiceResponse BecomeAwarePierreDead - Enemy becomes aware, but Pierre is recruited share_id:true voice:LegionRaider]] "Intruders! Alarm!"),
		T(512811805112, --[[VoiceResponse LegionRaider BecomeAwarePierreDead VoiceResponse BecomeAwarePierreDead - Enemy becomes aware, but Pierre is recruited share_id:true voice:LegionRaider]] "The foreigners are here! To arms!"),
		T(263339193755, --[[VoiceResponse LegionRaider BecomeAwarePierreDead VoiceResponse BecomeAwarePierreDead - Enemy becomes aware, but Pierre is recruited share_id:true voice:LegionRaider]] "Enemy spotted!")
	}),
	BecomeAwarePierreRecruited = TConcat({
		T(244800217248, --[[VoiceResponse LegionRaider BecomeAwarePierreRecruited VoiceResponse BecomeAwarePierreRecruited - Enemy becomes aware, but Pierre is recruited share_id:true voice:LegionRaider]] "Pierre, you traitor! I will kill you for the Major."),
		T(384241760157, --[[VoiceResponse LegionRaider BecomeAwarePierreRecruited VoiceResponse BecomeAwarePierreRecruited - Enemy becomes aware, but Pierre is recruited share_id:true voice:LegionRaider]] "Look! It's that traitor Pierre. I will kill you myself!"),
		T(487314460392, --[[VoiceResponse LegionRaider BecomeAwarePierreRecruited VoiceResponse BecomeAwarePierreRecruited - Enemy becomes aware, but Pierre is recruited share_id:true voice:LegionRaider]] "Huh? Enemies!"),
		T(955750400317, --[[VoiceResponse LegionRaider BecomeAwarePierreRecruited VoiceResponse BecomeAwarePierreRecruited - Enemy becomes aware, but Pierre is recruited share_id:true voice:LegionRaider]] "Alerter! Alerter!"),
		T(228222615830, --[[VoiceResponse LegionRaider BecomeAwarePierreRecruited VoiceResponse BecomeAwarePierreRecruited - Enemy becomes aware, but Pierre is recruited share_id:true voice:LegionRaider]] "We're under attack!"),
		T(453781901442, --[[VoiceResponse LegionRaider BecomeAwarePierreRecruited VoiceResponse BecomeAwarePierreRecruited - Enemy becomes aware, but Pierre is recruited share_id:true voice:LegionRaider]] "Intruders! Alarm!"),
		T(512811805112, --[[VoiceResponse LegionRaider BecomeAwarePierreRecruited VoiceResponse BecomeAwarePierreRecruited - Enemy becomes aware, but Pierre is recruited share_id:true voice:LegionRaider]] "The foreigners are here! To arms!"),
		T(263339193755, --[[VoiceResponse LegionRaider BecomeAwarePierreRecruited VoiceResponse BecomeAwarePierreRecruited - Enemy becomes aware, but Pierre is recruited share_id:true voice:LegionRaider]] "Enemy spotted!")
	}),
	Climbing = TConcat({
		T(849396157191, --[[VoiceResponse LegionRaider Climbing VoiceResponse Climbing - Emote. When unit is climbing over fences, on cliffs, etc. voice:LegionRaider]] "(climbing)"),
		T(817780656610, --[[VoiceResponse LegionRaider Climbing VoiceResponse Climbing - Emote. When unit is climbing over fences, on cliffs, etc. voice:LegionRaider]] "(climbing_2)")
	}),
	HeavyBreathing = TConcat({
		T(687691638963, --[[VoiceResponse LegionRaider HeavyBreathing VoiceResponse HeavyBreathing - During physical exertion voice:LegionRaider]] "(heavy breath)"),
		T(822314761429, --[[VoiceResponse LegionRaider HeavyBreathing VoiceResponse HeavyBreathing - During physical exertion voice:LegionRaider]] "(heavy breath_2)")
	}),
	Jumping = TConcat({
		T(670913876097, --[[VoiceResponse LegionRaider Jumping VoiceResponse Jumping - When jumping over small obstacles (e.g. puddles) voice:LegionRaider]] "(jumping over something)"),
		T(425280748160, --[[VoiceResponse LegionRaider Jumping VoiceResponse Jumping - When jumping over small obstacles (e.g. puddles) voice:LegionRaider]] "(jumping over something_2)")
	}),
	Pain = TConcat({
		T(311780644976, --[[VoiceResponse LegionRaider Pain VoiceResponse Pain - Hit by an attack (if surrounded SurroundedPain is played instead). Short. These are emotes - disregard the written text. voice:LegionRaider]] "Agh."),
		T(502637331638, --[[VoiceResponse LegionRaider Pain VoiceResponse Pain - Hit by an attack (if surrounded SurroundedPain is played instead). Short. These are emotes - disregard the written text. voice:LegionRaider]] "Ouch."),
		T(610171837732, --[[VoiceResponse LegionRaider Pain VoiceResponse Pain - Hit by an attack (if surrounded SurroundedPain is played instead). Short. These are emotes - disregard the written text. voice:LegionRaider]] "Ugh."),
		T(817825345988, --[[VoiceResponse LegionRaider Pain VoiceResponse Pain - Hit by an attack (if surrounded SurroundedPain is played instead). Short. These are emotes - disregard the written text. voice:LegionRaider]] "Pain4"),
		T(155608077217, --[[VoiceResponse LegionRaider Pain VoiceResponse Pain - Hit by an attack (if surrounded SurroundedPain is played instead). Short. These are emotes - disregard the written text. voice:LegionRaider]] "Pain5"),
		T(370002304246, --[[VoiceResponse LegionRaider Pain VoiceResponse Pain - Hit by an attack (if surrounded SurroundedPain is played instead). Short. These are emotes - disregard the written text. voice:LegionRaider]] "Pain6"),
		T(582354548755, --[[VoiceResponse LegionRaider Pain VoiceResponse Pain - Hit by an attack (if surrounded SurroundedPain is played instead). Short. These are emotes - disregard the written text. voice:LegionRaider]] "Pain7"),
		T(309623978691, --[[VoiceResponse LegionRaider Pain VoiceResponse Pain - Hit by an attack (if surrounded SurroundedPain is played instead). Short. These are emotes - disregard the written text. voice:LegionRaider]] "Pain8"),
		T(955931710128, --[[VoiceResponse LegionRaider Pain VoiceResponse Pain - Hit by an attack (if surrounded SurroundedPain is played instead). Short. These are emotes - disregard the written text. voice:LegionRaider]] "Pain9")
	}),
	Startled = TConcat({
		T(484566286690, --[[VoiceResponse LegionRaider Startled VoiceResponse Startled - Startled by hearing a sudden noise voice:LegionRaider]] "Huh?"),
		T(646104083600, --[[VoiceResponse LegionRaider Startled VoiceResponse Startled - Startled by hearing a sudden noise voice:LegionRaider]] "Wha-?")
	}),
	TacticalCareful = TConcat({
		T(639655019046, --[[VoiceResponse LegionRaider TacticalCareful VoiceResponse TacticalCareful - The other team is making gains during the battle (inflicted 2+ wounds during their turn) voice:LegionRaider]] "You won't break our spirit."),
		T(816070282793, --[[VoiceResponse LegionRaider TacticalCareful VoiceResponse TacticalCareful - The other team is making gains during the battle (inflicted 2+ wounds during their turn) voice:LegionRaider]] "Remember the Major's teaching. Every wound they inflict, you need to repay tenfold."),
		T(779762019256, --[[VoiceResponse LegionRaider TacticalCareful VoiceResponse TacticalCareful - The other team is making gains during the battle (inflicted 2+ wounds during their turn) voice:LegionRaider]] "Bite down on your pain and fight on!"),
		T(107240340582, --[[VoiceResponse LegionRaider TacticalCareful VoiceResponse TacticalCareful - The other team is making gains during the battle (inflicted 2+ wounds during their turn) voice:LegionRaider]] "The Major teaches us that pain is our ally.")
	}),
	TacticalCarefulMajorDead = TConcat({
		T(639655019046, --[[VoiceResponse LegionRaider TacticalCarefulMajorDead VoiceResponse TacticalCarefulMajorDead - Major dead version of TacticalCareful share_id:true voice:LegionRaider]] "You won't break our spirit."),
		T(816070282793, --[[VoiceResponse LegionRaider TacticalCarefulMajorDead VoiceResponse TacticalCarefulMajorDead - Major dead version of TacticalCareful share_id:true voice:LegionRaider]] "Remember the Major's teaching. Every wound they inflict, you need to repay tenfold."),
		T(779762019256, --[[VoiceResponse LegionRaider TacticalCarefulMajorDead VoiceResponse TacticalCarefulMajorDead - Major dead version of TacticalCareful share_id:true voice:LegionRaider]] "Bite down on your pain and fight on!")
	}),
	TacticalFocus = TConcat({
		T(885623976405, --[[VoiceResponse LegionRaider TacticalFocus VoiceResponse TacticalFocus - The team has missed  3+ times voice:LegionRaider]] "Fuck. The Major will have our hides if we keep missing."),
		T(706173759441, --[[VoiceResponse LegionRaider TacticalFocus VoiceResponse TacticalFocus - The team has missed  3+ times voice:LegionRaider]] "Damn, they are hard to get. We need to aim better."),
		T(112669883748, --[[VoiceResponse LegionRaider TacticalFocus VoiceResponse TacticalFocus - The team has missed  3+ times voice:LegionRaider]] "Curse you, lazy dogs! Fight better!"),
		T(171836284294, --[[VoiceResponse LegionRaider TacticalFocus VoiceResponse TacticalFocus - The team has missed  3+ times voice:LegionRaider]] "Stop shooting the air like cowardly dogs!")
	}),
	TacticalKilling = TConcat({
		T(175961604606, --[[VoiceResponse LegionRaider TacticalKilling VoiceResponse TacticalKilling - The team is winning the battle  (2+ units have been downed/killed) voice:LegionRaider]] "The Legion will be victorious this day!"),
		T(538162302386, --[[VoiceResponse LegionRaider TacticalKilling VoiceResponse TacticalKilling - The team is winning the battle  (2+ units have been downed/killed) voice:LegionRaider]] "Now you know to fear the Legion!"),
		T(112659541273, --[[VoiceResponse LegionRaider TacticalKilling VoiceResponse TacticalKilling - The team is winning the battle  (2+ units have been downed/killed) voice:LegionRaider]] "We will water the soil with the blood of you all!")
	}),
	TacticalLoss = TConcat({
		T(630072988164, --[[VoiceResponse LegionRaider TacticalLoss VoiceResponse TacticalLoss - The team is losing the battle (2+ units have been downed/killed) voice:LegionRaider]] "They will wipe us out. Remember - if we die, the Major will come to hell and give our souls a beating."),
		T(430987018340, --[[VoiceResponse LegionRaider TacticalLoss VoiceResponse TacticalLoss - The team is losing the battle (2+ units have been downed/killed) voice:LegionRaider]] "I thought foreigners were stupid and could not shoot worth a damn. What is happening?"),
		T(886870401595, --[[VoiceResponse LegionRaider TacticalLoss VoiceResponse TacticalLoss - The team is losing the battle (2+ units have been downed/killed) voice:LegionRaider]] "Weren't foreigners supposed to be bad at shooting? The Major said we are ten times better."),
		T(183407913205, --[[VoiceResponse LegionRaider TacticalLoss VoiceResponse TacticalLoss - The team is losing the battle (2+ units have been downed/killed) voice:LegionRaider]] "They are slaughtering us. ")
	}),
	TacticalPressing = TConcat({
		T(532376278358, --[[VoiceResponse LegionRaider TacticalPressing VoiceResponse TacticalPressing - The team is making gains during the battle (2+ wounds have been inflicted) voice:LegionRaider]] "Get them! Make them pay! For the Legion!"),
		T(355176956815, --[[VoiceResponse LegionRaider TacticalPressing VoiceResponse TacticalPressing - The team is making gains during the battle (2+ wounds have been inflicted) voice:LegionRaider]] "The Major will be pleased. Hurt them more!"),
		T(233116101486, --[[VoiceResponse LegionRaider TacticalPressing VoiceResponse TacticalPressing - The team is making gains during the battle (2+ wounds have been inflicted) voice:LegionRaider]] "You regret facing the Legion now, yes?")
	}),
	TacticalPressingMajorDead = TConcat({
		T(532376278358, --[[VoiceResponse LegionRaider TacticalPressingMajorDead VoiceResponse TacticalPressingMajorDead - Major dead version of TacticalPressing share_id:true voice:LegionRaider]] "Get them! Make them pay! For the Legion!"),
		T(233116101486, --[[VoiceResponse LegionRaider TacticalPressingMajorDead VoiceResponse TacticalPressingMajorDead - Major dead version of TacticalPressing share_id:true voice:LegionRaider]] "You regret facing the Legion now, yes?")
	}),
	TacticalRevenge = TConcat({
		T(717837787640, --[[VoiceResponse LegionRaider TacticalRevenge VoiceResponse TacticalRevenge - A unit from the team has been downed/killed voice:LegionRaider]] "You will pay, foreign dogs. Now it is us that will bring the pain."),
		T(812250619345, --[[VoiceResponse LegionRaider TacticalRevenge VoiceResponse TacticalRevenge - A unit from the team has been downed/killed voice:LegionRaider]] "For the Major! Kill them for our fallen."),
		T(514230939952, --[[VoiceResponse LegionRaider TacticalRevenge VoiceResponse TacticalRevenge - A unit from the team has been downed/killed voice:LegionRaider]] "Kill one of us and we kill ten of you!"),
		T(705399482311, --[[VoiceResponse LegionRaider TacticalRevenge VoiceResponse TacticalRevenge - A unit from the team has been downed/killed voice:LegionRaider]] "That was a mistake. Now we will kill you all.")
	}),
	TacticalRevengeMajorDead = TConcat({
		T(717837787640, --[[VoiceResponse LegionRaider TacticalRevengeMajorDead VoiceResponse TacticalRevengeMajorDead - Major dead version of TacticalRevenge share_id:true voice:LegionRaider]] "You will pay, foreign dogs. Now it is us that will bring the pain."),
		T(514230939952, --[[VoiceResponse LegionRaider TacticalRevengeMajorDead VoiceResponse TacticalRevengeMajorDead - Major dead version of TacticalRevenge share_id:true voice:LegionRaider]] "Kill one of us and we kill ten of you!"),
		T(705399482311, --[[VoiceResponse LegionRaider TacticalRevengeMajorDead VoiceResponse TacticalRevengeMajorDead - Major dead version of TacticalRevenge share_id:true voice:LegionRaider]] "That was a mistake. Now we will kill you all.")
	}),
	TacticalTaunt = TConcat({
		T(370815889789, --[[VoiceResponse LegionRaider TacticalTaunt VoiceResponse TacticalTaunt - The team has visible enemies from the other team and is shouting things at them voice:LegionRaider]] "Foreign dogs! You do not stand a chance against us."),
		T(298193394733, --[[VoiceResponse LegionRaider TacticalTaunt VoiceResponse TacticalTaunt - The team has visible enemies from the other team and is shouting things at them voice:LegionRaider]] "We are ten times better than you. TEN TIMES!"),
		T(552805897482, --[[VoiceResponse LegionRaider TacticalTaunt VoiceResponse TacticalTaunt - The team has visible enemies from the other team and is shouting things at them voice:LegionRaider]] "You will not leave our country alive."),
		T(108089802294, --[[VoiceResponse LegionRaider TacticalTaunt VoiceResponse TacticalTaunt - The team has visible enemies from the other team and is shouting things at them voice:LegionRaider]] "Face the Legion and die!")
	}),
	TakeCover = TConcat({
		T(595656376301, --[[VoiceResponse LegionRaider TakeCover VoiceResponse TakeCover - Played when the Take Cover action is used voice:LegionRaider]] "Keeping my head down!")
	}),
	Wounded = TConcat({
		T(880499875218, --[[VoiceResponse LegionRaider Wounded VoiceResponse Wounded - Unit is Wounded. (When the Wounded VR is played, the Pain VR should be suppressed.) Add a pain noise at the begining voice:LegionRaider]] "Je suis blessé!"),
		T(219244453722, --[[VoiceResponse LegionRaider Wounded VoiceResponse Wounded - Unit is Wounded. (When the Wounded VR is played, the Pain VR should be suppressed.) Add a pain noise at the begining voice:LegionRaider]] "Uff, that hurt!"),
		T(325800291297, --[[VoiceResponse LegionRaider Wounded VoiceResponse Wounded - Unit is Wounded. (When the Wounded VR is played, the Pain VR should be suppressed.) Add a pain noise at the begining voice:LegionRaider]] "Fuck!"),
		T(185269312207, --[[VoiceResponse LegionRaider Wounded VoiceResponse Wounded - Unit is Wounded. (When the Wounded VR is played, the Pain VR should be suppressed.) Add a pain noise at the begining voice:LegionRaider]] "Je suis grièvement blessé!"),
		T(160432728220, --[[VoiceResponse LegionRaider Wounded VoiceResponse Wounded - Unit is Wounded. (When the Wounded VR is played, the Pain VR should be suppressed.) Add a pain noise at the begining voice:LegionRaider]] "It hurts! It hurts!"),
		T(856426059381, --[[VoiceResponse LegionRaider Wounded VoiceResponse Wounded - Unit is Wounded. (When the Wounded VR is played, the Pain VR should be suppressed.) Add a pain noise at the begining voice:LegionRaider]] "I am wounded!"),
		T(607572959898, --[[VoiceResponse LegionRaider Wounded VoiceResponse Wounded - Unit is Wounded. (When the Wounded VR is played, the Pain VR should be suppressed.) Add a pain noise at the begining voice:LegionRaider]] "Uff, Ça fait mal!"),
		T(520049325300, --[[VoiceResponse LegionRaider Wounded VoiceResponse Wounded - Unit is Wounded. (When the Wounded VR is played, the Pain VR should be suppressed.) Add a pain noise at the begining voice:LegionRaider]] "Putain!")
	}),
	group = "Enemies",
	id = "LegionRaider",
})

