-- ========== GENERATED BY VoiceResponse Editor (Ctrl-Alt-V) DO NOT EDIT MANUALLY! ==========

PlaceObj('VoiceResponse', {
	AIAttack = TConcat({
		T(241143287426, --[[VoiceResponse Pierre AIAttack VoiceResponse AIAttack - When attacking voice:Pierre]] "I will make this as painful as possible."),
		T(242465586968, --[[VoiceResponse Pierre AIAttack VoiceResponse AIAttack - When attacking voice:Pierre]] "Die!"),
		T(757632457662, --[[VoiceResponse Pierre AIAttack VoiceResponse AIAttack - When attacking voice:Pierre]] "C'est très facile."),
		T(309957681111, --[[VoiceResponse Pierre AIAttack VoiceResponse AIAttack - When attacking voice:Pierre]] "Death to all foreigners!"),
		T(201469474136, --[[VoiceResponse Pierre AIAttack VoiceResponse AIAttack - When attacking voice:Pierre]] "For the Major!"),
		T(342455622573, --[[VoiceResponse Pierre AIAttack VoiceResponse AIAttack - When attacking voice:Pierre]] "PRENDS ÇA!"),
		T(209558525647, --[[VoiceResponse Pierre AIAttack VoiceResponse AIAttack - When attacking voice:Pierre]] "MEURS!"),
		T(291556101204, --[[VoiceResponse Pierre AIAttack VoiceResponse AIAttack - When attacking voice:Pierre]] "Attack!")
	}),
	AIDeadAlly = TConcat({
		T(168997376557, --[[VoiceResponse Pierre AIDeadAlly VoiceResponse AIDeadAlly - Played on dead human enemy ally voice:Pierre]] "I will avenge every one of my men you kill."),
		T(913973489421, --[[VoiceResponse Pierre AIDeadAlly VoiceResponse AIDeadAlly - Played on dead human enemy ally voice:Pierre]] "Cursed foreigners! I will pay you back in kind."),
		T(756844567978, --[[VoiceResponse Pierre AIDeadAlly VoiceResponse AIDeadAlly - Played on dead human enemy ally voice:Pierre]] "You will regret that."),
		T(491586063589, --[[VoiceResponse Pierre AIDeadAlly VoiceResponse AIDeadAlly - Played on dead human enemy ally voice:Pierre]] "You dare kill a Legion soldier? Now, you will die!")
	}),
	AIFlanking = TConcat({
		T(441173850346, --[[VoiceResponse Pierre AIFlanking VoiceResponse AIFlanking - Played when the AI is flanking an opponent voice:Pierre]] "Let's flank them!"),
		T(169579547305, --[[VoiceResponse Pierre AIFlanking VoiceResponse AIFlanking - Played when the AI is flanking an opponent voice:Pierre]] "Encircle them.")
	}),
	AIGasAreaSelection = TConcat({
		T(277826335727, --[[VoiceResponse Pierre AIGasAreaSelection VoiceResponse AIGasAreaSelection - Unit receiving gas effect or starting round in one. Suffocating. Emote. voice:Pierre]] "(coughing)")
	}),
	AIOverwatch = TConcat({
		T(574293353271, --[[VoiceResponse Pierre AIOverwatch VoiceResponse AIOverwatch - Enemy sets up overwatch voice:Pierre]] "If you move, you die."),
		T(545785006805, --[[VoiceResponse Pierre AIOverwatch VoiceResponse AIOverwatch - Enemy sets up overwatch voice:Pierre]] "Come and let me welcome you to Grand Chien.")
	}),
	AIStartingTurnAttack = TConcat({
		T(923860712457, --[[VoiceResponse Pierre AIStartingTurnAttack VoiceResponse AIStartingTurnAttack - Will move and attack this turn voice:Pierre]] "Whoever gets them, gets a reward."),
		T(771362748603, --[[VoiceResponse Pierre AIStartingTurnAttack VoiceResponse AIStartingTurnAttack - Will move and attack this turn voice:Pierre]] "Attack! Remember what I taught you!"),
		T(675299047967, --[[VoiceResponse Pierre AIStartingTurnAttack VoiceResponse AIStartingTurnAttack - Will move and attack this turn voice:Pierre]] "Loose formation! Go!"),
		T(116655790020, --[[VoiceResponse Pierre AIStartingTurnAttack VoiceResponse AIStartingTurnAttack - Will move and attack this turn voice:Pierre]] "Forward! Not a step back!")
	}),
	AIStartingTurnLastEnemy = TConcat({
		T(289665010242, --[[VoiceResponse Pierre AIStartingTurnLastEnemy VoiceResponse AIStartingTurnLastEnemy - This is the last standing enemy voice:Pierre]] "You may have killed my men, but I am still standing. And I will fight to the end."),
		T(169928286787, --[[VoiceResponse Pierre AIStartingTurnLastEnemy VoiceResponse AIStartingTurnLastEnemy - This is the last standing enemy voice:Pierre]] "I will be damned if I go down without taking one of you with me!")
	}),
	AIStartingTurnMoving = TConcat({
		T(611518469362, --[[VoiceResponse Pierre AIStartingTurnMoving VoiceResponse AIStartingTurnMoving - All enemy units will just move this turn. voice:Pierre]] "Reposition!"),
		T(945259598920, --[[VoiceResponse Pierre AIStartingTurnMoving VoiceResponse AIStartingTurnMoving - All enemy units will just move this turn. voice:Pierre]] "Move! Move! Move!"),
		T(733685794749, --[[VoiceResponse Pierre AIStartingTurnMoving VoiceResponse AIStartingTurnMoving - All enemy units will just move this turn. voice:Pierre]] "Don't bunch up, you idiots!"),
		T(105649069404, --[[VoiceResponse Pierre AIStartingTurnMoving VoiceResponse AIStartingTurnMoving - All enemy units will just move this turn. voice:Pierre]] "Spread out, you fools!")
	}),
	AITaunt = TConcat({
		T(225409558094, --[[VoiceResponse Pierre AITaunt VoiceResponse AITaunt - Played during the player's turn when the player has missed with 3 attacks. voice:Pierre]] "You are soft. This country will eat you alive!"),
		T(925757192428, --[[VoiceResponse Pierre AITaunt VoiceResponse AITaunt - Played during the player's turn when the player has missed with 3 attacks. voice:Pierre]] "I learned to shoot at six. You never learned.")
	}),
	BecomeAware = TConcat({
		T(830105914166, --[[VoiceResponse Pierre BecomeAware VoiceResponse BecomeAware - Becomes aware voice:Pierre]] "There you are, you foreign bastards."),
		T(423288338111, --[[VoiceResponse Pierre BecomeAware VoiceResponse BecomeAware - Becomes aware voice:Pierre]] "I see you, mercenary swine. Come face me!"),
		T(523135510347, --[[VoiceResponse Pierre BecomeAware VoiceResponse BecomeAware - Becomes aware voice:Pierre]] "Enemies! Attack them!")
	}),
	Pain = TConcat({
		T(138722087920, --[[VoiceResponse Pierre Pain VoiceResponse Pain - Hit by an attack (if surrounded SurroundedPain is played instead). Short. These are emotes - disregard the written text. voice:Pierre]] "Agh."),
		T(686247529720, --[[VoiceResponse Pierre Pain VoiceResponse Pain - Hit by an attack (if surrounded SurroundedPain is played instead). Short. These are emotes - disregard the written text. voice:Pierre]] "Ugh."),
		T(432968969481, --[[VoiceResponse Pierre Pain VoiceResponse Pain - Hit by an attack (if surrounded SurroundedPain is played instead). Short. These are emotes - disregard the written text. voice:Pierre]] "Ouch."),
		T(530293307239, --[[VoiceResponse Pierre Pain VoiceResponse Pain - Hit by an attack (if surrounded SurroundedPain is played instead). Short. These are emotes - disregard the written text. voice:Pierre]] "Pain4"),
		T(805499075137, --[[VoiceResponse Pierre Pain VoiceResponse Pain - Hit by an attack (if surrounded SurroundedPain is played instead). Short. These are emotes - disregard the written text. voice:Pierre]] "Pain5")
	}),
	TacticalCareful = TConcat({
		T(258633478752, --[[VoiceResponse Pierre TacticalCareful VoiceResponse TacticalCareful - The other team is making gains during the battle (inflicted 2+ wounds during their turn) voice:Pierre]] "Ignore the pain! Fight on!"),
		T(213823827460, --[[VoiceResponse Pierre TacticalCareful VoiceResponse TacticalCareful - The other team is making gains during the battle (inflicted 2+ wounds during their turn) voice:Pierre]] "Their attacks are weak and we are strong!")
	}),
	TacticalFocus = TConcat({
		T(765313120663, --[[VoiceResponse Pierre TacticalFocus VoiceResponse TacticalFocus - The team has missed  3+ times voice:Pierre]] "Aim better, you careless clowns!"),
		T(719313488053, --[[VoiceResponse Pierre TacticalFocus VoiceResponse TacticalFocus - The team has missed  3+ times voice:Pierre]] "If you cannot use a weapon, then use your fists!")
	}),
	TacticalKilling = TConcat({
		T(216078770791, --[[VoiceResponse Pierre TacticalKilling VoiceResponse TacticalKilling - The team is winning the battle  (2+ units have been downed/killed) voice:Pierre]] "Now they know why they fear the Legion!"),
		T(329610038573, --[[VoiceResponse Pierre TacticalKilling VoiceResponse TacticalKilling - The team is winning the battle  (2+ units have been downed/killed) voice:Pierre]] "Très bien! You are making the Major proud.")
	}),
	TacticalLoss = TConcat({
		T(593058889936, --[[VoiceResponse Pierre TacticalLoss VoiceResponse TacticalLoss - The team is losing the battle (2+ units have been downed/killed) voice:Pierre]] "Use cover, you idiots! What are you doing?"),
		T(716315636795, --[[VoiceResponse Pierre TacticalLoss VoiceResponse TacticalLoss - The team is losing the battle (2+ units have been downed/killed) voice:Pierre]] "We're taking casualties. Fight harder!")
	}),
	TacticalPressing = TConcat({
		T(854294624489, --[[VoiceResponse Pierre TacticalPressing VoiceResponse TacticalPressing - The team is making gains during the battle (2+ wounds have been inflicted) voice:Pierre]] "Press them, my brave Legionnaires!"),
		T(397731704070, --[[VoiceResponse Pierre TacticalPressing VoiceResponse TacticalPressing - The team is making gains during the battle (2+ wounds have been inflicted) voice:Pierre]] "La vache! Show them who we are!")
	}),
	TacticalReposition = TConcat({
		T(100956859961, --[[VoiceResponse Pierre TacticalReposition VoiceResponse TacticalReposition - The team has not started shooting but is repositioning during the battle voice:Pierre]] "Don't just run around! Fight them!"),
		T(558102111921, --[[VoiceResponse Pierre TacticalReposition VoiceResponse TacticalReposition - The team has not started shooting but is repositioning during the battle voice:Pierre]] "You don't win a battle by running and hiding!")
	}),
	TacticalRevenge = TConcat({
		T(628099222880, --[[VoiceResponse Pierre TacticalRevenge VoiceResponse TacticalRevenge - A unit from the team has been downed/killed voice:Pierre]] "We will make them pay for that!"),
		T(307996122841, --[[VoiceResponse Pierre TacticalRevenge VoiceResponse TacticalRevenge - A unit from the team has been downed/killed voice:Pierre]] "We must repay them in kind.")
	}),
	TacticalTaunt = TConcat({
		T(623823429725, --[[VoiceResponse Pierre TacticalTaunt VoiceResponse TacticalTaunt - The team has visible enemies from the other team and is shouting things at them voice:Pierre]] "The stupid fools walk right up to us! Destroy them."),
		T(230974005120, --[[VoiceResponse Pierre TacticalTaunt VoiceResponse TacticalTaunt - The team has visible enemies from the other team and is shouting things at them voice:Pierre]] "Look at these arrogant imbeciles! Legion, teach them a lesson.")
	}),
	TakeCover = TConcat({
		T(246312480227, --[[VoiceResponse Pierre TakeCover VoiceResponse TakeCover - Played when the Take Cover action is used voice:Pierre]] "Just try and hit me now!")
	}),
	VillainDefeated = TConcat({
		T(227269178974, --[[VoiceResponse Pierre VillainDefeated VoiceResponse VillainDefeated - Enemy lieutenant defeated. voice:Pierre]] "No!... No, it can't be... I... I surrender."),
		T(690638165181, --[[VoiceResponse Pierre VillainDefeated VoiceResponse VillainDefeated - Enemy lieutenant defeated. voice:Pierre]] "I have failed the Major. You have beaten me.")
	}),
	VillainHurt = TConcat({
		T(800204240433, --[[VoiceResponse Pierre VillainHurt VoiceResponse VillainHurt - Played on villain hp less than 50% voice:Pierre]] "You fight well but not well enough."),
		T(148540879646, --[[VoiceResponse Pierre VillainHurt VoiceResponse VillainHurt - Played on villain hp less than 50% voice:Pierre]] "You hit hard, I will give you that.")
	}),
	Wounded = TConcat({
		T(683686500543, --[[VoiceResponse Pierre Wounded VoiceResponse Wounded - Unit is Wounded. (When the Wounded VR is played, the Pain VR should be suppressed.) Add a pain noise at the begining voice:Pierre]] "Damn it!"),
		T(269042601572, --[[VoiceResponse Pierre Wounded VoiceResponse Wounded - Unit is Wounded. (When the Wounded VR is played, the Pain VR should be suppressed.) Add a pain noise at the begining voice:Pierre]] "Won't die yet!"),
		T(108434310331, --[[VoiceResponse Pierre Wounded VoiceResponse Wounded - Unit is Wounded. (When the Wounded VR is played, the Pain VR should be suppressed.) Add a pain noise at the begining voice:Pierre]] "Bastards!"),
		T(578294989619, --[[VoiceResponse Pierre Wounded VoiceResponse Wounded - Unit is Wounded. (When the Wounded VR is played, the Pain VR should be suppressed.) Add a pain noise at the begining voice:Pierre]] "Je suis blessé!"),
		T(526830046926, --[[VoiceResponse Pierre Wounded VoiceResponse Wounded - Unit is Wounded. (When the Wounded VR is played, the Pain VR should be suppressed.) Add a pain noise at the begining voice:Pierre]] "I am wounded!"),
		T(170573502397, --[[VoiceResponse Pierre Wounded VoiceResponse Wounded - Unit is Wounded. (When the Wounded VR is played, the Pain VR should be suppressed.) Add a pain noise at the begining voice:Pierre]] "Uff, Ça fait mal!"),
		T(655074008671, --[[VoiceResponse Pierre Wounded VoiceResponse Wounded - Unit is Wounded. (When the Wounded VR is played, the Pain VR should be suppressed.) Add a pain noise at the begining voice:Pierre]] "It will take more than that to kill me!"),
		T(634504852406, --[[VoiceResponse Pierre Wounded VoiceResponse Wounded - Unit is Wounded. (When the Wounded VR is played, the Pain VR should be suppressed.) Add a pain noise at the begining voice:Pierre]] "Uff, that hurt!")
	}),
	group = "Villains",
	id = "Pierre",
})

