-- ========== GENERATED BY VoiceResponse Editor (Ctrl-Alt-V) DO NOT EDIT MANUALLY! ==========

PlaceObj('VoiceResponse', {
	ActivityFinished = TConcat({
		T(912701519399, --[[VoiceResponse Sidney ActivityFinished VoiceResponse ActivityFinished - SatView activity finished voice:Sidney]] "...and Bob's your uncle! Ready for the next thing.")
	}),
	ActivityStarted = TConcat({
		T(566682004767, --[[VoiceResponse Sidney ActivityStarted VoiceResponse ActivityStarted - When an activity is started. Played by the firs merc associated with the task voice:Sidney]] "Right-o. Should be finished promptly.")
	}),
	AimAttack = TConcat({
		T(541945411190, --[[VoiceResponse Sidney AimAttack VoiceResponse AimAttack - When aiming and there is a decent chance of hitting voice:Sidney]] "No trouble at all."),
		T(315829997748, --[[VoiceResponse Sidney AimAttack VoiceResponse AimAttack - When aiming and there is a decent chance of hitting voice:Sidney]] "Shouldn't be a problem."),
		T(354977004005, --[[VoiceResponse Sidney AimAttack VoiceResponse AimAttack - When aiming and there is a decent chance of hitting voice:Sidney]] "Got this rotter dead to rights.")
	}),
	AimAttackStealth = TConcat({
		T(422270410098, --[[VoiceResponse Sidney AimAttackStealth VoiceResponse AimAttackStealth - When aiming and there is a decent chance of hitting. Used while Sneaking - voice should be shushed (except Steroid) voice:Sidney]] "I say, this one is in for a nasty surprise."),
		T(406192839074, --[[VoiceResponse Sidney AimAttackStealth VoiceResponse AimAttackStealth - When aiming and there is a decent chance of hitting. Used while Sneaking - voice should be shushed (except Steroid) voice:Sidney]] "There's a good chance I can do this quietly.")
	}),
	AimAttack_Low = TConcat({
		T(716049069820, --[[VoiceResponse Sidney AimAttack_Low VoiceResponse AimAttack_Low - When aiming and the CtH is less than 20% voice:Sidney]] "Sorry, but I think perhaps this may not work.")
	}),
	AimAttack_LowStealth = TConcat({
		T(789180933354, --[[VoiceResponse Sidney AimAttack_LowStealth VoiceResponse AimAttack_LowStealth - When aiming and there is very low chance of hitting. Used while Sneaking - voice should be shushed (except Steroid) voice:Sidney]] "Not bloody likely.")
	}),
	AmmoLow = TConcat({
		T(176421762160, --[[VoiceResponse Sidney AmmoLow VoiceResponse AmmoLow - Played when there is less than 25% of clip size or a full reload cannot be made voice:Sidney]] "Don't mean to be a bother, but I'm running low on ammunition.")
	}),
	AnimalFound = TConcat({
		T(246574412152, --[[VoiceResponse Sidney AnimalFound VoiceResponse AnimalFound - Enemy animal spotted. voice:Sidney]] "Some sort of hostile beast here.")
	}),
	BandageDownedUnit = TConcat({
		T(599660885716, --[[VoiceResponse Sidney BandageDownedUnit VoiceResponse BandageDownedUnit - When a downed unit is bandaged. Played by the unit that does the bandaging voice:Sidney]] "Right. There you are. Off you go.")
	}),
	BecomeHidden = TConcat({
		T(428874486085, --[[VoiceResponse Sidney BecomeHidden VoiceResponse BecomeHidden - Played when entering Sneak mode. Voice should be shushed (except Steroid) voice:Sidney]] "Time to slink 'round them."),
		T(103768298036, --[[VoiceResponse Sidney BecomeHidden VoiceResponse BecomeHidden - Played when entering Sneak mode. Voice should be shushed (except Steroid) voice:Sidney]] "Not very dignified, but I suppose it can't be helped.")
	}),
	BusySatView = TConcat({
		T(547017826237, --[[VoiceResponse Sidney BusySatView VoiceResponse BusySatView - Played when merc is in an activity for more than 8 hours. Students and Patients excluded. Played once per activity. voice:Sidney]] "I'm still tarrying.")
	}),
	Climbing = TConcat({
		T(725828601879, --[[VoiceResponse Sidney Climbing VoiceResponse Climbing - Emote. When unit is climbing over fences, on cliffs, etc. voice:Sidney]] "(climbing)"),
		T(574538629547, --[[VoiceResponse Sidney Climbing VoiceResponse Climbing - Emote. When unit is climbing over fences, on cliffs, etc. voice:Sidney]] "(climbing_2)")
	}),
	CombatEndEnemiesRemain = TConcat({
		T(215003252830, --[[VoiceResponse Sidney CombatEndEnemiesRemain VoiceResponse CombatEndEnemiesRemain - There are no more aware enemies but there are still enemies in the sector. voice:Sidney]] "Prudence is the word. We have not disposed of all of our foes.")
	}),
	CombatEndEnemiesRetreated = TConcat({
		T(237805574137, --[[VoiceResponse Sidney CombatEndEnemiesRetreated VoiceResponse CombatEndEnemiesRetreated - All enemies have retreated voice:Sidney]] "The rascals have scattered. Someone must have told them I was coming.")
	}),
	CombatEndNoEnemies = TConcat({
		T(402330827457, --[[VoiceResponse Sidney CombatEndNoEnemies VoiceResponse CombatEndNoEnemies - All enemies have been killed. voice:Sidney]] "Jolly good! That's the last of them.")
	}),
	CombatMovement = TConcat({
		T(186747536518, --[[VoiceResponse Sidney CombatMovement VoiceResponse CombatMovement - When ordering movement in combat. Up to one full sentence or two short ones. voice:Sidney]] "Tally-ho!"),
		T(958713141811, --[[VoiceResponse Sidney CombatMovement VoiceResponse CombatMovement - When ordering movement in combat. Up to one full sentence or two short ones. voice:Sidney]] "Right. Here we go!"),
		T(406801084173, --[[VoiceResponse Sidney CombatMovement VoiceResponse CombatMovement - When ordering movement in combat. Up to one full sentence or two short ones. voice:Sidney]] "I'll try to draw their fire."),
		T(572587503067, --[[VoiceResponse Sidney CombatMovement VoiceResponse CombatMovement - When ordering movement in combat. Up to one full sentence or two short ones. voice:Sidney]] "Right-o!"),
		T(561193044577, --[[VoiceResponse Sidney CombatMovement VoiceResponse CombatMovement - When ordering movement in combat. Up to one full sentence or two short ones. voice:Sidney]] "Of course."),
		T(311742924381, --[[VoiceResponse Sidney CombatMovement VoiceResponse CombatMovement - When ordering movement in combat. Up to one full sentence or two short ones. voice:Sidney]] "Yes, quite right.")
	}),
	CombatMovementStealth = TConcat({
		T(428874486085, --[[VoiceResponse Sidney CombatMovementStealth VoiceResponse CombatMovementStealth - When ordering movement while sneaking. Voice should be shushed (except Steroid) voice:Sidney]] "Time to slink 'round them."),
		T(316396914636, --[[VoiceResponse Sidney CombatMovementStealth VoiceResponse CombatMovementStealth - When ordering movement while sneaking. Voice should be shushed (except Steroid) voice:Sidney]] "Going quietly."),
		T(975220689745, --[[VoiceResponse Sidney CombatMovementStealth VoiceResponse CombatMovementStealth - When ordering movement while sneaking. Voice should be shushed (except Steroid) voice:Sidney]] "Understood. Mum's the word.")
	}),
	CombatStartDetected = TConcat({
		T(890227513149, --[[VoiceResponse Sidney CombatStartDetected VoiceResponse CombatStartDetected - When enemy detects a merc who was hiding. voice:Sidney]] "Bollocks! They've spotted me.")
	}),
	CombatStartPlayer = TConcat({
		T(233788908761, --[[VoiceResponse Sidney CombatStartPlayer VoiceResponse CombatStartPlayer - When player initiates combat with shot. voice:Sidney]] "Right, let's have a go!")
	}),
	CombatTaskCompleted = TConcat({
		T(948091360110, --[[VoiceResponse Sidney CombatTaskCompleted VoiceResponse CombatTaskCompleted - When the Combat Task issued by the merc is completed voice:Sidney]] "That bit of sport was just the thing!")
	}),
	CombatTaskFailed = TConcat({
		T(941552222506, --[[VoiceResponse Sidney CombatTaskFailed VoiceResponse CombatTaskFailed - When the Combat Task issued by the merc is failed voice:Sidney]] "Nevermind. It was just a bit of sport. We'll get it right next time.")
	}),
	CombatTaskGiven = TConcat({
		T(484329870270, --[[VoiceResponse Sidney CombatTaskGiven VoiceResponse CombatTaskGiven - When the merc sets the player a new Combat Task voice:Sidney]] "I've got an idea to add a bit of sport to this activity.")
	}),
	Comment = "Aristocratic British accent. Formal. Unruffled. Age: Adult, mature.",
	ContractExpired = TConcat({
		T(557815442607, --[[VoiceResponse Sidney ContractExpired VoiceResponse ContractExpired - when the mercs contract expires and the player has not extended it voice:Sidney]] "It appears our contract has expired. I must say, I was looking forward to seeing this conflict through to its conclusion. However, I could very well be back. Tally-ho!")
	}),
	DeathBuddy1 = TConcat({
		T(722480754651, --[[VoiceResponse Sidney DeathBuddy1 VoiceResponse DeathBuddy1 - Played on the death of Scope. voice:Sidney]] "Hard to imagine finishing this business without you, Scope, but I shall endeavor to soldier on.")
	}),
	DeathGeneral = TConcat({
		T(766169251475, --[[VoiceResponse Sidney DeathGeneral VoiceResponse DeathGeneral - Played when a character that is neither liked or disliked dies voice:Sidney]] "All too common in our line of work, I'm afraid. Come on, then. There's still work to be done.")
	}),
	DoorLocked = TConcat({
		T(487220166945, --[[VoiceResponse Sidney DoorLocked VoiceResponse DoorLocked - When a attempting to open locked door voice:Sidney]] "I daresay I won't be going this way.")
	}),
	Downed = TConcat({
		T(127086187176, --[[VoiceResponse Sidney Downed VoiceResponse Downed - When entering Downed state. Voice should be as if losing consciousness voice:Sidney]] "Oh, bother. Looks like I won't be meeting the lads at the bridge club after all.")
	}),
	Exhausted = TConcat({
		T(164735794075, --[[VoiceResponse Sidney Exhausted VoiceResponse Exhausted - when the merc becomes Exhausted voice:Sidney]] "I shall retire and resume work shortly.")
	}),
	FriendlyFireBuddy1 = TConcat({
		T(871865404556, --[[VoiceResponse Sidney FriendlyFireBuddy1 VoiceResponse FriendlyFireBuddy1 - Played on friendly fire by the unit hit if the hitting unit is Liked - Scope. voice:Sidney]] "Scope, are you having feminine problems?")
	}),
	FriendlyFireGeneral = TConcat({
		T(172959700569, --[[VoiceResponse Sidney FriendlyFireGeneral VoiceResponse FriendlyFireGeneral - Played on friendly fire by the unit hit if the hitting unit is neither Liked or Disliked voice:Sidney]] "I say!")
	}),
	GasAreaSelection = TConcat({
		T(904466565880, --[[VoiceResponse Sidney GasAreaSelection VoiceResponse GasAreaSelection - Unit receiving gas effect or starting round in one. voice:Sidney]] "(coughing)")
	}),
	GroupOrder = TConcat({
		T(974108006439, --[[VoiceResponse Sidney GroupOrder VoiceResponse GroupOrder - When movement ordered in follow mode or multi selected with other mercs. voice:Sidney]] "We'll pop right over."),
		T(550532181711, --[[VoiceResponse Sidney GroupOrder VoiceResponse GroupOrder - When movement ordered in follow mode or multi selected with other mercs. voice:Sidney]] "Come on, then."),
		T(264371388562, --[[VoiceResponse Sidney GroupOrder VoiceResponse GroupOrder - When movement ordered in follow mode or multi selected with other mercs. voice:Sidney]] "Right. Let's get a move on."),
		T(572587503067, --[[VoiceResponse Sidney GroupOrder VoiceResponse GroupOrder - When movement ordered in follow mode or multi selected with other mercs. voice:Sidney]] "Right-o!"),
		T(561193044577, --[[VoiceResponse Sidney GroupOrder VoiceResponse GroupOrder - When movement ordered in follow mode or multi selected with other mercs. voice:Sidney]] "Of course.")
	}),
	HealReceived = TConcat({
		T(634672267393, --[[VoiceResponse Sidney HealReceived VoiceResponse HealReceived - Bandaged by a merc or Metvirion used in Inventory voice:Sidney]] "Ah! Cheers, mate.")
	}),
	HealReceivedSatView = TConcat({
		T(755097534988, --[[VoiceResponse Sidney HealReceivedSatView VoiceResponse HealReceivedSatView - When a wound is removed by a Sector Operation. Uses HealReceived if blank. voice:Sidney]] "Feeling tip-top!")
	}),
	HeavilyWoundedSelection = TConcat({
		T(224902272227, --[[VoiceResponse Sidney HeavilyWoundedSelection VoiceResponse HeavilyWoundedSelection - Selected or autoselected with less than 20% health voice:Sidney]] "I wouldn't say no to a splash of gin to steady the nerves. ")
	}),
	HeavyBreathing = TConcat({
		T(677859046206, --[[VoiceResponse Sidney HeavyBreathing VoiceResponse HeavyBreathing - During physical exertion voice:Sidney]] "(heavy breath)"),
		T(773934313069, --[[VoiceResponse Sidney HeavyBreathing VoiceResponse HeavyBreathing - During physical exertion voice:Sidney]] "(heavy breath_2)")
	}),
	Idle = TConcat({
		T(575084446032, --[[VoiceResponse Sidney Idle VoiceResponse Idle - Play every 4 hours during which a squad has been inactive.. Played by any of the mercs in the squad. voice:Sidney]] "Free time is one thing I rarely get to enjoy.")
	}),
	InteractableFound = TConcat({
		T(494265198536, --[[VoiceResponse Sidney InteractableFound VoiceResponse InteractableFound - A custom interactable (quest related etc), herbs or salvage material found. voice:Sidney]] "What's this then?"),
		T(866645367935, --[[VoiceResponse Sidney InteractableFound VoiceResponse InteractableFound - A custom interactable (quest related etc), herbs or salvage material found. voice:Sidney]] "Well, what have we here?")
	}),
	InterestingSector = TConcat({
		T(404044934213, --[[VoiceResponse Sidney InterestingSector VoiceResponse InterestingSector - Reached a sector that is marked as interesting. There is somethingin there the player should explore. voice:Sidney]] "If our intel is worth anything, we should take a close look at this sector.")
	}),
	ItemDeteriorates = TConcat({
		T(194490804029, --[[VoiceResponse Sidney ItemDeteriorates VoiceResponse ItemDeteriorates - Played when a piece of equipment deteriotes to the point when it is in the Needs Repair condition voice:Sidney]] "Sorry. Not to be a bother, but I think my equipment could use a spot of maintenance.")
	}),
	ItemInPoorConditionEquipped = TConcat({
		T(498332785239, --[[VoiceResponse Sidney ItemInPoorConditionEquipped VoiceResponse ItemInPoorConditionEquipped - Played in Inventory when player equips weapon/armor that is in Poor Condition voice:Sidney]] "Quite all right. No trouble at all. Not like I was expecting something fresh from the factory.")
	}),
	Jumping = TConcat({
		T(810517767194, --[[VoiceResponse Sidney Jumping VoiceResponse Jumping - When jumping over small obstacles (e.g. puddles) voice:Sidney]] "(jumping over something)"),
		T(416265542244, --[[VoiceResponse Sidney Jumping VoiceResponse Jumping - When jumping over small obstacles (e.g. puddles) voice:Sidney]] "(jumping over something_2)")
	}),
	KillFriendlyFireBuddy1 = TConcat({
		T(705341058395, --[[VoiceResponse Sidney KillFriendlyFireBuddy1 VoiceResponse KillFriendlyFireBuddy1 - Played when a unit kills an ally with friendly fire and the dying unit is Liked - Scope. voice:Sidney]] "What a mess. She was truly a model woman and soldier. ")
	}),
	KillFriendlyFireGeneral = TConcat({
		T(740333946778, --[[VoiceResponse Sidney KillFriendlyFireGeneral VoiceResponse KillFriendlyFireGeneral - Played when a unit kills an ally with friendly fire and the dying unit is neither Liked nor Disliked voice:Sidney]] "Dreadfully sorry, old chap. Won't happen again.")
	}),
	LevelUp = TConcat({
		T(602121903178, --[[VoiceResponse Sidney LevelUp VoiceResponse LevelUp - Leveled up or a magazine is read. Only one played if multiple character level up. voice:Sidney]] "Delightful! Never pass up the chance for self-improvement!")
	}),
	LootFound = TConcat({
		T(894559985637, --[[VoiceResponse Sidney LootFound VoiceResponse LootFound - A loot container is nearby (e.g. dead body, crate,...) 10s cooldown voice:Sidney]] "Perhaps we should investigate that."),
		T(877634383801, --[[VoiceResponse Sidney LootFound VoiceResponse LootFound - A loot container is nearby (e.g. dead body, crate,...) 10s cooldown voice:Sidney]] "Might find something useful here."),
		T(830344330721, --[[VoiceResponse Sidney LootFound VoiceResponse LootFound - A loot container is nearby (e.g. dead body, crate,...) 10s cooldown voice:Sidney]] "Sorry, I think I spotted something.")
	}),
	LootOpened = TConcat({
		T(770937712163, --[[VoiceResponse Sidney LootOpened VoiceResponse LootOpened - Loot container opened. Supressed by ValuableItemFound voice:Sidney]] "Let's see what our friends have left behind.")
	}),
	LowChanceShot = TConcat({
		T(218260192349, --[[VoiceResponse Sidney LowChanceShot VoiceResponse LowChanceShot - Successful attack when the CtH is less than 20% voice:Sidney]] "Just proof that there's nothing a proper Englishman can't do.")
	}),
	ManyEnemiesSelection = TConcat({
		T(792940705804, --[[VoiceResponse Sidney ManyEnemiesSelection VoiceResponse ManyEnemiesSelection - Selected when the unit sees 5+ units in line of fire voice:Sidney]] "I say! That's quite a lot of hostiles.")
	}),
	MeleeEnemiesClosing = TConcat({
		T(614363300085, --[[VoiceResponse Sidney MeleeEnemiesClosing VoiceResponse MeleeEnemiesClosing - When enemy in melee range. Needs further clarification!!! voice:Sidney]] "This hooligan shall need to be taught a lesson.")
	}),
	MineFound = TConcat({
		T(773189416669, --[[VoiceResponse Sidney MineFound VoiceResponse MineFound - A mine (or other explosive trap) was found nearby voice:Sidney]] "Oh, bloody hell... got a live one here.")
	}),
	MineNearbySelection = TConcat({
		T(879651733994, --[[VoiceResponse Sidney MineNearbySelection VoiceResponse MineNearbySelection - Selected when there is a trap nearby voice:Sidney]] "That live trap is not good business.")
	}),
	MissHighChance = TConcat({
		T(998770084183, --[[VoiceResponse Sidney MissHighChance VoiceResponse MissHighChance - When a shot with 90%+ CtH was missed voice:Sidney]] "Well, that was a real cock up.")
	}),
	MissedByKillShot = TConcat({
		T(283244023778, --[[VoiceResponse Sidney MissedByKillShot VoiceResponse MissedByKillShot - When character missed a by a shot that would've killed him/her. Shot must have had 50%+ CtH. voice:Sidney]] "Well, that was a near run thing.")
	}),
	MockGeneral = TConcat({
		T(602036429064, --[[VoiceResponse Sidney MockGeneral VoiceResponse MockGeneral - 20% chance to play when another merc misses a high chance shot voice:Sidney]] "I say, would you like me to go out there and hold them still for you?")
	}),
	MockLike1 = TConcat({
		T(900827858732, --[[VoiceResponse Sidney MockLike1 VoiceResponse MockLike1 - Played on a high chance miss by Scope. voice:Sidney]] "Perhaps try pointing the gun at the enemy next time, love!")
	}),
	Negotiator = TConcat({
		T(874675532077, --[[VoiceResponse Sidney Negotiator VoiceResponse Negotiator - When an activity that is discounted by the Negotiator perk is started voice:Sidney]] "I say, can't we do this a tad cheaper? Looks like we can cut a few corners here and there."),
		T(834832124922, --[[VoiceResponse Sidney Negotiator VoiceResponse Negotiator - When an activity that is discounted by the Negotiator perk is started voice:Sidney]] "I believe there is a better way. ")
	}),
	NoAmmo = TConcat({
		T(747631297412, --[[VoiceResponse Sidney NoAmmo VoiceResponse NoAmmo - No more ammo in the gun and no more bullets. voice:Sidney]] "Looks like I'm out of ammo. Fisticuffs, is it then?")
	}),
	NotNow = TConcat({
		T(384490376696, --[[VoiceResponse Sidney NotNow VoiceResponse NotNow - When interacting with a NPC while in combat voice:Sidney]] "I'm afraid now is not the time to faff around.")
	}),
	OpponentFound = TConcat({
		T(247259995541, --[[VoiceResponse Sidney OpponentFound VoiceResponse OpponentFound - Enemy spotted. voice:Sidney]] "Enemy in sight."),
		T(384096049034, --[[VoiceResponse Sidney OpponentFound VoiceResponse OpponentFound - Enemy spotted. voice:Sidney]] "Hostile spotted.")
	}),
	OpponentKilled = TConcat({
		T(306187862102, --[[VoiceResponse Sidney OpponentKilled VoiceResponse OpponentKilled - When opponent killed (unless OponentKilledCrit or OponentKilled multi isplayed) voice:Sidney]] "That's one less rotter."),
		T(207356313053, --[[VoiceResponse Sidney OpponentKilled VoiceResponse OpponentKilled - When opponent killed (unless OponentKilledCrit or OponentKilled multi isplayed) voice:Sidney]] "That bloke's a goner."),
		T(266549170833, --[[VoiceResponse Sidney OpponentKilled VoiceResponse OpponentKilled - When opponent killed (unless OponentKilledCrit or OponentKilled multi isplayed) voice:Sidney]] "Enemy neutralized."),
		T(925073549623, --[[VoiceResponse Sidney OpponentKilled VoiceResponse OpponentKilled - When opponent killed (unless OponentKilledCrit or OponentKilled multi isplayed) voice:Sidney]] "Hostile removed."),
		T(561962154385, --[[VoiceResponse Sidney OpponentKilled VoiceResponse OpponentKilled - When opponent killed (unless OponentKilledCrit or OponentKilled multi isplayed) voice:Sidney]] "Target down.")
	}),
	OpponentKilledAnimal = TConcat({
		T(302389388191, --[[VoiceResponse Sidney OpponentKilledAnimal VoiceResponse OpponentKilledAnimal - When animal is killed voice:Sidney]] "Shame, but I couldn't chance the beast being rabid.")
	}),
	OpponentKilledHeadshot = TConcat({
		T(598490588186, --[[VoiceResponse Sidney OpponentKilledHeadshot VoiceResponse OpponentKilledHeadshot - Opponent killed with a headshot voice:Sidney]] "That's the trouble with these blokes. Can't keep their heads.")
	}),
	OpponentKilledMelee = TConcat({
		T(493574672192, --[[VoiceResponse Sidney OpponentKilledMelee VoiceResponse OpponentKilledMelee - Played when killing a unit with melee weapon voice:Sidney]] "Her Majesty's subjects are not to be trifled with.")
	}),
	OpponentKilledStealth = TConcat({
		T(957111097039, --[[VoiceResponse Sidney OpponentKilledStealth VoiceResponse OpponentKilledStealth - Played when a Stealth kill happens. Voice should be shushed (except Steroid) voice:Sidney]] "Dispatched that one quite cleanly, I must say.")
	}),
	Order = TConcat({
		T(572587503067, --[[VoiceResponse Sidney Order VoiceResponse Order - When movement ordered (out of combat) Should be very short (3-5 words) voice:Sidney]] "Right-o!"),
		T(561193044577, --[[VoiceResponse Sidney Order VoiceResponse Order - When movement ordered (out of combat) Should be very short (3-5 words) voice:Sidney]] "Of course."),
		T(754922120328, --[[VoiceResponse Sidney Order VoiceResponse Order - When movement ordered (out of combat) Should be very short (3-5 words) voice:Sidney]] "Brilliant."),
		T(311742924381, --[[VoiceResponse Sidney Order VoiceResponse Order - When movement ordered (out of combat) Should be very short (3-5 words) voice:Sidney]] "Yes, quite right."),
		T(141282443004, --[[VoiceResponse Sidney Order VoiceResponse Order - When movement ordered (out of combat) Should be very short (3-5 words) voice:Sidney]] "I'll pop right over, yes?")
	}),
	Outnumbered = TConcat({
		T(488017059981, --[[VoiceResponse Sidney Outnumbered VoiceResponse Outnumbered - Unit sees more enemies than allies voice:Sidney]] "I seem to be a bit outnumbered. Jolly good!")
	}),
	Overwatch = TConcat({
		T(165473145359, --[[VoiceResponse Sidney Overwatch VoiceResponse Overwatch - When setting overwatch voice:Sidney]] "Not to worry. I've got it covered.")
	}),
	OverwatchSelection = TConcat({
		T(391114948603, --[[VoiceResponse Sidney OverwatchSelection VoiceResponse OverwatchSelection - Selected when under Overwatch. voice:Sidney]] "Oh, drat! The enemy seems to have a fix on my position.")
	}),
	Pain = TConcat({
		T(875329782291, --[[VoiceResponse Sidney Pain VoiceResponse Pain - Hit by an attack (if surrounded SurroundedPain is played instead). Short. These are emotes - disregard the written text. voice:Sidney]] "Argh"),
		T(812619833192, --[[VoiceResponse Sidney Pain VoiceResponse Pain - Hit by an attack (if surrounded SurroundedPain is played instead). Short. These are emotes - disregard the written text. voice:Sidney]] "Mhh"),
		T(835458024509, --[[VoiceResponse Sidney Pain VoiceResponse Pain - Hit by an attack (if surrounded SurroundedPain is played instead). Short. These are emotes - disregard the written text. voice:Sidney]] "Ah"),
		T(980337462112, --[[VoiceResponse Sidney Pain VoiceResponse Pain - Hit by an attack (if surrounded SurroundedPain is played instead). Short. These are emotes - disregard the written text. voice:Sidney]] "Ouch"),
		T(629274583699, --[[VoiceResponse Sidney Pain VoiceResponse Pain - Hit by an attack (if surrounded SurroundedPain is played instead). Short. These are emotes - disregard the written text. voice:Sidney]] "Ugh"),
		T(924297008731, --[[VoiceResponse Sidney Pain VoiceResponse Pain - Hit by an attack (if surrounded SurroundedPain is played instead). Short. These are emotes - disregard the written text. voice:Sidney]] "Pain6")
	}),
	PinDown = TConcat({
		T(343380847258, --[[VoiceResponse Sidney PinDown VoiceResponse PinDown - When pinning down (sniper rifles only) voice:Sidney]] "Got this rotter pinned.")
	}),
	PraisesBuddy1 = TConcat({
		T(118870669927, --[[VoiceResponse Sidney PraisesBuddy1 VoiceResponse PraisesBuddy1 - Played on a successful kill by Scope. voice:Sidney]] "That Scope is the very model of a modern British woman!")
	}),
	PraisesFemale = TConcat({
		T(834349876023, --[[VoiceResponse Sidney PraisesFemale VoiceResponse PraisesFemale - Played when a female merc makes a kill (20% chance) voice:Sidney]] "I say, that young lady is a marvel!")
	}),
	PraisesMale = TConcat({
		T(480709551815, --[[VoiceResponse Sidney PraisesMale VoiceResponse PraisesMale - Played when a male merc makes a kill (20% chance) voice:Sidney]] "Well done, old chap!")
	}),
	SectorArrived = TConcat({
		T(392047478912, --[[VoiceResponse Sidney SectorArrived VoiceResponse SectorArrived - SatView - new sector reached. Played by random merc in squad. voice:Sidney]] "Sidney Nettleson, here. I've arrived. Do give me a ring.")
	}),
	Selection = TConcat({
		T(276067681071, --[[VoiceResponse Sidney Selection VoiceResponse Selection - when selected or autoselected voice:Sidney]] "Hmmm?"),
		T(787348353386, --[[VoiceResponse Sidney Selection VoiceResponse Selection - when selected or autoselected voice:Sidney]] "Sidney here."),
		T(519726152776, --[[VoiceResponse Sidney Selection VoiceResponse Selection - when selected or autoselected voice:Sidney]] "Yes? What is it?")
	}),
	SelectionStealth = TConcat({
		T(406192839074, --[[VoiceResponse Sidney SelectionStealth VoiceResponse SelectionStealth - when selected or autoselected voice:Sidney]] "There's a good chance I can do this quietly."),
		T(428874486085, --[[VoiceResponse Sidney SelectionStealth VoiceResponse SelectionStealth - when selected or autoselected voice:Sidney]] "Time to slink 'round them."),
		T(975220689745, --[[VoiceResponse Sidney SelectionStealth VoiceResponse SelectionStealth - when selected or autoselected voice:Sidney]] "Understood. Mum's the word.")
	}),
	SeriouslyWounded = TConcat({
		T(998266875213, --[[VoiceResponse Sidney SeriouslyWounded VoiceResponse SeriouslyWounded - Unit is seriously wounded (3 or more wounds) voice:Sidney]] "Keep calm and try not to die.")
	}),
	Startled = TConcat({
		T(363973731072, --[[VoiceResponse Sidney Startled VoiceResponse Startled - Startled by hearing a sudden noise voice:Sidney]] "Huh?"),
		T(263619526045, --[[VoiceResponse Sidney Startled VoiceResponse Startled - Startled by hearing a sudden noise voice:Sidney]] "Wha-?")
	}),
	SurroundedPain = TConcat({
		T(862560038077, --[[VoiceResponse Sidney SurroundedPain VoiceResponse SurroundedPain - hit by an attack when surrounded. Situation should be very dire voice:Sidney]] "Appears I'm in a bit of a pickle, eh what?")
	}),
	TacticalKilling = TConcat({
		T(641808870355, --[[VoiceResponse Sidney TacticalKilling VoiceResponse TacticalKilling - The team is winning the battle  (2+ units have been downed/killed) voice:Sidney]] "Well, that's a good sport.")
	}),
	TacticalPressing = TConcat({
		T(524865779588, --[[VoiceResponse Sidney TacticalPressing VoiceResponse TacticalPressing - The team is making gains during the battle (2+ wounds have been inflicted) voice:Sidney]] "This gets the blood flowing."),
		T(299525186723, --[[VoiceResponse Sidney TacticalPressing VoiceResponse TacticalPressing - The team is making gains during the battle (2+ wounds have been inflicted) voice:Sidney]] "Let's get stuck-in!")
	}),
	TakeCover = TConcat({
		T(208475540124, --[[VoiceResponse Sidney TakeCover VoiceResponse TakeCover - Played when the Take Cover action is used voice:Sidney]] "Taking cover!")
	}),
	ThreatSelection = TConcat({
		T(202321490845, --[[VoiceResponse Sidney ThreatSelection VoiceResponse ThreatSelection - Selected when under Pinned Down or in the area of an incoming explosion. voice:Sidney]] "I'm in a spot of bother. ")
	}),
	Tired = TConcat({
		T(661784189910, --[[VoiceResponse Sidney Tired VoiceResponse Tired - when the merc becomes tired voice:Sidney]] "My apologies, but I feel a bit shagged out.")
	}),
	Travelling = TConcat({
		T(988442829623, --[[VoiceResponse Sidney Travelling VoiceResponse Travelling - When a squad is travelling and enters new sector that is not the final destination of the travel. Played by the squad leader voice:Sidney]] "Onward, I say. Our destination is within reach.")
	}),
	ValuableItemFound = TConcat({
		T(427798041920, --[[VoiceResponse Sidney ValuableItemFound VoiceResponse ValuableItemFound - Loot container opened with a valuable item inside voice:Sidney]] "I daresay the lads at the bridge club should like to have a look at this.")
	}),
	WeaponBroken = TConcat({
		T(921975528986, --[[VoiceResponse Sidney WeaponBroken VoiceResponse WeaponBroken - When the player's weapon breaks voice:Sidney]] "Oh, bollocks! This simply won't do. I shall require another firearm.")
	}),
	WeaponJammed = TConcat({
		T(152721710472, --[[VoiceResponse Sidney WeaponJammed VoiceResponse WeaponJammed - When weapon has jammed voice:Sidney]] "Ah. Misfire. Not to worry. Have it cleared in a jiff.")
	}),
	Wounded = TConcat({
		T(487168287461, --[[VoiceResponse Sidney Wounded VoiceResponse Wounded - Unit is Wounded. (When the Wounded VR is played, the Pain VR should be suppressed.) voice:Sidney]] "Just a scratch."),
		T(971919185769, --[[VoiceResponse Sidney Wounded VoiceResponse Wounded - Unit is Wounded. (When the Wounded VR is played, the Pain VR should be suppressed.) voice:Sidney]] "Bloody rotter got a lucky hit."),
		T(599762584940, --[[VoiceResponse Sidney Wounded VoiceResponse Wounded - Unit is Wounded. (When the Wounded VR is played, the Pain VR should be suppressed.) voice:Sidney]] "It's fine. Perfect, even.")
	}),
	group = "MercenariesOld",
	id = "Sidney",
})

