-- ========== GENERATED BY VoiceResponse Editor (Ctrl-Alt-V) DO NOT EDIT MANUALLY! ==========

PlaceObj('VoiceResponse', {
	AIArchetypeAngry = TConcat({
		T(102301742817, --[[VoiceResponse ThugGunner AIArchetypeAngry VoiceResponse AIArchetypeAngry - Played when AI switches archetype and weapons because he is angry voice:ThugGunner]] "I'm pissed. Now you die!"),
		T(152923299771, --[[VoiceResponse ThugGunner AIArchetypeAngry VoiceResponse AIArchetypeAngry - Played when AI switches archetype and weapons because he is angry voice:ThugGunner]] "Now you'll see how we deal with your kind around here."),
		T(845362417595, --[[VoiceResponse ThugGunner AIArchetypeAngry VoiceResponse AIArchetypeAngry - Played when AI switches archetype and weapons because he is angry voice:ThugGunner]] "Think you're tough? I'll show you tough!")
	}),
	AIArchetypeScared = TConcat({
		T(900814455158, --[[VoiceResponse ThugGunner AIArchetypeScared VoiceResponse AIArchetypeScared - Played when AI switches archetype and weapons because he is scared voice:ThugGunner]] "Let's scram. "),
		T(726285973130, --[[VoiceResponse ThugGunner AIArchetypeScared VoiceResponse AIArchetypeScared - Played when AI switches archetype and weapons because he is scared voice:ThugGunner]] "Fuck. I need to take cover."),
		T(473105595864, --[[VoiceResponse ThugGunner AIArchetypeScared VoiceResponse AIArchetypeScared - Played when AI switches archetype and weapons because he is scared voice:ThugGunner]] "This isn't worth it. I gotta get out of here.")
	}),
	AIAttack = TConcat({
		T(136865579894, --[[VoiceResponse ThugGunner AIAttack VoiceResponse AIAttack - When attacking voice:ThugGunner]] "Get 'em!"),
		T(878205439714, --[[VoiceResponse ThugGunner AIAttack VoiceResponse AIAttack - When attacking voice:ThugGunner]] "Take that!"),
		T(408753920888, --[[VoiceResponse ThugGunner AIAttack VoiceResponse AIAttack - When attacking voice:ThugGunner]] "I don't like your face."),
		T(556356311385, --[[VoiceResponse ThugGunner AIAttack VoiceResponse AIAttack - When attacking voice:ThugGunner]] "Die!"),
		T(361746672558, --[[VoiceResponse ThugGunner AIAttack VoiceResponse AIAttack - When attacking voice:ThugGunner]] "MEURS!"),
		T(474150813371, --[[VoiceResponse ThugGunner AIAttack VoiceResponse AIAttack - When attacking voice:ThugGunner]] "Feed you to the fishes."),
		T(497823130378, --[[VoiceResponse ThugGunner AIAttack VoiceResponse AIAttack - When attacking voice:ThugGunner]] "PRENDS ÇA!"),
		T(629454265341, --[[VoiceResponse ThugGunner AIAttack VoiceResponse AIAttack - When attacking voice:ThugGunner]] "Je les ai!")
	}),
	AIAutofire = TConcat({
		T(414773379205, --[[VoiceResponse ThugGunner AIAutofire VoiceResponse AIAutofire - Enemy uses Autofire. Played during gunfire noises. voice:ThugGunner]] "Suppressive fire!"),
		T(705005445193, --[[VoiceResponse ThugGunner AIAutofire VoiceResponse AIAutofire - Enemy uses Autofire. Played during gunfire noises. voice:ThugGunner]] "Laying it on 'em!"),
		T(492636720568, --[[VoiceResponse ThugGunner AIAutofire VoiceResponse AIAutofire - Enemy uses Autofire. Played during gunfire noises. voice:ThugGunner]] "Tir de suppression!"),
		T(860838379843, --[[VoiceResponse ThugGunner AIAutofire VoiceResponse AIAutofire - Enemy uses Autofire. Played during gunfire noises. voice:ThugGunner]] "Je vous couvre!")
	}),
	AIBerserkerPerk = TConcat({
		T(110171102543, --[[VoiceResponse ThugGunner AIBerserkerPerk VoiceResponse AIBerserkerPerk - The AI berserker perk is activated voice:ThugGunner]] "I'm taking you all down. RIGHT NOW!"),
		T(645801846494, --[[VoiceResponse ThugGunner AIBerserkerPerk VoiceResponse AIBerserkerPerk - The AI berserker perk is activated voice:ThugGunner]] "I'LL KILL YOU!!!")
	}),
	AIDeadAlly = TConcat({
		T(954994485585, --[[VoiceResponse ThugGunner AIDeadAlly VoiceResponse AIDeadAlly - Played on dead human enemy ally voice:ThugGunner]] "You will pay! I swear, you will pay!"),
		T(153973238965, --[[VoiceResponse ThugGunner AIDeadAlly VoiceResponse AIDeadAlly - Played on dead human enemy ally voice:ThugGunner]] "You kill one of my friends, I kill you!"),
		T(226323821269, --[[VoiceResponse ThugGunner AIDeadAlly VoiceResponse AIDeadAlly - Played on dead human enemy ally voice:ThugGunner]] "This is not going well."),
		T(944355111272, --[[VoiceResponse ThugGunner AIDeadAlly VoiceResponse AIDeadAlly - Played on dead human enemy ally voice:ThugGunner]] "Never liked 'em anyway."),
		T(474119094709, --[[VoiceResponse ThugGunner AIDeadAlly VoiceResponse AIDeadAlly - Played on dead human enemy ally voice:ThugGunner]] "Ah, shit. That fucker owed me money.")
	}),
	AIDeadAnimal = TConcat({
		T(836334159717, --[[VoiceResponse ThugGunner AIDeadAnimal VoiceResponse AIDeadAnimal - Played on dead non human enemy ally voice:ThugGunner]] "Heyyyy, I kinda liked that little guy."),
		T(608299170127, --[[VoiceResponse ThugGunner AIDeadAnimal VoiceResponse AIDeadAnimal - Played on dead non human enemy ally voice:ThugGunner]] "I used to feed it every day. You will pay for this!"),
		T(388276802196, --[[VoiceResponse ThugGunner AIDeadAnimal VoiceResponse AIDeadAnimal - Played on dead non human enemy ally voice:ThugGunner]] "You shoot my animals on my turf? You're dead.")
	}),
	AIDeath = TConcat({
		T(103962405140, --[[VoiceResponse ThugGunner AIDeath VoiceResponse AIDeath - Enemy dies voice:ThugGunner]] "Agh Ugh!"),
		T(886454479972, --[[VoiceResponse ThugGunner AIDeath VoiceResponse AIDeath - Enemy dies voice:ThugGunner]] "Hagh Agh!"),
		T(765642069409, --[[VoiceResponse ThugGunner AIDeath VoiceResponse AIDeath - Enemy dies voice:ThugGunner]] "Aghagh..."),
		T(827107212757, --[[VoiceResponse ThugGunner AIDeath VoiceResponse AIDeath - Enemy dies voice:ThugGunner]] "Ahhh... ahhh"),
		T(697223685042, --[[VoiceResponse ThugGunner AIDeath VoiceResponse AIDeath - Enemy dies voice:ThugGunner]] "Uff"),
		T(378015539495, --[[VoiceResponse ThugGunner AIDeath VoiceResponse AIDeath - Enemy dies voice:ThugGunner]] "Aghhh..."),
		T(141934506385, --[[VoiceResponse ThugGunner AIDeath VoiceResponse AIDeath - Enemy dies voice:ThugGunner]] "cough"),
		T(433928749286, --[[VoiceResponse ThugGunner AIDeath VoiceResponse AIDeath - Enemy dies voice:ThugGunner]] "Ahhg"),
		T(349043685993, --[[VoiceResponse ThugGunner AIDeath VoiceResponse AIDeath - Enemy dies voice:ThugGunner]] "Ouch ah")
	}),
	AIDoubleBarrel = TConcat({
		T(484142328000, --[[VoiceResponse ThugGunner AIDoubleBarrel VoiceResponse AIDoubleBarrel - Enemy uses Double Barrel. Played during gunfire noises voice:ThugGunner]] "Take this!"),
		T(815144008649, --[[VoiceResponse ThugGunner AIDoubleBarrel VoiceResponse AIDoubleBarrel - Enemy uses Double Barrel. Played during gunfire noises voice:ThugGunner]] "Meet my sweet little girl!"),
		T(471837966846, --[[VoiceResponse ThugGunner AIDoubleBarrel VoiceResponse AIDoubleBarrel - Enemy uses Double Barrel. Played during gunfire noises voice:ThugGunner]] "Gonna blow you away, pal.")
	}),
	AIFlanked = TConcat({
		T(460623084123, --[[VoiceResponse ThugGunner AIFlanked VoiceResponse AIFlanked - Flanked and hit. voice:ThugGunner]] "They are all over me!"),
		T(778126410394, --[[VoiceResponse ThugGunner AIFlanked VoiceResponse AIFlanked - Flanked and hit. voice:ThugGunner]] "Help! I'm flanked!"),
		T(786111316981, --[[VoiceResponse ThugGunner AIFlanked VoiceResponse AIFlanked - Flanked and hit. voice:ThugGunner]] "I'm surrounded!")
	}),
	AIFlanking = TConcat({
		T(305002670586, --[[VoiceResponse ThugGunner AIFlanking VoiceResponse AIFlanking - Played when the AI is flanking an opponent voice:ThugGunner]] "Surround them!"),
		T(801923981366, --[[VoiceResponse ThugGunner AIFlanking VoiceResponse AIFlanking - Played when the AI is flanking an opponent voice:ThugGunner]] "Get around the side!"),
		T(731989775560, --[[VoiceResponse ThugGunner AIFlanking VoiceResponse AIFlanking - Played when the AI is flanking an opponent voice:ThugGunner]] "Encerclez-les!"),
		T(677596988214, --[[VoiceResponse ThugGunner AIFlanking VoiceResponse AIFlanking - Played when the AI is flanking an opponent voice:ThugGunner]] "Débordez-les !")
	}),
	AIGasAreaSelection = TConcat({
		T(320744711837, --[[VoiceResponse ThugGunner AIGasAreaSelection VoiceResponse AIGasAreaSelection - Unit receiving gas effect or starting round in one. Suffocating. Emote. voice:ThugGunner]] "(coughing)")
	}),
	AILoseCover = TConcat({
		T(341060527782, --[[VoiceResponse ThugGunner AILoseCover VoiceResponse AILoseCover - Unit in cover getting exposed voice:ThugGunner]] "This ain't good. I'm a sitting duck here!"),
		T(979458000009, --[[VoiceResponse ThugGunner AILoseCover VoiceResponse AILoseCover - Unit in cover getting exposed voice:ThugGunner]] "Damn, I'm out in the open.")
	}),
	AIMeleeOpportunist = TConcat({
		T(708364604779, --[[VoiceResponse ThugGunner AIMeleeOpportunist VoiceResponse AIMeleeOpportunist - In melee range voice:ThugGunner]] "Just you and me, cupcake."),
		T(867615459623, --[[VoiceResponse ThugGunner AIMeleeOpportunist VoiceResponse AIMeleeOpportunist - In melee range voice:ThugGunner]] "Oh, gonna have some fun with you."),
		T(526849374709, --[[VoiceResponse ThugGunner AIMeleeOpportunist VoiceResponse AIMeleeOpportunist - In melee range voice:ThugGunner]] "Now you're mine!"),
		T(664802245719, --[[VoiceResponse ThugGunner AIMeleeOpportunist VoiceResponse AIMeleeOpportunist - In melee range voice:ThugGunner]] "Je t’ai eu!"),
		T(806524230736, --[[VoiceResponse ThugGunner AIMeleeOpportunist VoiceResponse AIMeleeOpportunist - In melee range voice:ThugGunner]] "Maintenant, tu es à moi!")
	}),
	AIMobile = TConcat({
		T(943787089270, --[[VoiceResponse ThugGunner AIMobile VoiceResponse AIMobile - Enemy uses a mobile shot or run&gun voice:ThugGunner]] "Moving out! Cover me!"),
		T(426926511943, --[[VoiceResponse ThugGunner AIMobile VoiceResponse AIMobile - Enemy uses a mobile shot or run&gun voice:ThugGunner]] "Come on! Follow me!"),
		T(277941234385, --[[VoiceResponse ThugGunner AIMobile VoiceResponse AIMobile - Enemy uses a mobile shot or run&gun voice:ThugGunner]] "Let's get 'em, guys!")
	}),
	AIOverwatch = TConcat({
		T(689999216033, --[[VoiceResponse ThugGunner AIOverwatch VoiceResponse AIOverwatch - Enemy sets up overwatch voice:ThugGunner]] "Keeping an eye out."),
		T(460835581331, --[[VoiceResponse ThugGunner AIOverwatch VoiceResponse AIOverwatch - Enemy sets up overwatch voice:ThugGunner]] "I got a special present for ya."),
		T(798156714470, --[[VoiceResponse ThugGunner AIOverwatch VoiceResponse AIOverwatch - Enemy sets up overwatch voice:ThugGunner]] "Les voici! "),
		T(157248101195, --[[VoiceResponse ThugGunner AIOverwatch VoiceResponse AIOverwatch - Enemy sets up overwatch voice:ThugGunner]] "Vous voilà!")
	}),
	AIPinDown = TConcat({
		T(611624232694, --[[VoiceResponse ThugGunner AIPinDown VoiceResponse AIPinDown - Enemy uses PinDown voice:ThugGunner]] "One in the open!"),
		T(866228913366, --[[VoiceResponse ThugGunner AIPinDown VoiceResponse AIPinDown - Enemy uses PinDown voice:ThugGunner]] "Gonna keep this one busy."),
		T(580985957938, --[[VoiceResponse ThugGunner AIPinDown VoiceResponse AIPinDown - Enemy uses PinDown voice:ThugGunner]] "Cible repérée!")
	}),
	AIStartingTurnAttack = TConcat({
		T(718499907398, --[[VoiceResponse ThugGunner AIStartingTurnAttack VoiceResponse AIStartingTurnAttack - Will move and attack this turn voice:ThugGunner]] "Kill these bastards!"),
		T(233545344506, --[[VoiceResponse ThugGunner AIStartingTurnAttack VoiceResponse AIStartingTurnAttack - Will move and attack this turn voice:ThugGunner]] "Move! Shoot! Do something!"),
		T(324249514402, --[[VoiceResponse ThugGunner AIStartingTurnAttack VoiceResponse AIStartingTurnAttack - Will move and attack this turn voice:ThugGunner]] "Get them! The boss needs them dead. "),
		T(804771137052, --[[VoiceResponse ThugGunner AIStartingTurnAttack VoiceResponse AIStartingTurnAttack - Will move and attack this turn voice:ThugGunner]] "Spread Out!"),
		T(769068122973, --[[VoiceResponse ThugGunner AIStartingTurnAttack VoiceResponse AIStartingTurnAttack - Will move and attack this turn voice:ThugGunner]] "Split up!")
	}),
	AIStartingTurnLastEnemy = TConcat({
		T(380612627746, --[[VoiceResponse ThugGunner AIStartingTurnLastEnemy VoiceResponse AIStartingTurnLastEnemy - This is the last standing enemy voice:ThugGunner]] "I'm not dying here without a fight."),
		T(650985538864, --[[VoiceResponse ThugGunner AIStartingTurnLastEnemy VoiceResponse AIStartingTurnLastEnemy - This is the last standing enemy voice:ThugGunner]] "Shit! I'm the only one left."),
		T(679176101650, --[[VoiceResponse ThugGunner AIStartingTurnLastEnemy VoiceResponse AIStartingTurnLastEnemy - This is the last standing enemy voice:ThugGunner]] "The boss will hear of this and then you'll pay.")
	}),
	AIStartingTurnMoving = TConcat({
		T(335724478849, --[[VoiceResponse ThugGunner AIStartingTurnMoving VoiceResponse AIStartingTurnMoving - All enemy units will just move this turn. voice:ThugGunner]] "This is our turf. Protect it."),
		T(881028789728, --[[VoiceResponse ThugGunner AIStartingTurnMoving VoiceResponse AIStartingTurnMoving - All enemy units will just move this turn. voice:ThugGunner]] "Let's move out!"),
		T(231597251796, --[[VoiceResponse ThugGunner AIStartingTurnMoving VoiceResponse AIStartingTurnMoving - All enemy units will just move this turn. voice:ThugGunner]] "Don't just stand around! Move!"),
		T(347937335482, --[[VoiceResponse ThugGunner AIStartingTurnMoving VoiceResponse AIStartingTurnMoving - All enemy units will just move this turn. voice:ThugGunner]] "Get out of my ass and get moving!"),
		T(350048817482, --[[VoiceResponse ThugGunner AIStartingTurnMoving VoiceResponse AIStartingTurnMoving - All enemy units will just move this turn. voice:ThugGunner]] "Scatter!"),
		T(410465740871, --[[VoiceResponse ThugGunner AIStartingTurnMoving VoiceResponse AIStartingTurnMoving - All enemy units will just move this turn. voice:ThugGunner]] "Dispersez-vous!"),
		T(872193821647, --[[VoiceResponse ThugGunner AIStartingTurnMoving VoiceResponse AIStartingTurnMoving - All enemy units will just move this turn. voice:ThugGunner]] "Planquez-vous!")
	}),
	AITaunt = TConcat({
		T(966444552633, --[[VoiceResponse ThugGunner AITaunt VoiceResponse AITaunt - Played during the player's turn when the player has missed with 3 attacks. voice:ThugGunner]] "Blind Johnny shoots better than you."),
		T(198563425597, --[[VoiceResponse ThugGunner AITaunt VoiceResponse AITaunt - Played during the player's turn when the player has missed with 3 attacks. voice:ThugGunner]] "Is that all you got?"),
		T(192500483404, --[[VoiceResponse ThugGunner AITaunt VoiceResponse AITaunt - Played during the player's turn when the player has missed with 3 attacks. voice:ThugGunner]] "Hahahahahahaha!")
	}),
	AIThrowGrenade = TConcat({
		T(687584443936, --[[VoiceResponse ThugGunner AIThrowGrenade VoiceResponse AIThrowGrenade - Enemy throws grenade voice:ThugGunner]] "Fire in the hole!"),
		T(463293953111, --[[VoiceResponse ThugGunner AIThrowGrenade VoiceResponse AIThrowGrenade - Enemy throws grenade voice:ThugGunner]] "Grenade!"),
		T(562208581157, --[[VoiceResponse ThugGunner AIThrowGrenade VoiceResponse AIThrowGrenade - Enemy throws grenade voice:ThugGunner]] "Ça va chauffer! "),
		T(911347622332, --[[VoiceResponse ThugGunner AIThrowGrenade VoiceResponse AIThrowGrenade - Enemy throws grenade voice:ThugGunner]] "Here's a little something for ya!")
	}),
	BecomeAware = TConcat({
		T(129755768266, --[[VoiceResponse ThugGunner BecomeAware VoiceResponse BecomeAware - Becomes aware voice:ThugGunner]] "Huh? Who are these guys?"),
		T(973753654221, --[[VoiceResponse ThugGunner BecomeAware VoiceResponse BecomeAware - Becomes aware voice:ThugGunner]] "What are you doing here? Leave now or die."),
		T(293846496493, --[[VoiceResponse ThugGunner BecomeAware VoiceResponse BecomeAware - Becomes aware voice:ThugGunner]] "Looks like some chumps are coming around for a beating."),
		T(757041939010, --[[VoiceResponse ThugGunner BecomeAware VoiceResponse BecomeAware - Becomes aware voice:ThugGunner]] "What? Who are you?"),
		T(441608807674, --[[VoiceResponse ThugGunner BecomeAware VoiceResponse BecomeAware - Becomes aware voice:ThugGunner]] "What are you looking at?")
	}),
	Climbing = TConcat({
		T(612963070481, --[[VoiceResponse ThugGunner Climbing VoiceResponse Climbing - Emote. When unit is climbing over fences, on cliffs, etc. voice:ThugGunner]] "(climbing)"),
		T(861967175103, --[[VoiceResponse ThugGunner Climbing VoiceResponse Climbing - Emote. When unit is climbing over fences, on cliffs, etc. voice:ThugGunner]] "(climbing_2)")
	}),
	HeavyBreathing = TConcat({
		T(845875095091, --[[VoiceResponse ThugGunner HeavyBreathing VoiceResponse HeavyBreathing - During physical exertion voice:ThugGunner]] "(heavy breath)"),
		T(336336770655, --[[VoiceResponse ThugGunner HeavyBreathing VoiceResponse HeavyBreathing - During physical exertion voice:ThugGunner]] "(heavy breath_2)")
	}),
	Jumping = TConcat({
		T(448961706092, --[[VoiceResponse ThugGunner Jumping VoiceResponse Jumping - When jumping over small obstacles (e.g. puddles) voice:ThugGunner]] "(jumping over something)"),
		T(843048483744, --[[VoiceResponse ThugGunner Jumping VoiceResponse Jumping - When jumping over small obstacles (e.g. puddles) voice:ThugGunner]] "(jumping over something_2)")
	}),
	Pain = TConcat({
		T(584349934440, --[[VoiceResponse ThugGunner Pain VoiceResponse Pain - Hit by an attack (if surrounded SurroundedPain is played instead). Short. These are emotes - disregard the written text. voice:ThugGunner]] "Agh."),
		T(774753806652, --[[VoiceResponse ThugGunner Pain VoiceResponse Pain - Hit by an attack (if surrounded SurroundedPain is played instead). Short. These are emotes - disregard the written text. voice:ThugGunner]] "Ouch."),
		T(941174304190, --[[VoiceResponse ThugGunner Pain VoiceResponse Pain - Hit by an attack (if surrounded SurroundedPain is played instead). Short. These are emotes - disregard the written text. voice:ThugGunner]] "Ugh."),
		T(981674913441, --[[VoiceResponse ThugGunner Pain VoiceResponse Pain - Hit by an attack (if surrounded SurroundedPain is played instead). Short. These are emotes - disregard the written text. voice:ThugGunner]] "Pain4"),
		T(286496232244, --[[VoiceResponse ThugGunner Pain VoiceResponse Pain - Hit by an attack (if surrounded SurroundedPain is played instead). Short. These are emotes - disregard the written text. voice:ThugGunner]] "Pain5")
	}),
	Startled = TConcat({
		T(786783776733, --[[VoiceResponse ThugGunner Startled VoiceResponse Startled - Startled by hearing a sudden noise voice:ThugGunner]] "Huh?"),
		T(497998080439, --[[VoiceResponse ThugGunner Startled VoiceResponse Startled - Startled by hearing a sudden noise voice:ThugGunner]] "Wha-?")
	}),
	TacticalCareful = TConcat({
		T(299709437913, --[[VoiceResponse ThugGunner TacticalCareful VoiceResponse TacticalCareful - The other team is making gains during the battle (inflicted 2+ wounds during their turn) voice:ThugGunner]] "Who are these guys? They are good."),
		T(667151682136, --[[VoiceResponse ThugGunner TacticalCareful VoiceResponse TacticalCareful - The other team is making gains during the battle (inflicted 2+ wounds during their turn) voice:ThugGunner]] "How about you join us instead? I'm sure the boss will pay you better."),
		T(357914637770, --[[VoiceResponse ThugGunner TacticalCareful VoiceResponse TacticalCareful - The other team is making gains during the battle (inflicted 2+ wounds during their turn) voice:ThugGunner]] "These guys are tough, but we're tougher.")
	}),
	TacticalFocus = TConcat({
		T(901251096024, --[[VoiceResponse ThugGunner TacticalFocus VoiceResponse TacticalFocus - The team has missed  3+ times voice:ThugGunner]] "Guys, start shooting better. We can't be missing so much. "),
		T(364194183524, --[[VoiceResponse ThugGunner TacticalFocus VoiceResponse TacticalFocus - The team has missed  3+ times voice:ThugGunner]] "Somebody hit something, will ya?"),
		T(939873138759, --[[VoiceResponse ThugGunner TacticalFocus VoiceResponse TacticalFocus - The team has missed  3+ times voice:ThugGunner]] "We're not gonna scare them away by shooting in the air.")
	}),
	TacticalKilling = TConcat({
		T(913884261195, --[[VoiceResponse ThugGunner TacticalKilling VoiceResponse TacticalKilling - The team is winning the battle  (2+ units have been downed/killed) voice:ThugGunner]] "What a bunch of losers! Let's finish this."),
		T(187770797877, --[[VoiceResponse ThugGunner TacticalKilling VoiceResponse TacticalKilling - The team is winning the battle  (2+ units have been downed/killed) voice:ThugGunner]] "These guys are not so tough after all."),
		T(584754026442, --[[VoiceResponse ThugGunner TacticalKilling VoiceResponse TacticalKilling - The team is winning the battle  (2+ units have been downed/killed) voice:ThugGunner]] "Think the Boss is gonna like this.")
	}),
	TacticalLoss = TConcat({
		T(834445218355, --[[VoiceResponse ThugGunner TacticalLoss VoiceResponse TacticalLoss - The team is losing the battle (2+ units have been downed/killed) voice:ThugGunner]] "They are too good. Watch out!"),
		T(427697226329, --[[VoiceResponse ThugGunner TacticalLoss VoiceResponse TacticalLoss - The team is losing the battle (2+ units have been downed/killed) voice:ThugGunner]] "We are losing too many!"),
		T(693972700952, --[[VoiceResponse ThugGunner TacticalLoss VoiceResponse TacticalLoss - The team is losing the battle (2+ units have been downed/killed) voice:ThugGunner]] "They're clobbering us!")
	}),
	TacticalPressing = TConcat({
		T(511628089133, --[[VoiceResponse ThugGunner TacticalPressing VoiceResponse TacticalPressing - The team is making gains during the battle (2+ wounds have been inflicted) voice:ThugGunner]] "That's it. We are kicking their asses."),
		T(532666233481, --[[VoiceResponse ThugGunner TacticalPressing VoiceResponse TacticalPressing - The team is making gains during the battle (2+ wounds have been inflicted) voice:ThugGunner]] "Boss says rough you up, we rough you up."),
		T(325219763844, --[[VoiceResponse ThugGunner TacticalPressing VoiceResponse TacticalPressing - The team is making gains during the battle (2+ wounds have been inflicted) voice:ThugGunner]] "Bet you're sorry you messed with us.")
	}),
	TacticalRevenge = TConcat({
		T(840194381877, --[[VoiceResponse ThugGunner TacticalRevenge VoiceResponse TacticalRevenge - A unit from the team has been downed/killed voice:ThugGunner]] "That's it. Time for revenge."),
		T(224968614168, --[[VoiceResponse ThugGunner TacticalRevenge VoiceResponse TacticalRevenge - A unit from the team has been downed/killed voice:ThugGunner]] "You killed my buddy. You're gonna pay."),
		T(512946279852, --[[VoiceResponse ThugGunner TacticalRevenge VoiceResponse TacticalRevenge - A unit from the team has been downed/killed voice:ThugGunner]] "We lost a guy. It's personal now.")
	}),
	TacticalTaunt = TConcat({
		T(672907775055, --[[VoiceResponse ThugGunner TacticalTaunt VoiceResponse TacticalTaunt - The team has visible enemies from the other team and is shouting things at them voice:ThugGunner]] "You have no place being on our turf. "),
		T(516003328193, --[[VoiceResponse ThugGunner TacticalTaunt VoiceResponse TacticalTaunt - The team has visible enemies from the other team and is shouting things at them voice:ThugGunner]] "Gonna make you bleed, mercs."),
		T(164935728161, --[[VoiceResponse ThugGunner TacticalTaunt VoiceResponse TacticalTaunt - The team has visible enemies from the other team and is shouting things at them voice:ThugGunner]] "You know too much. Now you gotta die."),
		T(452934983320, --[[VoiceResponse ThugGunner TacticalTaunt VoiceResponse TacticalTaunt - The team has visible enemies from the other team and is shouting things at them voice:ThugGunner]] "You want a piece of me?")
	}),
	TakeCover = TConcat({
		T(466408539963, --[[VoiceResponse ThugGunner TakeCover VoiceResponse TakeCover - Played when the Take Cover action is used voice:ThugGunner]] "Tucking in!")
	}),
	Wounded = TConcat({
		T(519471425626, --[[VoiceResponse ThugGunner Wounded VoiceResponse Wounded - Unit is Wounded. (When the Wounded VR is played, the Pain VR should be suppressed.) voice:ThugGunner]] "Je suis blessé!"),
		T(854677147561, --[[VoiceResponse ThugGunner Wounded VoiceResponse Wounded - Unit is Wounded. (When the Wounded VR is played, the Pain VR should be suppressed.) voice:ThugGunner]] "Uff, that hurt!"),
		T(804990347005, --[[VoiceResponse ThugGunner Wounded VoiceResponse Wounded - Unit is Wounded. (When the Wounded VR is played, the Pain VR should be suppressed.) voice:ThugGunner]] "Fuck!"),
		T(664112701908, --[[VoiceResponse ThugGunner Wounded VoiceResponse Wounded - Unit is Wounded. (When the Wounded VR is played, the Pain VR should be suppressed.) voice:ThugGunner]] "Gonna need a bandage."),
		T(249946498790, --[[VoiceResponse ThugGunner Wounded VoiceResponse Wounded - Unit is Wounded. (When the Wounded VR is played, the Pain VR should be suppressed.) voice:ThugGunner]] "Je suis grièvement blessé!"),
		T(272064397771, --[[VoiceResponse ThugGunner Wounded VoiceResponse Wounded - Unit is Wounded. (When the Wounded VR is played, the Pain VR should be suppressed.) voice:ThugGunner]] "Damn, that hurts!"),
		T(653492018618, --[[VoiceResponse ThugGunner Wounded VoiceResponse Wounded - Unit is Wounded. (When the Wounded VR is played, the Pain VR should be suppressed.) voice:ThugGunner]] "Uff, Ça fait mal!"),
		T(290694676633, --[[VoiceResponse ThugGunner Wounded VoiceResponse Wounded - Unit is Wounded. (When the Wounded VR is played, the Pain VR should be suppressed.) voice:ThugGunner]] "Putain!")
	}),
	group = "Enemies",
	id = "ThugGunner",
})

