-- ========== GENERATED BY ImpQuestionDef Editor DO NOT EDIT MANUALLY! ==========

PlaceObj('ImpQuestionDef', {
	SortKey = 1,
	answers = {
		PlaceObj('ImpAnswer', {
			'answer', T(304358936790, --[[ImpQuestionDef Question1 answer]] "The dojo. You are teaching the yellow belts humility."),
			'stats_changes', {
				PlaceObj('ImpStatChange', {
					'stat', "Health",
					'change', 5,
				}),
				PlaceObj('ImpStatChange', {
					'stat', "Agility",
					'change', 5,
				}),
				PlaceObj('ImpStatChange', {
					'stat', "Dexterity",
					'change', 5,
				}),
				PlaceObj('ImpStatChange', {
					'stat', "Strength",
					'change', 10,
				}),
			},
			'perk_changes', {
				PlaceObj('ImpPerkChange', {
					'perk', "MeleeTraining",
					'change', 10,
				}),
				PlaceObj('ImpPerkChange', {
					'perk', "Teacher",
					'change', 5,
				}),
			},
		}),
		PlaceObj('ImpAnswer', {
			'answer', T(793113087364, --[[ImpQuestionDef Question1 answer]] "The beach. You are attaching a minigun and armor plates to your favorite motor boat."),
			'stats_changes', {
				PlaceObj('ImpStatChange', {
					'stat', "Marksmanship",
					'change', 5,
				}),
				PlaceObj('ImpStatChange', {
					'stat', "Mechanical",
					'change', 15,
				}),
			},
			'perk_changes', {
				PlaceObj('ImpPerkChange', {
					'perk', "Psycho",
					'change', 5,
				}),
				PlaceObj('ImpPerkChange', {
					'perk', "AutoWeapons",
					'change', 5,
				}),
				PlaceObj('ImpPerkChange', {
					'perk', "HeavyWeaponsTraining",
					'change', 5,
				}),
				PlaceObj('ImpPerkChange', {
					'perk', "MrFixit",
					'change', 5,
				}),
			},
		}),
		PlaceObj('ImpAnswer', {
			'answer', T(624823331959, --[[ImpQuestionDef Question1 answer]] "The shooting range. You are drawing obscene pictures on the targets with bullet holes."),
			'stats_changes', {
				PlaceObj('ImpStatChange', {
					'stat', "Dexterity",
					'change', 10,
				}),
				PlaceObj('ImpStatChange', {
					'stat', "Marksmanship",
					'change', 15,
				}),
			},
			'perk_changes', {
				PlaceObj('ImpPerkChange', {
					'perk', "Scoundrel",
					'change', 5,
				}),
				PlaceObj('ImpPerkChange', {
					'perk', "CQCTraining",
					'change', 10,
				}),
			},
		}),
		PlaceObj('ImpAnswer', {
			'answer', T(981509961395, --[[ImpQuestionDef Question1 answer]] "The office. You are helping your secretary who somehow got stuck in the weapons cabinet. Again."),
			'stats_changes', {
				PlaceObj('ImpStatChange', {
					'stat', "Leadership",
					'change', 10,
				}),
				PlaceObj('ImpStatChange', {
					'stat', "Medical",
					'change', 5,
				}),
			},
			'perk_changes', {
				PlaceObj('ImpPerkChange', {
					'perk', "Negotiator",
					'change', 15,
				}),
				PlaceObj('ImpPerkChange', {
					'perk', "MrFixit",
					'change', 10,
				}),
			},
		}),
	},
	group = "Default",
	id = "Question1",
	question = T(601201759682, --[[ImpQuestionDef Question1 question]] "It's a sunny day. You are enjoying a rest from mercenary work and are at your favorite place, which is..."),
})

PlaceObj('ImpQuestionDef', {
	SortKey = 2,
	answers = {
		PlaceObj('ImpAnswer', {
			'answer', T(280912840904, --[[ImpQuestionDef Question2 answer]] "You and your team destroyed a terrorist camp. It wasn't an actual assignment - you just needed to use the bathroom."),
			'stats_changes', {
				PlaceObj('ImpStatChange', {
					'stat', "Leadership",
					'change', 10,
				}),
				PlaceObj('ImpStatChange', {
					'stat', "Explosives",
					'change', 5,
				}),
			},
			'perk_changes', {
				PlaceObj('ImpPerkChange', {
					'perk', "Stealthy",
					'change', 5,
				}),
				PlaceObj('ImpPerkChange', {
					'perk', "Throwing",
					'change', 10,
				}),
				PlaceObj('ImpPerkChange', {
					'perk', "AutoWeapons",
					'change', 5,
				}),
				PlaceObj('ImpPerkChange', {
					'perk', "HeavyWeaponsTraining",
					'change', 5,
				}),
			},
		}),
		PlaceObj('ImpAnswer', {
			'answer', T(294834778838, --[[ImpQuestionDef Question2 answer]] "You infiltrated a secret military complex in North Korea dressed as a little girl, killing three bad guys with a bobby pin and a teddy bear."),
			'stats_changes', {
				PlaceObj('ImpStatChange', {
					'stat', "Agility",
					'change', 5,
				}),
				PlaceObj('ImpStatChange', {
					'stat', "Dexterity",
					'change', 5,
				}),
			},
			'perk_changes', {
				PlaceObj('ImpPerkChange', {
					'perk', "Scoundrel",
					'change', 5,
				}),
				PlaceObj('ImpPerkChange', {
					'perk', "Stealthy",
					'change', 10,
				}),
				PlaceObj('ImpPerkChange', {
					'perk', "NightOps",
					'change', 5,
				}),
				PlaceObj('ImpPerkChange', {
					'perk', "MrFixit",
					'change', 10,
				}),
			},
		}),
		PlaceObj('ImpAnswer', {
			'answer', T(269396281074, --[[ImpQuestionDef Question2 answer]] "You sniped three enemies before the first body hit the ground. One of them was piloting a helicopter."),
			'stats_changes', {
				PlaceObj('ImpStatChange', {
					'stat', "Agility",
					'change', 10,
				}),
				PlaceObj('ImpStatChange', {
					'stat', "Dexterity",
					'change', 15,
				}),
				PlaceObj('ImpStatChange', {
					'stat', "Marksmanship",
					'change', 15,
				}),
			},
			'perk_changes', {
				PlaceObj('ImpPerkChange', {
					'perk', "NightOps",
					'change', 5,
				}),
			},
		}),
		PlaceObj('ImpAnswer', {
			'answer', T(396571894474, --[[ImpQuestionDef Question2 answer]] "You got drunk the night before the mission even started, and eliminated the bad guys all by yourself. When the team arrived, they found you snoring amidst the corpses."),
			'stats_changes', {
				PlaceObj('ImpStatChange', {
					'stat', "Health",
					'change', 5,
				}),
				PlaceObj('ImpStatChange', {
					'stat', "Strength",
					'change', 5,
				}),
			},
			'perk_changes', {
				PlaceObj('ImpPerkChange', {
					'perk', "Psycho",
					'change', 10,
				}),
				PlaceObj('ImpPerkChange', {
					'perk', "NightOps",
					'change', 15,
				}),
				PlaceObj('ImpPerkChange', {
					'perk', "HeavyWeaponsTraining",
					'change', 5,
				}),
			},
		}),
	},
	group = "Default",
	id = "Question2",
	question = T(857683948964, --[[ImpQuestionDef Question2 question]] "You finished your previous assignment six months ago, when..."),
})

PlaceObj('ImpQuestionDef', {
	SortKey = 3,
	answers = {
		PlaceObj('ImpAnswer', {
			'answer', T(327515619458, --[[ImpQuestionDef Question3 answer]] "Nothing spectacular - cars exploding, buildings demolished, a satellite falling down from low orbit... Just the usual amount of indiscriminate justice."),
			'stats_changes', {
				PlaceObj('ImpStatChange', {
					'stat', "Health",
					'change', 10,
				}),
				PlaceObj('ImpStatChange', {
					'stat', "Explosives",
					'change', 10,
				}),
			},
			'perk_changes', {
				PlaceObj('ImpPerkChange', {
					'perk', "Throwing",
					'change', 10,
				}),
				PlaceObj('ImpPerkChange', {
					'perk', "HeavyWeaponsTraining",
					'change', 10,
				}),
			},
		}),
		PlaceObj('ImpAnswer', {
			'answer', T(487320801852, --[[ImpQuestionDef Question3 answer]] "You hunted down all of your enemies, the friends of your enemies, and the enemies of your friends - but then the enemies of your enemies turned against you!"),
			'stats_changes', {
				PlaceObj('ImpStatChange', {
					'stat', "Health",
					'change', 5,
				}),
				PlaceObj('ImpStatChange', {
					'stat', "Agility",
					'change', 10,
				}),
				PlaceObj('ImpStatChange', {
					'stat', "Wisdom",
					'change', 5,
				}),
			},
			'perk_changes', {
				PlaceObj('ImpPerkChange', {
					'perk', "Psycho",
					'change', 5,
				}),
				PlaceObj('ImpPerkChange', {
					'perk', "MeleeTraining",
					'change', 5,
				}),
				PlaceObj('ImpPerkChange', {
					'perk', "Stealthy",
					'change', 5,
				}),
				PlaceObj('ImpPerkChange', {
					'perk', "NightOps",
					'change', 5,
				}),
			},
		}),
		PlaceObj('ImpAnswer', {
			'answer', T(199586374926, --[[ImpQuestionDef Question3 answer]] "Your favorite jeep got a scratch. Those responsible screamed for hours."),
			'stats_changes', {
				PlaceObj('ImpStatChange', {
					'stat', "Strength",
					'change', 5,
				}),
				PlaceObj('ImpStatChange', {
					'stat', "Mechanical",
					'change', 15,
				}),
			},
			'perk_changes', {
				PlaceObj('ImpPerkChange', {
					'perk', "Psycho",
					'change', 10,
				}),
				PlaceObj('ImpPerkChange', {
					'perk', "MrFixit",
					'change', 10,
				}),
			},
		}),
		PlaceObj('ImpAnswer', {
			'answer', T(838912736274, --[[ImpQuestionDef Question3 answer]] "You made the mistake of sparing some of the bad guys, tending to their wounds and sending them to jail - only to discover that they later escaped."),
			'stats_changes', {
				PlaceObj('ImpStatChange', {
					'stat', "Wisdom",
					'change', 10,
				}),
				PlaceObj('ImpStatChange', {
					'stat', "Medical",
					'change', 15,
				}),
			},
			'perk_changes', {
				PlaceObj('ImpPerkChange', {
					'perk', "Negotiator",
					'change', 10,
				}),
				PlaceObj('ImpPerkChange', {
					'perk', "Teacher",
					'change', 5,
				}),
			},
		}),
	},
	group = "Default",
	id = "Question3",
	question = T(869805955317, --[[ImpQuestionDef Question3 question]] "Yet you made some new enemies with that mission. What happened?"),
})

PlaceObj('ImpQuestionDef', {
	SortKey = 4,
	answers = {
		PlaceObj('ImpAnswer', {
			'answer', T(512874192288, --[[ImpQuestionDef Question4 answer]] "You're furious. You jump in your car and drive like hell. So they have the location of your home? You have homing missiles for them."),
			'stats_changes', {
				PlaceObj('ImpStatChange', {
					'stat', "Agility",
					'change', 5,
				}),
				PlaceObj('ImpStatChange', {
					'stat', "Strength",
					'change', 5,
				}),
				PlaceObj('ImpStatChange', {
					'stat', "Mechanical",
					'change', 15,
				}),
			},
			'perk_changes', {
				PlaceObj('ImpPerkChange', {
					'perk', "Psycho",
					'change', 5,
				}),
				PlaceObj('ImpPerkChange', {
					'perk', "HeavyWeaponsTraining",
					'change', 10,
				}),
			},
		}),
		PlaceObj('ImpAnswer', {
			'answer', T(373253549946, --[[ImpQuestionDef Question4 answer]] "You are worried. Random bad guys invading your home are bad for your dogs' diets!"),
			'stats_changes', {
				PlaceObj('ImpStatChange', {
					'stat', "Health",
					'change', 10,
				}),
				PlaceObj('ImpStatChange', {
					'stat', "Leadership",
					'change', 10,
				}),
				PlaceObj('ImpStatChange', {
					'stat', "Explosives",
					'change', 5,
				}),
			},
			'perk_changes', {
				PlaceObj('ImpPerkChange', {
					'perk', "Negotiator",
					'change', 5,
				}),
				PlaceObj('ImpPerkChange', {
					'perk', "Teacher",
					'change', 10,
				}),
			},
		}),
		PlaceObj('ImpAnswer', {
			'answer', T(386627070373, --[[ImpQuestionDef Question4 answer]] "You are annoyed. When the landmines in your yard go off, the body parts will land on your neighbor's lawn and you'll never hear the end of it!"),
			'stats_changes', {
				PlaceObj('ImpStatChange', {
					'stat', "Health",
					'change', 5,
				}),
				PlaceObj('ImpStatChange', {
					'stat', "Explosives",
					'change', 15,
				}),
			},
			'perk_changes', {
				PlaceObj('ImpPerkChange', {
					'perk', "Psycho",
					'change', 10,
				}),
				PlaceObj('ImpPerkChange', {
					'perk', "Throwing",
					'change', 5,
				}),
				PlaceObj('ImpPerkChange', {
					'perk', "HeavyWeaponsTraining",
					'change', 5,
				}),
			},
		}),
		PlaceObj('ImpAnswer', {
			'answer', T(318167894050, --[[ImpQuestionDef Question4 answer]] "You don't care. That's just a dummy location and not your real place. But now you know where THEY are."),
			'stats_changes', {
				PlaceObj('ImpStatChange', {
					'stat', "Wisdom",
					'change', 5,
				}),
			},
			'perk_changes', {
				PlaceObj('ImpPerkChange', {
					'perk', "Scoundrel",
					'change', 10,
				}),
				PlaceObj('ImpPerkChange', {
					'perk', "Stealthy",
					'change', 15,
				}),
				PlaceObj('ImpPerkChange', {
					'perk', "NightOps",
					'change', 5,
				}),
				PlaceObj('ImpPerkChange', {
					'perk', "MrFixit",
					'change', 5,
				}),
			},
		}),
	},
	group = "Default",
	id = "Question4",
	question = T(697843725789, --[[ImpQuestionDef Question4 question]] 'Suddenly, your pager bleeps about a new email from "udienow@hackmail.com". You raise an eyebrow, open your OutBook and read this: "U WILL PAY FOR YOUR TRANSGRESSIONS! WE KNOW WHERE U LIVE!!!1!". There is a photo of your front porch attached.\nHow much are you concerned?'),
})

PlaceObj('ImpQuestionDef', {
	SortKey = 5,
	answers = {
		PlaceObj('ImpAnswer', {
			'answer', T(709290762895, --[[ImpQuestionDef Question5 answer]] '"Sure. Wanna buy some?"'),
			'stats_changes', {
				PlaceObj('ImpStatChange', {
					'stat', "Medical",
					'change', 5,
				}),
			},
			'perk_changes', {
				PlaceObj('ImpPerkChange', {
					'perk', "Negotiator",
					'change', 5,
				}),
				PlaceObj('ImpPerkChange', {
					'perk', "Scoundrel",
					'change', 10,
				}),
				PlaceObj('ImpPerkChange', {
					'perk', "Stealthy",
					'change', 10,
				}),
				PlaceObj('ImpPerkChange', {
					'perk', "NightOps",
					'change', 10,
				}),
			},
		}),
		PlaceObj('ImpAnswer', {
			'answer', T(555134068352, --[[ImpQuestionDef Question5 answer]] '"About time! You\'re here with the detonators, right? Sorry, I didn\'t recognize you. There seems to be a lot of turnover in your job."'),
			'stats_changes', {
				PlaceObj('ImpStatChange', {
					'stat', "Explosives",
					'change', 10,
				}),
			},
			'perk_changes', {
				PlaceObj('ImpPerkChange', {
					'perk', "Negotiator",
					'change', 10,
				}),
				PlaceObj('ImpPerkChange', {
					'perk', "Scoundrel",
					'change', 5,
				}),
				PlaceObj('ImpPerkChange', {
					'perk', "Throwing",
					'change', 5,
				}),
				PlaceObj('ImpPerkChange', {
					'perk', "MrFixit",
					'change', 10,
				}),
			},
		}),
		PlaceObj('ImpAnswer', {
			'answer', T(435882983828, --[[ImpQuestionDef Question5 answer]] '"My mom always told me not to take stuff from strangers. So let me introduce myself before I take all of your stuff..."'),
			'stats_changes', {
				PlaceObj('ImpStatChange', {
					'stat', "Health",
					'change', 10,
				}),
				PlaceObj('ImpStatChange', {
					'stat', "Strength",
					'change', 15,
				}),
			},
			'perk_changes', {
				PlaceObj('ImpPerkChange', {
					'perk', "Psycho",
					'change', 5,
				}),
				PlaceObj('ImpPerkChange', {
					'perk', "MeleeTraining",
					'change', 10,
				}),
			},
		}),
		PlaceObj('ImpAnswer', {
			'answer', T(790544974927, --[[ImpQuestionDef Question5 answer]] '"I\'ve got no time for this. Step aside, or I\'ll open a new hole or two in your ass."'),
			'stats_changes', {
				PlaceObj('ImpStatChange', {
					'stat', "Health",
					'change', 5,
				}),
				PlaceObj('ImpStatChange', {
					'stat', "Marksmanship",
					'change', 10,
				}),
			},
			'perk_changes', {
				PlaceObj('ImpPerkChange', {
					'perk', "Teacher",
					'change', 5,
				}),
				PlaceObj('ImpPerkChange', {
					'perk', "AutoWeapons",
					'change', 10,
				}),
				PlaceObj('ImpPerkChange', {
					'perk', "CQCTraining",
					'change', 10,
				}),
			},
		}),
	},
	group = "Default",
	id = "Question5",
	question = T(402775694453, --[[ImpQuestionDef Question5 question]] 'You are almost home when a stranger in a trench coat appears and stands in your way. "Psst, hey, what do ya\' say \'bout some good stuff?"\nWhat is your response?'),
})

PlaceObj('ImpQuestionDef', {
	SortKey = 6,
	answers = {
		PlaceObj('ImpAnswer', {
			'answer', T(780650256000, --[[ImpQuestionDef Question6 answer]] "You show him your favorite hobby - limb origami."),
			'stats_changes', {
				PlaceObj('ImpStatChange', {
					'stat', "Health",
					'change', 5,
				}),
				PlaceObj('ImpStatChange', {
					'stat', "Agility",
					'change', 10,
				}),
				PlaceObj('ImpStatChange', {
					'stat', "Strength",
					'change', 10,
				}),
			},
			'perk_changes', {
				PlaceObj('ImpPerkChange', {
					'perk', "MeleeTraining",
					'change', 15,
				}),
			},
		}),
		PlaceObj('ImpAnswer', {
			'answer', T(230121349025, --[[ImpQuestionDef Question6 answer]] "Where there was a knife in his hand, now there is a hole. Pfft. There's always some dimwit who brings a knife to a gun fight."),
			'stats_changes', {
				PlaceObj('ImpStatChange', {
					'stat', "Dexterity",
					'change', 5,
				}),
				PlaceObj('ImpStatChange', {
					'stat', "Marksmanship",
					'change', 10,
				}),
			},
			'perk_changes', {
				PlaceObj('ImpPerkChange', {
					'perk', "AutoWeapons",
					'change', 10,
				}),
				PlaceObj('ImpPerkChange', {
					'perk', "CQCTraining",
					'change', 15,
				}),
			},
		}),
		PlaceObj('ImpAnswer', {
			'answer', T(498476604373, --[[ImpQuestionDef Question6 answer]] "You almost drop your grenade laughing."),
			'stats_changes', {
				PlaceObj('ImpStatChange', {
					'stat', "Explosives",
					'change', 15,
				}),
			},
			'perk_changes', {
				PlaceObj('ImpPerkChange', {
					'perk', "Psycho",
					'change', 5,
				}),
				PlaceObj('ImpPerkChange', {
					'perk', "Throwing",
					'change', 10,
				}),
				PlaceObj('ImpPerkChange', {
					'perk', "HeavyWeaponsTraining",
					'change', 10,
				}),
			},
		}),
		PlaceObj('ImpAnswer', {
			'answer', T(393583271358, --[[ImpQuestionDef Question6 answer]] "You open your medical bag and introduce him to the novel concept of reverse first aid."),
			'stats_changes', {
				PlaceObj('ImpStatChange', {
					'stat', "Dexterity",
					'change', 10,
				}),
				PlaceObj('ImpStatChange', {
					'stat', "Wisdom",
					'change', 5,
				}),
				PlaceObj('ImpStatChange', {
					'stat', "Medical",
					'change', 15,
				}),
			},
			'perk_changes', {
				PlaceObj('ImpPerkChange', {
					'perk', "Stealthy",
					'change', 5,
				}),
				PlaceObj('ImpPerkChange', {
					'perk', "Throwing",
					'change', 5,
				}),
			},
		}),
	},
	group = "Default",
	id = "Question6",
	question = T(622599467549, --[[ImpQuestionDef Question6 question]] 'With a flash of steel, the stranger pulls a knife from his coat. "Hands up, merc. You walked right into our trap".'),
})

PlaceObj('ImpQuestionDef', {
	SortKey = 7,
	answers = {
		PlaceObj('ImpAnswer', {
			'answer', T(864060862472, --[[ImpQuestionDef Question7 answer]] "You kill him. Not that you needed his permission, but it feels better with it."),
			'stats_changes', {
				PlaceObj('ImpStatChange', {
					'stat', "Leadership",
					'change', 5,
				}),
			},
			'perk_changes', {
				PlaceObj('ImpPerkChange', {
					'perk', "Psycho",
					'change', 5,
				}),
				PlaceObj('ImpPerkChange', {
					'perk', "Teacher",
					'change', 5,
				}),
				PlaceObj('ImpPerkChange', {
					'perk', "Throwing",
					'change', 5,
				}),
				PlaceObj('ImpPerkChange', {
					'perk', "AutoWeapons",
					'change', 5,
				}),
				PlaceObj('ImpPerkChange', {
					'perk', "HeavyWeaponsTraining",
					'change', 5,
				}),
				PlaceObj('ImpPerkChange', {
					'perk', "CQCTraining",
					'change', 10,
				}),
			},
		}),
		PlaceObj('ImpAnswer', {
			'answer', T(284763867811, --[[ImpQuestionDef Question7 answer]] "You don't find death threats to be funny, so you smash his face with your fist. \"NO, THTOP! THITH HURTH!\" sounds so much funnier."),
			'stats_changes', {
				PlaceObj('ImpStatChange', {
					'stat', "Health",
					'change', 5,
				}),
				PlaceObj('ImpStatChange', {
					'stat', "Strength",
					'change', 10,
				}),
			},
			'perk_changes', {
				PlaceObj('ImpPerkChange', {
					'perk', "Psycho",
					'change', 10,
				}),
				PlaceObj('ImpPerkChange', {
					'perk', "Scoundrel",
					'change', 5,
				}),
				PlaceObj('ImpPerkChange', {
					'perk', "MeleeTraining",
					'change', 10,
				}),
			},
		}),
		PlaceObj('ImpAnswer', {
			'answer', T(229739583015, --[[ImpQuestionDef Question7 answer]] "You handcuff him, attach a timed explosive to his belt, and tell him HE is dead already and doesn't know it yet, but he's about to!"),
			'stats_changes', {
				PlaceObj('ImpStatChange', {
					'stat', "Dexterity",
					'change', 10,
				}),
				PlaceObj('ImpStatChange', {
					'stat', "Explosives",
					'change', 10,
				}),
			},
			'perk_changes', {
				PlaceObj('ImpPerkChange', {
					'perk', "Scoundrel",
					'change', 10,
				}),
				PlaceObj('ImpPerkChange', {
					'perk', "Teacher",
					'change', 10,
				}),
			},
		}),
		PlaceObj('ImpAnswer', {
			'answer', T(652744169946, --[[ImpQuestionDef Question7 answer]] "You bring him home, tied up in your trunk, for a proper interrogation with truth serum and assorted motivation tools."),
			'stats_changes', {
				PlaceObj('ImpStatChange', {
					'stat', "Agility",
					'change', 5,
				}),
				PlaceObj('ImpStatChange', {
					'stat', "Wisdom",
					'change', 10,
				}),
				PlaceObj('ImpStatChange', {
					'stat', "Mechanical",
					'change', 5,
				}),
				PlaceObj('ImpStatChange', {
					'stat', "Medical",
					'change', 5,
				}),
			},
			'perk_changes', {
				PlaceObj('ImpPerkChange', {
					'perk', "Negotiator",
					'change', 10,
				}),
				PlaceObj('ImpPerkChange', {
					'perk', "NightOps",
					'change', 5,
				}),
			},
		}),
	},
	group = "Default",
	id = "Question7",
	question = T(310745910344, --[[ImpQuestionDef Question7 question]] '"Kill me if you want!" he yells. "You\'re dead already, you just don\'t know it yet!"'),
})

PlaceObj('ImpQuestionDef', {
	SortKey = 8,
	answers = {
		PlaceObj('ImpAnswer', {
			'answer', T(387726913263, --[[ImpQuestionDef Question8 answer]] "You kick down the front door with a machine gun in one hand, an assault rifle in the other and a knife between your teeth, and this is just half of the weapons you carry."),
			'stats_changes', {
				PlaceObj('ImpStatChange', {
					'stat', "Strength",
					'change', 15,
				}),
				PlaceObj('ImpStatChange', {
					'stat', "Marksmanship",
					'change', 5,
				}),
			},
			'perk_changes', {
				PlaceObj('ImpPerkChange', {
					'perk', "MeleeTraining",
					'change', 5,
				}),
				PlaceObj('ImpPerkChange', {
					'perk', "AutoWeapons",
					'change', 15,
				}),
			},
		}),
		PlaceObj('ImpAnswer', {
			'answer', T(919630474387, --[[ImpQuestionDef Question8 answer]] 'You do it by the book: call for backup, throw a flashbang, take cover inside with your gun in hand, and yell: "Freeze!"'),
			'stats_changes', {
				PlaceObj('ImpStatChange', {
					'stat', "Leadership",
					'change', 15,
				}),
			},
			'perk_changes', {
				PlaceObj('ImpPerkChange', {
					'perk', "Negotiator",
					'change', 10,
				}),
				PlaceObj('ImpPerkChange', {
					'perk', "Throwing",
					'change', 5,
				}),
				PlaceObj('ImpPerkChange', {
					'perk', "CQCTraining",
					'change', 10,
				}),
			},
		}),
		PlaceObj('ImpAnswer', {
			'answer', T(668866014833, --[[ImpQuestionDef Question8 answer]] "You prowl around the house and silently climb through an open window with a knife in hand and a wicked smile on your face."),
			'stats_changes', {
				PlaceObj('ImpStatChange', {
					'stat', "Agility",
					'change', 15,
				}),
				PlaceObj('ImpStatChange', {
					'stat', "Dexterity",
					'change', 10,
				}),
			},
			'perk_changes', {
				PlaceObj('ImpPerkChange', {
					'perk', "Scoundrel",
					'change', 5,
				}),
				PlaceObj('ImpPerkChange', {
					'perk', "Stealthy",
					'change', 5,
				}),
				PlaceObj('ImpPerkChange', {
					'perk', "NightOps",
					'change', 5,
				}),
			},
		}),
		PlaceObj('ImpAnswer', {
			'answer', T(900903387347, --[[ImpQuestionDef Question8 answer]] "You just sigh and get your first aid kit ready before you enter - although you're quite sure that those poor fuckers are beyond saving already."),
			'stats_changes', {
				PlaceObj('ImpStatChange', {
					'stat', "Health",
					'change', 10,
				}),
				PlaceObj('ImpStatChange', {
					'stat', "Wisdom",
					'change', 15,
				}),
				PlaceObj('ImpStatChange', {
					'stat', "Medical",
					'change', 15,
				}),
			},
		}),
	},
	group = "Default",
	id = "Question8",
	question = T(466051841375, --[[ImpQuestionDef Question8 question]] "When you finally get home, you see there are tracks on the lawn and the front door of your house is ajar. What do you do?"),
})

PlaceObj('ImpQuestionDef', {
	SortKey = 9,
	answers = {
		PlaceObj('ImpAnswer', {
			'answer', T(190915033400, --[[ImpQuestionDef Question9 answer]] "They died of ignorance. They ignored your warning sign about the landmines in the entryway - it was right there in the locked pantry, in a pizza box, written in Sanskrit."),
			'stats_changes', {
				PlaceObj('ImpStatChange', {
					'stat', "Wisdom",
					'change', 10,
				}),
				PlaceObj('ImpStatChange', {
					'stat', "Explosives",
					'change', 15,
				}),
			},
			'perk_changes', {
				PlaceObj('ImpPerkChange', {
					'perk', "Negotiator",
					'change', 5,
				}),
				PlaceObj('ImpPerkChange', {
					'perk', "Throwing",
					'change', 5,
				}),
				PlaceObj('ImpPerkChange', {
					'perk', "HeavyWeaponsTraining",
					'change', 5,
				}),
			},
		}),
		PlaceObj('ImpAnswer', {
			'answer', T(519691498059, --[[ImpQuestionDef Question9 answer]] "They died of lead poisoning. Your twelve-year old niece is immensely proud of her submachine gun skills."),
			'stats_changes', {
				PlaceObj('ImpStatChange', {
					'stat', "Leadership",
					'change', 5,
				}),
				PlaceObj('ImpStatChange', {
					'stat', "Marksmanship",
					'change', 10,
				}),
			},
			'perk_changes', {
				PlaceObj('ImpPerkChange', {
					'perk', "Teacher",
					'change', 15,
				}),
				PlaceObj('ImpPerkChange', {
					'perk', "AutoWeapons",
					'change', 10,
				}),
			},
		}),
		PlaceObj('ImpAnswer', {
			'answer', T(678677560358, --[[ImpQuestionDef Question9 answer]] "They died for science. They contributed by testing Newton's laws with the help of a pressure plate, a block of granite, and their own skulls."),
			'stats_changes', {
				PlaceObj('ImpStatChange', {
					'stat', "Wisdom",
					'change', 5,
				}),
				PlaceObj('ImpStatChange', {
					'stat', "Mechanical",
					'change', 15,
				}),
			},
			'perk_changes', {
				PlaceObj('ImpPerkChange', {
					'perk', "Scoundrel",
					'change', 10,
				}),
				PlaceObj('ImpPerkChange', {
					'perk', "MrFixit",
					'change', 10,
				}),
			},
		}),
		PlaceObj('ImpAnswer', {
			'answer', T(537340812999, --[[ImpQuestionDef Question9 answer]] "They just died of Joy and Laughter. Those happen to be the names of your favorite Rottweilers."),
			'stats_changes', {
				PlaceObj('ImpStatChange', {
					'stat', "Agility",
					'change', 10,
				}),
				PlaceObj('ImpStatChange', {
					'stat', "Leadership",
					'change', 15,
				}),
			},
			'perk_changes', {
				PlaceObj('ImpPerkChange', {
					'perk', "Scoundrel",
					'change', 5,
				}),
				PlaceObj('ImpPerkChange', {
					'perk', "MeleeTraining",
					'change', 5,
				}),
				PlaceObj('ImpPerkChange', {
					'perk', "Teacher",
					'change', 5,
				}),
			},
		}),
	},
	group = "Default",
	id = "Question9",
	question = T(819859637674, --[[ImpQuestionDef Question9 question]] "Inside there is another surprise in the form of two armed intruders - both very, very dead. You investigate their remains to determine the cause of death."),
})

PlaceObj('ImpQuestionDef', {
	SortKey = 10,
	answers = {
		PlaceObj('ImpAnswer', {
			'answer', T(547043968987, --[[ImpQuestionDef Question10 answer]] "Investigate and find more about these assholes who attacked you. If there are more of them, you will hunt them down pro bono."),
			'stats_changes', {
				PlaceObj('ImpStatChange', {
					'stat', "Agility",
					'change', 5,
				}),
				PlaceObj('ImpStatChange', {
					'stat', "Dexterity",
					'change', 5,
				}),
				PlaceObj('ImpStatChange', {
					'stat', "Wisdom",
					'change', 15,
				}),
				PlaceObj('ImpStatChange', {
					'stat', "Marksmanship",
					'change', 5,
				}),
			},
			'perk_changes', {
				PlaceObj('ImpPerkChange', {
					'perk', "Stealthy",
					'change', 5,
				}),
				PlaceObj('ImpPerkChange', {
					'perk', "CQCTraining",
					'change', 5,
				}),
			},
		}),
		PlaceObj('ImpAnswer', {
			'answer', T(590472140243, --[[ImpQuestionDef Question10 answer]] "Search the bodies for weapons, ammo and valuables. This is how nature works - cows give us milk, hens give us eggs, and bad guys give us loot."),
			'stats_changes', {
				PlaceObj('ImpStatChange', {
					'stat', "Dexterity",
					'change', 5,
				}),
				PlaceObj('ImpStatChange', {
					'stat', "Mechanical",
					'change', 15,
				}),
				PlaceObj('ImpStatChange', {
					'stat', "Medical",
					'change', 10,
				}),
			},
			'perk_changes', {
				PlaceObj('ImpPerkChange', {
					'perk', "Scoundrel",
					'change', 10,
				}),
			},
		}),
		PlaceObj('ImpAnswer', {
			'answer', T(627075811868, --[[ImpQuestionDef Question10 answer]] "Throw the bodies to your pigs. Good job! Now you have to piss off somebody else - poor piggies will be hungry again soon enough."),
			'stats_changes', {
				PlaceObj('ImpStatChange', {
					'stat', "Health",
					'change', 10,
				}),
				PlaceObj('ImpStatChange', {
					'stat', "Strength",
					'change', 5,
				}),
				PlaceObj('ImpStatChange', {
					'stat', "Medical",
					'change', 5,
				}),
			},
			'perk_changes', {
				PlaceObj('ImpPerkChange', {
					'perk', "Psycho",
					'change', 10,
				}),
				PlaceObj('ImpPerkChange', {
					'perk', "NightOps",
					'change', 10,
				}),
			},
		}),
		PlaceObj('ImpAnswer', {
			'answer', T(998720195922, --[[ImpQuestionDef Question10 answer]] "Gosh, you missed mercenary work. You should look for a contract, form another jagged alliance and get back in action."),
			'stats_changes', {
				PlaceObj('ImpStatChange', {
					'stat', "Strength",
					'change', 5,
				}),
				PlaceObj('ImpStatChange', {
					'stat', "Leadership",
					'change', 15,
				}),
				PlaceObj('ImpStatChange', {
					'stat', "Wisdom",
					'change', 5,
				}),
				PlaceObj('ImpStatChange', {
					'stat', "Marksmanship",
					'change', 5,
				}),
			},
			'perk_changes', {
				PlaceObj('ImpPerkChange', {
					'perk', "Negotiator",
					'change', 10,
				}),
			},
		}),
	},
	group = "Default",
	id = "Question10",
	question = T(618063679660, --[[ImpQuestionDef Question10 question]] "All is well that ends well, except maybe not so well for those thugs. What do you do next?"),
})

PlaceObj('ImpQuestionDef', {
	SortKey = 11,
	group = "Outcome",
	id = "Outcome_Health",
	question = T(556776336861, --[[ImpQuestionDef Outcome_Health question]] "Your personality type is: <em>Champion</em> (ISTP). You are independent and you care little for the status quo. But if anyone tries to stand in your way, they will soon realize they have not enough status to handle your quo."),
})

PlaceObj('ImpQuestionDef', {
	SortKey = 12,
	group = "Outcome",
	id = "Outcome_Agility",
	question = T(251363658485, --[[ImpQuestionDef Outcome_Agility question]] 'Your personality type is: <em>Mediator</em> (INFP). You are careful, quiet and reserved. You enjoy spending time alone and you perform well when you are away from others, but you are not shy. You are fully capable of dealing with "social situations", and then quickly escape before they discover the bodies.'),
})

PlaceObj('ImpQuestionDef', {
	SortKey = 13,
	group = "Outcome",
	id = "Outcome_Dexterity",
	question = T(835401057248, --[[ImpQuestionDef Outcome_Dexterity question]] "Your personality type is: <em>Artist</em> (ISFP). You are capable of devoting your attention to small details, like figures moving around in your scope. You are intuitive and very much attuned to sensory information, such as the direction of the wind, the gentle resistance of the air and the subtle movements of the unsuspecting enemy when you're throwing a knife. "),
})

PlaceObj('ImpQuestionDef', {
	SortKey = 14,
	group = "Outcome",
	id = "Outcome_Strength",
	question = T(959045833463, --[[ImpQuestionDef Outcome_Strength question]] "Your personality type is: <em>Persuader</em> (ESTP). You make up your mind quickly and you do what needs to be done without much hesitation. After all, if there is a brick wall in front of you and you need to be on the other side, there is one obvious solution. Doors are for pussies."),
})

PlaceObj('ImpQuestionDef', {
	SortKey = 15,
	group = "Outcome",
	id = "Outcome_Leadership",
	question = T(137788648846, --[[ImpQuestionDef Outcome_Leadership question]] "Your personality type is: <em>Commander</em> (ENTJ). You are a natural leader and you excel at taking charge. You are highly rational and place a great emphasis on objective and logical information. Personal feelings, emotional breakdowns, and screams for mercy do not factor much into your choices."),
})

PlaceObj('ImpQuestionDef', {
	SortKey = 16,
	group = "Outcome",
	id = "Outcome_Wisdom",
	question = T(926791273230, --[[ImpQuestionDef Outcome_Wisdom question]] "Your personality type is: <em>Inspector</em> (ISTJ). You take a logical approach to achieving goals and completing projects and you are able to work at a steady pace toward accomplishing tasks. You are perceptive, but in order to focus on the task at hand you tend to ignore unnecessary distractions, such as dead bodies in your wake."),
})

PlaceObj('ImpQuestionDef', {
	SortKey = 17,
	group = "Outcome",
	id = "Outcome_Marksmanship",
	question = T(808751901318, --[[ImpQuestionDef Outcome_Marksmanship question]] "Your personality type is: <em>Performer</em> (ESFP). You have a strong awareness of your surroundings and you are also very perceptive when it comes to other people. You are quick to spot a problem and you can offer a solution with deadly precision."),
})

PlaceObj('ImpQuestionDef', {
	SortKey = 18,
	group = "Outcome",
	id = "Outcome_Mechanical",
	question = T(822848262096, --[[ImpQuestionDef Outcome_Mechanical question]] "Your personality type is: <em>Thinker</em> (INTP). You are resourceful, flexible, and good at thinking outside the box, the instruction manual, and the constraints of common sense. You prefer to see the bigger picture, such as this wonderfully renovated machine gun, and you don't care about little details, such as putting the safety switch back in place."),
})

PlaceObj('ImpQuestionDef', {
	SortKey = 19,
	group = "Outcome",
	id = "Outcome_Explosives",
	question = T(757985513286, --[[ImpQuestionDef Outcome_Explosives question]] "Your personality type is: <em>Crafter</em> (ISTP). You enjoy new experiences and you like the thrill of choosing the red wire over the blue one. However, you are not well attuned to the emotional states of others, and you can sometimes be seen as a bit insensitive just because you laugh when bad guys explode to pieces."),
})

PlaceObj('ImpQuestionDef', {
	SortKey = 20,
	group = "Outcome",
	id = "Outcome_Medical",
	question = T(239485734676, --[[ImpQuestionDef Outcome_Medical question]] 'Your personality type is: <em>Protector</em> (ISFJ). You are compassionate, helpful, and sensitive to the feelings of others. This means you may feel bad when you shoot someone who is trying to kill you, so you try thinking of it as "preventive medicine".'),
})

PlaceObj('ImpQuestionDef', {
	SortKey = 21,
	group = "Outcome",
	id = "Outcome_Negotiator",
	question = T(623410679456, --[[ImpQuestionDef Outcome_Negotiator question]] "Your dominant psychological need is: <em>Relatedness</em>. You try to connect with others, understand them and even make them see your point of view - although sometimes it is only to get them in line with your gun sights."),
})

PlaceObj('ImpQuestionDef', {
	SortKey = 22,
	group = "Outcome",
	id = "Outcome_Psycho",
	question = T(298366348508, --[[ImpQuestionDef Outcome_Psycho question]] "Your dominant psychological need is: <em>Autonomy</em>. Above all, you value your personal freedom. You need to have control and freedom over your own actions. Anyone trying to tell you what to do should pick another approach or you will SMASH THEIR FUCKING FACE IN."),
})

PlaceObj('ImpQuestionDef', {
	SortKey = 23,
	group = "Outcome",
	id = "Outcome_Scoundrel",
	question = T(307189587346, --[[ImpQuestionDef Outcome_Scoundrel question]] "Your dominant psychological need is: <em>Competence</em>. The world is your playground - you strive to gain mastery in a given field of work or study (or indeed, in all of them). You are driven by the desire to succeed in your endeavours, sometimes with no heed of the means necessary or the body count."),
})

PlaceObj('ImpQuestionDef', {
	SortKey = 31,
	group = "Outcome",
	id = "Outcome_HandToHand",
	question = T(923151766919, --[[ImpQuestionDef Outcome_HandToHand question]] "Your spirit animal is the <em>Kangaroo</em>."),
})

PlaceObj('ImpQuestionDef', {
	SortKey = 32,
	group = "Outcome",
	id = "Outcome_Stealthy",
	question = T(130857062963, --[[ImpQuestionDef Outcome_Stealthy question]] "Your spirit animal is the <em>Chameleon</em>."),
})

PlaceObj('ImpQuestionDef', {
	SortKey = 33,
	group = "Outcome",
	id = "Outcome_NightOps",
	question = T(758642855665, --[[ImpQuestionDef Outcome_NightOps question]] "Your spirit animal is the <em>Owl</em>."),
})

PlaceObj('ImpQuestionDef', {
	SortKey = 34,
	group = "Outcome",
	id = "Outcome_Teaching",
	question = T(830313450081, --[[ImpQuestionDef Outcome_Teaching question]] "Your spirit animal is the <em>Fox</em>."),
})

PlaceObj('ImpQuestionDef', {
	SortKey = 35,
	group = "Outcome",
	id = "Outcome_Throwing",
	question = T(807206719068, --[[ImpQuestionDef Outcome_Throwing question]] "Your spirit animal is the <em>Tiger</em>."),
})

PlaceObj('ImpQuestionDef', {
	SortKey = 36,
	group = "Outcome",
	id = "Outcome_AutoWeapons",
	question = T(664143185535, --[[ImpQuestionDef Outcome_AutoWeapons question]] "Your spirit animal is the <em>Wolf</em>."),
})

PlaceObj('ImpQuestionDef', {
	SortKey = 37,
	group = "Outcome",
	id = "Outcome_HeavyWeapons",
	question = T(835906172905, --[[ImpQuestionDef Outcome_HeavyWeapons question]] "Your spirit animal is the <em>Rhino</em>."),
})

PlaceObj('ImpQuestionDef', {
	SortKey = 38,
	group = "Outcome",
	id = "Outcome_MrFixIt",
	question = T(374730237073, --[[ImpQuestionDef Outcome_MrFixIt question]] "Your spirit animal is the <em>Octopus</em>."),
})

PlaceObj('ImpQuestionDef', {
	SortKey = 39,
	group = "Outcome",
	id = "Outcome_CQCtraining",
	question = T(205447472997, --[[ImpQuestionDef Outcome_CQCtraining question]] "Your spirit animal is the <em>Wolverine</em>."),
})

