-- ========== GENERATED BY RadioStationPreset Editor DO NOT EDIT MANUALLY! ==========

PlaceObj('RadioStationPreset', {
	Files = {
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Gunpowder and Tobacco",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Hangars",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Adjani Valley",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Tin Roofs",
		}),
	},
	Folder = "Music/Empty",
	display_name = T(892223837895, --[[RadioStationPreset Battle_Easy display_name]] "Battle_Easy"),
	group = "Default",
	id = "Battle_Easy",
})

PlaceObj('RadioStationPreset', {
	Files = {
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Merc's Flow",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Executing The Plan",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Raising The Stakes",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Payday",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Lock stock and Barrel",
		}),
	},
	Folder = "Music/Empty",
	display_name = T(201444845120, --[[RadioStationPreset Battle_Normal display_name]] "Battle_Normal"),
	group = "Default",
	id = "Battle_Normal",
})

PlaceObj('RadioStationPreset', {
	Files = {
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Biff's Call",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Storming The Fortress",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Legion's March",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Masks Off",
		}),
	},
	Folder = "Music/Empty",
	display_name = T(977945023064, --[[RadioStationPreset Battle_Tough display_name]] "Battle_Tough"),
	group = "Default",
	id = "Battle_Tough",
})

PlaceObj('RadioStationPreset', {
	Folder = "Music/Cerebral_Battle_Easy",
	SilenceDuration = 0,
	group = "Default",
	id = "Combat_Cerebral_Easy",
})

PlaceObj('RadioStationPreset', {
	Files = {
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Cat & Mouse",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Hunters And Prey",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Bloody Rocks",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Man made Jungle",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'EmptyTrack', true,
			'Duration', 120000,
		}),
	},
	Folder = "Music/Empty",
	display_name = T(985432288062, --[[RadioStationPreset Cursed_Conflict display_name]] "Cursed_Conflict"),
	group = "Default",
	id = "Cursed_Conflict",
})

PlaceObj('RadioStationPreset', {
	Files = {
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Hunters And Prey",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Bloody Rocks",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Wandering Paths",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/It's Too Quiet",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Whispers In The Rain",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'EmptyTrack', true,
			'Duration', 120000,
		}),
	},
	Folder = "Music/Empty",
	display_name = T(676204303343, --[[RadioStationPreset Cursed_Exploration display_name]] "Cursed_Exploration"),
	group = "Default",
	id = "Cursed_Exploration",
})

PlaceObj('RadioStationPreset', {
	Files = {
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Gunpowder and Tobacco",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Hangars",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Tin Roofs",
		}),
	},
	Folder = "Music/Empty",
	display_name = T(929479411713, --[[RadioStationPreset ErnieFlip_Conflict display_name]] "ErnieFlip_Conflict"),
	group = "Default",
	id = "ErnieFlip_Conflict",
})

PlaceObj('RadioStationPreset', {
	Files = {
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Gathering Clouds",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/The Cost Of War",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Time To Rest",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/The Aftermath",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Ukuphina (for Strings)",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Senzeni Na (for Strings)",
		}),
	},
	Folder = "Music/Empty",
	display_name = T(351284449790, --[[RadioStationPreset ErnieFlip_Exploration display_name]] "ErnieFlip_Exploration"),
	group = "Default",
	id = "ErnieFlip_Exploration",
})

PlaceObj('RadioStationPreset', {
	Files = {
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Scent of Arulco",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/I Dream of Peace",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Into The Fog",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/The Fracture",
		}),
	},
	Folder = "Music/Empty",
	display_name = T(462278695377, --[[RadioStationPreset Ernie_Conflict display_name]] "Ernie_Conflict"),
	group = "Default",
	id = "Ernie_Conflict",
})

PlaceObj('RadioStationPreset', {
	Files = {
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Wandering Paths",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Will to Survive",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/The Guns Are Silent",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Far From Over",
		}),
	},
	Folder = "Music/Empty",
	display_name = T(739648070225, --[[RadioStationPreset Ernie_Exploration display_name]] "Ernie_Exploration"),
	group = "Default",
	id = "Ernie_Exploration",
})

PlaceObj('RadioStationPreset', {
	Folder = "Music/Exploration_Beach",
	group = "Default",
	id = "Exploration_Beach",
})

PlaceObj('RadioStationPreset', {
	Folder = "Music/Exploration_Highlands",
	display_name = T(495312413337, --[[RadioStationPreset Exploration_Highlands display_name]] "Exploration Highlands"),
	group = "Default",
	id = "Exploration_Highlands",
})

PlaceObj('RadioStationPreset', {
	Files = {
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Entering The Village",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Awaiting Orders",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/I Dream of Peace",
		}),
	},
	Folder = "Music/Empty",
	display_name = T(923077795576, --[[RadioStationPreset Farmland_Conflict display_name]] "Farmland_Conflict"),
	group = "Default",
	id = "Farmland_Conflict",
})

PlaceObj('RadioStationPreset', {
	Files = {
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Far From Over",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/The Road To Pantagruel",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Violet Skies",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Breaking Bread",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Sign of Civilization",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Sanctuary",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Time to go",
		}),
	},
	Folder = "Music/Empty",
	display_name = T(168355251756, --[[RadioStationPreset Farmland_Exploration display_name]] "Farmland_Exploration"),
	group = "Default",
	id = "Farmland_Exploration",
})

PlaceObj('RadioStationPreset', {
	Files = {
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Hangars",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Adjani Valley",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Entering The Village",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/The Fracture",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Into The Fog",
		}),
	},
	Folder = "Music/Empty",
	display_name = T(861430519958, --[[RadioStationPreset Jungle_Conflict display_name]] "Jungle_Conflict"),
	group = "Default",
	id = "Jungle_Conflict",
})

PlaceObj('RadioStationPreset', {
	Files = {
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Hunters And Prey",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Bloody Rocks",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Wandering Paths",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/It's Too Quiet",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Whispers In The Rain",
		}),
	},
	Folder = "Music/Empty",
	display_name = T(431305875638, --[[RadioStationPreset Jungle_Exploration display_name]] "Jungle_Exploration"),
	group = "Default",
	id = "Jungle_Exploration",
})

PlaceObj('RadioStationPreset', {
	Files = {
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Tin Roofs",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/11 59",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/The Stage is set",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Cat & Mouse",
		}),
	},
	Folder = "Music/Empty",
	display_name = T(545086217721, --[[RadioStationPreset Outpost_Conflict display_name]] "Outpost_Conflict"),
	group = "Default",
	id = "Outpost_Conflict",
})

PlaceObj('RadioStationPreset', {
	Files = {
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Rustling Leaves",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/The Guns Are Silent",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Growing Uncertainty",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Far From Over",
		}),
	},
	Folder = "Music/Empty",
	display_name = T(533653041907, --[[RadioStationPreset Outpost_Exploration display_name]] "Outpost_Exploration"),
	group = "Default",
	id = "Outpost_Exploration",
})

PlaceObj('RadioStationPreset', {
	Files = {
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/GS_JA3_The_Jagged_Alliance_44100_16",
		}),
	},
	Folder = "Music/Empty",
	display_name = T(817928478019, --[[RadioStationPreset PreGameMenu display_name]] "Pre-Game Main Menu"),
	group = "Default",
	id = "PreGameMenu",
})

PlaceObj('RadioStationPreset', {
	Files = {
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Satellite View",
		}),
	},
	Folder = "Music/Empty",
	SilenceDuration = 0,
	group = "Default",
	id = "SatelliteRadio",
})

PlaceObj('RadioStationPreset', {
	Files = {
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Adjani Valley",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/The Stage is set",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Awaiting Orders",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Hunters And Prey",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Bloody Rocks",
		}),
	},
	Folder = "Music/Empty",
	display_name = T(512055975366, --[[RadioStationPreset Savanna_Conflict display_name]] "Savanna_Conflict"),
	group = "Default",
	id = "Savanna_Conflict",
})

PlaceObj('RadioStationPreset', {
	Files = {
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Hunters And Prey",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Bloody Rocks",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Rustling Leaves",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Will to Survive",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Gathering Clouds",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Far From Over",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Walled Garden",
		}),
	},
	Folder = "Music/Empty",
	display_name = T(442933848439, --[[RadioStationPreset Savanna_Exploration display_name]] "Savanna_Exploration"),
	group = "Default",
	id = "Savanna_Exploration",
})

PlaceObj('RadioStationPreset', {
	Files = {
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Walled Garden",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Ukuphina",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Tin Roofs",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Bloody Rocks",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Poacher's Camp",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Babu Mnumzane",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Izindlu Zodaka",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Magcina",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Segniyahamba",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Senzeni Na",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Thula Sizwe",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Thula Baba",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Hunters And Prey",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Gunpowder and Tobacco",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/A Simple Life",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Dusty Roads",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Working in the Mines",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Senzeni Na (for Strings)",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Senzeni Na (for Strings)",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Violet Skies",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Breaking Bread",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Carnival Queen",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Magcina (Instrumental)",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Sign of Civilization",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Sanctuary",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Time to go",
		}),
	},
	group = "Default",
	id = "Scripted",
})

PlaceObj('RadioStationPreset', {
	Files = {
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Working in the Mines",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Segniyahamba (for Strings)",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Violet Skies",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Carnival Queen",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Walled Garden",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Sanctuary",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Time to go",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Breaking Bread",
		}),
	},
	Folder = "Music/Empty",
	display_name = T(964727616479, --[[RadioStationPreset Sector_Complete display_name]] "Sector_Complete"),
	group = "Default",
	id = "Sector_Complete",
})

PlaceObj('RadioStationPreset', {
	Files = {
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/The Aftermath",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/The Cost Of War",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Far From Over",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Ukuphina (for Strings)",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Senzeni Na (for Strings)",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Sign of Civilization",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Senzeni Na",
			'Frequency', 10,
		}),
	},
	Folder = "Music/Empty",
	display_name = T(124514205046, --[[RadioStationPreset Sector_Failed display_name]] "Sector_Complete"),
	group = "Default",
	id = "Sector_Failed",
})

PlaceObj('RadioStationPreset', {
	Files = {
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Gunpowder and Tobacco",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Scent of Arulco",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Awaiting Orders",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/The Fracture",
		}),
	},
	Folder = "Music/Empty",
	display_name = T(467166751552, --[[RadioStationPreset SpecificDump_Conflict display_name]] "SpecificDump_Conflict"),
	group = "Default",
	id = "SpecificDump_Conflict",
})

PlaceObj('RadioStationPreset', {
	Files = {
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Rustling Leaves",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Gathering Clouds",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/The Cost Of War",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Far From Over",
		}),
	},
	Folder = "Music/Empty",
	display_name = T(711135560870, --[[RadioStationPreset SpecificDump_Exploration display_name]] "SpecificDump_Exploration"),
	group = "Default",
	id = "SpecificDump_Exploration",
})

PlaceObj('RadioStationPreset', {
	Files = {
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Big Trouble in Little Fleetown",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/I Dream of Peace",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Into The Fog",
		}),
	},
	Folder = "Music/Empty",
	display_name = T(215513399714, --[[RadioStationPreset SpecificMansion_Conflict display_name]] "SpecificMansion_Conflict"),
	group = "Default",
	id = "SpecificMansion_Conflict",
})

PlaceObj('RadioStationPreset', {
	Files = {
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Will to Survive",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/The Guns Are Silent",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/The Cost Of War",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Ukuphina (for Strings)",
		}),
	},
	Folder = "Music/Empty",
	display_name = T(438834082934, --[[RadioStationPreset SpecificMansion_Exploration display_name]] "SpecificMansion_Exploration"),
	group = "Default",
	id = "SpecificMansion_Exploration",
})

PlaceObj('RadioStationPreset', {
	Files = {
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Gunpowder and Tobacco",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Hangars",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Adjani Valley",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Tin Roofs",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Scent of Arulco",
		}),
	},
	Folder = "Music/Empty",
	display_name = T(118155450147, --[[RadioStationPreset SpecificMilitary_Conflict display_name]] "SpecificMilitary_Conflict"),
	group = "Default",
	id = "SpecificMilitary_Conflict",
})

PlaceObj('RadioStationPreset', {
	Files = {
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Rustling Leaves",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Growing Uncertainty",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Time To Rest",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Far From Over",
		}),
	},
	Folder = "Music/Empty",
	display_name = T(963388630695, --[[RadioStationPreset SpecificMilitary_Exploration display_name]] "SpecificMilitary_Exploration"),
	group = "Default",
	id = "SpecificMilitary_Exploration",
})

PlaceObj('RadioStationPreset', {
	Files = {
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Segniyahamba (for Strings)",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Violet Skies",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Walled Garden",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Sanctuary",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Time to go",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Sign of Civilization",
		}),
	},
	Folder = "Music/Empty",
	display_name = T(863733616303, --[[RadioStationPreset SpecificSpooky_Complete display_name]] "SpecificSpooky_Complete"),
	group = "Default",
	id = "SpecificSpooky_Complete",
})

PlaceObj('RadioStationPreset', {
	Files = {
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Gunpowder and Tobacco",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/11 59",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Cat & Mouse",
		}),
	},
	Folder = "Music/Empty",
	display_name = T(266990614986, --[[RadioStationPreset SpecificSpooky_Conflict display_name]] "SpecificSpooky_Conflict"),
	group = "Default",
	id = "SpecificSpooky_Conflict",
})

PlaceObj('RadioStationPreset', {
	Files = {
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/It's Too Quiet",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/The Aftermath",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Whispers In The Rain",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Will to Survive",
		}),
	},
	Folder = "Music/Empty",
	display_name = T(983080343617, --[[RadioStationPreset SpecificSpooky_Exploration display_name]] "SpecificSpooky_Exploration"),
	group = "Default",
	id = "SpecificSpooky_Exploration",
})

PlaceObj('RadioStationPreset', {
	Files = {
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Bloody Rocks",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Hunters And Prey",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Man made Jungle",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Poacher's Camp",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/The Road To Pantagruel",
		}),
	},
	Folder = "Music/Empty",
	display_name = T(128410451782, --[[RadioStationPreset SpecificVoodooRitual_Exploration display_name]] "SpecificSpooky_Exploration"),
	group = "Default",
	id = "SpecificVoodooRitual_Exploration",
})

PlaceObj('RadioStationPreset', {
	Files = {
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Hunters And Prey",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Bloody Rocks",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Man made Jungle",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Into The Fog",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Man made Jungle",
		}),
	},
	Folder = "Music/Empty",
	display_name = T(653744755362, --[[RadioStationPreset Swamp_Conflict display_name]] "Swamp_Conflict"),
	group = "Default",
	id = "Swamp_Conflict",
})

PlaceObj('RadioStationPreset', {
	Files = {
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Hunters And Prey",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Bloody Rocks",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Wandering Paths",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/It's Too Quiet",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Whispers In The Rain",
		}),
	},
	Folder = "Music/Empty",
	display_name = T(901260274831, --[[RadioStationPreset Swamp_Exploration display_name]] "Swamp_Exploration"),
	group = "Default",
	id = "Swamp_Exploration",
})

PlaceObj('RadioStationPreset', {
	Files = {
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Segniyahamba (for Strings)",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Ukuphina (for Strings)",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/The Road To Pantagruel",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Walled Garden",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Magcina (Instrumental)",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Carnival Queen",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Ukuphina",
			'Frequency', 10,
		}),
	},
	Folder = "Music/Empty",
	display_name = T(857383365357, --[[RadioStationPreset Town_Complete display_name]] "Town_Complete"),
	group = "Default",
	id = "Town_Complete",
})

PlaceObj('RadioStationPreset', {
	Files = {
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Gunpowder and Tobacco",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Adjani Valley",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/The Stage is set",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Big Trouble in Little Fleetown",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Into The Fog",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/11 59",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Tin Roofs",
		}),
	},
	Folder = "Music/Empty",
	display_name = T(843394344566, --[[RadioStationPreset Town_Conflict display_name]] "Town_Conflict"),
	group = "Default",
	id = "Town_Conflict",
})

PlaceObj('RadioStationPreset', {
	Files = {
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Big Trouble in Little Fleetown",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Will to Survive",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Growing Uncertainty",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/The Cost Of War",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Time To Rest",
		}),
	},
	Folder = "Music/Empty",
	display_name = T(993647595714, --[[RadioStationPreset Town_Exploration display_name]] "Town_Exploration"),
	group = "Default",
	id = "Town_Exploration",
})

PlaceObj('RadioStationPreset', {
	Files = {
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Gunpowder and Tobacco",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/11 59",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Cat & Mouse",
		}),
	},
	Folder = "Music/Empty",
	display_name = T(108889889902, --[[RadioStationPreset Underground_Conflict display_name]] "Underground_Conflict"),
	group = "Default",
	id = "Underground_Conflict",
})

PlaceObj('RadioStationPreset', {
	Files = {
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/It's Too Quiet",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/The Aftermath",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Whispers In The Rain",
		}),
	},
	Folder = "Music/Empty",
	display_name = T(918761167316, --[[RadioStationPreset Underground_Exploration display_name]] "Underground_Exploration"),
	group = "Default",
	id = "Underground_Exploration",
})

PlaceObj('RadioStationPreset', {
	Files = {
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/The Road To Pantagruel",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/A Simple Life",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Dusty Roads",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Working in the Mines",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Carnival Queen",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Magcina (Instrumental)",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Magcina",
			'Frequency', 10,
		}),
	},
	Folder = "Music/Empty",
	display_name = T(731608119905, --[[RadioStationPreset Village_Complete display_name]] "Village_Complete"),
	group = "Default",
	id = "Village_Complete",
})

PlaceObj('RadioStationPreset', {
	Files = {
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Entering The Village",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Big Trouble in Little Fleetown",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Awaiting Orders",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/I Dream of Peace",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Hunters And Prey",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Bloody Rocks",
		}),
	},
	Folder = "Music/Empty",
	display_name = T(393409394235, --[[RadioStationPreset Village_Conflict display_name]] "Village_Conflict"),
	group = "Default",
	id = "Village_Conflict",
})

PlaceObj('RadioStationPreset', {
	Files = {
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Will to Survive",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/The Guns Are Silent",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/The Road To Pantagruel",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Breaking Bread",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Sign of Civilization",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Sanctuary",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Time to go",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Ukuphina (for Strings)",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Violet Skies",
		}),
	},
	Folder = "Music/Empty",
	display_name = T(530508731469, --[[RadioStationPreset Village_Exploration display_name]] "Village_Exploration"),
	group = "Default",
	id = "Village_Exploration",
})

PlaceObj('RadioStationPreset', {
	Files = {
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Hangars",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Adjani Valley",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Scent of Arulco",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/The Fracture",
		}),
	},
	Folder = "Music/Empty",
	display_name = T(221063095598, --[[RadioStationPreset Wasteland_Conflict display_name]] "Wasteland_Conflict"),
	group = "Default",
	id = "Wasteland_Conflict",
})

PlaceObj('RadioStationPreset', {
	Files = {
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Rustling Leaves",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/The Guns Are Silent",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Growing Uncertainty",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Gathering Clouds",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/The Cost Of War",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/The Aftermath",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Time To Rest",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Wandering Paths",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Ukuphina (for Strings)",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Walled Garden",
		}),
	},
	Folder = "Music/Empty",
	display_name = T(966417606593, --[[RadioStationPreset Wasteland_Exploration display_name]] "Wasteland_Exploration"),
	group = "Default",
	id = "Wasteland_Exploration",
})

PlaceObj('RadioStationPreset', {
	Files = {
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Merc's Flow",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Working in the Mines",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/The Road To Pantagruel",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Magcina",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/The Cost Of War",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/The Guns Are Silent",
		}),
	},
	Folder = "Music/Empty",
	Mode = "list",
	display_name = T(495489790952, --[[RadioStationPreset _Playlist_Credits display_name]] "Outro Radio"),
	group = "Default",
	id = "_Playlist_Credits",
})

PlaceObj('RadioStationPreset', {
	Files = {
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Senzeni Na (for Strings)",
		}),
		PlaceObj('RadioPlaylistTrack', {
			'Track', "Music/Ukuphina (for Strings)",
		}),
	},
	Folder = "Music/Empty",
	Mode = "list",
	display_name = T(516145380074, --[[RadioStationPreset _Playlist_Outro display_name]] "Outro Radio"),
	group = "Default",
	id = "_Playlist_Outro",
})

