-- ========== GENERATED BY ShipmentSquadPreset Editor DO NOT EDIT MANUALLY! ==========

PlaceObj('ShipmentSquadPreset', {
	IntelText = T(727560651771, --[[ShipmentSquadPreset DiamondShipment IntelText]] "Diamond shipments are carried by a specific enemy. Retrieve the shipment then cash it in from the inventory for a large sum."),
	IntelTitle = T(698851860680, --[[ShipmentSquadPreset DiamondShipment IntelTitle]] "Diamond Shipment"),
	SquadName = T(628667613443, --[[ShipmentSquadPreset DiamondShipment SquadName]] "Diamond Shipment"),
	TimelineEventHint = T(221405332676, --[[ShipmentSquadPreset DiamondShipment TimelineEventHint]] "Intercepting the squad and obtaining the shipment would bring in a large sum of money."),
	TimelineEventText = T(503401894580, --[[ShipmentSquadPreset DiamondShipment TimelineEventText]] "The diamond shipment will reach <em><SectorId(destination)></em> and leave Grand Chien."),
	TimelineEventTitle = T(781818063159, --[[ShipmentSquadPreset DiamondShipment TimelineEventTitle]] "Diamond Shipment Enroute"),
	badge_icon = "UI/Hud/iw_diamond",
	group = "Default",
	icon = "UI/Icons/SateliteView/diamond_shipments",
	id = "DiamondShipment",
	intel_icon = "UI/Hud/iw_diamond_briefcases",
	squad_icon = "UI/Icons/SateliteView/enemy_squad_diamonds",
	squad_icon_2 = "UI/Icons/SateliteView/enemy_squad_diamonds_2",
	weight = 75,
})

PlaceObj('ShipmentSquadPreset', {
	EnableConditions = {
		PlaceObj('PlayerHasMoney', {
			Amount = 20000,
		}),
	},
	IntelText = T(835297574227, --[[ShipmentSquadPreset WeaponShipment IntelText]] "A Weapons shipment is carried by a specific enemy. Retrieve it to arm yourself."),
	IntelTitle = T(725351288796, --[[ShipmentSquadPreset WeaponShipment IntelTitle]] "Weapon Shipment"),
	SquadName = T(502279399841, --[[ShipmentSquadPreset WeaponShipment SquadName]] "Weapon Shipment"),
	TimelineEventHint = T(304200486126, --[[ShipmentSquadPreset WeaponShipment TimelineEventHint]] "Intercepting the squad and obtaining the shipment will bring in weapons and ammo."),
	TimelineEventText = T(802856419931, --[[ShipmentSquadPreset WeaponShipment TimelineEventText]] "The weapons shipment will reach <em><SectorId(destination)></em> and leave Grand Chien."),
	TimelineEventTitle = T(417965247138, --[[ShipmentSquadPreset WeaponShipment TimelineEventTitle]] "Weapon Shipment Enroute"),
	badge_icon = "UI/Hud/iw_weapons",
	group = "Default",
	icon = "UI/Icons/SateliteView/weapon_shipments",
	id = "WeaponShipment",
	intel_icon = "UI/Hud/iw_weapons_intel",
	item = "WeaponShipment",
	squad_icon = "UI/Icons/SateliteView/enemy_squad_weapons",
	squad_icon_2 = "UI/Icons/SateliteView/enemy_squad_weapons_2",
	weight = 25,
})

