-- ========== GENERATED BY BanterDef Editor DO NOT EDIT MANUALLY! ==========

PlaceObj('BanterDef', {
	Lines = {
		PlaceObj('BanterLine', {
			'Text', T(672023214845, --[[BanterDef Dolls_00_PoetsNote Text]] "There is a poem by Edgar Allan Poe."),
			'Voiced', false,
			'FloatUp', true,
		}),
	},
	Once = true,
	group = "Banters_Local_Wetlands_DollBog",
	id = "Dolls_00_PoetsNote",
})

PlaceObj('BanterDef', {
	Lines = {
		PlaceObj('BanterLine', {
			'Annotation', "Line from the poem Lenore by Edgar Allan Poe",
			'Text', T(616227525464, --[[BanterDef Dolls_01_Verse_1 Text]] '"Ah, broken is the golden bowl! - the spirit flown forever!"'),
			'Voiced', false,
			'FloatUp', true,
		}),
	},
	group = "Banters_Local_Wetlands_DollBog",
	id = "Dolls_01_Verse_1",
})

PlaceObj('BanterDef', {
	Lines = {
		PlaceObj('BanterLine', {
			'Annotation', "Line from the poem Lenore by Edgar Allan Poe",
			'Text', T(485694706717, --[[BanterDef Dolls_01_Verse_2 Text]] '"Let the bell toll! - a saintly soul floats on the Stygian river"'),
			'Voiced', false,
			'FloatUp', true,
		}),
	},
	group = "Banters_Local_Wetlands_DollBog",
	id = "Dolls_01_Verse_2",
})

PlaceObj('BanterDef', {
	Lines = {
		PlaceObj('BanterLine', {
			'Annotation', "Line from the poem Lenore by Edgar Allan Poe",
			'Text', T(634049352389, --[[BanterDef Dolls_01_Verse_3 Text]] '"And, Guy De Vere, hast thou no tear? - weep now or never more!"'),
			'Voiced', false,
			'FloatUp', true,
		}),
	},
	group = "Banters_Local_Wetlands_DollBog",
	id = "Dolls_01_Verse_3",
})

PlaceObj('BanterDef', {
	Lines = {
		PlaceObj('BanterLine', {
			'Annotation', "Line from the poem Lenore by Edgar Allan Poe",
			'Text', T(927358223448, --[[BanterDef Dolls_01_Verse_4 Text]] '"See! on yon drear and rigid bier low lies thy love, Lenore!"'),
			'Voiced', false,
			'FloatUp', true,
		}),
	},
	group = "Banters_Local_Wetlands_DollBog",
	id = "Dolls_01_Verse_4",
})

PlaceObj('BanterDef', {
	Lines = {
		PlaceObj('BanterLine', {
			'Annotation', "Line from the poem Lenore by Edgar Allan Poe",
			'Text', T(906199902392, --[[BanterDef Dolls_01_Verse_5 Text]] '"Come, let the burial rite be read - the funeral song be sung!"'),
			'Voiced', false,
			'FloatUp', true,
		}),
	},
	group = "Banters_Local_Wetlands_DollBog",
	id = "Dolls_01_Verse_5",
})

PlaceObj('BanterDef', {
	Lines = {
		PlaceObj('BanterLine', {
			'Annotation', "Line from the poem Lenore by Edgar Allan Poe",
			'Text', T(423668261139, --[[BanterDef Dolls_01_Verse_6 Text]] '"An anthem for the queenliest dead that ever died so young"'),
			'Voiced', false,
			'FloatUp', true,
		}),
	},
	group = "Banters_Local_Wetlands_DollBog",
	id = "Dolls_01_Verse_6",
})

PlaceObj('BanterDef', {
	Lines = {
		PlaceObj('BanterLine', {
			'Annotation', "Line from the poem Lenore by Edgar Allan Poe",
			'Text', T(981844407197, --[[BanterDef Dolls_01_Verse_7 Text]] '"A dirge for her the doubly dead in that she died so young."'),
			'Voiced', false,
			'FloatUp', true,
		}),
	},
	group = "Banters_Local_Wetlands_DollBog",
	id = "Dolls_01_Verse_7",
})

PlaceObj('BanterDef', {
	Lines = {
		PlaceObj('BanterLine', {
			'Text', T(174146835567, --[[BanterDef Dolls_02_Discovery Text]] "<wisdom-s>"),
			'Voiced', false,
			'FloatUp', true,
		}),
		PlaceObj('BanterLine', {
			'Text', T(681896552387, --[[BanterDef Dolls_02_Discovery Text]] "This is not a doll but a female corpse, cemented and painted over."),
			'Voiced', false,
			'FloatUp', true,
		}),
	},
	Once = true,
	group = "Banters_Local_Wetlands_DollBog",
	id = "Dolls_02_Discovery",
})

