-- ========== GENERATED BY CharacterEffectCompositeDef Editor DO NOT EDIT MANUALLY! ==========

PlaceObj('CharacterEffectCompositeDef', {
	'Group', "System",
	'Id', "ClaustrophobiaChecked",
	'SortKey', 2,
	'object_class', "StatusEffect",
	'DisplayName', T(145876002652, --[[CharacterEffectCompositeDef ClaustrophobiaChecked DisplayName]] "Claustrophobia Checked"),
	'RemoveOnEndCombat', true,
	'RemoveOnSatViewTravel', true,
	'RemoveOnCampaignTimeAdvance', true,
})

