-- ========== GENERATED BY CharacterEffectCompositeDef Editor DO NOT EDIT MANUALLY! ==========

PlaceObj('CharacterEffectCompositeDef', {
	'Id', "Conscience_Sinful",
	'Parameters', {
		PlaceObj('PresetParamNumber', {
			'Name', "days",
			'Value', 1,
			'Tag', "<days>",
		}),
		PlaceObj('PresetParamPercent', {
			'Name', "decrease",
			'Value', 30,
			'Tag', "<decrease>%",
		}),
	},
	'Comment', "conversations related",
	'object_class', "StatusEffect",
	'unit_reactions', {
		PlaceObj('UnitReaction', {
			Event = "OnNewDay",
			Handler = function (self, target)
				Conscience_CheckExpiration(self, target, "guilty_start_time")
			end,
		}),
		PlaceObj('UnitReaction', {
			Event = "OnCalcPersonalMorale",
			Handler = function (self, target, value)
				return value - 2
			end,
		}),
	},
	'DisplayName', T(634244208298, --[[CharacterEffectCompositeDef Conscience_Sinful DisplayName]] "Remorseful"),
	'Description', T(518452710606, --[[CharacterEffectCompositeDef Conscience_Sinful Description]] "Morale decreased by 2 for a day."),
	'AddEffectText', T(949084683649, --[[CharacterEffectCompositeDef Conscience_Sinful AddEffectText]] "<em><DisplayName></em> is full of remorse and lost Morale"),
	'OnAdded', function (self, obj)
		self:SetParameter("guilty_start_time", Game.CampaignTime)
	end,
	'OnRemoved', function (self, obj)
		-- Handles old guilty modifiers, new guilty applies morale modifier
		local stats = UnitPropertiesStats:GetProperties()
		for i, stat in ipairs(stats) do
			obj:RemoveModifier("guilty_" .. stat.id, stat.id)
		end
	end,
	'type', "Debuff",
	'Icon', "UI/Hud/Status effects/encumbered",
	'HasFloatingText', true,
})

