-- ========== GENERATED BY CharacterEffectCompositeDef Editor DO NOT EDIT MANUALLY! ==========

PlaceObj('CharacterEffectCompositeDef', {
	'Group', "Perk-Personal",
	'Id', "GruntyPerk",
	'Parameters', {
		PlaceObj('PresetParamNumber', {
			'Name', "cthMod",
			'Tag', "<cthMod>",
		}),
	},
	'Comment', "Grunty - free shot at battle start",
	'object_class', "Perk",
	'unit_reactions', {
		PlaceObj('UnitReaction', {
			Event = "OnCombatStarting",
			Handler = function (self, target, load_game)
				if load_game then return end
				
				local enemy = target:GetClosestEnemy()
				if enemy then
					local weapon = target:GetActiveWeapons()
					if IsKindOf(weapon, "Firearm") and not IsKindOf(weapon, "HeavyWeapon") then
						local action = target:GetDefaultAttackAction("ranged")
						local args = {target = enemy, gruntyPerk = true}
						LockCameraMovement("grunty perk")
						StartCombatAction(action.id, target, 0, args)
					end
				end
			end,
		}),
	},
	'DisplayName', T(562334332352, --[[CharacterEffectCompositeDef GruntyPerk DisplayName]] "Überraschung"),
	'Description', T(742416202176, --[[CharacterEffectCompositeDef GruntyPerk Description]] "<em>Attacks</em> the <em>closest</em> enemy with a firearm when <em>combat starts</em>, if possible.\n\nCan't be used with Heavy Weapons."),
	'Icon', "UI/Icons/Perks/GruntyPerk",
	'Tier', "Personal",
})

