-- ========== GENERATED BY CharacterEffectCompositeDef Editor DO NOT EDIT MANUALLY! ==========

PlaceObj('CharacterEffectCompositeDef', {
	'Group', "Agility",
	'Id', "LuckyStreak",
	'SortKey', 7,
	'Parameters', {
		PlaceObj('PresetParamNumber', {
			'Name', "crits_number",
			'Value', 2,
			'Tag', "<crits_number>",
		}),
	},
	'object_class', "Perk",
	'msg_reactions', {
		PlaceObj('MsgReaction', {
			Event = "OnAttack",
			Handler = function (self, attacker, action, target, results, attack_args)
				local reaction_idx = table.find(self.msg_reactions or empty_table, "Event", "OnAttack")
				if not reaction_idx then return end
				
				local function exec(self, attacker, action, target, results, attack_args)
				if results.crit and IsKindOf(target, "Unit") then
					attacker:AddStatusEffect("LuckyStreakBuff")
				end
				end
				local id = GetCharacterEffectId(self)
				
				if id then
					if IsKindOf(attacker, "StatusEffectObject") and attacker:HasStatusEffect(id) then
						exec(self, attacker, action, target, results, attack_args)
					end
				else
					exec(self, attacker, action, target, results, attack_args)
				end
				
			end,
			HandlerCode = function (self, attacker, action, target, results, attack_args)
				if results.crit and IsKindOf(target, "Unit") then
					attacker:AddStatusEffect("LuckyStreakBuff")
				end
			end,
		}),
	},
	'DisplayName', T(838318520600, --[[CharacterEffectCompositeDef LuckyStreak DisplayName]] "Lucky Streak"),
	'Description', T(350209296951, --[[CharacterEffectCompositeDef LuckyStreak Description]] "Become <GameTerm('Inspired')> when you make <em><crits_number></em> <GameTerm('Crits')> in the <em>same</em> turn."),
	'Icon', "UI/Icons/Perks/LuckyStreak",
	'Tier', "Gold",
	'Stat', "Agility",
	'StatValue', 90,
})

