-- ========== GENERATED BY CharacterEffectCompositeDef Editor DO NOT EDIT MANUALLY! ==========

PlaceObj('CharacterEffectCompositeDef', {
	'Group', "Perk-Specialization",
	'Id', "NightOps",
	'SortKey', 100,
	'Parameters', {
		PlaceObj('PresetParamPercent', {
			'Name', "night_acc_penalty_reduction",
			'Value', 66,
			'Tag', "<night_acc_penalty_reduction>%",
		}),
		PlaceObj('PresetParamPercent', {
			'Name', "night_vision_penalty_reduction",
			'Value', 50,
			'Tag', "<night_vision_penalty_reduction>%",
		}),
	},
	'object_class', "Perk",
	'DisplayName', T(942189694921, --[[CharacterEffectCompositeDef NightOps DisplayName]] "Night Ops"),
	'Description', T(183266673872, --[[CharacterEffectCompositeDef NightOps Description]] "Reduced penalties to <em>Accuracy</em> when at <em>Night</em> and in <em>underground</em> Sectors."),
	'Icon', "UI/Icons/Perks/NightOps",
	'Tier', "Specialization",
})

