-- ========== GENERATED BY SetpiecePrg Editor (Ctrl-Alt-S) DO NOT EDIT MANUALLY! ==========

PlaceObj('SetpiecePrg', {
	Map = "D-17 - Ille Morat",
	group = "IlleMorat",
	hidden_actors = false,
	id = "BeasIntro_BeastAiming",
	PlaceObj('SetpieceTeleport', {
		Actors = "TriggerUnits",
		Marker = "SP_BeastPort_01",
	}),
	PlaceObj('SetpieceSetStance', {
		Actors = "TriggerUnits",
		Stance = "Crouch",
	}),
	PlaceObj('SetpieceGotoPosition', {
		Actors = "TriggerUnits",
		AssignTo = "SP_BeastGoTo",
		Marker = "SP_BeastGoTo_01",
		Stance = "Crouch",
	}),
	PlaceObj('SetpieceGotoPosition', {
		Actors = "TriggerUnits",
		AssignTo = "SP_BeastGoTo",
		Marker = "SP_BeastAim",
		Stance = "Crouch",
		UseRun = false,
		animated_rotation = true,
	}),
	PlaceObj('SetpieceSleep', {
		Time = 5,
	}),
	PlaceObj('SetpieceAnimation', {
		Actors = "TriggerUnits",
		Animation = "ar_Crouch_Aim",
		Duration = 10000,
	}),
})

