-- ========== GENERATED BY SetpiecePrg Editor (Ctrl-Alt-S) DO NOT EDIT MANUALLY! ==========

PlaceObj('SetpiecePrg', {
	Effects = {
		PlaceObj('PlayBanterEffect', {
			Banters = {
				"FortCorazon07_kill",
			},
			searchInMap = true,
			searchInMarker = false,
		}),
	},
	Map = "H-4U - Fortress Basement",
	RestoreCamera = true,
	group = "Deaths",
	id = "CorazonDies",
	PlaceObj('SetpieceFadeOut', {}),
	PlaceObj('SetpieceFadeIn', {
		FadeInDelay = 0,
		FadeInTime = 300,
		Wait = false,
	}),
	PlaceObj('SetpieceAssignFromGroup', {
		AssignTo = "Corazone",
		Group = "CorazonSantiagoEnemy",
	}),
	PlaceObj('SetpieceAssignFromParam', {
		AssignTo = "Merc",
		Parameter = "TriggerUnits",
	}),
	PlaceObj('PrgPlaySetpiece', {
		Prg = "ConversationKill_SubPiece",
		PrgClass = "SetpiecePrg",
		Shooter = function (self) return Merc end,
		Target = function (self) return Corazone end,
	}),
})

