-- ========== GENERATED BY SetpiecePrg Editor (Ctrl-Alt-S) DO NOT EDIT MANUALLY! ==========

PlaceObj('SetpiecePrg', {
	Map = "D-8 - Pantagruel Downtown",
	Params = {
		"MainActor",
		"TargetActor",
	},
	TakePlayerControl = false,
	group = "Pantagruel",
	id = "DowntownFirstEnter_LegionSideActor2",
	PlaceObj('SetpieceTeleport', {
		Actors = "MainActor",
		AssignTo = "LegionActor3Start",
		Marker = "LegionSideActor2Start",
	}),
	PlaceObj('SetpieceSetStance', {
		Actors = "MainActor",
	}),
	PlaceObj('SetpieceSleep', {
		Time = 1200,
	}),
	PlaceObj('SetpieceGotoPosition', {
		Actors = "MainActor",
		AssignTo = "LegionSideActor1_GoTo",
		Marker = "LegionSideActor2_GoTo",
		Stance = "Standing",
		animated_rotation = true,
	}),
	PlaceObj('SetpieceSleep', {
		Time = 900,
	}),
	PlaceObj('SetpieceWaitCheckpoint', {
		WaitCheckpoint = "PantagruelFirstEnter_SynPoint",
	}),
	PlaceObj('SetpieceShoot', {
		Actors = "MainActor",
		AssignTo = "AttackPointLegion1",
		InitialDelay = 600,
		NumShots = 2,
		ShotInterval = 400,
		TargetBodyPart = "Arms",
		TargetOffset = 700,
		TargetPos = "AttackPointLegionSide2",
		TargetType = "Point",
		TargetUnits = "TargetActor",
	}),
	PlaceObj('SetpieceSleep', {
		Time = 4000,
	}),
	PlaceObj('SetpieceGotoPosition', {
		Actors = "MainActor",
		AssignTo = "LegionSideActor2_GoTo2",
		Marker = "LegionSideActor2_GoTo2",
		Stance = "Standing",
		animated_rotation = true,
	}),
})

