-- ========== GENERATED BY SetpiecePrg Editor (Ctrl-Alt-S) DO NOT EDIT MANUALLY! ==========

PlaceObj('SetpiecePrg', {
	Map = "L-9 - Port Cacao Dump",
	RestoreCamera = true,
	StopMercMovement = false,
	Visibility = "Player",
	group = "PortCacao",
	hidden_actors = false,
	id = "DumpFlower",
	PlaceObj('SetpieceFadeOut', {
		FadeOutTime = 300,
	}),
	PlaceObj('SetpieceFadeIn', {
		Wait = false,
	}),
	PlaceObj('SetpieceCamera', {
		CamProps = {
			floor = 0,
		},
		CamType = "Tac",
		Duration = 4000,
		Easing = 6,
		LookAt1 = point(170776, 160307, 7104),
		LookAt2 = point(170776, 160307, 7104),
		PanOnly = true,
		Pos1 = point(161895, 150663, 18104),
		Pos2 = point(161895, 150663, 18104),
		Zoom = 650,
	}),
})

