-- ========== GENERATED BY SetpiecePrg Editor (Ctrl-Alt-S) DO NOT EDIT MANUALLY! ==========

PlaceObj('SetpiecePrg', {
	Comment = "Main Setpiece",
	Map = "B-12 - Landsbach Mine",
	RestoreCamera = true,
	group = "Landsbach",
	hidden_actors = false,
	id = "Landsbach_SigfriedAttack",
	PlaceObj('SetpieceFadeOut', {
		FadeOutTime = 300,
	}),
	PlaceObj('PrgPlayEffect', {
		Effects = {
			PlaceObj('UnitsDespawnAmbientLife', {}),
		},
	}),
	PlaceObj('PrgPlayEffect', {
		Effects = {
			PlaceObj('ConditionalEffect', {
				'Conditions', {
					PlaceObj('SetpieceIsTestMode', {}),
				},
				'Effects', {
					PlaceObj('QuestSetVariableBool', {
						Prop = "SigfriedBattle",
						QuestId = "Landsbach",
					}),
				},
			}),
		},
	}),
	PlaceObj('PrgPlayEffect', {
		Effects = {
			PlaceObj('MusicSetTrack', {
				Playlist = "Scripted",
				Track = "Music/The Stage is set",
			}),
		},
	}),
	PlaceObj('SetpieceFadeIn', {
		FadeInDelay = 0,
		FadeInTime = 300,
		Wait = false,
	}),
	PlaceObj('SetpieceAssignFromGroup', {
		AssignTo = "Bounce",
		Group = "BounceEnemy",
	}),
	PlaceObj('SetpieceAssignFromGroup', {
		AssignTo = "Gunther",
		Group = "Gunther",
	}),
	PlaceObj('SetpieceAssignFromGroup', {
		AssignTo = "Doorknob",
		Group = "DoorknobEnemy",
	}),
	PlaceObj('SetpieceAssignFromGroup', {
		AssignTo = "NightClubThug1",
		Group = "NightClubThug1",
	}),
	PlaceObj('SetpieceAssignFromGroup', {
		AssignTo = "NightClubThug2",
		Group = "NightClubThug2",
	}),
	PlaceObj('SetpieceAssignFromGroup', {
		AssignTo = "NightClubThug3",
		Group = "NightClubThug3",
	}),
	PlaceObj('SetpieceAssignFromGroup', {
		AssignTo = "NightClubThug4",
		Group = "NightClubThug4",
	}),
	PlaceObj('SetpieceAssignFromGroup', {
		AssignTo = "NightClubThug5",
		Group = "NightClubThug5",
	}),
	PlaceObj('SetpieceAssignFromGroup', {
		AssignTo = "NightClubThug6",
		Group = "NightClubThug6",
	}),
	PlaceObj('SetpieceAssignFromGroup', {
		AssignTo = "NightClubThug7",
		Group = "NightClubThug7",
	}),
	PlaceObj('SetpieceAssignFromGroup', {
		AssignTo = "NightClubThug8",
		Group = "NightClubThug8",
	}),
	PlaceObj('SetpieceAnimation', {
		Actors = "Bounce",
		Animation = "ar_Crouch_Idle",
		Wait = false,
	}),
	PlaceObj('SetpieceAnimation', {
		Actors = "Doorknob",
		Animation = "ar_Crouch_Idle",
		Wait = false,
	}),
	PlaceObj('SetpieceAnimation', {
		Actors = "NightClubThug1",
		Animation = "ar_Crouch_Idle",
		Wait = false,
	}),
	PlaceObj('SetpieceAnimation', {
		Actors = "NightClubThug2",
		Animation = "ar_Crouch_Idle",
		Wait = false,
	}),
	PlaceObj('SetpieceAnimation', {
		Actors = "NightClubThug3",
		Animation = "ar_Crouch_Idle",
		Wait = false,
	}),
	PlaceObj('SetpieceAnimation', {
		Actors = "NightClubThug4",
		Animation = "ar_Crouch_Idle",
		Wait = false,
	}),
	PlaceObj('SetpieceAnimation', {
		Actors = "NightClubThug5",
		Animation = "ar_Crouch_Idle",
		Wait = false,
	}),
	PlaceObj('SetpieceAnimation', {
		Actors = "NightClubThug6",
		Animation = "ar_Crouch_Idle",
		Wait = false,
	}),
	PlaceObj('SetpieceAnimation', {
		Actors = "NightClubThug7",
		Animation = "ar_Crouch_Idle",
		Wait = false,
	}),
	PlaceObj('SetpieceAnimation', {
		Actors = "NightClubThug8",
		Animation = "ar_Crouch_Idle",
		Wait = false,
	}),
	PlaceObj('SetpieceFadeIn', {
		Checkpoint = "1st Scene",
		FadeInDelay = 0,
		FadeInTime = 5000,
		Wait = false,
	}),
	PlaceObj('SetpieceCamera', {
		CameraMode = "Show all",
		Checkpoint = "1st Scene",
		Duration = 5500,
		LookAt1 = point(139911, 160134, 10462),
		LookAt2 = point(142396, 160422, 10047),
		Movement = "harmonic",
		Pos1 = point(135205, 158569, 11095),
		Pos2 = point(137602, 159187, 10745),
		Wait = false,
	}),
	PlaceObj('SetpieceGotoPosition', {
		Actors = "Bounce",
		AssignTo = "SmileyRunOut",
		Marker = "Bounce_Go_To_01",
		Stance = "Crouch",
		UseRun = false,
		Wait = false,
	}),
	PlaceObj('SetpieceGotoPosition', {
		Actors = "Doorknob",
		AssignTo = "SmileyRunOut",
		Marker = "Doorknob_Go_To_01",
		Stance = "Crouch",
		UseRun = false,
		Wait = false,
	}),
	PlaceObj('SetpieceGotoPosition', {
		Actors = "NightClubThug1",
		AssignTo = "SmileyRunOut",
		Marker = "Merc3_Go_To_01",
		Stance = "Crouch",
		UseRun = false,
		Wait = false,
	}),
	PlaceObj('SetpieceGotoPosition', {
		Actors = "NightClubThug2",
		AssignTo = "SmileyRunOut",
		Marker = "Merc1_Go_To_01",
		Stance = "Crouch",
		UseRun = false,
		Wait = false,
	}),
	PlaceObj('SetpieceGotoPosition', {
		Actors = "NightClubThug3",
		AssignTo = "SmileyRunOut",
		Marker = "NightClubThug6_Go_To_01",
		Stance = "Crouch",
		UseRun = false,
		Wait = false,
	}),
	PlaceObj('SetpieceGotoPosition', {
		Actors = "NightClubThug4",
		AssignTo = "SmileyRunOut",
		Marker = "NightClubThug2_Go_To_01",
		Stance = "Crouch",
		UseRun = false,
		Wait = false,
	}),
	PlaceObj('SetpieceGotoPosition', {
		Actors = "NightClubThug5",
		AssignTo = "SmileyRunOut",
		Marker = "NightClubThug7_Go_To_01",
		Stance = "Crouch",
		UseRun = false,
		Wait = false,
	}),
	PlaceObj('SetpieceGotoPosition', {
		Actors = "NightClubThug6",
		AssignTo = "SmileyRunOut",
		Marker = "Merc6_Go_To_01",
		Stance = "Crouch",
		UseRun = false,
		Wait = false,
	}),
	PlaceObj('SetpieceGotoPosition', {
		Actors = "NightClubThug4",
		AssignTo = "SmileyRunOut",
		Marker = "NightClubThug4_Go_To_01",
		Stance = "Crouch",
		UseRun = false,
		Wait = false,
	}),
	PlaceObj('SetpieceGotoPosition', {
		Actors = "NightClubThug7",
		AssignTo = "SmileyRunOut",
		Marker = "Merc4_Go_To_01",
		Stance = "Crouch",
		UseRun = false,
		Wait = false,
	}),
	PlaceObj('SetpieceGotoPosition', {
		Actors = "NightClubThug8",
		AssignTo = "SmileyRunOut",
		Marker = "NightClubThug3_Go_To_01",
		Stance = "Crouch",
		UseRun = false,
		Wait = false,
	}),
	PlaceObj('SetpieceSleep', {
		Time = 5500,
	}),
	PlaceObj('SetpieceCamera', {
		CameraMode = "Show all",
		Checkpoint = "2nd Scene",
		Duration = 10000,
		LookAt1 = point(177493, 164540, 8999),
		LookAt2 = point(184744, 160549, 8434),
		Movement = "harmonic",
		Pos1 = point(182007, 166303, 10228),
		Pos2 = point(189259, 162312, 9664),
		Wait = false,
	}),
	PlaceObj('PrgPlayEffect', {
		Checkpoint = "2nd Scene",
		Effects = {
			PlaceObj('PlayBanterEffect', {
				Banters = {
					"Landsbach_Bounce03",
				},
				searchInMap = true,
				searchInMarker = false,
			}),
		},
		Wait = false,
	}),
	PlaceObj('SetpieceWaitCheckpoint', {
		WaitCheckpoint = "2nd Scene",
	}),
	PlaceObj('SetpieceCamera', {
		CamType = "Tac",
		CameraMode = "Show all",
		Checkpoint = "3rd Scene",
		Duration = 1700,
		LookAt1 = point(185121, 166277, 12853),
		LookAt2 = point(185121, 166276, 12853),
		Movement = "harmonic",
		Pos1 = point(187430, 170344, 14623),
		Pos2 = point(187430, 170344, 14623),
		Wait = false,
	}),
	PlaceObj('SetpieceSleep', {
		Time = 1700,
	}),
	PlaceObj('SetpieceShoot', {
		Actors = "Bounce",
		Checkpoint = "BouneShooting",
		NumShots = 3,
		TargetPos = "BounceShooting",
		TargetType = "Point",
		Wait = false,
	}),
	PlaceObj('SetpieceSleep', {
		Time = 500,
	}),
	PlaceObj('SetpieceShoot', {
		Actors = "Doorknob",
		NumShots = 3,
		TargetPos = "DoorknobShooting",
		TargetType = "Point",
	}),
	PlaceObj('SetpieceShoot', {
		Actors = "NightClubThug1",
		NumShots = 3,
		TargetPos = "Thug_01Shooting",
		TargetType = "Point",
	}),
	PlaceObj('SetpieceShoot', {
		Actors = "NightClubThug2",
		NumShots = 3,
		TargetPos = "DoorknobShooting",
		TargetType = "Point",
	}),
	PlaceObj('SetpieceSleep', {
		Time = 1,
	}),
	PlaceObj('SetpieceShoot', {
		Actors = "Doorknob",
		NumShots = 3,
		TargetPos = "DoorknobShooting",
		TargetType = "Point",
		Wait = false,
	}),
	PlaceObj('SetpieceWaitCheckpoint', {
		WaitCheckpoint = "BouneShooting",
	}),
	PlaceObj('SetpieceFadeOut', {
		FadeOutTime = 2000,
	}),
	PlaceObj('SetpieceSleep', {
		Time = 500,
	}),
	PlaceObj('PrgPlayEffect', {
		Effects = {
			PlaceObj('ForceResetAmbientLife', {}),
		},
	}),
	PlaceObj('PrgForceStopSetpiece', {}),
})

