-- ========== GENERATED BY ParticleSystemPreset Editor DO NOT EDIT MANUALLY! ==========

PlaceObj('ParticleSystemPreset', {
	game_time_animated = true,
	group = "Grenade_Smoke",
	id = "SmokeGrenade_1x1_Grey",
	stable_cam_distance = true,
	PlaceObj('ParticleEmitter', {
		'label', "Smoke",
		'emit_detail_level', 100,
		'max_live_count', 10,
		'parts_per_sec', 200,
		'lifetime_min', 2000,
		'lifetime_max', 4000,
		'texture', "Textures/Particles/mist.tga",
		'normalmap', "Textures/Particles/mist.norm.tga",
		'frames', point(2, 2),
		'far_softness', 100,
		'outlines', {
			{
				point(32, 32),
				point(32, 2016),
				point(2016, 2016),
				point(2016, 32),
			},
			{
				point(2080, 2016),
				point(3968, 2016),
				point(4064, 32),
				point(2080, 32),
			},
			{
				point(32, 4032),
				point(2016, 4032),
				point(2016, 2080),
				point(32, 2080),
			},
			{
				point(2080, 4032),
				point(4064, 4032),
				point(4064, 2080),
				point(2080, 2080),
			},
		},
		'texture_hash', 6609993512092536490,
	}, nil, nil),
	PlaceObj('ParticleBehaviorPickFrame', nil, nil, nil),
	PlaceObj('ParticleBehaviorRandomSpeedSpray', {
		'spread_angle', 36000,
		'vel_min', 100,
		'vel_max', 100,
	}, nil, nil),
	PlaceObj('ParticleBehaviorFadeInOut', {
		'fade_curve', {
			range_y = 10,
			scale = 1000,
			point(0, 0, 0),
			point(324, 114, 114),
			point(680, 74, 74),
			point(1000, 0, 0),
		},
	}, nil, nil),
	PlaceObj('ParticleBehaviorResizeCurve', {
		'max_size', 4000,
		'size_curve', {
			range_y = 10,
			scale = 1000,
			point(0, 424, 424),
			point(383, 581, 581),
			point(699, 782, 782),
			point(1000, 1000, 1000),
		},
	}, nil, nil),
	PlaceObj('ParticleBehaviorRotate', {
		'rpm_curve', {
			range_y = 10,
			scale = 10,
			point(0, 0, 0),
			point(352, 38, 38),
			point(661, -1, -1),
			point(1000, 0, 0),
		},
		'rpm_curve_range', range(-120, 120),
	}, nil, nil),
	PlaceObj('ParticleBehaviorColorize', {
		'start_color_min', RGBA(255, 248, 242, 255),
		'start_color_max', RGBA(242, 235, 229, 255),
		'mid_color', RGBA(204, 188, 177, 255),
		'end_color', RGBA(179, 164, 155, 255),
	}, nil, nil),
	PlaceObj('ParticleBehaviorWind', {
		'probability', 20,
	}, nil, nil),
})

