-- ========== GENERATED BY XTemplate Editor (Alt-F3) DO NOT EDIT MANUALLY! ==========

PlaceObj('XTemplate', {
	group = "Zulu",
	id = "IModeCombatCharge",
	PlaceObj('XTemplateWindow', {
		'__class', "IModeCombatCharge",
	}, {
		PlaceObj('XTemplateTemplate', {
			'__template', "IModeCombatAttackBaseGeneric",
		}),
		}),
})

