-- ========== GENERATED BY XTemplate Editor (Alt-F3) DO NOT EDIT MANUALLY! ==========

PlaceObj('XTemplate', {
	__is_kind_of = "XRolloverWindow",
	group = "Zulu",
	id = "RolloverBobbyRay",
	PlaceObj('XTemplateTemplate', {
		'__template', "RolloverGeneric",
		'Margins', box(8, 6, 0, 50),
		'MaxWidth', 350,
	}),
})

