-- ========== GENERATED BY XTemplate Editor (Alt-F3) DO NOT EDIT MANUALLY! ==========

PlaceObj('XTemplate', {
	__is_kind_of = "XRolloverWindow",
	group = "Zulu",
	id = "RolloverInventoryBobbyRay",
	PlaceObj('XTemplateWindow', {
		'__condition', function (parent, context) return not UseNewInventoryRollover(ResolvePropObj(context)) end,
		'__class', "PDARolloverClass",
		'BorderWidth', 0,
		'UseClipBox', false,
		'Background', RGBA(240, 240, 240, 0),
		'FocusedBackground', RGBA(240, 240, 240, 0),
	}, {
		PlaceObj('XTemplateTemplate', {
			'__condition', function (parent, context)
				local cnt = ResolvePropObj(context)
				return cnt and not cnt:IsWeapon()
			end,
			'__template', "RolloverInventoryBase",
			'Margins', box(0, -6, 8, 50),
			'MinWidth', 350,
			'MaxWidth', 350,
		}),
		PlaceObj('XTemplateFunc', {
			'name', "Open(self,...)",
			'func', function (self,...)
				PDARolloverClass.Open(self,...)
			end,
		}),
		}),
	PlaceObj('XTemplateTemplate', {
		'__condition', function (parent, context) return UseNewInventoryRollover(ResolvePropObj(context)) end,
		'__template', "RolloverInventoryWeapon",
		'Margins', box(0, 6, 8, 50),
		'MaxWidth', 350,
	}),
})

