-- ========== GENERATED BY InventoryItemCompositeDef Editor (Ctrl-Alt-Y) DO NOT EDIT MANUALLY! ==========

UndefineClass('Detonator')
DefineClass.Detonator = {
	__parents = { "TrapDetonator" },
	__generated_by_class = "InventoryItemCompositeDef",


	object_class = "TrapDetonator",
	Repairable = false,
	ScrapParts = 5,
	Icon = "UI/Icons/Items/detonator",
	DisplayName = T(747561295307, --[[InventoryItemCompositeDef Detonator DisplayName]] "Remote"),
	DisplayNamePlural = T(428906062831, --[[InventoryItemCompositeDef Detonator DisplayNamePlural]] "Remotes"),
	Description = "",
	AdditionalHint = T(861733747986, --[[InventoryItemCompositeDef Detonator AdditionalHint]] "<bullet_point> Used to trigger Remote-detonated explosives in an area"),
	UnitStat = "Explosives",
	AreaOfEffect = 5,
	ThrowRange = 20,
}

